### ISSUE TITLE
OutOfMemoryException on small problem (Bugzilla #788)

### ISSUE THREAD

**Issue by mpreiner** [CVC4/CVC4#1001]
**Imported from Bugzilla**
Reporter: *Pierre van de Laar*
Status: *NEW*
Severity: *normal*
Assigned to: *Andrew Reynolds*
Component: *Strings*
Milestone: *---*
Version: *master*
Platform: *PC*
OS: *Windows*

Original attachment names and IDs:
- _[bugMinimizedCVC4.smt2](http://cvc4.cs.stanford.edu/bugzilla_attachments/421_bugMinimizedCVC4.smt2)_ (Small file that causes out of memory for CVC4, ID 421)

On 2017-03-29 23:53:44 -0700, Pierre van de Laar wrote:
> Created attachment 421
> Small file that causes out of memory for CVC4
> 
> When I run the attached file with the latest nightly build of cvc4 on windows [Version 6.1.7601] as follows:
> 
> cvc4\-2017\-03\-28\-win32\-opt.exe \-\-incremental \-\-strings\-exp \-\-fmf\-fun\-rlv \-\-uf\-ss\-fair bugMinimizedCVC4.smt2
> 
> I get as output (after a very long time):
> (:name "cvc4")
> (:version "1.5\-prerelease")
> CVC4 threw an "unexpected" exception.
> terminate called after throwing an instance of 'CVC4::Minisat::OutOfMemoryException'
> 
> This application has requested the Runtime to terminate it in an unusual way.
> Please contact the application's support team for more information.
> 
> I also get a pop\-up window stating:
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> cvc4\-2017\-03\-28\-win32\-opt.exe has stopped working
> A problem caused the program to stop working correctly.
> Please close the program.
> 
> \-> Close the program
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> 
> Note: when I run the same problem with Z3 I get an answer within seconds.

**Comment by ajreynol** [comment]
This problem requires better support for regular expression membership in CVC4.

**Comment by ajreynol** [comment]
This benchmark is now solved in ~2 seconds in current master. I tested https://github.com/CVC4/CVC4/commit/1823d6d537a59d85a17f09f53c8128d934c420a3 but I don't know the commit that improved the performance for this.
