### ISSUE TITLE
Removal of boolean term conversion in 1f4b954a causes a few regressions (Bugzilla #809)

### ISSUE THREAD

**Issue by mpreiner** [CVC4/CVC4#1022]
**Imported from Bugzilla**
Reporter: *Florian Schanda*
Status: *NEW*
Severity: *minor*
Assigned to: *Clark Barrett*
Component: *{Internals} Boolean terms*
Milestone: *---*
Version: *master*
Platform: *All*
OS: *All*

Original attachment names and IDs:
- _[logger.ads_50_55_range_check.smt2](http://cvc4.cs.stanford.edu/bugzilla_attachments/444_logger.ads_50_55_range_check.smt2)_ (example vc, ID 444)

On 2017-05-17 03:05:27 -0700, Florian Schanda wrote:
> Created attachment 444
> example vc
> 
> Hi Andrew,
> 
> Just thought I should file a small regression; we have a few VCs (one is attached) where previously \-\-boolean\-term\-conversion\-mode\=native was needed to give unsat; current master branch doesn't seem to be able to come to a conclusion anytime soon.
> 
> Any advice on what we should do instead to discharge it?
> 
> Thanks,
> 
>    Florian

**Comment by ajreynol** [comment]
I'm moving this to my "challenge benchmark" set and closing this issue.
