### ISSUE TITLE
uninterpreted constants are renamed, causing clashes in models (Bugzilla #818)

### ISSUE THREAD

**Issue by mpreiner** [CVC4/CVC4#1031]
**Imported from Bugzilla**
Reporter: *Andrew Reynolds*
Status: *NEW*
Severity: *enhancement*
Assigned to: *Andrew Reynolds*
Component: *Models and counterexamples*
Milestone: *1.6*
Version: *master*
Platform: *PC*
OS: *Linux*

Original attachment names and IDs:
- _[rename-bug.smt2](http://cvc4.cs.stanford.edu/bugzilla_attachments/451_rename-bug.smt2)_ (attachment, ID 451)

On 2017-06-02 06:57:30 -0700, Andrew Reynolds wrote:
> Created attachment 451
> attachment
> 
> Running cvc4 \-\-dump\-models on attachment gives this:
> 
> sat
> (model
> ; cardinality of u\+u is 3
> (declare\-sort u\+u 0)
> ; rep: _@uc\_u\_u\_0
> ; rep: _@uc\_u\_u\_1
> ; rep: _@uc\_u\_u\_2
> ; cardinality of u\-u is 3
> (declare\-sort u\-u 0)
> ; rep: _@uc\_u\_u\_0
> ; rep: _@uc\_u\_u\_1
> ; rep: _@uc\_u\_u\_2
> (define\-fun a () u\+u _@uc\_u\_u\_0)
> (define\-fun b () u\+u _@uc\_u\_u\_1)
> (define\-fun c () u\+u _@uc\_u\_u\_2)
> (define\-fun d () u\-u _@uc\_u\_u\_0)
> (define\-fun e () u\-u _@uc\_u\_u\_1)
> (define\-fun f () u\-u _@uc\_u\_u\_2)
> )
> 
> \+ and \- are renamed to \_ causing a clash.

**Comment by ajreynol** [comment]
This is no longer an issue in current master.
