### ISSUE TITLE
Assertion failure in UFDT benchmarks (Bugzilla #828)

### ISSUE THREAD

**Issue by mpreiner** [CVC4/CVC4#1041]
**Imported from Bugzilla**
Reporter: *Andres Noetzli*
Status: *NEW*
Severity: *enhancement*
Assigned to: *Andrew Reynolds*
Component: *Quantifiers*
Milestone: *1.6*
Version: *master*
Platform: *PC*
OS: *Linux*

Original attachment names and IDs:
- _[ufdt_assert.smt2](http://cvc4.cs.stanford.edu/bugzilla_attachments/459_ufdt_assert.smt2)_ (Example, ID 459)

On 2017-06-18 00:57:44 -0700, Andres Noetzli wrote:
> Created attachment 459
> Example
> 
> The attached benchmark fails with the following error message:
> 
> $ ./cvc4\-assertions \-\-no\-e\-matching \-\-full\-saturate\-quant ufdt\_assert.smt2
> (error "Assertion failure.
> void CVC4::TheoryEngine::ensureLemmaAtoms(const std::vector<CVC4::NodeTemplate<false> >&, CVC4::theory::TheoryId)
> ../../../../src/theory/theory\_engine.cpp:1708:
> 
>   eqNormalized.getKind() \=\= kind::EQUAL
> ")
> 
> The stack trace is as follows:
> 
> \# 0  0x0000000001ba6578 in raise ()
> \# 1  0x0000000001ba67da in abort ()
> \# 2  0x000000000042877d in CVC4::main::sigint\_handler(int, siginfo\_t\*, void\*) ()
> \# 3  <signal handler called>
> \# 4  0x000000000089a2c9 in CVC4::theory::QuantifiersModule::areEqual(CVC4::NodeTemplate<false>, CVC4::NodeTemplate<false>) ()
> \# 5  0x0000000000f903e2 in CVC4::theory::quantifiers::MatchGen::doMatching(CVC4::theory::quantifiers::QuantConflictFind\*, CVC4::theory::quantifiers::QuantInfo\*)
>     ()
> \# 6  0x0000000000f97a84 in CVC4::theory::quantifiers::MatchGen::getNextMatch(CVC4::theory::quantifiers::QuantConflictFind\*, CVC4::theory::quantifiers::QuantInfo\*) ()
> \# 7  0x0000000000f97895 in CVC4::theory::quantifiers::MatchGen::getNextMatch(CVC4::theory::quantifiers::QuantConflictFind\*, CVC4::theory::quantifiers::QuantInfo\*) ()
> \# 8  0x0000000000f98081 in CVC4::theory::quantifiers::MatchGen::getNextMatch(CVC4::theory::quantifiers::QuantConflictFind\*, CVC4::theory::quantifiers::QuantInfo\*) ()
> \# 9  0x0000000000f97cbd in CVC4::theory::quantifiers::MatchGen::getNextMatch(CVC4::theory::quantifiers::QuantConflictFind\*, CVC4::theory::quantifiers::QuantInfo\*) ()
> \# 10 0x0000000000f9e279 in CVC4::theory::quantifiers::QuantConflictFind::check(CVC4::theory::Theory::Effort, unsigned int) ()
> \# 11 0x0000000000cdd0f8 in CVC4::theory::QuantifiersEngine::check(CVC4::theory::Theory::Effort) ()
> \# 12 0x0000000000906adf in CVC4::theory::quantifiers::TheoryQuantifiers::check(CVC4::theory::Theory::Effort) ()
> \# 13 0x0000000000659ca6 in CVC4::TheoryEngine::check(CVC4::theory::Theory::Effort) ()
> \# 14 0x0000000000ccfb2c in CVC4::prop::TheoryProxy::theoryCheck(CVC4::theory::Theory::Effort) ()
> \# 15 0x00000000010169c7 in CVC4::Minisat::Solver::propagate(CVC4::Minisat::Solver::TheoryCheckType) ()
> \# 16 0x0000000001016bc3 in CVC4::Minisat::Solver::search(int) ()
> \# 17 0x0000000001017e49 in CVC4::Minisat::Solver::solve\_() ()
> \# 18 0x0000000001087988 in CVC4::Minisat::SimpSolver::solve\_(bool, bool) ()
> \# 19 0x000000000101c558 in CVC4::prop::MinisatSatSolver::solve() ()
> \# 20 0x0000000000cce461 in CVC4::prop::PropEngine::checkSat() ()
> \# 21 0x000000000057f5ad in CVC4::SmtEngine::check() ()
> \# 22 0x0000000000582355 in CVC4::SmtEngine::checkSatisfiability(CVC4::Expr const&, bool, bool) ()
> \# 23 0x0000000000583093 in CVC4::SmtEngine::checkSat(CVC4::Expr const&, bool) ()
> \# 24 0x00000000005335fe in CVC4::CheckSatCommand::invoke(CVC4::SmtEngine\*) ()
> \# 25 0x0000000000537a4f in CVC4::Command::invoke(CVC4::SmtEngine\*, std::ostream&) ()
> \# 26 0x000000000041c06b in CVC4::main::smtEngineInvoke(CVC4::SmtEngine\*, CVC4::Command\*, std::ostream\*) ()
> \# 27 0x000000000041e934 in CVC4::main::CommandExecutor::doCommandSingleton(CVC4::Command\*) ()
> \# 28 0x0000000000423757 in runCvc4(int, char\*\*, CVC4::Options&) ()
> \# 29 0x0000000000403916 in main ()

On 2017-06-18 06:23:42 -0700, Andrew Reynolds wrote:
> I believe this is related to Boolean terms \+ theory combination.
> 
> The problematic atom using "\-d theory::atoms" is :
> 
> TheoryEngine::ensureLemmaAtoms(): (\= true BOOLEAN\_TERM\_VARIABLE\_18138) with nf BOOLEAN\_TERM\_VARIABLE\_18138
> 
> I'll think about a way to conservatively fix this.

On 2017-06-18 07:09:42 -0700, Andrew Reynolds wrote:
> I've fixed the issue in:
> 
> https://github.com/CVC4/CVC4/commit/7938b8dd3f7781751f8e9df3c06d0264b68e123a
> 
> This weakens the assertion in ensureTheoryAtoms so that we ignore literals of the form V \= true and V \= false where V is a BOOLEAN\_TERM\_VARIABLE.
> 
> I suspect there are better ways to fix this. It looks as though theoryOf( V \= true ) \= THEORY\_UF, which is why it is being considered in ensureTheoryAtoms from CollectAtoms.  Somewhat strangely, at the moment, it is common for both V \= true and V to be asserted to theories (see \-t theory::assertions).
> 
> One thing to reconsider here is whether V \= true should rewrite to V.  As I recall there are invariants regarding rewriting equalities that may be violated when doing this.

**Comment by ajreynol** [comment]
I think the original fix mentioned here is correct. My impression is that V = true shouldn't rewrite to V.

Closing this issue since the question about the rewriting was the only open question here.
