### ISSUE TITLE
Revisit whether to exit on ModalExceptions (Bugzilla #831)

### ISSUE THREAD

**Issue by mpreiner** [CVC4/CVC4#1044]
**Imported from Bugzilla**
Reporter: *Andrew Reynolds*
Status: *NEW*
Severity: *enhancement*
Assigned to: *Andrew Reynolds*
Component: *{Internals} Utilities*
Milestone: *1.6*
Version: *master*
Platform: *PC*
OS: *Linux*

On 2017-07-05 14:15:13 -0700, Andrew Reynolds wrote:
> Concerning the issue Clement brought up on cvc4\-devel involving ModalExceptions, there are a number of situations where we need to decide if CVC4 should give a warning and exit, or just give a warning and continue:
> 
> \- Call to get\-value/get\-model/get\-unsat\-core/get\-proof/get\-info after unexpected response (sat/unknown/unsat)
> \- Call to get\-value/get\-model/get\-unsat\-core/get\-proof/get\-info and option is not set (produce\-models/produce\-unsat\-cores) or the build does not support it
> \- Call to set\-logic after initialization
> \- Call to pop when no context to pop
> 
> All of these it is possible to print a warning and continue without any side effects.
> 
> Making this a post\-1.5 release milestone.
> 
> \-Andy

On 2017-07-10 15:53:17 -0700, Andrew Reynolds wrote:
> CVC4 now prints an error and continues for ModalExceptions of the first kind above after this commit: https://github.com/CVC4/CVC4/commit/54d24c786d6a843cc72dfb5e377603349ea5e42

**Comment by ajreynol** [comment]
This was fixed in #1074.
