### ISSUE TITLE
Run examples as part of Travis tests (Bugzilla #834)

### ISSUE THREAD

**Issue by mpreiner** [CVC4/CVC4#1047]
**Imported from Bugzilla**
Reporter: *Andres Noetzli*
Status: *NEW*
Severity: *enhancement*
Assigned to: *Andres Noetzli*
Component: *Build system (configure, make, make install)*
Milestone: *---*
Version: *master*
Platform: *All*
OS: *Linux*

On 2017-07-19 12:42:08 -0700, Andres Noetzli wrote nothing.

**Comment by 4tXJ7f** [comment]
Fixed in #2663.

**Comment by 4tXJ7f** [comment]
Fixed in #2663.
