### ISSUE TITLE
Regression test datatypes/v5l30058.cvc fails with GCC 7.1.1 (Bugzilla #844)

### ISSUE THREAD

**Issue by mpreiner** [CVC4/CVC4#1050]
**Imported from Bugzilla**
Reporter: *Aina Niemetz*
Status: *NEW*
Severity: *normal*
Assigned to: *Andrew Reynolds*
Component: *Datatypes*
Milestone: *---*
Version: *master*
Platform: *PC*
OS: *Linux*

On 2017-08-16 11:44:57 -0700, Aina Niemetz wrote:
> Regression test regress0/datatypes/v5l30058.cvc fails with an assertion error when compiling CVC4 with GCC 7.1.1.
> 
> 
> Debug build:
> void CVC4::theory::TheoryEngineModelBuilder::debugCheckModel(CVC4::Model\*)
> ../../../../src/theory/theory\_model.cpp:1002:          
>                                                        
>   tm\->getValue(\*eqc\_i) \=\= rep
> run with \-d check\-model::rep\-checking for details
> 
> 
> Production build:
> void CVC4::TheoryEngine::checkTheoryAssertionsWithModel()
> ../../../../src/theory/theory\_engine.cpp:2226:
> 
> THEORY\_DATATYPES has an asserted fact that the model doesn't satisfy.
> The fact: NOT(node(x9) \= termITE\_4)
> Model value: FALSE

**Comment by ajreynol** [comment]
This is fixed by https://github.com/CVC4/CVC4/commit/d7dadde871ae4775748695b0b7f9deee49576c0a
