### ISSUE TITLE
CVC4 does not support overloaded symbols in datatypes definitions

### ISSUE THREAD

**Issue by PaulMeng** [CVC4/CVC4#1063]
```
(set-logic ALL)
(declare-datatypes () ((Enum0 (In_Air) (On_Ground) (None))))
(declare-datatypes () ((Enum1 (True) (False) (None))))
(declare-fun var_0 () Enum0)
(declare-fun var_1 () Enum1)
(assert (= var_0 None))
(assert (= var_1 None))
(check-sat)
```

For the above model, CVC4 throws a parsing error:

(error "Parse Error: /Users/baoluomeng/Documents/research/cvc4/etc/enum.smt2:3.50: Symbol 'None' previously declared as a variable
  (declare-datatypes () ((Enum1 (True) (False) (None))))                                                ^
")

The error indicates that CVC4 might not allow to overload symbols in datatype declarations. However, Z3 supports it by using qualified names for overloaded symbols when referring to them. For example, Z3 accepts the following model where one may use "as" to specify the qualified name for "None".

```
(set-logic ALL)
(declare-datatypes () ((Enum0 (In_Air) (On_Ground) (None))))
(declare-datatypes () ((Enum1 (True) (False) (None))))
(declare-fun var_0 () Enum0)
(declare-fun var_1 () Enum1)
(assert (= var_0 (as None Enum0)))
(assert (= var_1 (as None Enum1)))
(check-sat)
```

Btw, this issue was also opened on stackoverflow (https://stackoverflow.com/questions/45819576/cvc4-parsing-errorthe-same-formula-passes-z3).
I have verified it using a development version of CVC4 (1b274e5) with flag "--lang=smt2.5" and Z3 (http://rise4fun.com/z3).

**Comment by ajreynol** [comment]
I can quickly argue that we should not be able to overload constructors.  Here is an example that is ambiguous whether it is SAT or UNSAT:

(declare-datatypes () ((Enum0 (In_Air) (None))))
(declare-datatypes () ((Enum1 (True) (In_Air) (None))))
(assert (not (= In_Air None)))
(check-sat)

This is UNSAT if we assume the disequality is between Enum0 and SAT if it is between Enum1.

**Comment by ajreynol** [comment]
Paul, can you make a branch of a proposed solution for this and then we can discuss?

**Comment by PaulMeng** [comment]
Sure, I will do that.
Btw, I cannot see your previous comment about the ambiguity of using overloaded symbols. Did you delete it?

**Comment by PaulMeng** [comment]
I think we could just adopt Z3's approach to introduce a new keyword to allow users to specify qualified names for overloaded symbols when referring to them. They do not have to use qualified names if no overloaded symbol is used. Otherwise, they must use qualified names.

This would require to extend the front end, but require more work on the internal representation of those symbols to distinguish them. But it should not need to change the decision procedure.

The above idea is just based on my understanding of enumeration types. I am not sure if other datatypes could cause different trouble. 

I have made a branch in my CVC4 repo. (https://github.com/PaulMeng/CVC4/tree/overloadsymbol)

**Comment by ajreynol** [comment]
Yes, this is all theoretically possible if we insist on type annotations for all overloaded symbols, e.g. if f is overloaded (defined to be T1 and T2) then we must write (as f T1) or (as f T2) wherever we use f.  We already have parsing support for "as".
You will need to modify the smt2 parser to allow multiple definitions with the same name but different type.

It is very questionable to me whether this is a good idea, Cesare might be a good person to talk to about this.

**Comment by timothy-king** [comment]
If one has to write (as f T1) everywhere but the declaration, why not write this as |as f T1|? Seems to avoid all of the special casing and modifications to the parser for a small amount of checking at declaration time (that one would need for generating (as f T1) in terms anyways).

**Comment by ajreynol** [comment]
I would agree with Tim that this feature has very little benefit as far as I can tell.  The only benefit you can say is that in the declaration you're allowed to use the same names, but you always have to manually disambiguate everywhere else.  Perhaps we could get more information from the user about this.

Also, notice we don't want to allow overloading without type casts since this allows inputs like this:

(set-logic ALL)
(declare-datatypes () ((Enum0 (In_Air) (True) (False) (None))))
(declare-datatypes () ((Enum1 (True) (False) (None))))
(declare-fun var_0 () Enum0)
(declare-fun var_1 () Enum1)
(assert (not (= None True)))
(check-sat)

This is unsatisfiable but we can't even infer the types in the disequality.

**Comment by PaulMeng** [comment]
We have a meeting with GE tomorrow. I will ask them more about this. As far as I know, they use CVC4 as an executable, and the input fed to CVC4 is dumped from a translator using Z3 API. Since Z3 allows overloaded symbols in declarations, the input given to CVC4 would probably also contain overloaded symbols. 

I agree that changing from (as f T1) to |as f T1| would avoid the problem. But that would require quite some work for them. I am not sure if they want to do that but I will let them know this option.

**Comment by ajreynol** [comment]
Fixed in https://github.com/CVC4/CVC4/commit/252860a96565f3c73fff7132eb06059c90582bdd
