### ISSUE TITLE
Coverity Scan CID #1362737

### ISSUE THREAD

**Issue by timothy-king** [CVC4/CVC4#1081]
In CommandExecutor::doCommandSingleton, the internal variable g can be set multiple times. g is used to print additional information at the exit of a function. It is plausible that both a memory leak can happen and that output the user is requesting is not being printed. (It is also plausible that there are mutually incompatible options being set.) This function should be rewritten so that g cannot be set more than once. It seems fine to abort if this ever happens.

I re-assigned the issue from myself to Andres in Coverity Scan.

**Comment by 4tXJ7f** [comment]
What do you think about turning `g` into an `std::vector< std::unique_ptr<Command> >`? Like that users could combine dump commands with fewer restriction (e.g. use `--dump-synth` and `--dump-unsat-cores` together).

**Comment by 4tXJ7f** [comment]
See commit here https://github.com/4tXJ7f/CVC4/commit/cc0f8b1f96a11fe532cf96fb37de10fab060edc4.
