### ISSUE TITLE
Nullptr dereference in cvc3_compatibility layer

### ISSUE THREAD

**Issue by timothy-king** [CVC4/CVC4#1106]
There is a guaranteed nullptr dereference in the cvc3_compatibility layer (see Coverity cid 1362755). I have a fix in PR #1089 that updates the C++ interface. This function is used by the java bindings which fail to compile with the new interface. See the build failure in travis: https://travis-ci.org/CVC4/CVC4/builds/274450978 . The bindings need to be updated to use this fix.

Clark, please re-assign this to the owner of the java bindings so they can take the patch over and complete it with fixes for the java bindings.

**Comment by 4tXJ7f** [comment]
I have submitted a fix for the Java interface.

**Comment by 4tXJ7f** [comment]
Fixed in #1089.
