### ISSUE TITLE
Very long computing time for a rather simple SyGuS problem

### ISSUE THREAD

**Issue by iwob** [CVC4/CVC4#1151]
Hello,

I ran the following SyGuS script for like 2.5 hours and it didn't end. The problem seems not to be very hard. The version with three variables took around 145 seconds, which was also pretty long compared to other scripts I tested. I used cvc4-2017-09-26-x86_64-linux-opt nightly build.

```
(set-logic LIA)

(synth-fun arithmeticseries4 ((a Int) (b Int) (c Int) (d Int)) Int

((Start Int (a b c d 0 1
    (+ Start Start)
    (- Start Start)
    (ite StartBool Start Start)))

    (StartBool Bool ((and StartBool StartBool)
        (or StartBool StartBool)
        (=> StartBool StartBool)
        (not StartBool)
        (<= Start Start)
        (= Start Start)
        (>= Start Start)))))

(declare-var a Int)
(declare-var b Int)
(declare-var c Int)
(declare-var d Int)
      
(constraint (=> (and (= (- b a) (- c b)) (= (- c b) (- d c))) (= (arithmeticseries4 a b c d) 1)))
(constraint (=> (not (and (= (- b a) (- c b)) (= (- c b) (- d c)))) (= (arithmeticseries4 a b c d) 0)))
(check-synth)
```

**Comment by ajreynol** [comment]
Hi,

Thanks for the benchmark.

You can try the option --cegqi-si=all

This enables the single invocation approach to synthesis which is very fast for kinds of problems you gave (which CVC4 is able to solve instantly). 

As a caveat, the option --cegqi-si=all may produce non-optimal solutions, and is restricted to "single invocation properties" where all occurrences of the function-to-synthesize are applied to a fixed set of variables.  For more details on this approach, see: http://homepage.divms.uiowa.edu/~ajreynol/pres-synt17-ajr.pdf

Regardless, I'll look into why cvc4 in default mode (where it uses enumerative SyGuS) is slow for this one.

**Comment by iwob** [comment]
Thank you very much, with this option problem is solved instantly. I'm interested mainly in problems with single invocation property. I assumed that CVC checks this automatically.

By "non-optimal solutions" do you mean solutions which do not completely meet the constraints? Or do you mean only their size? Probably the former, given that CVC4 tends to provide quite long solutions compared e.g. to EUSOLVER.

**Comment by ajreynol** [comment]
By non-optimal I mean large size (they do completely meet the constraints).  Indeed, CVC4 in this mode will produce larger solutions than EUSOLVER.

**Comment by ajreynol** [comment]
The performance of the enumerative approach seems reasonable for this example since the solution size is large.  I'll close this issue and keep the benchmark in mind for future optimizations to the enumerative solver in CVC4.
