### ISSUE TITLE
Support replace all in strings

### ISSUE THREAD

**Issue by ajreynol** [CVC4/CVC4#1165]
The replace all operator has been requested by some users and is implemented in a few existing string solvers.

**Comment by Muon** [comment]
👍 This would be super useful for my work! Out of curiosity, which string solvers have replaceAll implemented?

**Comment by ajreynol** [comment]
The string solver S3 is alone the one I know about that supports replaceAll.  

I hopefully will have some time in the coming months to add support for this in CVC4.
