### ISSUE TITLE
Strings API for constants automatically converts escape sequences

### ISSUE THREAD

**Issue by ajreynol** [CVC4/CVC4#1169]
As pointed out by Kshitij in this email:

Hi Andy (or anyone else interested),

I am using CVC4 with String theory from the API, and I find some
unexpected transformations being done to the string during construction,
which I am afraid will lead to unexpected results. Would appreciate if
could clarify.

If I am to do something like [c++ psuedo-code]

  Assert(mkExpr(EQUAL, 2,
                mkExpr(STRLEN, String("\\n"))))

(arguments are two character: [the slash character, n character])

CVC4 will give UNSAT, when I expect it to give SAT. Because it converts
"\n" to a single character in internal representation:

  String(const char* s) {
    std::string stmp(s);
    toInternal(stmp);
  }

(in regexp.h)

It is doing some transformation for characters following "\".

That looks incorrect to me?

--Kshitij

Note: I haven't tried this via API yet -- only via command line, where I
see this behavior:

(set-logic QF_S)
(assert (= (str.len "\n") 2))
(check-sat)

gives unsat.  AFAICT, this is what is going to happen with API as well,
unless there is some trickery going on elsewhere.

**Comment by ajreynol** [comment]
Proposed fix here:  https://github.com/ajreynol/CVC4/tree/stringsApiEscSeq

**Comment by kbansal** [comment]
Hi Andy,

Thanks for looking into this. At a high-level, was looking for two methods which are inverse of each other, and allow bypassing the escaping logic. One to convert from a C++ string object to CVC4::String, and other to convert from CVC4::String to a C++ string object.

I will comment further on the pull request/commits.

Kshitij

**Comment by ajreynol** [comment]
This was fixed by #1245.
