### ISSUE TITLE
way to signal CVC4 to abort?

### ISSUE THREAD

**Issue by bchurchill** [CVC4/CVC4#1186]
I'm looking to run CVC4 in a thread, and I would like a way to signal CVC4 to abort computation.  It doesn't need to abort immediately, just shut down when it gets a chance.  Is there a way to do this via the C++ api?

**Comment by 4tXJ7f** [comment]
Are you planning to reuse the instance after that?

**Comment by bchurchill** [comment]
If possible, yes.

**Comment by barrettcw** [comment]
We could provide a functionality to tell CVC4 to abort, but the problem is that the CVC4 instance would not be left in a clean state and could not be re-used.  So you would have to delete the solver and restart it anyway, so killing the thread is probably just as good.

**Comment by bchurchill** [comment]
Okay, thanks.
