### ISSUE TITLE
Simple str.contains assertion takes forever to check

### ISSUE THREAD

**Issue by someone-with-default-username** [CVC4/CVC4#1189]
Obviously unsatisfiable assertion takes forever to check
```
(set-logic ALL_SUPPORTED)
(declare-const x Int)
(assert (str.contains (str.++ "some text" (int.to.str x)) "vector"))
(check-sat)
```

I've tried builds `cvc4-1.5-win32-opt.exe` and `cvc4-2017-10-02-win32-opt.exe`.

**Comment by ajreynol** [comment]
Thanks for the benchmark, I can confirm that CVC4 will not solve this one currently.  This is quite tricky to solve but should be doable, I'll let you know when I have a solution.

**Comment by ajreynol** [comment]
This is fixed after https://github.com/CVC4/CVC4/commit/675e82e32a34911163f9de0e6389eb107be5b0f1

Cheers,
Andy
