### ISSUE TITLE
SyGuS invariant synthesis parsing is not robust to variable ordering

### ISSUE THREAD

**Issue by ajreynol** [CVC4/CVC4#1190]
This benchmark does not parse, since declare-primed-var are not in order with the arguments in the pre,post,trans:

(set-option :print-success true)
(set-logic LIA)
(synth-inv inv-f ((x Int) (y Int) (b Bool)))
(declare-primed-var b Bool)
(declare-primed-var x Int)
(declare-primed-var y Int)
(define-fun pre-f ((x Int) (y Int) (b Bool)) Bool
  (and 
    (and (>= x 5) (<= x 9))
    (and (>= y 1) (<= y 3))
  )
)
(define-fun trans-f ((x Int) (y Int) (b Bool) (x! Int) (y! Int) (b! Bool)) Bool
  (and 
    (and (= b! b) (= y! x))
    (ite b (= x! (+ x 10)) (= x! (+ x 12)))
  )
)
(define-fun post-f ((x Int) (y Int) (b Bool)) Bool true)
(inv-constraint inv-f pre-f trans-f post-f)
(check-synth)

**Comment by ajreynol** [comment]
It is questionable whether benchmarks like this should be accepted.  The SyGuS format technically allows it, but the format is a bit nonsensical, since it implicitly considers how variables are shadowed, i.e. (x Int) in pre-f corresponds to the global (declare-primed-var x Int).
There isn't an obvious/clean solution to this that I can see at the moment.

**Comment by HanielB** [comment]
Closed via #2509
