### ISSUE TITLE
Minimal model cores

### ISSUE THREAD

**Issue by ajreynol** [CVC4/CVC4#1233]
It would be interesting to have the feature that prints only the "core" of a model, that is, a subset of the model values that can be extended arbitrarily, here is an example:

(declare-fun x () Int)
(declare-fun y () Int)
(declare-fun z () Int)
(declare-fun f (Int) Int)
(assert (= (f x) 0))
(assert (or (> z 5) (> y 5)))
(check-sat)

By default we may get a model looking like this:

(model
(declare-fun x () Int 2)
(declare-fun y () Int 0)
(declare-fun z () Int 6)
(declare-fun f ((_x Int)) Int 0)
)

This could be minimized to:

(model
(declare-fun z () Int 6)
(declare-fun f ((_x Int)) Int 0)
)

Notice that

(and
(= ((\ _x 0) x) 0)
(or (> 6 5) (> y 5))
)

rewrites to 

true

(for any x,y), which our rewriter would detect. Hence the functionality of check-model + rewriter could be used to greedily minimize various for which the input still rewrites to true.

**Comment by barrettcw** [comment]
There is an experimental option, --omit-dont-cares, which tries to do this
already by leaving out variables that were not assigned in the model
(rather than assigning them values using a type iterator).  The
functionality is pretty limited though.

-Clark

**Comment by ajreynol** [comment]
Cool, I'll have a look.
