### ISSUE TITLE
Incorrect result + assertion failure in nonClausalSimplify when arrays enabled on QF_BV benchmark

### ISSUE THREAD

**Issue by timothy-king** [CVC4/CVC4#1247]
Attached are two smt2 files reduced from a report by David Melski on cvc-bugs@. The files are the same except one sets the logic to QF_ABV and the other to QF_BV.
[srt2.abv.smt2.log](https://github.com/CVC4/CVC4/files/1384901/srt2.abv.smt2.log)
[srt2.bv.smt2.log](https://github.com/CVC4/CVC4/files/1384902/srt2.bv.smt2.log)

The QF_BV version correctly answers unsat. The QF_ABV version answers sat in non-debug builds and has the following assertion failure in debug builds:
> 
> $ ./builds/bin/cvc4 --lang=smt2 ./srt2.abv.smt2.log
> 
> CVC4 threw an "unexpected" exception (one that wasn't properly specified
> in the throws() specifier for the throwing function).
> 
> The exception is:
> <unsupported>
> 
> terminate called after throwing an instance of 'CVC4::AssertionException'
>   what():  Assertion failure.
> bool CVC4::smt::SmtEnginePrivate::nonClausalSimplify()
> ../../../../src/smt/smt_engine.cpp:2926:
> 
>   d_topLevelSubstitutions.apply(learnedLiteral) == learnedLiteral
> 
> Aborted
> 

The problem appears to be a mixture of ITEs + incremental solving + preprocessing.

Reproduced on 459cb24dafae7b6253476cfae07a54fc5a4a9166 .

**Comment by timothy-king** [comment]
The original file sent by David Melski:
[sym-read-tests.158.log](https://github.com/CVC4/CVC4/files/1384904/sym-read-tests.158.log)

**Comment by barrettcw** [comment]
Fixed in 1257
