### ISSUE TITLE
Nightly builds are not being produced

### ISSUE THREAD

**Issue by timothy-king** [CVC4/CVC4#1248]
> It seems your nightly builds stopped being produced (http://cvc4.cs.stanford.edu/downloads/builds/x86_64-linux-opt/unstable/).

Last build was "11-Oct-2017 05:53".

**Comment by mpreiner** [comment]
Working on it, root partition on the nightly machine is full due to too many docker images.

**Comment by barrettcw** [comment]
We had this problem before - I thought Cristian had fixed it - have you
checked with him?

-Clark

**Comment by mpreiner** [comment]
I'm currently moving the docker images to /barrett/scratch. This frees
15G on / and we will not have any space problems anymore in the future.

**Comment by barrettcw** [comment]
I'm worried that this will just hide the problem.  Why are there so many
docker images?  We need to make sure they are garbage collected regularly.

**Comment by mpreiner** [comment]
We had to do some cleanup of the containers. I still moved /var/lib/docker to /barrett/scratch in order to avoid running out of disk space on root.

**Comment by 4tXJ7f** [comment]
For anyone watching this issue the nightlies are working again thanks to @mpreiner (except RPM builds which are expected to work again at the end of next week).

**Comment by mpreiner** [comment]
Nightly builds are fixed - the docker builds (competition, RPM) are working again after fixing docker on barrett1.
