### ISSUE TITLE
Hang when finding string with minimum length not containing character

### ISSUE THREAD

**Issue by Muon** [CVC4/CVC4#1275]
The following test case hangs.

```smt2
(set-option :strings-exp true)
(set-logic QF_S)

(declare-const x String)

;(assert (= (str.indexof x "=" 0) (- 1)))
(assert (not (str.contains x "=")))
(assert (> (str.len x) 256))

(check-sat)
```

Trying it with much shorter lengths produces `sat`, but increasing the number makes CVC4 run slower. Maybe there's some brute force search going on?

**Comment by ajreynol** [comment]
Hi, thanks for the benchmark.

An option in CVC4 that can solve this problem quickly is "--strings-guess-model", which does a guess/check strategy that is often able to terminate with "SAT" quickly.  

I haven't done extensive testing with this option, so I don't know whether it helps on larger benchmarks.
I would be curious if this option helps in your use case.  I can revisit enabling it by default in CVC4 if it does help.

**Comment by Muon** [comment]
Just ran some experiments with it and it seems to work. Hopefully this wasn't just a fluke!

**Comment by ajreynol** [comment]
Good to hear.  The option isn't a fluke concerning correctness (the response/models it returns have the same correctness guarantees than without the option).
I'd be interested if you have benchmarks where CVC4 is non-terminating with the option.

**Comment by ajreynol** [comment]
I'll close this issue for now, do let me know if you have any further questions.
