### ISSUE TITLE
Support define-fun-rec in CVC parser

### ISSUE THREAD

**Issue by ajreynol** [CVC4/CVC4#1316]
As requested by Kostas Oikonomou in this email:

"
Is it possible to define a recursive function in the CVC4 native language?
Like an analogue of the SMTLIB "define-fun-rec"?
"

**Comment by ajreynol** [comment]
To support this, we first need to decide on a syntax for define-fun-rec, which would preferably be something that closely follows the structure of define-fun-rec / define-fun-recs.  Notice that this issue should probably be resolved first:
https://github.com/CVC4/CVC4/issues/839

**Comment by arjunvish** [comment]
Initial proposal for recursive function syntax:
func-name (input_type_1, ..., input_type_n) -> output_type = FUN (n-bound-variables): term
where, n-bound-variables are the typed declaration of the input variables.
Example 1:
fact (INT) -> INT = FUN (i : INT): IF (i > 0) THEN i * fact (i - 1) ELSE 1 ENDIF;

Example 2:
f (INT, INT, BOOLEAN) -> INT = FUN (x, y : INT, z : BOOLEAN): IF (x > 0 AND y > 0) THEN x + y + f (x - 1, y - 1, z) ELSE 0 ENDIF;

**Comment by ajreynol** [comment]
Can you give an example of mutually recursive functions?  Here is an smt2 example:

(define-funs-rec ((is-even ((x Int)) Int) (is-odd ((y Int)) Int)) 
(
(ite (= x 0) 1 (ite (= (is-odd (- x 1)) 0) 1 0)) 
(ite (= y 0) 0 (ite (= (is-even (- y 1)) 0) 1 0))
))

What would this be in *.cvc?

**Comment by arjunvish** [comment]
Extending the syntax to definition of multiple recursive functions:
fname_1 (input_types_1) -> output_type_1,  ..., fname_n (input_types_n) -> output_type_n = FUNS (params_1): term_1, ..., (params_n): term_n

For the mutually recursive functions is-odd and is-even:
is-even (INT) -> INT, is-odd (INT) -> INT = 
FUNS 
	(x : INT): IF (x = 0) THEN 1 ELSE (IF (is-odd(x - 1) = 0) THEN 1 ELSE 0 ENDIF) ENDIF, 
	(y : INT): IF (y = 0) THEN 0 ELSE (IF (is-even(y - 1) = 0) THEN 1 ELSE 0ENDIF) ENDIF;

**Comment by ajreynol** [comment]
This looks pretty good to me. One minor change I'd recommend is to add a colon between the function name and the type:

fact : (INT) -> INT = FUN (i : INT): IF (i > 0) THEN i * fact (i - 1) ELSE 1 ENDIF;

If you're fine with this, go ahead and make a branch, let me know if you have questions.

**Comment by arjunvish** [comment]
Sure. Thank you.

**Comment by ajreynol** [comment]
Decided on a syntax change:

REC-FUN fact : (INT) -> INT = LAMBDA (i : INT): IF (i > 0) THEN i * fact (i - 1) ELSE 1 ENDIF;

REC-FUNS is-even : (INT) -> INT, is-odd : (INT) -> INT =
LAMBDA (x : INT): IF (x = 0) THEN 1 ELSE (IF (is-odd(x - 1) = 0) THEN 1 ELSE 0 ENDIF) ENDIF,
LAMBDA (y : INT): IF (y = 0) THEN 0 ELSE (IF (is-even(y - 1) = 0) THEN 1 ELSE 0ENDIF) ENDIF;

This makes it clearer that we need to forward declare the functions.

**Comment by ajreynol** [comment]
REC-FUN five : INT = 5;

is also legal.

**Comment by ajreynol** [comment]
g : INT -> INT;

REC_FUN f : INT -> INT = g;

...is not legal.

**Comment by ajreynol** [comment]
This issue has been resolved in https://github.com/CVC4/CVC4/commit/d8994e79a67778b99e03dbe5a9437c4eb75c6c06.
