### ISSUE TITLE
CVC4 Installation Issue on Ubuntu

### ISSUE THREAD

**Issue by RyanCaleb** [CVC4/CVC4#1341]
Dear CVC4 community,

 I am trying to install from source CVC4 on an Ubuntu-64 machine. I need
it in order to install afterwards Maude 2.7 alpha 103 release
 - Maude 2.7 is still in alpha
state and it is not publicly available yet

During the CVC4 installation process I have met a problem that I have
not been able to solve in the last few days. It has to do with the
creation of the libcvc4.la library:

 . . .
 CXXLC libcvc4.la
 /usr/bin/ld /usr/local/lib/libgmp.a (get_str.o): relocation
R_X86_64_PC32 against symbol `__gmpn_invert_limb' can not be used when
making a share object; recompile with -fPIC.

 As a common precondition for Maude 2.7 I had already installed static
versions of the library of GMP 6.0.0 from source. As suggested in
Maude's INSTALL file, I configured GMP with --disable-shared
--enable-cxx flags. Maude 2.7 release 101 and previous versions of Maude
were successfully built on top of it.

 After downloading CVC4 1.3 I executed ./contrib/get-antl4-3.4 to creat
antlr and configured CVC4 with the options
--with-antlr-dir=/usr/local/antlr-3.4
ANTLR=/usr/local/antlr-3.4/bin/antlr3, as suggested in CVC4 INSTALL file
and executed the make command to build the complete system.

 Everything runs fine in the making up to the creation of the
libcvc4.la, which yields the following error: 

. . .
 CXXLC libcvc4.la
 /usr/bin/ld /usr/local/lib/libgmp.a (get_str.o): relocation
R_X86_64_PC32 against symbol `__gmpn_invert_limb' can not be used when
making a share object; recompile with -fPIC. 

/usr/local/lib/libgmp.a: could not read symbols: Bad value 

After googling it I configured GMP and CVV4 to compile with the -fPIC
option, though neither libcvc4.la or libgmp.a are shared libraries.
However, the error remains, though in another object file. 

CXXLC libcvc4.la
 /usr/bin/ld /usr/local/lib/libgmp.a (mod_1_1.o): relocation R_X86_64_32
against symbol `.rodata.str1.8' can not be used when making a share
object; recompile with -fPIC. 

I have repeated the process with GMP version 4.2, which is the latest
version of GMP reported to have been successfully used to build CVC4,
and the errors are the same. 

I've been compiling with g++ version 4.8.1: 

g++ --version 

g++ (Ubuntu 4.8.1-2ubuntu1~12.04) 4.8.1 

Any hint on how to solve it?

I didn't find the right solution from the internet.
References:  https://cs.nyu.edu/pipermail/cvc-users/2014/000588.html

[animated infographic
](https://blog.advids.co/20-innovative-animated-infographic-video-marketing-examples/)

**Comment by 4tXJ7f** [comment]
This is spam, I've reported the user.
