### ISSUE TITLE
Create cvc4_stack. 

### ISSUE THREAD

**Issue by aniemetz** [CVC4/CVC4#1383]
For now this is going to use a std::stack with vector as an underlying container.

It should provide a `pop()` method that pops and at the same time returns the popped element, e.g., 

```
int elem = stack.pop();
```

rather than having to call, e.g.,

```
int elem = stack.top();
stack.pop();
``` 

This is to be used for iterative traversals over data structures (e.g., DFS traversal over nodes).

**Comment by 4tXJ7f** [comment]
We have decided to put in the code guidelines that we should not use `std::stack` but that we do not create a custom datastructure.

**Comment by ajreynol** [comment]
Can we close this?

**Comment by aniemetz** [comment]
It's not yet incorporated in the code guidelines, we'll close it when we did.

**Comment by aniemetz** [comment]
https://github.com/CVC4/CVC4/wiki/Code-Style-Guidelines#inline-functions
