### ISSUE TITLE
Revisit regressions where --no-check-proofs is used

### ISSUE THREAD

**Issue by ajreynol** [CVC4/CVC4#1418]

**Comment by yoni206** [comment]
The string "--no-check-proofs" occurs in 16 tests.

**Tests with no problem**
In the following 3 tests, this is fine, as these tests use options that cannot be combined with proofs:
https://github.com/CVC4/CVC4/tree/master/test/regress/regress0/quantifiers/lra-triv-gn.smt2
https://github.com/CVC4/CVC4/tree/master/test/regress/regress0/datatypes/empty_tuprec.cvc
https://github.com/CVC4/CVC4/tree/master/test/regress/regress0/bv/test-bv_intro_pow2.smt2

In the following test, this is redundant, as the instance is SAT. I suggest to remove the options in #2184 :
https://github.com/CVC4/CVC4/tree/master/test/regress/regress1/bv/bv-int-collapse2-sat.smt2

**Tests with assertion errors**
In the following tests, an Assertion error is raised when adding --check-proof:
https://github.com/CVC4/CVC4/tree/master/test/regress/regress0/arrays/incorrect10.smt
https://github.com/CVC4/CVC4/tree/master/test/regress/regress1/bv/bug787.smt2
Note that the first one is explicitly related to this issue in #1398 .

**Tests with SAT vs. UNSAT problems**
In the following tests, the result is UNSAT, but when adding --check-proof, we get SAT:
https://github.com/CVC4/CVC4/tree/master/test/regress/regress0/bv/bv2nat-ground-c.smt2
https://github.com/CVC4/CVC4/tree/master/test/regress/regress0/bv/bv-int-collapse1.smt2
https://github.com/CVC4/CVC4/tree/master/test/regress/regress0/bv/bv-int-collapse2.smt2
https://github.com/CVC4/CVC4/tree/master/test/regress/regress0/bv/bv2nat-simp-range.smt2
https://github.com/CVC4/CVC4/tree/master/test/regress/regress1/bv/bv2nat-ground.smt2

**Tests that take too much time to run**
https://github.com/CVC4/CVC4/tree/master/test/regress/regress0/arith/bug569.smt2
https://github.com/CVC4/CVC4/tree/master/test/regress/regress1/quantifiers/symmetric_unsat_7.smt2
https://github.com/CVC4/CVC4/tree/master/test/regress/regress1/decision/quant-symmetric_unsat_7.smt2.expect
https://github.com/CVC4/CVC4/tree/master/test/regress/regress1/nl/nl_uf_lalt.smt2

**A test with a printing problem**
In the following test there is no problem with --check-proof, but rather with dump-proof:
https://github.com/CVC4/CVC4/tree/master/test/https://github.com/CVC4/CVC4/blob/master/test/regress/regress1/fmf/PUZ001%2B1.smt2

**Comment by yoni206** [comment]
Tests that returned sat instead of unsat when --check-proof was enabled are fixed in #2214 .
I guess that the next important group is the one with assertion errors.

@4tXJ7f , what should we do with the tests that take too much to run with --check-proof? Maybe we should just move them to the list of tests with no problems (I guess that if they take too long, then putting --no-check-proof is a good idea)?

**Comment by ajreynol** [comment]
Concerns old proof code, the removal of the old proof code fixed this issue.
