### ISSUE TITLE
datatype declarations according to SMT v2.6 not possible

### ISSUE THREAD

**Issue by julianthome** [CVC4/CVC4#1433]
Datatype declarations such as 

```
(declare-datatype MyList (par (T) ((nelem) (cons (hd T) (tl (MyList T)))))) 
```

are not supported by CVC4 (version 1.5). When executed with this input, CVC will respond with the following message:

```
(error "Parse Error: mytest.smt2:1.16: expected SMT-LIBv2 command, got `declare-datatype'.

  (declare-datatype MyList (par (T) ((nelem) (cons (hd T) (tl (MyList T)...
   ^
")
```

For more information please have a look at this [post](https://stackoverflow.com/questions/47620234/modelling-generic-datatypes-for-z3-and-or-smtv2-6/47623885#comment82276649_47623885).

**Comment by ajreynol** [comment]
Thanks for the bug report.
Indeed, CVC4 was not properly parsing single parametric datatypes properly.
This is fixed in #1435, which should be merged to master shortly.
