### ISSUE TITLE
Add Cryptominisat 5 support.

### ISSUE THREAD

**Issue by yurivict** [CVC4/CVC4#1454]
The current version of cryptominisat is 5.0.2. Do you support it?

**Comment by mpreiner** [comment]
Not yet, but it's on our TODO list.

**Comment by yurivict** [comment]
Do you have an estimate for when this might be expected?
I am writing because CVC4 needs a FreeBSD port, and out default version of cryptominisat is 4.
I am hesitant to create the cryptominisat4 just for CVC4.

**Comment by mpreiner** [comment]
Sorry, we don't have an estimate on that yet. I can have a look at cryptominisat 5 support in February at the earliest, but I don't want to promise it ;-)

**Comment by mpreiner** [comment]
#1664 uses Cryptominisat5.
