### ISSUE TITLE
Make call to ./autogen.sh the first step of how to INSTALL cvc4

### ISSUE THREAD

**Issue by quickbeam123** [CVC4/CVC4#1477]
Currently, the sequence

    ./configure   [use --prefix to specify a prefix; default /usr/local]
    make
    make check    [optional but a good idea!]

is advised. But there is no ./configure (yet) after a fresh download.

**Comment by mpreiner** [comment]
Hi,
Depends on whether you compile the sources from a repository checkout or you compile it from the sources provided with our stable/nightly releases. The section you quoted is for the latter.

If you are building CVC4 from the repository look at _Building CVC4 from a repository checkout_ first.

**Comment by ajreynol** [comment]
Perhaps we should rearrange the order in INSTALL? I'd agree it's not obvious to run ./autogen.sh despite this being pretty critical.

**Comment by quickbeam123** [comment]
OK, I see I should have just kept on reading and would have found

"To build from a repository checkout (rather than a distributed CVC4
tarball), there are additional dependences; see below."

So this is not so much about the INSTALL file being wrong, but a suggestion for its improvement.

**Comment by aniemetz** [comment]
Addressed in https://github.com/CVC4/CVC4/commit/31043ac507a58d757f39eda3c74d0ae8884a071b.
