### ISSUE TITLE
lib vs lib64 when downloading antlr-3.4

### ISSUE THREAD

**Issue by quickbeam123** [CVC4/CVC4#1479]
Both contrib/get-antlr-3.4 and cvc4's configure assume that LIBANTLR3C_INSTALL_DIR will contain a sub-folder "lib". However, (at least one) 64 bit installation left behind only "lib64". This prevents contrib/get-antlr-3.4 from finishing and configure from confirming antlr-3.4 is in place.

**Comment by mpreiner** [comment]
Can you give me more information on how to reproduce this? What OS are you using and what steps did you make to get to this point?

**Comment by quickbeam123** [comment]
I ran contrib/get-antlr-3.4 on x86_64 Linux and it broke down on 

mv lib/libantlr3c.a lib/libantlr3c-static.a

At that point, I had lib64 as a subfolder, but not lib, in the antlr-3.4 folder.

In the end, I made things work by following http://cvc4.cs.stanford.edu/wiki/Developer%27s_Guide#ANTLR3 
to finish the process, and then renaming the said lib64 to lib, which made ./configure pass through.

**Comment by 4tXJ7f** [comment]
Which distribution was that on? What's your version of autoconf and automake?

**Comment by 4tXJ7f** [comment]
@quickbeam123 Is this still an issue? We are preparing a new release of CVC4, so we try to get some issues sorted out before that and would appreciate any information that you could provide us with.

**Comment by quickbeam123** [comment]
Hey, yes, I think so. I just pulled the latest version of CVC4. And started installation with

./contrib/get-antlr-3.4

as suggested, getting the following line after a while:

mv: cannot stat 'lib/libantlr3c.a': No such file or directory

ls antlr-3.4/ gives:
bin  config.guess  include  lib64  share  src

Running on:
cat /etc/os-release
NAME="openSUSE Leap"
VERSION="42.3"
...

uname -r
4.4.175-89-default

autoconf (GNU Autoconf) 2.69
automake (GNU automake) 1.13.4

Cheers!
