### ISSUE TITLE
Opencv Kurulumu Python ve Pycharm Nasıl Yapılır (WİNDOWS)

### ISSUE THREAD

**Issue by opencvkurulumu** [CVC4/CVC4#1491]
İmage processing işlemi yapacaksanız sizin için en iyi kaynak python ve opencv 'dir. Windows için opencv kurulumu ve python kurulumu için pycharm idle 'yi kullanmamız mümkün.

[python kurulumu](https://dogankayadelen.com.tr/opencv-kurulumu-ve-python-kurulumu-pycharm/)
[opencv kurulumu](https://dogankayadelen.com.tr/opencv-kurulumu-ve-python-kurulumu-pycharm/)
[pycharm kurulumu](https://dogankayadelen.com.tr/opencv-kurulumu-ve-python-kurulumu-pycharm/)

**Comment by 4tXJ7f** [comment]
Also, reported for spam.
