### ISSUE TITLE
Python API

### ISSUE THREAD

**Issue by umangm** [CVC4/CVC4#1522]
Hi,

Is there an available documentation for the Python API ?
I am struggling with basic things such as 

1. How to extract values from the solver into Python's datatypes.
2. What are the possible Expression operators (KINDs)
3. Can I do Sum(list_of_expressions) just like I can in z3 ? Similarly, Is it possible to concisely write And(list_of_expressions) similar to z3 ?

Any leads would be helpful.

**Comment by 4tXJ7f** [comment]
Right now, there is unfortunately no good documentation for the Python API. All the language bindings that we have right now are (semi-)automatically generated from our C++ code, so there are essentially no language-specific features like `Sum(list_of_expressions)`. On the positive side, this means that you can take a look at the [examples for C++/Java](https://github.com/CVC4/CVC4/blob/master/examples/api) to see how things work and it should be pretty similar for the Python API (the issue with `mkBoolConst` in #1521 is one of the few differences). There is an ongoing project in our lab to create a nice solver-independent Python API that you might be interested in, it's called [smt-switch](https://github.com/makaimann/smt-switch). Right now, this API is for bitvectors, arrays, and Booleans only. If you need theories other than those, the [CVC4-specific file](https://github.com/makaimann/smt-switch/blob/master/smt_switch/src/solvers/CVC4Solver.py) might still be a good resource for dealing with the CVC4 Python bindings.

To extract values from the model into native Python types, you can use the `getConst*()` methods as illustrated in the following example:

```
from CVC4 import ExprManager, SmtEngine, SExpr, BitVector
import CVC4

em = ExprManager()
solver = SmtEngine(em)
solver.setOption("produce-models", SExpr("true"))
bool_type = em.booleanType()
bv_type = em.mkBitVectorType(32)

a = em.mkBoolConst(True)
b = em.mkVar("b", bool_type)
solver.assertFormula(em.mkExpr(CVC4.XOR, a, b))

x = em.mkVar("x", bv_type)
c = em.mkConst(BitVector(32, 5))
solver.assertFormula(em.mkExpr(CVC4.EQUAL, x, c))

result = solver.checkSat()
print(result.toString())
print(solver.getValue(b).getConstBoolean())
# getConstBitVector() gets a BitVector object
# getValue() gets an (arbitrary-precision) Integer representation from the
# BitVector
# getUnsignedLong() converts the Integer into a 64-bit integer
print(solver.getValue(x).getConstBitVector().getValue().getUnsignedLong())
```

To get a list of available kinds, you can take a look at `Kind_t` in `builds/src/expr/kind.h` (this file is generated during compilation).

Finally, do not hesitate to ask further questions, we are happy to help and it is great to see that there is interest in the CVC4 Python bindings.

**Comment by 4tXJ7f** [comment]
@HanielB reminded me that there is also [PySMT](https://github.com/pysmt/pysmt). I have no experience with PySMT but they seem to [use the CVC4 Python API](https://github.com/pysmt/pysmt/blob/master/pysmt/solvers/cvc4.py). This might be a nice reference/alternative to the barebones API provided by CVC4.
