### ISSUE TITLE
Python fitsSignedLong

### ISSUE THREAD

**Issue by umangm** [CVC4/CVC4#1524]
Hi,

I have a LRA formula which is satisfiable.
For a real variable whose value (in the model generated) is too large (which I confirmed by checking that `fitsSignedLong` returns False), is there a way to get the value in a python data type ?

For example, the `toString()` returns a value of `14473843461835685650567046378952431` for which `fitsSignedLong()` returns `False` .

**Comment by 4tXJ7f** [comment]
Your best bet is probably to just parse the string into a Python integer (Python integers have an arbitrary precision by default): `int('14473843461835685650567046378952431')`. Not very elegant but it works. Internally, we store large integers using GMP or CLN and it would require some additional code and thought to convert them to native Python integers.
