### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by chuchufan1990** [CVC4/CVC4#1533]
Hi,

I installed CVC4 with Python bindings ( following the instructions [here](https://mytekmek.wordpress.com/2015/05/22/cvc4-python-api-on-mac/)) but for Ubuntu

However, I am stuck with the following error.

```
>>> import CVC4
>>> from CVC4 import ExprManager
>>> ExprManager()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "CVC4.py", line 6201, in __init__
    self.this.append(this)
  File "CVC4.py", line 6195, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, ExprManager, name)
  File "CVC4.py", line 74, in _swig_getattr
    return _swig_getattr_nondynamic(self, class_type, name, 0)
  File "CVC4.py", line 69, in _swig_getattr_nondynamic
    return object.__getattr__(self, name)
AttributeError: type object 'object' has no attribute '__getattr__'
```

It would be great if you could help me resolve this.

**Comment by 4tXJ7f** [comment]
Which version of CVC4, Python and Ubuntu are you using? The following steps work for me (CVC4 master, Ubuntu 16.04, Python 2.7.12):

```
git clone git@github.com:CVC4/CVC4.git CVC4_python
cd CVC4_python
contrib/get-antlr-3.4
./autogen.sh
./configure --enable-language-bindings=python --prefix `pwd`/out_dir
make && make install
export PYTHONPATH=`pwd`/out_dir/share/pyshared/
cd out_dir/share/pyshared/
ln -s ../../lib/pyshared/CVC4.so _CVC4.so
cd ../../..
python examples/SimpleVC.py
```

**Comment by chuchufan1990** [comment]
I am using Python-2.7.12 and OS is MATE Desktop Environment 1.12.1 (and not Ubuntu, sorry about that).
I will try the steps you mentioned and come back soon.

**Comment by chuchufan1990** [comment]
I get the same error. It looks like this might be a swig issue.

**Comment by 4tXJ7f** [comment]
Hm, interesting. Which version of Swig are you using? I am using 2.0.12.

**Comment by chuchufan1990** [comment]
SWIG Version 3.0.8

**Comment by 4tXJ7f** [comment]
Ah, I seem to remember that there are issues with Swig 3, could you try using Swig 2? I'll open an issue for Swig 3 compatibility.

**Comment by 4tXJ7f** [comment]
Great, thanks for the update!
