### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by umangm** [CVC4/CVC4#1545]
How do I cite CVC4 ?

**Comment by HanielB** [comment]
You should refer to the publication at CAV 2011 by Barrett et al:

https://link.springer.com/chapter/10.1007/978-3-642-22110-1_14

A possible bibtex entry:

@inproceedings{Barrett2011,
author="Barrett, Clark
and Conway, Christopher L.
and Deters, Morgan
and Hadarean, Liana
and Jovanovi{\'{c}}, Dejan
and King, Tim
and Reynolds, Andrew
and Tinelli, Cesare",
editor="Gopalakrishnan, Ganesh
and Qadeer, Shaz",
title={{CVC4}},
booktitle={{Computer Aided Verification (CAV)}},
year="2011",
publisher="Springer",
pages="171--177",
doi="10.1007/978-3-642-22110-1_14",
url="http://dx.doi.org/10.1007/978-3-642-22110-1_14"
}
