### ISSUE TITLE
Assertion surprisingly incomplete

### ISSUE THREAD

**Issue by mcoulont** [CVC4/CVC4#1670]
Hi

I use cvc4-1.5-win32-opt.exe.

When I submit 
QUERY FORALL (x:INT) : EXISTS (y:INT) : (x*y=x) ;
I get "unknown (INCOMPLETE)".

But, when I submit  FORALL (x:INT) : (x*1=x) ;
I get "valid".

I have the feeling to miss something.
Could somenone help me please ?

**Comment by ajreynol** [comment]
Hi, 
CVC4 has only heuristic support for non-linear arithmetic + quantifiers. I've improved support for this in my latest PR (#1674).
Cheers,
Andy

**Comment by mcoulont** [comment]
Hi Andy

Even if Istudied mathematics and logic, I'm an amateur and my automated proving hobby is quite recent. Therefore my questions can be naive and show my lack of understanding.

Why a larger set of examples ? 
To make kind of built-in axioms which would give a new feature named "CEGQI for non-linear" ?

Hoping not to disturb you
Marc

**Comment by ajreynol** [comment]
By "larger set of examples", I mean if you had a set of benchmarks that we could performance test CVC4 on, that would be helpful in the future. Although no worries if you don't.

Internally, we use counterexample-guided quantifier instantiation (CEGQI) to handle problems with quantifiers + arithmetic (see http://homepage.divms.uiowa.edu/~ajreynol/fmsd17-instla.pdf, this is enabled by default when you run cvc4).
