### ISSUE TITLE
Hang on a certain simple regex constraint

### ISSUE THREAD

**Issue by Muon** [CVC4/CVC4#1684]
The following minimal testcase hangs on the current (Mar 8) Windows nightly build of CVC4.

```smt2
(set-logic QF_S)
(set-option :strings-std-ascii false)
(declare-const s String)
(assert (str.in.re s (re.* (re.range "\x00" "\xFF"))))
(assert (str.in.re s (re.range "\x00" "\xFF")))
(check-sat)
```

**Comment by ajreynol** [comment]
I can confirm this behavior.  This requires improvements to the regular expression solver in CVC4, I will take a closer look at this.

**Comment by ajreynol** [comment]
Hi,
Sorry for the delay in response.  Master CVC4 now solves this benchmark quickly after this commit:  

https://github.com/CVC4/CVC4/commit/c9f50eed48fa920320f93921415885f0042b9d39

Btw, this benchmark was very helpful to see (we are currently trying to further improve our reg exp solver). If you have others like it where CVC4 hangs, do send them.

Cheers,
Andy 

PS The option `strings-std-ascii` was renamed to `strings-print-ascii`.
