### ISSUE TITLE
Assertion failure with --solve-int-as-bv on regression test

### ISSUE THREAD

**Issue by 4tXJ7f** [CVC4/CVC4#1715]
CVC4 fails with an assertion failure when using --solve-int-as-bv on arith-interval.cvc

```
builds/bin/cvc4 --solve-int-as-bv=4 test/regress/regress0/arith/integers/arith-interval.cvc
Assertion failure
CVC4::expr::NodeValue* CVC4::NodeBuilder<N>::constructNV() [with unsigned int nchild_thresh = 10]
../../../../src/expr/node_builder.h:969:

  getNumChildren() >= kind::metakind::getLowerBoundForKind(getKind())
Nodes with kind APPLY_UF must have at least 1 children (the one under construction has 0)
```

**Comment by barrettcw** [comment]
Took a look at this - the issue is that solve-int-as-bv should only be allowed on pure QF_BV problems.

**Comment by 4tXJ7f** [comment]
Hm, do you mean QF_NIA? My understanding is that this pass takes an integer problem as input and turns it into a bitvector problem.

**Comment by barrettcw** [comment]
Oops - you are right - it needs to be QF_IDL, QF_LIA, or QF_NIA - it doesn't work with theory combination.
