### ISSUE TITLE
check-sat command not printed properly

### ISSUE THREAD

**Issue by ajreynol** [CVC4/CVC4#1744]

**Comment by ajreynol** [comment]
--dump=assertions crashes on TPTP inputs.  It prints check-sat-assuming with --dump=raw-benchmark in smt2 language.

**Comment by 4tXJ7f** [comment]
Actually, this might have been fixed in #1764 (if I understand the issue correctly). Would you mind double-checking?

**Comment by ajreynol** [comment]
The issue with crashing TPTP inputs is fixed. However, smt2 inputs with "check-sat" are still printed as "check-sat-assuming (true)".
