### ISSUE TITLE
Cardinality of string elements

### ISSUE THREAD

**Issue by LeventErkok** [CVC4/CVC4#1781]
According to http://cvc4.cs.stanford.edu/wiki/Strings#Alphabet CVC4 strings are composed of alphabets with 256 elements. The attached benchmark tries to generate all of them by enumerating the solutions returned by CVC4. Alas, it only generates 128 elements, those with ASCII codes 65 through 192.

I suspect this is a bug, but wanted to double check. Run the attached script with `cvc4 --incremental`, using a freshly built cvc4 using brew.

[b.smt2.txt](https://github.com/CVC4/CVC4/files/1913878/b.smt2.txt)

**Comment by 4tXJ7f** [comment]
Thank you for your report, @LeventErkok. I can reproduce this on the current master, it really looks like a bug. Btw. you don't have to run it with `--incremental` since it doesn't contain multiple `check-sat` commands.

**Comment by ajreynol** [comment]
Yes, you're right. The default cardinality for CVC4 is currently 128, which doesn't match the documentation on the webpage.  I've submitted a PR (#1783) to update the default cardinality to be 256.

**Comment by 4tXJ7f** [comment]
@LeventErkok To get the version of CVC4 with the fix, use `--HEAD` when installing from homebrew. Please let us know if you experience any further issues.
