### ISSUE TITLE
Unreachable code reached when printing a certain array proof

### ISSUE THREAD

**Issue by yoni206** [CVC4/CVC4#1790]
To reproduce:
run `CVC4/builds/bin/cvc4 --lang=smt2 --dump-proofs --no-bv-ineq --no-bv-algebraic` on examples from comments below.

**Comment by yoni206** [comment]
Status: trying to minimize input.

**Comment by 4tXJ7f** [comment]
Minimized to:
```
(set-logic QF_AUFBV)
(declare-fun _substvar_165_ () (_ BitVec 64))
(declare-fun _substvar_211_ () (_ BitVec 64))
(declare-fun _substvar_212_ () (_ BitVec 64))
(declare-fun _substvar_220_ () (_ BitVec 64))
(declare-fun mem___0 () (Array (_ BitVec 64) (_ BitVec 64)))
(declare-fun mem___2 () (Array (_ BitVec 64) (_ BitVec 64)))
(declare-fun mem___1 () (Array (_ BitVec 64) (_ BitVec 64)))
(assert (not (and (= ((_ extract 2 0) (bvadd _substvar_165_ (_ bv18446744073709551608 64))) (_ bv0 3)) (=> (= mem___1 (store mem___0 (_ bv0 64) (_ bv0 64))) (not (= mem___2 (store mem___1 (bvadd _substvar_165_ (_ bv18446744073709551600 64)) (_ bv0 64))))))))
(assert (not (=> (= _substvar_212_ (select mem___2 (bvadd _substvar_165_ (_ bv18446744073709551608 64)))) (not (= _substvar_211_ _substvar_212_)))))
(declare-fun mem___3 () (Array (_ BitVec 64) (_ BitVec 64)))
(assert (= mem___3 (store mem___2 (_ bv0 64) (_ bv0 64))))
(assert (= (_ bv0 64) (select mem___3 (bvadd _substvar_165_ (_ bv18446744073709551608 64)))))
(assert (= _substvar_220_ (bvadd (_ bv0 64) _substvar_211_)))
(assert (not (= ((_ extract 0 0) (bvadd _substvar_220_ (_ bv0 64))) (_ bv0 1))))
(check-sat)
```

**Comment by yoni206** [comment]
further minimized (lower bv-width)

`(set-logic AUFBV)
(declare-fun _substvar_212_ () (_ BitVec 16))
(declare-fun _substvar_211_ () (_ BitVec 16))
(declare-fun _substvar_165_ () (_ BitVec 16))
(declare-fun _substvar_220_ () (_ BitVec 16))
(set-option :produce-models true)
(declare-fun mem___0 () (Array (_ BitVec 16) (_ BitVec 16)))
(declare-fun mem___2 () (Array (_ BitVec 16) (_ BitVec 16)))
(declare-fun mem___1 () (Array (_ BitVec 16) (_ BitVec 16)))
(assert (= (=> (= mem___1 (store mem___0 (_ bv0 16) (_ bv0 16))) (=> (= mem___2 (store mem___1 (bvadd _substvar_165_ (_ bv184 16)) (_ bv0 16))) false)) false))
(assert (= (=> (= _substvar_212_ (select mem___2 (bvadd _substvar_165_ (_ bv18408 16)))) (=> (= _substvar_211_ _substvar_212_) false)) false))
(declare-fun mem___3 () (Array (_ BitVec 16) (_ BitVec 16)))
(assert (= (=> (= mem___3 (store mem___2 (_ bv0 16) (_ bv0 16))) false) false))
(assert (= (=> (= (_ bv0 16) (select mem___3 (bvadd _substvar_165_ (_ bv18408 16)))) false) false))
(assert (= (=> (= _substvar_220_ (bvadd (_ bv0 16) _substvar_211_)) false) false))
(assert (= (= ((_ extract 0 0) (bvadd _substvar_220_ (_ bv0 16))) (_ bv0 1)) false))
(check-sat)`

**Comment by nafur** [comment]
This issue concerns the old proof code as well. We thus close it
