### ISSUE TITLE
bv proofs with undeclared identifiers

### ISSUE THREAD

**Issue by yoni206** [CVC4/CVC4#1841]
Some proofs that are produced for bv are malformed, in the sense that an identifier is used before it is declared.

To reproduce, run `cvc4 --lang=smt2 --dump-proofs --no-bv-ineq --no-bv-algebraic --no-bv-eq smt.txt` (attached).
The resulted proof is also attached (plf.txt).
When checking it with lfsc, you get "Undeclared identifier: bb.cl36389".

And indeed,
`bb.cl36389` is used in line 20014, but is declared in line 20399 (with a `\ bb.cl36389`)

Note that smt.txt was minimized using ddSMT, but I didn't succeed in minimizing it further by making the bitvector width smaller.

[smt.txt](https://github.com/CVC4/CVC4/files/1965618/smt.txt)
[plf.txt](https://github.com/CVC4/CVC4/files/1965617/plf.txt)

**Comment by ajreynol** [comment]
Concerns the old proof code, closing this issue.
