### ISSUE TITLE
Undeclared symbol in CVC dump

### ISSUE THREAD

**Issue by 4tXJ7f** [CVC4/CVC4#1880]
We are getting the following error when running on the dump of the regression test from #1867:

```
Parse Error: <stdin>:9.10: Symbol 'pos' not declared as a variable

  ASSERT pos(d[r3]) = {r1};
         ^
```

**Comment by ajreynol** [comment]
This is no longer an issue in latest master https://github.com/CVC4/CVC4/commit/453de9df0af984491f6ced883220fdbf113f078b.
