### ISSUE TITLE
Coverity Scan is timing out

### ISSUE THREAD

**Issue by timothy-king** [CVC4/CVC4#1938]
Coverity scan is once again repeatedly timing out on Travis:
https://travis-ci.org/CVC4/CVC4/builds/379803800 . It is getting as far as compiling src/main/ in most iterations before timing out at ~50m. Results take minutes to upload. A more stable solution would be to decrease build times by ~10m (about 20% overall).

@barrettcw feel free to reassign if there is a better candidate to lead this effort.

**Comment by 4tXJ7f** [comment]
The Coverity hasn't been part of Travis for a while now (#2373), closing this out-dated issue.
