### ISSUE TITLE
Segfaults on bad sygus file

### ISSUE THREAD

**Issue by cdonovick** [CVC4/CVC4#1945]
Given a a synth-fun with and production rule with a let with more than 1  "body" GTerm i.e. matching 
`(let ((<Symbol> <SortExpr> <GTerm>)+) <GTerm> <GTerm>+)` 
instead of 
`(let ((<Symbol> <SortExpr> <GTerm>)+) <GTerm>)`
CVC4 will segfault.

Minimal example:
```smt
(set-logic LIA)

(synth-fun bad ((x Int)) Int (
	(Start Int (
		(let ((shared Int Start))
			(+ shared shared)
			(* shared shared)
		)
	))
))	
```

**Comment by ajreynol** [comment]
Thanks for the input, it doesn't surprise me that we don't exit gracefully on this.  Btw, I would strong advise against using "let" in sygus grammars. We support them to be complaint, but there isn't a lot of advantage in using them, above you could just do (* 2 Start) instead.
I will look into catching this error in the parser next week.
