### ISSUE TITLE
Assertion failure in MiniSat when doing incremental solving

### ISSUE THREAD

**Issue by 4tXJ7f** [CVC4/CVC4#1978]
Daniel found an issue with CVC4's incremental solving: https://github.com/CVC4/CVC4/issues/1349#issuecomment-391757556. His example results in the following error:

```
lt-cvc4: ../../../../src/prop/minisat/mtl/Alloc.h:64: T& CVC4::Minisat::RegionAllocator<T>::operator[](CVC4::Minisat::RegionAllocator<T>::Ref) [with T = unsigned int; CVC4::Minisat::RegionAllocator<T>::Ref = unsigned int]: Assertion `r >= 0 && r < sz' failed.
Aborted (core dumped)
```

**Comment by 4tXJ7f** [comment]
After delta debugging:
```
(set-logic ALL)
(declare-fun _substvar_29_ () Bool)
(declare-fun _substvar_30_ () Bool)
(declare-fun _substvar_36_ () Bool)
(assert (= false (and _substvar_29_ _substvar_30_)))
(check-sat)
(assert false)
(push 1)
(assert _substvar_36_)
(check-sat)
```

**Comment by nafur** [comment]
Both the original input from https://github.com/CVC4/CVC4/issues/1349#issuecomment-391757556 and the smaller instance from https://github.com/CVC4/CVC4/issues/1978#issuecomment-391882951 are solved without problems by the current master.
We can thus consider this fixed, I'll add a PR to add the smaller instance as regression test.
