### ISSUE TITLE
BV slicer assertion failure

### ISSUE THREAD

**Issue by 4tXJ7f** [CVC4/CVC4#1993]
The following assertion failure occurs on the incremental ABVFP/20170501-Heizmann-UltimateAutomizer/exp_loop_true-unreach-call.c.smt2 benchmark:

```
(error "Assertion failure.
virtual CVC4::Node CVC4::theory::bv::CoreSolver::getModelValue(CVC4::TNode)
../../../../src/theory/bv/bv_subtheory_core.cpp:465:

 d_slicer->isCoreTerm(var)
")
```

**Comment by aniemetz** [comment]
It seems that adding FP to ABV breaks an invariant in the core bv solver
When computing the care graph, getModelValue is called on a bv addition, but getModelValue of CoreSolver asserts that this is not possible, see comments by Liana here:
https://github.com/CVC4/CVC4/blob/master/src/theory/bv/bv_subtheory_core.cpp#L462

**Comment by aniemetz** [comment]
That's good and bad news at the same time :-)
Thanks for looking into this @martin-cs!

**Comment by martin-cs** [comment]
On Thu, 2018-05-31 at 13:18 -0700, Andres Noetzli wrote:
> He was able to minimize the example and after doing some additional
> minimization, we now have:
> 
> ```
> (set-logic ABV)
> ```

Additional minimisation!  I think QF_ABV  still triggers this problem.

**Comment by aniemetz** [comment]
#2057 addresses this problem.
