### ISSUE TITLE
Assertion failure in MiniSat on QF_NRA benchmarks

### ISSUE THREAD

**Issue by 4tXJ7f** [CVC4/CVC4#1998]
We get an assertion failure in MiniSat on certain QF_NRA benchmarks:
```
$ ./cvc4  /barrett/scratch/benchmarks/benchmark_repos/smtlib/QF_NRA/hycomp/ball_count_2d_slope.05.seq_lazy_lemmas_global_14.smt2
cvc4: ../../../../../../src/prop/minisat/simp/SimpSolver.cc:170: bool CVC4::Minisat::SimpSolver::addClause_(CVC4::Minisat::vec<CVC4::Minis
at::Lit>&, bool, CVC4::ClauseId&): Assertion `!isEliminated(var(ps[i]))' failed.
Aborted
```

Benchmarks:
```
non-incremental/QF_NRA/hycomp/ball_count_2d_slope.03.seq_lazy_global_14.smt2
non-incremental/QF_NRA/hycomp/ball_count_2d_slope.05.seq_lazy_lemmas_global_14.smt2
non-incremental/QF_NRA/hycomp/ball_count_2d_slope.02.seq_lazy_lemmas_global_14.smt2
non-incremental/QF_NRA/hycomp/ball_count_2d_slope.04.seq_lazy_lemmas_global_14.smt2
non-incremental/QF_NRA/hycomp/ball_count_2d_slope.02.seq_lazy_global_14.smt2
non-incremental/QF_NRA/hycomp/ball_count_2d_slope.01.seq_lazy_global_14.smt2
non-incremental/QF_NRA/hycomp/ball_count_2d_slope.02.seq_lazy_global_12.smt2
```

**Comment by ajreynol** [comment]
This is a duplicated of: https://github.com/CVC4/CVC4/issues/1040

I believe the assertion is too strong, the non-linear solver breaks a previously held invariant that one should not introduce literals that have been eliminated. 

I'm going to close the other issue and mark this one as minor.

**Comment by ajreynol** [comment]
Another option to resolve this, I think this block of code may be related:
https://github.com/CVC4/CVC4/blob/master/src/smt/smt_engine.cpp#L2200
It seems we explicitly disable this for some logics, which may in fact be for the same reason described above.  I am going to try to disable elimination for non-linear and see if it resolves the assertion failure, and whether there is an impact on performance.
