### ISSUE TITLE
Question: nightly builds on windows no longer produced?

### ISSUE THREAD

**Issue by pjljvandelaar** [CVC4/CVC4#2000]
On http://cvc4.cs.stanford.edu/downloads/builds/win32-opt/unstable/ the latest nightly build for windows are no longer provided.
Is this intentional? Or did something break?

**Comment by 4tXJ7f** [comment]
Thank you for bringing this to our attention. This is certainly not intentional. I'll take a look at why this is happening.

**Comment by 4tXJ7f** [comment]
I think I found the issue. If all goes well, we should have a Windows build after the nightly builds tomorrow. Btw. the new builds are going to be 64-bit, please let us know if you need 32-bit builds.

**Comment by pjljvandelaar** [comment]
64 bits are fine

**Comment by 4tXJ7f** [comment]
@pjljvandelaar Sorry about the delay, the Windows nightlies are now working again. You can find them here: http://cvc4.cs.stanford.edu/downloads/builds/win64-opt/unstable/

Please let me know if they work for you.

**Comment by pjljvandelaar** [comment]
Fine..  problem solved
