### ISSUE TITLE
Assertion failure in checkTfTangentPlanesFun

### ISSUE THREAD

**Issue by 4tXJ7f** [CVC4/CVC4#2032]
Flags: `--no-e-matching --no-quant-cf --full-saturate-quant`
File: AUFNIRA/aviation/bts5878_why.smt2

Error:
```
(error "Assertion failure.
bool CVC4::theory::arith::NonlinearExtension::checkTfTangentPlanesFun(CVC4::Node, unsigned int, std::vector<CVC4::NodeTemplate<true> >&)
../../../../src/theory/arith/nonlinear_extension.cpp:4171:

  v_pab.isConst()
")
```

**Comment by 4tXJ7f** [comment]
Minimized:
```
(set-logic AUFNIRA)
(declare-fun abs_real (Real) Real)
(assert (forall ((?xu103_67 Real)) (=> (<= ?xu103_67 0.0) (= (abs_real ?xu103_67) 0.0))))
(declare-fun log (Real) Real)
(assert (forall ((?xu104_68 Real)) (= (log (exp ?xu104_68)) ?xu104_68)))
(check-sat)
```

**Comment by ajreynol** [comment]
There is an issue here, "exp" is being treated as the exponential function, but I assume in the original SMT input "exp" was an uninterpreted function?  We likely need to guard the addition of trascendental functions with a logic.

Regardless, this does indicate there is an issue with trancendental functions + quantifiers.

**Comment by 4tXJ7f** [comment]
Yes, you are correct. Line 117 of the original input: `(declare-fun exp (Real) Real)`
