### ISSUE TITLE
Assertion failure in Aig_ManDupDfs

### ISSUE THREAD

**Issue by 4tXJ7f** [CVC4/CVC4#2037]
Flags: `--unconstrained-simp --bv-div-zero-const --bv-intro-pow2 --bitblast=eager --bv-sat-solver=cadical --bitblast-aig --bv-abstraction --bv-eq-slicer=auto`
File: QF_BV/sage/app1/bench_615.smt2

Error:
```
cvc4: src/aig/aig/aigDup.c:602: Aig_ManDupDfs: Assertion `p->pEquivs != NULL || Aig_ManBufNum(p) != 0 || Aig_ManNodeNum(p) == Aig_ManNodeNu
m(pNew)' failed.
```

**Comment by nafur** [comment]
Apparently, this has been fixed in the meantime:

> $ bin/cvc4 --version
This is CVC4 version 1.9-prerelease [git master 02fa1dea]
compiled with GCC version 9.3.0
on Aug 14 2020 12:55:05

> $ bin/cvc4 --unconstrained-simp --bv-div-zero-const --bv-intro-pow2 --bitblast=eager --bv-sat-solver=cadical --bitblast-aig --bv-abstraction --bv-eq-slicer=auto bench_615.smt2 
unsat

So I guess we can close it?

**Comment by aniemetz** [comment]
Hm, maybe this was only in combination with the EQ slicer, which is now gone. The current BV engine is soon to be depricated anyways. Yes, we can close this.
