### ISSUE TITLE
Illegal argument error

### ISSUE THREAD

**Issue by 4tXJ7f** [CVC4/CVC4#2041]
Flags: `--simplification=none`
File: AUFNIRA/nasa/vc_normalize_subst/cl5_nebula_norm_0019.fof.smt2

Error:
```
(error "Illegal argument detected
const T& CVC4::expr::NodeValue::getConst() const [with T = CVC4::Rational]
metakind.cpp:516:

  `*this' is a bad argument; expected getKind() == ::CVC4::kind::CONST_RATIONAL to hold
Improper kind for getConst<::CVC4::Rational>()")
```

**Comment by ajreynol** [comment]
It looks like this is related to #2036?

**Comment by 4tXJ7f** [comment]
I'll retest after #2052 has been merged.

**Comment by 4tXJ7f** [comment]
It looks like you are right @ajreynol. I ran on the benchmark for 5 minutes and the error did not occur anymore (competition build, commit af5832b). Closing this for now.
