### ISSUE TITLE
Assertion failure in preRegisterTermInternal

### ISSUE THREAD

**Issue by 4tXJ7f** [CVC4/CVC4#2045]
Flags: `--decision=internal --full-saturate-quant`
File: AUFBVDTLIA/20172804-Barrett/rec-fun-ijcar2016/wo-wdf/mutant_wo_fd_vcs_wdf/2.5-cvc4-AbsFun.scala-4.smt2-2.smt2

Error:
```
(error "Assertion failure.
void CVC4::theory::arrays::TheoryArrays::preRegisterTermInternal(CVC4::TNode)
../../../../src/theory/arrays/theory_arrays.cpp:653:

  d_isPreRegistered.find(node) != d_isPreRegistered.end()
")
```

**Comment by ajreynol** [comment]
I can't seem to reproduce this one, maybe it was recently fixed? Can you retest or send me a minimized example?

**Comment by 4tXJ7f** [comment]
I am able to reproduce it with that commit (simple debug build `./configure debug`).

**Comment by ajreynol** [comment]
got it now, i think i copied the wrong benchmark.

**Comment by ajreynol** [comment]
This seems to be a minor issue, I think the assertion is wrong.  I will submit a PR that makes it so that we don't get this assertion failure.
