### ISSUE TITLE
CVC4 equivalent of Z3's seq.unit

### ISSUE THREAD

**Issue by OrenGitHub** [CVC4/CVC4#2075]
Hi,
(This question is cross posted on SO [here](https://stackoverflow.com/questions/50885233/cvc4-equivalent-of-z3s-seq-unit))
I'm trying to run the following unsat example with both Z3 and CVC4.
If I replace **"\x00"** with **(seq.unit #x00)** then it's not a problem for Z3,
but CVC4 complains it doesn't know seq.unit.

    (declare-fun AB_serial_1_version_0 () String)
    (declare-fun AB_serial_1_version_1 () String)
    
    (assert (= (str.len AB_serial_1_version_0) 16))
    (assert (= (str.len AB_serial_1_version_1) (str.len AB_serial_1_version_0)))
    (assert (= (str.at AB_serial_1_version_1 15) "\x00"))
    ;;; (assert (= (str.at AB_serial_1_version_1 15) (seq.unit #x00)))
    
    (assert (= (str.indexof (str.substr AB_serial_1_version_1 0 (- 16 0)) "\x00" 0) (- 0 1)))
    (check-sat)

Here is the command line call:

    cvc4 --strings-exp --quiet --produce-models --lang=smt2 ./example.txt

And here is what cvc4 complains about when I use the seq.unit line instead:

    (error "Parse Error: ./example.txt:7.54: Symbol 'seq.unit' not declared as a variable

    ...= (str.at AB_serial_1_version_1 15) (seq.unit #x00)))
                                            ^
    ")

I guess there is some equivalent in CVC4 right?
I mean converting a bit vector 8 to a length 1 String.
Thanks!

**Comment by ajreynol** [comment]
Thanks for the benchmark.  Unfortunately there isn't anything that converts between bitvectors and strings at the moment. 

We are planning to add support for sequences soon (issue #1122). Although of course there isn't an SMT standard for sequences yet.  I will keep this issue in mind when we add support for sequences.

**Comment by OrenGitHub** [comment]
Thanks @ajreynol , so just to be sure, if I want to perform the equivalent of **to-Upper**,
I will have to do something equivalent to the following "home-made" bit blasting
(shown just for index 2, and only 4  first lower case letters are considered):

    (declare-const before String)
    (declare-const after  String)
    
    (assert (= (str.len before ) (str.len after)))
    
    (assert (= (str.at after 2)
    (ite (= (str.at before 2) "a") "A"
    (ite (= (str.at before 2) "b") "B"
    (ite (= (str.at before 2) "c") "C" "D")))))
    ;;; etc. etc.
    
    (assert (= before "aDbMT"))
    (check-sat)
    (get-value (before after))

**Comment by ajreynol** [comment]
Actually, there is a nice way to do this in CVC4 that doesn't rely on bit-vectors.  CVC4 supports a new operator "str.code" of type String -> Int, which converts between one-character strings and an integer corresponding to the "code" of that character. So for example, str.code( "A" ) = 65, str.code( "a" ) = 97.  By convention, strings that are not one character are mapped to -1, so str.code( "" ) = str.code( "AB" ) = -1. Using this operator, you can define a predicate that holds exactly when one string is the upper-case conversion of the other:

```; y is the result of converting x to upper-case
(define-fun isUpper ((x String) (y String)) Bool
(and (= (str.len x) (str.len y))
(forall ((i Int)) (=> 
(and (<= 0 i) (< i (str.len x)))
(= (str.code (str.at y i))
(ite (and (<= 97 (str.code (str.at x i))) (<= (str.code (str.at x i)) 122))
  (- (str.code (str.at x i)) 32)
  (str.code (str.at x i))))))))
```

Notice that I am subtracting 32 from the code when character i of x is a lower case letter. Given this benchmark:

```(set-logic ALL)
(set-option :strings-exp true)
(set-option :produce-models true)
(declare-const before String)
(declare-const after  String)

(assert (= (str.len before ) (str.len after)))

; y is the result of converting x to upper-case
(define-fun isUpper ((x String) (y String)) Bool
(and (= (str.len x) (str.len y))
(forall ((i Int)) (=> 
(and (<= 0 i) (< i (str.len x)))
(= (str.code (str.at y i))
(ite (and (<= 97 (str.code (str.at x i))) (<= (str.code (str.at x i)) 122))
  (- (str.code (str.at x i)) 32)
  (str.code (str.at x i))))))))

(assert (= before "aDbMT"))
(assert (isUpper before after))
(check-sat)
(get-value (before after))```

CVC4 quickly responds with:

```sat
((before "aDbMT") (after "ADBMT"))
```

**Comment by OrenGitHub** [comment]
That's helpful, thanks!
I guess it's interesting CVC4 has

    str.code: (one-letter) String ---> Int

and Z3 has

    seq.unit: BV8 ---> (one-letter) String ...

**Comment by OrenGitHub** [comment]
Actually, when I think of it, what's wrong with **implementing seq.unit** by **combining** `bv2nat` and `str.code`? like this example here which gives correct results pretty fast:

    (declare-const before String)
    (declare-const after  String)
    (declare-const c (_ BitVec 8))
    
    (assert (= (str.len before ) (str.len after)))
    
    ; y is the result of converting x to upper-case
    (define-fun isUpper ((x String) (y String)) Bool
    (and (= (str.len x) (str.len y))
    (forall ((i Int)) (=> 
    (and (<= 0 i) (< i (str.len x)))
    (= (str.code (str.at y i))
    (ite (and (<= 97 (str.code (str.at x i))) (<= (str.code (str.at x i)) 122))
      (- (str.code (str.at x i)) 32)
      (str.code (str.at x i))))))))
    
    ;;;(assert (= before "aDbMT"))
    
    (assert (= (str.len before) 10))
    
    (assert (< (str.indexof before "a" 0) (str.indexof before "b" 0)))
    (assert (> (str.indexof before "a" 0) 0))
    
    (assert (and (<= 99 (str.code (str.at before 5))) (<= (str.code (str.at before 5)) 103)))
    
    (assert (= (bv2nat c) (str.code (str.at before 5))))
    
    (assert (bvslt c #x66))
    
    (assert (isUpper before after))
    (check-sat)
    (get-value (before after c))

**Comment by ajreynol** [comment]
Yes, that's true, you could do this. :)

One thing to be careful about is that the cardinality of the bit-vectors you are using fits the range of the alphabet of the strings (bit-vectors whose bv2int value is greater than 256 cannot be assigned a code). Also, we haven't spent much time optimizing bv2nat in CVC4, so it may not be as fast as it could be.

But feel free to send further benchmarks if you run into any other issues.

**Comment by OrenGitHub** [comment]
Thanks!
