### ISSUE TITLE
Cvc4 1.6 was released yet no windows binary available

### ISSUE THREAD

**Issue by pjljvandelaar** [CVC4/CVC4#2152]
As a cvc4 user I would like to use the latest release. Unfortunately I can't find a binary windows version at http://cvc4.cs.stanford.edu/downloads/.
Do I look in the wrong location?
Or is the windows version not yet available?

**Comment by 4tXJ7f** [comment]
It looks like the binary was either not generated or not uploaded. I am looking into it.

**Comment by 4tXJ7f** [comment]
The binary is now available at http://cvc4.cs.stanford.edu/downloads/builds/win64-opt/ . Please let me know if you experience any issues.

**Comment by pjljvandelaar** [comment]
Thanks!
