### ISSUE TITLE
Timeout via the C++ API?

### ISSUE THREAD

**Issue by leonardoalt** [CVC4/CVC4#2174]
Hi all,
Is there a way to give a time limit (similar to `--tlimit` or `--tlimit-per`) via the C++ API?

**Comment by 4tXJ7f** [comment]
Yes, you can use [`SmtEngine::setTimeLimit()`](https://github.com/CVC4/CVC4/blob/d4c49e755a53e7333c7638a5aeafe8baa2ea56d3/src/smt/smt_engine.h#L841), which allows you to specify a timeout in milliseconds.
