### ISSUE TITLE
Where is the configure file in the root directory?

### ISSUE THREAD

**Issue by swagatata** [CVC4/CVC4#2175]
The installation instructions both in the INSTALL file and in http://cvc4.cs.stanford.edu/wiki/Building_CVC4_from_source mention running 

`./configure `

But there is no configure file in the repo.

**Comment by mpreiner** [comment]
`./configure` is packaged with source release tarballs. If you want to compile from a repository checkout you first have to run `./autogen.sh`, which will create the `./configure` script. This step is described in the section `Building CVC4 from a repository checkout`.
