### ISSUE TITLE
kons iş ilanları

### ISSUE THREAD

**Issue by gf3107** [CVC4/CVC4#2176]
[xn--konsiilanlar-d5b05d.com](url)
Kons Bayan iş ilanları, solist ilanları, dansöz ilanları, Konsomatris iş ilanları, flaş menejerlik güvencesi ile konsişilanları.com

**Comment by martin-cs** [comment]
Spam

**Comment by gf3107** [comment]
is not spam 
www.konsişilanları.com

**Comment by martin-cs** [comment]
This is for reporting issues with CVC4, in English.  It is not for advertising Turkish websites.  Please stop doing this; no-one is following the links or translating the test.

**Comment by gf3107** [comment]
thanks for interested.
