### ISSUE TITLE
Potentially wrong result when down-casting floating-point numbers using RNA rounding

### ISSUE THREAD

**Issue by 4tXJ7f** [CVC4/CVC4#2183]
Z3 and CVC4 report a different result on the following benchmark:
```
(set-logic QF_FP)
(declare-fun r () (_ FloatingPoint 5 9))
(assert (= (fp #b1 #b00000 #xff) ((_ to_fp 5 9) RNA (fp #b1 #b00000 #b1111111110))))
(check-sat)
```

Z3 reports `sat` while CVC4 reports `unsat`. My MPFR wrapper agrees with Z3, so chances that this is a bug in CVC4/symfpu are non-zero.

**Comment by 4tXJ7f** [comment]
Interestingly, it looks like Z3 4.7.1 agrees with CVC4 (the `sat` answer was the [online](https://rise4fun.com/z3) version). It also makes more sense given the input but I am leaving this issue open to confirm that CVC4's answer of `(fp #b1 #b00001 #x00000000)` for the conversion is indeed correct.

**Comment by martin-cs** [comment]
It should be UNSAT because the value does indeed round to `(fp #b1 #b00001 #x00000000)`.  @florianschanda did report some bugs in Z3, especially around RNA so there change is likely a fix of that issue.  However I added it as a regression test : https://github.com/CVC4/CVC4/pull/3008

**Comment by 4tXJ7f** [comment]
For the record, I've tested it again with a recent Z3 version (commit bd46c52f959e01ac7c65bbf634994c6e9649f927) and it answered `unsat`.

**Comment by 4tXJ7f** [comment]
Closing the issue since we've determined that CVC4's answer was correct.
