### ISSUE TITLE
Error during configure: unit: command not found

### ISSUE THREAD

**Issue by yurivict** [CVC4/CVC4#2188]
I'm seeing this on FreeBSD:
```
checking for cxxtestgen... no
../../../configure: line 25437: unit: command not found
usage: basename string [suffix]
       basename [-a] [-s suffix] string [...]
checking for /usr/local/bin/python3.6... /usr/local/bin/python3.6
```

**Comment by 4tXJ7f** [comment]
Thanks a lot for the report. Could you post your builds/config.log? I'll take a closer look at what's going on.

**Comment by 4tXJ7f** [comment]
Hmm, the config.log does not contain any more details unfortunately. Would you mind sharing your `configure` file as well? The line of the error does not seem to match anything useful in my `configure`. Thanks!

**Comment by yurivict** [comment]
[configure-with-log-ext.log](https://github.com/CVC4/CVC4/files/2216725/configure-with-log-ext.log)
