### ISSUE TITLE
CVC4 cannot differentiate between `QF_SEP` and `QF_S`

### ISSUE THREAD

**Issue by ayveejay** [CVC4/CVC4#2230]
As part of #2229, it would be good to add a test that validates that a `RecoverableModalException` is raised if (e.g.,) `getHeadExpr` is called without using `QF_SEP`.

However, currently it is only possible use separation logic with `QF_ALL_SUPPORTED`. If you try to use `QF_SEP`, then CVC4 thinks it is `QF_S` (for strings) with the extra characters `EP` on the end:

```
LogicInfo::setLogicString(): junk ("EP") at end of logic string: QF_SEP
```

**Comment by ajreynol** [comment]
It's true, separation logic has not been incorporated into logic. The only way to use it is with "ALL" or "ALL_SUPPORTED".  

If we did want to add this to logic strings, I think separation logic isn't a normal theory so I'd be in favor of making it a separate part of the logic string, e.g.:
`QF_SEP_UF`
`QF_SEP_LIA`
etc.

**Comment by ayveejay** [comment]
This isn't actually a big deal to me (and it was probably a known thing); I opened the case more so it wouldn't get forgotten and might get actioned in the future.

Testing the "failure" of the "heap API" was possible by using QF_IDL and requesting the heap in a "stupid way".
