### ISSUE TITLE
 Symbol 'bvlshr' not declared as a variable

### ISSUE THREAD

**Issue by jgaleotti** [CVC4/CVC4#2241]
Hi,
CVC4 Version 1.4 accepts the bit vector operation bvlshr (defined in the SMTLib format). For example, given the following SMTLib query:

```

(set-logic SLIRA)
(set-option :produce-models true)
(set-option :strings-exp true)
(declare-fun var1 () Int)
(declare-fun var0 () Int)
(assert (= var1 10))
(assert (= var0 (ite (<= (bv2nat (bvlshr ((_ int2bv 32) var1) ((_ int2bv 32) 1))) 2147483647) (bv2nat (bvlshr ((_ int2bv 32) var1) ((_ int2bv 32) 1))) (- (bv2nat (bvadd (bvxor (bvlshr ((_ int2bv 32) var1) ((_ int2bv 32) 1)) ((_ int2bv 32) (- 1))) ((_ int2bv 32) 1)))))))
(check-sat)
(get-model)
(exit)
```

And the CVC4 command:
` cvc4  --rewrite-divk --lang smt --finite-model-find --tlimit=1000 query_bvlshr.smt`

The output of CVC4 Version 1.4 is:
```
.smt 
sat
(model
(define-fun var1 () Int 10)
(define-fun var0 () Int 5)
)
```

When the same command is executed on CVC4 versions 1.5 or 1.6, the output is a parse error:
```

(error "Parse Error: query_bvlshr.smt:8.40: Symbol 'bvlshr' not declared as a variable

  (assert (= var0 (ite (<= (bv2nat (bvlshr ((_ int2bv 32) var1) ((_ int2...
                                    ^
")
```

**Comment by andrewvaughanj** [comment]
Not an official reply by any means: but why are you using `bv` expressions in a `SLIRA` instance? If I change your logic from `SLIRA` to `QF_ALL_SUPPORTED` then it works "as expected".

I would guess that CVC4 has been "fixed" to not allow `bv` expressions when the BV theory has not been selected.

**Comment by jgaleotti** [comment]
My bad. I will close the issue.
