### ISSUE TITLE
www.felixnonwovens.com

### ISSUE THREAD

**Issue by asd-meryem** [CVC4/CVC4#2278]
PP spunbond nonwoven,Surgical Drape fabric,Ceramic waterproofing membrane

Nonwovens, Films and Laminates Felix is a diversified supplier of nonwovens, films and laminates. Cutting edge technological competence in all our manufacturing sites results in high performance products available throughout the Felix. Spunbond nonwoven, thermal bonding, fiber spinning, polymer extrusion, film production, lamination, printing , slitting, polymer mixing and various surface treatments are all part of Felix technology portfolio.

http://www.felixnonwovens.com

**Comment by martin-cs** [comment]
Spam.
