### ISSUE TITLE
get-unsat-assumptions response does not comply with SMT-LIB format

### ISSUE THREAD

**Issue by daniel-larraz** [CVC4/CVC4#2298]
When I run CVC4 (in incremental mode) with the attached file [two_counters.lus.ic3.1.zip](https://github.com/CVC4/CVC4/files/2283553/two_counters.lus.ic3.1.zip) I get:

[__ic3_clause_4_n1_0, __ic3_clause_4_n1_4, __ic3_frame_0]

Expected output:

(__ic3_clause_4_n1_0 __ic3_clause_4_n1_4 __ic3_frame_0)

**Comment by 4tXJ7f** [comment]
Thanks for the report. This should be an easy fix.
