### ISSUE TITLE
Hard Kind2-BMC problems for CVC4

### ISSUE THREAD

**Issue by daniel-larraz** [CVC4/CVC4#2305]
Hello,

Attached you can find a set of [SMT scripts](https://github.com/CVC4/CVC4/files/2288492/BMC.zip) to be solved in incremental mode that Z3 and Yices 2 can solve in seconds, but CVC4 can not solve in minutes.

Could you please take a look at them to check if there is something you can do?

Thank you,
Daniel

**Comment by ajreynol** [comment]
Thanks for the benchmarks.

For internal discussion:

As an initial step, I've profiled and found that arithmetic's propagate method is consistently 40% of the run time on these benchmarks.  Using the option `--new-prop`, this decreases to 8%. We should aim to make this option default.

**Comment by daniel-larraz** [comment]
If you take a look at the logic of the SMT problems that I uploaded, you can see it does not include any restrictions at all (it is the predefined symbol ALL). Although this is not a big deal for Z3 and Yices 2, it makes a big difference for CVC4. In fact, I found that providing a specific logic for these problems is enough for solving all the original Lustre models with a time limit of 2 minutes per problem. However, even doing that, the total time that it takes to solve all the problems using CVC4 is much longer than the total time that it takes when using Z3 or Yices 2.

So after you improved the code, I performed the following tests:

First, I ran Kind 2 with CVC4 again over the original 41 Lustre models using your suggested flags (--decision=internal --ext-rew-prep --ext-rew-prep-agg) and the "ALL" logic. Kind 2 could find a counterexample for 31 of the 41 models using a time limit of 2 minutes per problem. That is a considerable improvement with respect to the original situation, but there were still 10 problems that could not be solved with this setting.

Then I repeated the experiment, but providing a specific logic this time. In this case, Kind 2 could solve the 41 problems in a time comparable to the one that it takes when using Z3. I extended the experiment to the whole set of benchmarks, and I got similar results (same number of solved problems in comparable amount of time). In other words, the combination of using a specific logic and the suggested command-line options made CVC4 competitive with respect to Z3.

Since providing a specific logic is not a problem in our context, I do not consider the current performance of CVC4 a major issue anymore. However, notice there is room for improvement. First, by reducing the time differences of solving the problems when the logic is provided or not. But secondly, by improving the solving times even when the logic is provided. Although CVC4 times are comparable to Z3 times, Yices 2 outperforms Z3 and CVC4 for the SMT problems generated by Kind 2.

For instance, Z3 (4.7.1) can solve all the 41 SMT problems on my laptop in 64s (with a specific logic) and in 74s (with the ALL logic). Whereas Yices 2 (2.6.0) can solve all 41 SMT problems in 7.25s (with a specific logic) and in 23s (with the ALL logic). See this [attachment](https://github.com/CVC4/CVC4/files/2340770/BMC_with_logic.zip) for a version of the problems with a specific logic.

As a final note. Here are some concrete numbers of how Kind 2 performs with different SMT solvers over our benchmark set (896 problems):

Safe: Z3 (485 in 694s), Yices 2 (481 in 412s), CVC4 (478 in 878s)

Unsafe: Z3 (379 in 551s), Yices 2 (379 in 392s), CVC4 (379 in 493s)

**Comment by barrettcw** [comment]
Thanks for the update Daniel.  Glad to see that we have made significant
progress here.  Clearly, there is still more that can be done though.

-Clark

**Comment by ajreynol** [comment]
Closing this issue now that #2633 was merged.
