### ISSUE TITLE
FitAdim.com - Fit Adım

### ISSUE THREAD

**Issue by emreuysal23** [CVC4/CVC4#2406]
FitAdim.com kişisel blog sayfası; antrenman, beslenme, yaşam ve sağlık ile ilgili aradığınız bir çok bilgiyi bulabileceğiniz en önemli kaynaklarınızdan biri olacaktır. 

**[FitAdim.com - Fit Adım](https://fitadim.com/)**

Ayrıca sosyal medya hesapları da mevcut. 

**[Facebook.com/Fitadimcom](https://www.facebook.com/Fitadimcom)** 

**[Twitter.com/fitadim](https://twitter.com/fitadim)** 

**[Instagram.com/fitadim](https://www.instagram.com/fitadim/)**

**Comment by martin-cs** [comment]
SPAM
