### ISSUE TITLE
Men Jewelry Design

### ISSUE THREAD

**Issue by tyrandesign** [CVC4/CVC4#2414]
Way from the Vatican outside the gorgeously decorated, high-walled palaces of the aristocratic cardinals, there was a very different Rome. The Rome of a sweaty, yelling crowd, a hundred thousand of them jostling in the markets and the piazzas, the Rome of sour wine, old garlic, street urchins, shifty part-time soldiers who’d cut your purse or your throat, just as soon as look at you.

The Rome of beggars, buskers, tumblers, quacks and whores. Thousands of them working away in the Ortaccio, the evil Eden down by the river Tiber. This was Caravaggio’s Rome, cheap rooms and drunken nights with other perpetually broke painters, living on their wits and shady credit, up for bother, always on the fly. Their motto as they prowled the streets,

Nec Spe, Nec Metu, ”without hope, without fear”

Men Jewelry Design   www.tyrandesign.com

**Comment by tyrandesign** [comment]
www.tyrandesign.com

**Comment by martin-cs** [comment]
SPAM
