### ISSUE TITLE
Illegal argument error

### ISSUE THREAD

**Issue by LiuShellway** [CVC4/CVC4#2429]
I met an error with the attached file. Could you please help me check where the problem is?

Command:
 cvc4 test.smt2 --strings-exp

Error:
(error "Illegal argument detected
CVC4::theory::TheoryId CVC4::theory::kindToTheoryId(CVC4::Kind)

  `k' is a bad argument
bad kind")

[test.txt](https://github.com/CVC4/CVC4/files/2353297/test.txt)

**Comment by ajreynol** [comment]
I can confirm this behavior.  I am working on a fix.

**Comment by ajreynol** [comment]
Hello, thanks for reporting this error. I've fixed this in PR #2444, which should be merged soon.

Btw, CVC4 natively supports a conversion from strings to bytes, `str.code`. Hence you can use this alternative definition in your encoding:

`(define-fun byte_2_int ((s String)) Int (ite (= (str.len s) 1) (str.code s) 256))`

This makes the updated CVC4 solve your problem in .6 seconds (as opposed to 13 seconds).

**Comment by LiuShellway** [comment]
Thanks for the info. I will try that.
