### ISSUE TITLE
cvc4 does not terminate with --tlimit=5000 when --fmf-fun-rlv is enabled

### ISSUE THREAD

**Issue by yoni206** [CVC4/CVC4#2438]
`cvc4 --lang=smt2 --tlimit=5000 --fmf-fun-rlv file.txt` does not terminate, where file.txt
 is attached.

[file.txt](https://github.com/CVC4/CVC4/files/2359088/file.txt)

**Comment by ajreynol** [comment]
Closing this since it is subsumed by #2908.
