### ISSUE TITLE
Better Error Reporting for Tests that timeout.

### ISSUE THREAD

**Issue by alex-ozdemir** [CVC4/CVC4#2560]
## Overview
One would expect that invoking a beefy regression test with a 2-second time limit would result in that time limit being exceeded. And indeed, it does, however the output of the test in this situation does not communicate that exceeding the time limit was the cause of the failure.

## Steps to Reproduce
1. Build CVC4
2. Run `TEST_TIMEOUT=2 ctest --output-on-failure -j1 -R regress4/instance_1151.smt`
3. See the following output 4 seconds later
```
Test project /home/aozdemir/repos/CVC4/build
    Start 1765: regress4/instance_1151.smt
1/1 Test #1765: regress4/instance_1151.smt .......***Failed    4.05 sec
1..2
# Starting
not ok - Differences between expected and actual output on stdout - Flags: []
*** 

--- 

***************

*** 0 ****

--- 1 ----

+ sat

Error output:

not ok - Differences between expected and actual output on stdout - Flags: ['--check-models']
*** 

--- 

***************

*** 0 ****

--- 1 ----

+ sat

Error output:



0% tests passed, 1 tests failed out of 1

Label Time Summary:
regress4    =   4.05 sec*proc (1 test)

Total Test time (real) =   4.08 sec

The following tests FAILED:
	1765 - regress4/instance_1151.smt (Failed)
Errors while running CTest
```
4. Notice the difference between the actual behavior (above) and the expected behavior (some message indicating that the time limit was exceeded).

## Relevant information

`ctest` is our new test runner and to get it to show *any* test output you need to pass the `--output-on-failure` flag.

Ultimate `test/regression/run_regression.py` runs the regression tests, and it is probably where the change needs to happen.

**Comment by mpreiner** [comment]
The problem here is that using `TEST_TIMEOUT` only sets the timeout for the regression script, but a timeout is not communicated to ctest (not sure if that is possible). You can use ctest itself to set a time limit with `ctest --timeout 2 ...`.

**Comment by alex-ozdemir** [comment]
Yep! My apologies for forgetting to close this.
