### ISSUE TITLE
Do not terminate when calling (get-info :reason-unknown) after sat/unsat

### ISSUE THREAD

**Issue by 4tXJ7f** [CVC4/CVC4#2584]
Right now, we are terminating if the user calls `(get-info :reason-unknown)` after a sat/unsat answer (see quoted email below). This is not very user-friendly. We should just output an error and continue accepting commands. Should be a fairly easy fix.

> Hi Andres,
> 
> Thanks for the answer. I tried to play with that but I'm annoyed with 
> the behavior of CVC4 in case I issue a command "(get-info 
> :reason-unknown)" after a "(check-sat)" that did not result in "unknown" 
> (but "sat" or "unsat"): CVC4 prints an error message:
> 
> (error "Can't get-info :reason-unknown when the last result wasn't 
> unknown!")
> 
> which is not a problem, but also terminates abruptly with error code 1. 
> It would be much more convenient if the process continue to interpret 
> further commands. Is there any way to overcome that behavior?
> 
> I tried to use the same "get-info" with Z3 and I'm quite happy that it 
> works. I would be glad to be able to do the same with CVC4!
> 
> Thanks in advance for any suggestions,
> 
> - Claude

**Comment by ajreynol** [comment]
Note: this is related to https://github.com/CVC4/CVC4/issues/1044
