### ISSUE TITLE
Work and Travel 

### ISSUE THREAD

**Issue by veli90** [CVC4/CVC4#2619]
<a href="https://troyint.com/">Work and Travel</a> programı, Amerika Birleşik Devletleri tarafından resmi olarak sınırları belirlenmiş ve desteklenen bir kültürel değişim programıdır. Work and Travel programı, şartları programa katılıma uygun üniversite öğrencilerine yaz tatillerini Amerika’da değerlendirerek uluslararası bir kültürel değişim yaşama ve tecrübe edinme fırsatını sunar. Work and Travel katılımcılarına özel bilgi ve beceri gerektirmeyen sezonel işlerde maksimum 4 ay süre ile Amerika’da çalışma ve kalma hakkı veren program, öğrencilere edinecekleri tecrübeyi minimum maliyete getirebilme olanağı sağlar. İsteyen öğrenciler program bitiminde toplam program süresini aşmayacak şekilde 25 güne kadar Amerika’da seyahat ve eğlenme amaçlı da kalabilirler.

Bu sayede`[ Work and Travel ](https://troyint.com/)`katılımcıları, yaşam masraflarını karşılayarak minimum maliyetle bir yazlarını Amerika’da geçirme imkânı elde eder ve Amerikan kültürünü yakından tanıma, farklı kültürlerden insanlarla tanışma, kendi kültürünü yeni insanlara aktarma, zengin tecrübelerle ülkelerine dönebilirler. Bu program sayesinde evrensel dil olarak görülen İngilizce bilgi ve becerilerinizi, bu dilin konuşulduğu bir ülkede yaşayarak geliştirme imkanı yakalayabilirsiniz. Bu benzersiz deneyim sayesinde insanlarla iletişim kurma yeteneğinizi geliştirip, Amerika’da yaşamış olmanın verdiği tecrübe ile ufkunuzun genişlediğini göreceksiniz.

**Comment by martin-cs** [comment]
SPAM.
