### ISSUE TITLE
Potential termination issue in strings

### ISSUE THREAD

**Issue by 4tXJ7f** [CVC4/CVC4#2626]
The following input does not terminate within three seconds when run with `--strings-fmf --strings-exp --decision=internal --tlimit 3000`:

```
(set-logic SLIA)
(declare-const x String)
(declare-const n Int)
(assert (not (= (str.replace x "0" "") (str.replace x (int.to.str n) ""))))
(check-sat)
(get-model)
```

**Comment by ajreynol** [comment]
This is with decision=internal, which strings isn't optimized for. Regardless I'll have a look. It may be due to a fairness issue when strings-fmf and UF fmf are combined (the latter is due to the fact that the reduction for int.to.str involves UF).
