### ISSUE TITLE
./configure.sh --static doesn't generate a statically linked binary

### ISSUE THREAD

**Issue by martin-cs** [CVC4/CVC4#2672]
$ ./configure.sh debug --symfpu --prefix=/home/martin/install/CVC4-fp-debug --static --debug-symbols
...
$ file ~/install/CVC4-fp-debug/bin/cvc4 
/home/martin/install/CVC4-fp-debug/bin/cvc4: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=cbc60e7d50af2a4733c79dc4f25e01116580b8f3, not stripped

Using master at c5982fa8f .

**Comment by mpreiner** [comment]
Try `--no-unit-testing`. When we compile debug with unit tests we force a shared build, otherwise you end up with very large unit test binaries. There should be actually a warning during configure phase (https://github.com/CVC4/CVC4/blob/master/CMakeLists.txt#L198).

**Comment by martin-cs** [comment]
On Tue, 2018-10-23 at 20:56 -0700, Mathias Preiner wrote:
> Try `--no-unit-testing`. When we compile debug with unit tests we
> force a shared build, otherwise you end up with very large unit test
> binaries. There should be actually a warning during configure phase (
> https://github.com/CVC4/CVC4/blob/master/CMakeLists.txt#L198).

That seems to do the trick.  I completely missed the warning.  If
static linking and unit tests are incompatable and static linking is
off by default, could we have --static imply --no-unit-testing?

**Comment by 4tXJ7f** [comment]
Yeah, I think that it would be a good idea to have `--static` imply `--no-unit-testing`.
