### ISSUE TITLE
Logo Destek Merkezi

### ISSUE THREAD

**Issue by SysEngineer27** [CVC4/CVC4#2693]
[http://www.norabilisim.com/logo-destek/](url)
Logo Destek ekibi olarak firmaların şirket hedeflerine ulaşmasını sağlayacak iş gereksinimlerini logo destek, logo servis ve logo danışmanlık metodolojisiyle tespit ederek, gerek bakım anlaşmalı yerinde logo destek, uzak logo destek ve telefon ile logo destek hizmetlerimiz, gerekse çağrı bazlı logo destek ve logo servis hizmetlerimizle, LOGO ürün grubu kapsamındaki (Start, Go 3, Tiger 3, Tiger 3 Enterprise, Bordro Plus) yazılımlardan ve logo çatısı altındaki diğer ürünlerden maximum kullanıcı performansı ve maximum verim alabilmenizi sağlamaktayız. Şimdi sizlere sağladığımız logo destek hizmetlerimizle yaptığınız yatırımın karşılığını almak zamanı.

**Comment by martin-cs** [comment]
SPAM.
