### ISSUE TITLE
autogen.sh not present in the downloaded cvc4 sources.

### ISSUE THREAD

**Issue by avritichauhan** [CVC4/CVC4#2700]
I downloaded cvc4 sources from this link: 
https://cvc4.cs.stanford.edu/downloads/builds/src/cvc4-1.6.tar.gz

As given in the INSTALL file, for building CVC4, the first step:
./autogen.sh

But I am unable to locate this file anywhere in the downloaded package.

**Comment by 4tXJ7f** [comment]
For the source distribution of CVC4 1.6, you can skip this step and directly proceed to `./configure`. `./autogen.sh` was only necessary when cloning from Github.

Note that we switched to CMake for newer versions of CVC4. If you are interested in building current master, the steps are a bit different (see the current INSTALL file for details).

**Comment by avritichauhan** [comment]
I cloned cvc4 master from github. As suggested, according to the steps given in the current INSTALL, the following steps were used to build cvc4 without GLPed libraries ( as per our requirement):
./configure --no-gpl
cd ./build
**make**

While making, we get the following linking error(build for src/libcvc4.so.5' failed) as shown in the attached screen shot:
![cvc4so_failed](https://user-images.githubusercontent.com/24314631/48353137-ae71de80-e6b4-11e8-88db-8d951df2a325.png)

Please provide your suggestions to resolve this error.

Note: I have used **CVC4/contrib/gmp** to install GMP libraries.

**Comment by 4tXJ7f** [comment]
We should have a better check for that a `configure` time. The issue is that `contrib/get-gmp` only compiles a static version of the GMP libraries. I'd recommend to remove the GMP folder that has been created in your CVC4 directory, then installing GMP via the package manager of your Linux distribution, and then to reconfigure and recompile CVC4. Sorry about the confusion!

**Comment by avritichauhan** [comment]
I was able to build cvc4, hence closing this issue. Thanks a lot for your help.
