### ISSUE TITLE
industry 4.0

### ISSUE THREAD

**Issue by siskonyazilimveotomasyon** [CVC4/CVC4#2715]
[industry 4.0](https://www.siskon.com.tr)
[endüstri 4.0](https://www.siskon.com.tr)
[endüstri40](https://www.siskon.com.tr)
[automation](https://www.siskon.com.tr)
[software](https://www.siskon.com.tr)
[OEE](https://www.siskon.com.tr)

**Comment by martin-cs** [comment]
SPAM.
