### ISSUE TITLE
Echo doesn't flush output

### ISSUE THREAD

**Issue by agacek** [CVC4/CVC4#2720]
Starting sometime after CVC 1.4, the `echo` command no longer causes output to be flushed. Here is Python code demonstrating the issue:

```
import subprocess

p = subprocess.Popen(['cvc4', '--lang', 'smt'], stdout=subprocess.PIPE, stdin=subprocess.PIPE)
p.stdin.write(b'(echo "foo")\n')
p.stdin.flush()
print(p.stdout.readline())
```

With `cvc4-1.4-win32-opt.exe` the output is

```
b'"foo"\r\n'
```

With `cvc4-1.6-win64-opt.exe`, there is no output and the test program hangs.

**Comment by agacek** [comment]
Git bisect says the issue was introduced in 0da095c3f5be79a85c085b4b46d7a0a0513ecdd6. Based on that commit, perhaps the issue is that CVC4 is buffering the input?

**Comment by 4tXJ7f** [comment]
The issue should be fixed on master now. Tomorrow morning, a fixed Windows build should be available at http://cvc4.cs.stanford.edu/downloads/builds/win64-opt/unstable/ (assuming that our nightly tests pass). If you find time, it would be great if you could confirm that the issue has been fixed.

**Comment by agacek** [comment]
Yes, I confirm that this resolves the original issue which led to this test case. Thanks!
