### ISSUE TITLE
repeated selectors in datatype declarations

### ISSUE THREAD

**Issue by LeventErkok** [CVC4/CVC4#2769]
For this benchmark:

```
(set-logic ALL)
(declare-datatypes ((t1 1)) ((par (T1) ((mkt1 (p1 T1))))))
(declare-datatypes ((t2 1)) ((par (T1) ((mkt2 (p1 T1))))))
(define-fun s1 () (t1 Int) (mkt1 3))
(define-fun s2 () (t2 Int) (mkt2 3))
(define-fun s3 () Int (p1 s1))
(define-fun s4 () Int (p1 s2))
(assert (= s3 s4))
(check-sat)
```

cvc4 is saying:

```
(error "Parse Error: c.smt2:6.29: Cannot find unambiguous overloaded function for argument types.")
```

But I believe this must be valid. Page 61 of http://smtlib.cs.uiowa.edu/papers/smt-lib-reference-v2.6-r2017-07-18.pdf says:

> Since δ1, . . . , δn are sort symbols, none of them can be a previously declared sort symbol.
> Similarly, constructors and selectors are function symbols, so none of them can be a
> previous declared/defined function symbol. This has the effect of also prohibiting, for
> instance, the use of the same constructor in different datatypes or the use of repeated
> instances of the same selector in the same datatype.

which only prohibits the use of the same selector in the same datatype. (Uses over multiple datatypes is OK.)

For whatever it's worth, z3 accepts this benchmark without complaints. 

My CVC4 is a bit old:

```
$ cvc4 --version
This is CVC4 version 1.6-prerelease [git master 37a080c0 (with modifications)]
compiled with GCC version 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)
on Apr 15 2018 20:51:25
```

please let me know if newer versions fix this and I'll upgrade!

**Comment by ajreynol** [comment]
This is not expected. This input technically should be allowed.
The error is specific to repeated selectors in *parameteric* datatypes. This benchmark goes through just fine:
```
(set-logic ALL)
(declare-datatypes ((t1 0)) (((mkt1 (p1 Int)))))
(declare-datatypes ((t2 0)) (((mkt2 (p1 Int)))))
(define-fun s1 () t1 (mkt1 3))
(define-fun s2 () t2 (mkt2 3))
(define-fun s3 () Int (p1 s1))
(define-fun s4 () Int (p1 s2))
(assert (= s3 s4))
(check-sat)
```
I will look into this.

**Comment by ajreynol** [comment]
This is fixed in my latest PR, thanks for the bug report :)
