### ISSUE TITLE
Linking error in static build

### ISSUE THREAD

**Issue by kanigsson** [CVC4/CVC4#2796]
I'm attempting a static build of current cvc4 master:
```./configure.sh --static --optimized --no-debug-symbols --no-proofs --antlr-dir=/path/to/antlr --prefix=/myprefix```

Everything goes well until the link at the very end:
```
[ 98%] Linking CXX executable ../../bin/cvc4
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: cannot find -lm
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status
```

This is using gcc 7 on linux opensuse 15.0.

Any idea what could cause this?

**Comment by 4tXJ7f** [comment]
It looks like it could not find the static version of glibc (some distributions don't ship with the static version by default). Either install the static version of glibc or configure with `--no-static-binary` to exclude system libraries from being linked in statically.

**Comment by 4tXJ7f** [comment]
I just submitted a PR that fixes an issue with `--static --no-static-binary` (PR #2798). Please update master before using those options.

**Comment by kanigsson** [comment]
Installing the static version of glibc worked for me. I'm closing this.
