### ISSUE TITLE
cmake and building on windows

### ISSUE THREAD

**Issue by kanigsson** [CVC4/CVC4#2802]
Hello,

using the old configure-based build system we were building cvc4 on windows/cygwin using a mingw-based compiler, which worked fine. We only had to pregenerate the configure script on Linux.

It seems that the new cmake configuration doesn't work on windows at all, cmake systematically selects the Microsoft compiler:
```
$ ./configure.sh --win64
-- Building for: Visual Studio 12 2013
-- The C compiler identification is MSVC 18.0.40629.0
-- The CXX compiler identification is MSVC 18.0.40629.0
```

Is compilation on windows (not cross compilation from linux) still supported?

**Comment by 4tXJ7f** [comment]
For our nightly builds, we are building the Windows binaries for CVC4 on Linux, so Windows/Cygwin is currently not tested. I'll take a look.

**Comment by 4tXJ7f** [comment]
I installed Visual Studio (to make sure that I have the compiler installed) and Cygwin (64-bit) on a Windows 10 VM. Then I started the Cygwin64 Terminal, cloned CVC4, and tried to run `./configure.sh --win64` and it seems to pick the correct compiler for me:

```
$ ./configure.sh --win64
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/x86_64-w64-mingw32-gcc.exe
-- Check for working C compiler: /usr/bin/x86_64-w64-mingw32-gcc.exe -- works
```

Are you using the 64-bit version of Cygwin? What is the output of `which x86_64-w64-mingw32-gcc`? Do you have the environment variables `CC` or `CXX` set to some values (they are empty for me)?

**Comment by kanigsson** [comment]
Thanks for testing (I know this is tedious :-)) I'm not using the cygwin compiler but another mingw compiler. But I realize that my compiler is 32bits. Is compiling a 32bit version still supported? If not, I will see if we can switch to a 64bit version.

**Comment by kanigsson** [comment]
The MinGW compiler I have is the GNAT compiler from AdaCore. It's a native compiler, I just use cygwin to process the configure script, access to unix commands etc. Thanks for your comment on 32bit. Right now there is no bug on your side so I will close the issue. I will try with 64bit (and see if we can live without 32bit version) and come back if I have other issues.

**Comment by 4tXJ7f** [comment]
If you continue to experience issues and I can get a copy of the compiler from somewhere, let me know. I am happy to do some additional testing.

**Comment by kanigsson** [comment]
OK I got one step further in my investigations. I first wanted to try the configuration you support, and indeed "configure.sh" seems to work on cygwin, with cygwin-provided mingw compiler and cygwin-provided cmake. But it fails as in my first message if I use a native cmake installed from cmake.org. I also have a rough understanding why - cygwin cmake is basically the linux version compiled for cygwin, so it doesn't really expect/look for MSVC. But the native windows cmake does. Do you think the approach using (Mingw Makefiles)[https://cmake.org/cmake/help/v3.6/generator/MinGW%20Makefiles.html] has chances of success?

**Comment by kanigsson** [comment]
Answering my own question - no. On windows, using ```-G "MinGW Makefiles"``` creates Makefiles with commandlines that are intended for cmd.exe; but this won't really work as the cvc4 build has some bash scripts that require processing by a unix shell. I guess it would be nice to document at least that on windows a cygwin environment including cmake is required.

**Comment by kanigsson** [comment]
I am moving to a linux-based cross compilation, so I am closing this.
