### ISSUE TITLE
Build with Java Bindings

### ISSUE THREAD

**Issue by JoergPfaehler** [CVC4/CVC4#2806]
I am currently trying to build CVC4 1.6 with Java bindings and I can not get it to work. It always fails with

[...]
checking for requested user language bindings... java
checking for availability of java binding... Java support will be built
checking jni.h usability... no
checking jni.h presence... no
checking for jni.h... no
configure: error: Language binding `java' requested by user, but it cannot be built (the preceding few lines should give an indication why this is).

I currently call configure with:

./configure --enable-language-bindings=java JAVA_CPPFLAGS=-I/usr/lib/jvm/java-8-openjdk-amd64/include

Since I am trying to do this in a docker container, I attached the Dockerfile. This should allow you to reproduce the problem (by putting the [Dockerfile](https://github.com/CVC4/CVC4/files/2770568/Dockerfile.txt) in an empty directory and calling "docker build ." in that directory, assuming docker is installed).

**Comment by 4tXJ7f** [comment]
Thanks for the report and the Docker container. I'll take a look.

**Comment by 4tXJ7f** [comment]
It worked for me with the following changes: install `default-jdk` and use the include path `JAVA_CPPFLAGS="-I/usr/lib/jvm/default-java/include/"`. I've uploaded the modified Dockerfile [here](https://paste.rs/jbK). Hope this helps!

**Comment by JoergPfaehler** [comment]
As far as I can see installing default-jdk uses JDK7. The openjdk-8-jdk package is already installed (it is provided by the "FROM java:8" part). I also checked that the JAVA_CPPFLAGS path passed in my Dockerfile actually exists and contains a jni.h file. Any idea why the configure script can handle JDK7 but not JDK8? Note that I have the same problem on my desktop computer (although it's a Ubuntu 18.10 with JDK8 and JDK11 installed), so it's not just docker. I was just glad that the problem is reproducible for everyone with the docker file.

**Comment by 4tXJ7f** [comment]
Alright, the following seems to work: use `-I/usr/lib/jvm/java-8-openjdk-amd64/include/ -I/usr/lib/jvm/java-8-openjdk-amd64/include/linux` for the include paths. `include/linux` contains `jni_md.h` which is included from `jni.h`. [Here](https://paste.rs/aFY) is the updated Dockerfile. I am still compiling but at least configuring worked.

**Comment by JoergPfaehler** [comment]
Ah, thank you for the quick feedback. It now works. It would be nice if this could be added to the installation instructions (assuming this is still needed in the next version, because I don't see anything about JAVA_CPPFLAGS in current INSTALL.md file)!

**Comment by 4tXJ7f** [comment]
It looks like the `java` image is [deprecated](https://hub.docker.com/_/java/) in favor of the `openjdk` [image](https://hub.docker.com/_/openjdk/). Because of that, the `java` image seems to be based on an older Linux distribution, which comes with an old version of CMake and SWIG. Those versions are too old for building CVC4 master, so it would be a bit more involved to build it in such a container. However, building it in an `openjdk:8` based container is no problem ([Dockerfile](https://paste.rs/x1B)) and doesn't require any special environment variables.
