### ISSUE TITLE
Python wrapper does not encapsulate exceptions

### ISSUE THREAD

**Issue by mikand** [CVC4/CVC4#2810]
The CVC4 python wrapper does not encapsulate C++ exceptions into python exceptions causing a crash of the entire python application when an exception is thrown by CVC4.

For example, consider the snipped below:
```python
import CVC4
cvc4 = CVC4.SmtEngine(CVC4.ExprManager())
cvc4.setOption("non-existing", CVC4.SExpr("true"))
```

this produces the following error that kills python:
```
terminate called after throwing an instance of 'CVC4::UnrecognizedOptionException'
  what():  Error in option parsing: Unrecognized informational or option key or setting: non-existing
Aborted
```

The expected behavior should be a python exception that is catch-able by python.

**Comment by mikand** [comment]
As a follow-up note, SWIG allows exception wrapping using the `%except` directive: http://www.swig.org/Doc1.1/HTML/Exceptions.html#n8

Also, there is a library for language-independent wrapping, simply adding the following to your mail `.i` file should do the trick:
```
%include exception.i       

%except {
	try {
		$function
	} catch(RangeError) {
		SWIG_exception(SWIG_ValueError, "Range Error");
	} catch(DivisionByZero) {
		SWIG_exception(SWIG_DivisionByZero, "Division by zero");
	} catch(OutOfMemory) {
		SWIG_exception(SWIG_MemoryError, "Out of memory");
	} catch(...) {
		SWIG_exception(SWIG_RuntimeError,"Unknown exception");
	}
}
```

**Comment by 4tXJ7f** [comment]
Thank you for the report and your suggestion on how to fix this! I will take a look.
