### ISSUE TITLE
datatypes: type checking issue

### ISSUE THREAD

**Issue by LeventErkok** [CVC4/CVC4#2832]
I've a bit of an old cvc4, compiled Apr 15 2018. If the master fixes this issue, please do let me know!

For this benchmark:

```
(set-option :produce-models true)
(set-logic ALL)
(declare-datatypes ((SBVEither 2)) ((par (T1 T2)
                                    ((left_SBVEither  (get_left_SBVEither  T1))
                                     (right_SBVEither (get_right_SBVEither T2))))))

(declare-fun s0 () (_ BitVec 8))
(define-fun s1 () (SBVEither (_ BitVec 8) (_ BitVec 8)) (left_SBVEither s0))
(check-sat)
(get-model)
```

I get:

```
$ cvc4 c.smt2
(error "Declared type of defined constant does not match its definition
The constant   : s1
Declared type  : (SBVEither (_ BitVec 8) (_ BitVec 8)) 275
The definition : (left_SBVEither (as s0 T1))
Definition type: (SBVEither (_ BitVec 8) T2) 278")
```

which is just not true. (Also some bizarre numbers being printed in the message, but I guess that's just an artifact of the system.)

For what it's worth, z3 accepts this benchmark as is.

**Comment by ajreynol** [comment]
Hi Levent,

For this input, cvc4 fails since the type of term `(left_SBVEither s0)` cannot be fully inferred, since the T2 parameter of its return type is unconstrained.

The relevant part of the SMT LIB standard is 3.6.4: http://smtlib.cs.uiowa.edu/papers/smt-lib-reference-v2.6-r2017-07-18.pdf

This version of the benchmark goes through with cvc4:

```
(set-option :produce-models true)
(set-logic ALL)
(declare-datatypes ((SBVEither 2)) ((par (T1 T2)
                                    ((left_SBVEither  (get_left_SBVEither  T1))
                                     (right_SBVEither (get_right_SBVEither T2))))))

(declare-fun s0 () (_ BitVec 8))
(define-fun s1 () (SBVEither (_ BitVec 8) (_ BitVec 8)) (as (left_SBVEither s0) (SBVEither (_ BitVec 8) (_ BitVec 8))))
(check-sat)
(get-model)
```

I would recommend using the `(as _ T)` syntax for any case where the return type of a term is ambiguous.

Cheers,
Andy

**Comment by LeventErkok** [comment]
Thanks Andy.

Unfortunately, I cannot get z3 to accept the modified version you've given. So, I'm having hard time finding something that works for both cvc4 and z3.

When I pass your modified version to z3 it says:

```
(error "line 8 column 61: invalid indexed identifier, '_' expected")
```

I can ping z3 folks if you think this is a z3 issue. Let me know.

**Comment by ajreynol** [comment]
Yes, I'm not sure what indexed identifier z3 is referring to there.

**Comment by LeventErkok** [comment]
Thanks! I filed a z3 issue (linked above). Hopefully we can come to a common understanding.
