### ISSUE TITLE
datatype parsing

### ISSUE THREAD

**Issue by LeventErkok** [CVC4/CVC4#2833]
For this benchmark:

```
(set-option :produce-models true)
(set-logic ALL)
(declare-datatypes ((SBVMaybe 1)) ((par (T)
                                    (nothing_SBVMaybe
                                     (just_SBVMaybe (get_just_SBVMaybe T))))))
```

cvc4 says:

```
(error "Parse Error: cvc4bug.smt2:4.53: Sequence terminated early by token: 'nothing_SBVMaybe'.

  ...                            (nothing_SBVMaybe
                                  ^
")
```

I believe the benchmark is correctly formatted. (z3 accepts is as is.)

Caveat: My cvc4 is from April of 2018. Let me know if the master branch fixes the issue!

**Comment by ajreynol** [comment]
Actually, this benchmark is not smt 2.6 compliant: `nothing_SBVMaybe` is a nullary constructor; it thus must be surrounded by parenthesis, see page 61: http://smtlib.cs.uiowa.edu/papers/smt-lib-reference-v2.6-r2017-07-18.pdf
Here is the smt 2.6 compliant version, which both z3 and cvc4 accept:
```
(set-option :produce-models true)
(set-logic ALL)
(declare-datatypes ((SBVMaybe 1)) 
(
(par (T)
((nothing_SBVMaybe) (just_SBVMaybe (get_just_SBVMaybe T)))
)
)
)
(check-sat)
```

**Comment by LeventErkok** [comment]
Thanks Andy! That makes sense; these parens always get me.
