### ISSUE TITLE
simple datatype syntax

### ISSUE THREAD

**Issue by LeventErkok** [CVC4/CVC4#2840]
I think the following is valid syntax:

```
(set-logic ALL)
(declare-datatypes () ((Color (Red) (Yellow) (Blue))))
```

z3 accepts it as is. But cvc4 says:

```
(error "Parse Error: b.smt2:2.24: Too many datatypes defined in this block.

  (declare-datatypes () ((Color (Red) (Yellow) (Blue))))
                          ^
")
```

Is this a z3 extension? Or perhaps cvc4 parser is having a hard time?

**Comment by 4tXJ7f** [comment]
By default, CVC4 is expecting SMT-LIB 2.6 syntax for datatypes. For your example, that would be (see [SMT-LIB 2.6](http://smtlib.cs.uiowa.edu/papers/smt-lib-reference-v2.6-r2017-07-18.pdf), page 61):
```
(declare-datatypes ( (Color 0) ) (
  ( (Red) (Yellow) (Blue) )
))
```
If you use the option `--lang=smt2.5`, then your example above parses fine but it is probably better to use SMT-LIB 2.6 if possible

**Comment by LeventErkok** [comment]
Thanks! That did the trick indeed.
