### ISSUE TITLE
Fix QF_LRA proofs

### ISSUE THREAD

**Issue by 4tXJ7f** [CVC4/CVC4#2855]
The following regressions fail with QF_LRA proofs:

- [ ] https://github.com/CVC4/CVC4/blob/master/test/regress/regress0/lemmas/sc_init_frame_gap.induction.smt
- [ ] https://github.com/CVC4/CVC4/blob/master/test/regress/regress1/lemmas/pursuit-safety-8.smt
- [ ] https://github.com/CVC4/CVC4/blob/master/test/regress/regress1/lemmas/simple_startup_9nodes.abstract.base.smt
- [ ] https://github.com/CVC4/CVC4/blob/master/test/regress/regress2/arith/pursuit-safety-11.smt
- [ ] https://github.com/CVC4/CVC4/blob/master/test/regress/regress2/arith/pursuit-safety-12.smt
- [x]  https://github.com/CVC4/CVC4/blob/master/test/regress/regress0/uflra/constants0.smt
- [ ]  https://github.com/CVC4/CVC4/blob/master/test/regress/regress0/uflra/pb_real_10_0200_10_22.smt
- [ ]  https://github.com/CVC4/CVC4/blob/master/test/regress/regress0/uflra/pb_real_10_0200_10_26.smt

Our support for QF_LRA proofs is limited but we should output trust statements instead of failing the proof check.

**Comment by 4tXJ7f** [comment]
Found some more tests that fail for QF_UFLRA.

**Comment by alex-ozdemir** [comment]
Following up on this, I've found a few bugs

## ITE translation bug

This is actually a bug in the both `TheoryProof` and `ArithProof`. `TheoryProof` will convert some `Bool`s to `formula`s in ITEs. It does this with the support of the `printsAsBool` function, which should be subclass defined. `ArithProof` neglected to define it, and `TheoryProof` was doing something slightly wrong anyway.

Tests

* [https://github.com/CVC4/CVC4/blob/master/test/regress/regress1/lemmas/simple_startup_9nodes.abstract.base.smtv1.smt2](https://github.com/CVC4/CVC4/blob/master/test/regress/regress1/lemmas/simple_startup_9nodes.abstract.base.smtv1.smt2)

## Integer Reasoning 

Sometimes we do integer reasoning, even if the problem in LRA. The current proof system produces invalid proofs in this case.

Tests

* [https://github.com/CVC4/CVC4/blob/master/test/regress/regress0/lemmas/sc_init_frame_gap.induction.smtv1.smt2](https://github.com/CVC4/CVC4/blob/master/test/regress/regress0/lemmas/sc_init_frame_gap.induction.smtv1.smt2)
* [https://github.com/CVC4/CVC4/blob/master/test/regress/regress1/lemmas/pursuit-safety-8.smtv1.smt2](https://github.com/CVC4/CVC4/blob/master/test/regress/regress1/lemmas/pursuit-safety-8.smtv1.smt2)
* [https://github.com/CVC4/CVC4/blob/master/test/regress/regress1/lemmas/simple_startup_9nodes.abstract.base.smtv1.smt2](https://github.com/CVC4/CVC4/blob/master/test/regress/regress1/lemmas/simple_startup_9nodes.abstract.base.smtv1.smt2)
* [https://github.com/CVC4/CVC4/blob/master/test/regress/regress2/arith/pursuit-safety-11.smtv1.smt2](https://github.com/CVC4/CVC4/blob/master/test/regress/regress2/arith/pursuit-safety-11.smtv1.smt2)
* [https://github.com/CVC4/CVC4/blob/master/test/regress/regress2/arith/pursuit-safety-12.smtv1.smt2](https://github.com/CVC4/CVC4/blob/master/test/regress/regress2/arith/pursuit-safety-12.smtv1.smt2)

## Stray Equalities

Sometimes there are equalities floating around in the system, which I thought were all normalized to `>=` and negations thereof. I need to investigate.

* [ https://github.com/CVC4/CVC4/blob/master/test/regress/regress0/uflra/pb_real_10_0200_10_22.smtv1.sm2]( https://github.com/CVC4/CVC4/blob/master/test/regress/regress0/uflra/pb_real_10_0200_10_22.smtv1.smt2)

## Uninterpreted Functions

In UFLRA, there some to be some uninterpreted functions floating around, which I had assumed would not be there (e.g. I thought that we did purification, or something like that).

* [ https://github.com/CVC4/CVC4/blob/master/test/regress/regress0/uflra/pb_real_10_0200_10_26.smtv1.sm2]( https://github.com/CVC4/CVC4/blob/master/test/regress/regress0/uflra/pb_real_10_0200_10_26.smtv1.smt2)


Anyways, thanks for finding all of these, Andres! They've been helpful for guiding me to parts of the Theory of arithmetic which trick our current proof machinery.

**Comment by barrettcw** [comment]
Great work Alex!  Is it possible to craft an example that gets a wrong answer (not just a wrong proof) because of the ITE translation bug?

**Comment by alex-ozdemir** [comment]
I do not believe that is possible, because the buggy translation process is only part of proof-production.

**Comment by barrettcw** [comment]
Got it.  Thanks.

**Comment by ajreynol** [comment]
This concerns the old proof code, closing this issue.
