### ISSUE TITLE
build of cvc4 failed with SWIG 4

### ISSUE THREAD

**Issue by jplesnik** [CVC4/CVC4#2860]
SWIG is preparing new release 4.0. I am trying to rebuild its dependencies with pre-release in Fedora. 

CVC4 failed during the build with following error
```
BUILDSTDERR: java.cpp:1619:110:   required from here
BUILDSTDERR: /usr/include/c++/9/bits/stl_construct.h:75:7: error: no matching function for call to 'CVC4::Datatype::Datatype()'
BUILDSTDERR:    75 |     { ::new(static_cast<void*>(__p)) _T1(std::forward<_Args>(__args)...); }
BUILDSTDERR:       |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
You can found complete build log [here](https://jplesnik.fedorapeople.org/swig-4/cvc4/build.log)

I wrote about it SWIG's upstream. They described me the reason of the error and proposed me the possisble solution. Evetrything could be found [here](https://sourceforge.net/p/swig/mailman/message/36601046/)

**Comment by 4tXJ7f** [comment]
Thanks a lot for letting us know! That doesn't look like a difficult fix, I'll take care of it.

**Comment by jamesjer** [comment]
Has anybody made any progress on this?  I maintain the cvc4 package for Fedora.  The new version of swig has been built for Fedora Rawhide, and cvc4 now fails to build.  The solution proposed by swig upstream does fix building the Java interface, but the python 3 interface is broken both with and without that patch.  If somebody can tell me what needs to happen to get the python 3 interface building again, that would be very helpful.  Thank you.

**Comment by 4tXJ7f** [comment]
@jamesjer Sorry about the long delay, we've had some busy times and couldn't spend as much time on maintenance. I hope to fix this this week.

**Comment by jamesjer** [comment]
That's okay.  I understand being busy.  I've done some experimenting tonight, and I think I may have found the solution.  I need to do one more test build, and if that works out, I'll make a pull request.

**Comment by 4tXJ7f** [comment]
I actually have a build now that seems to work, too :) Is your fix based on CVC4 1.6?

**Comment by 4tXJ7f** [comment]
Alright, it looks like with my fix the bindings compile using Swig 4.0.0 as well as Swig 2.0.12. Which version of CVC4 do you need the fix for? Is a fix on `master` sufficient? There have been some pretty big changes since CVC4 1.6 in terms of building it (mainly the switch from autotools to CMake).

**Comment by jamesjer** [comment]
Actually, I am looking at CVC4 1.7.  Does your fix affect the python 3 build, too?  I'll try adding a patch with your commit and see how things work out.  Thank you!

**Comment by 4tXJ7f** [comment]
The Python 3 bindings were building for me without issues. If you encounter an error while testing, could you please send me the log?

**Comment by jamesjer** [comment]
I'm not sure why I was having trouble before, but after applying your patch, adding drat2er support, and making a few other minor adjustments, the python 3 trouble I was having before is gone.  I'm not sure what made it go away, but I just got a successful build.  We can consider this issue resolved.  Thank you!

**Comment by 4tXJ7f** [comment]
Awesome, this is great to hear. Please do not hesitate to contact us if you encounter further issues or if you have suggestions to make the build process easier for package maintainers. It is important to us that CVC4 is available as widely as possible, so we really appreciate your efforts.
