### ISSUE TITLE
Differing SyGuS results with --sygus-stream

### ISSUE THREAD

**Issue by BillHallahan** [CVC4/CVC4#2881]
The attached zip file has 3 files: tester.sl, tester2.sl, and tester3.sl.

tester.sl and tester2.sl both return unknown when run with no flags.  However, CVC4 finds multiple solutions almost immediately when --sygus-stream is used.

tester3.sl is a slightly modified version of tester2.sl.  The only difference is the constraint on line 41 has been changed from (constraint (= (add (B "j")) (B "j"))) to (constraint (= (add (B "j")) (B "ja"))).  Running with no flags returns unknown, while running with --sygus-stream seems to hang (I'm not sure if this is actually a bug, or if CVC4 would eventually find a solution.  But considering how small the needed change from the solution to tester2.sl is, the slow speed seems suspicious to me.)

Edit: I should add, I was running the version of CVC4 on master on March 21st at 4:09 PM EST.

[tester.zip](https://github.com/CVC4/CVC4/files/2994054/tester.zip)

**Comment by ajreynol** [comment]
Thanks for the report. Btw, the reason you are getting different performance with `--sygus-stream` is because this option disables the PBE solver. The PBE solver has not been tested for problems with datatypes.  You can get the same performance using `--no-sygus-pbe`.

**Comment by BillHallahan** [comment]
"Btw, the reason you are getting different performance with --sygus-stream is because this option disables the PBE solver."
Ah, thanks! Didn't realize that.

**Comment by BillHallahan** [comment]
Hey, I made a mistake in tester3.sl, sorry.  It turns out you can't synthesize a function that satisfies the examples with the grammar I gave.  I've attached a corrected version which CVC4 can deal with pretty quickly (I added (B ntString) at line 15).
[tester3.sl.zip](https://github.com/CVC4/CVC4/files/2994172/tester3.sl.zip)
