### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [CVC4/CVC4#2887]
I would like to point out that an identifier like “[`__CVC4__LOGIC_REQUEST_H`](https://github.com/CVC4/CVC4/blob/3eac9d04c5d4bfba81142d4a5fe91b86590b32ae/src/smt/logic_request.h#L26 "Update candidate")” [does not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by 4tXJ7f** [comment]
Thanks for pointing this out. I'll bring it up at our next team meeting.

**Comment by aniemetz** [comment]
Thanks for pointing this out! We agree and will adjust these accordingly.

**Comment by 4tXJ7f** [comment]
Fixed in #2974.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?
