### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [CVC4/CVC4#2888]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [CutInfo](https://github.com/CVC4/CVC4/blob/14b9dbaa0c9e8dce52d1a28595dc1cc80756abed/src/theory/arith/cut_log.cpp#L113 "Destructor for CutInfo")
- [IllegalArgumentException::formatVariadic](https://github.com/CVC4/CVC4/blob/047e75b485ad16a729083c210ba4064943d2e7c5/src/base/exception.cpp#L59 "IllegalArgumentException::formatVariadic function")
- [TypeSet](https://github.com/CVC4/CVC4/blob/14b9dbaa0c9e8dce52d1a28595dc1cc80756abed/src/theory/type_set.cpp#L22 "Destructor for TypeSet")

**Comment by 4tXJ7f** [comment]
From a cursory look, it seems like the heap allocations in `CutInfo` and `TypeSet` could actually be `std::unique_ptr`s, which we prefer to manual `new`s and `delete`s since we switched to C++11. I'll update.

**Comment by elfring** [comment]
[A few update candidates were left over](https://github.com/CVC4/CVC4/blob/054ed31cd3ff5a24322c465189879374dee0b1ca/src/base/exception.cpp#L35 "Update candidate: Implementation of LastExceptionBuffer class"), weren't there?
