### ISSUE TITLE
Timeout on CVC4 1.7

### ISSUE THREAD

**Issue by BillHallahan** [CVC4/CVC4#2902]
On recent versions of CVC4 (1.7, from both March 19th and March 22nd) both myself and one other user have had issues with timeouts not working consistently.  Here's a log from my command line:

```
Bills-MacBook-Pro:LIVS BillHallahan$ time cvc4 test.sl 
unsat
(define-fun g ((x1 JSIdentifier)) JSIdentifier (JSInt (* 3 (* (jsInt x1) (jsInt x1)))))

real	0m8.386s
user	0m8.270s
sys	0m0.047s
Bills-MacBook-Pro:LIVS BillHallahan$ time cvc4 test.sl --tlimit 4000
unknown

real	0m11.387s
user	0m10.291s
sys	0m1.089s
Bills-MacBook-Pro:LIVS BillHallahan$ time cvc4 test.sl --tlimit 1
unsat
(define-fun g ((x1 JSIdentifier)) JSIdentifier (JSInt (* 3 (* (jsInt x1) (jsInt x1)))))

real	0m8.158s
user	0m8.105s
sys	0m0.047s
Bills-MacBook-Pro:LIVS BillHallahan$ time cvc4 test.sl --tlimit 100
unknown

real	0m11.942s
user	0m10.586s
sys	0m1.350s
```
With no timeout, CVC4 finds a solution in about 8 seconds.  But with a timeout, CVC4 seems to either ignore the timeout (and find the solution in about 8 seconds anyway), or take 11 seconds to timeout with unknown (despite the actual timeouts I specified being 4 seconds and .1 seconds.)
I am running MacOs (Mojave), the other user is running Ubuntu 18.04.

**Comment by ajreynol** [comment]
Can you send test.sl?  Generally the accuracy of timeouts depends on how often the code is checking resource limits. It is probably the case that some of the sygus code is not doing this often enough. We should be able to fix this fairly easily.

**Comment by BillHallahan** [comment]
Sure!  Sorry, probably should have done that before...
[test.sl.zip](https://github.com/CVC4/CVC4/files/3015227/test.sl.zip)
