### ISSUE TITLE
Wrong model on CVC4 1.6

### ISSUE THREAD

**Issue by idanb55** [CVC4/CVC4#2904]
Running on windows 10 64bit

cvc4-1.6-win64-opt.exe -m --smt cvc4_bug_example.txt

The following specification is unsatisfiable, but the solver says otherwise.
The model suggested as a satisfying model does not actually satisfy the model.
I got:
sat
(model
(define-fun n () Int 3)
(define-fun f () Int 1)
(define-fun m () Int 0)
(define-fun b () (Set Int) (as emptyset (Set Int)))
(define-fun c () (Set Int) (singleton 0))
(define-fun UNIVERALSET () (Set Int) (union (union (singleton 0) (singleton (- 1))) (singleton (- 2))))
)

But in that model, |(U/b) & (U/c)|=2, and as n=3 the assertion on line 25 does not hold.

[cvc4_bug_example.txt](https://github.com/CVC4/CVC4/files/3019191/cvc4_bug_example.txt)

**Comment by ajreynol** [comment]
Thanks a lot for the report. I was able to reproduce. This is fixed in my latest pull request and should be merged to master soon.
