### ISSUE TITLE
(error "vector") in PBE mode, but not with --no-sygus-pbe

### ISSUE THREAD

**Issue by BillHallahan** [CVC4/CVC4#2914]
The attached SyGuS problem outputs:
(error "vector")
when run in PBE mode (or, equivalently, run with no arguments on the command line.)
When run with --no-sygus-pbe, CVC4 finds a solution:
(define-fun substring ((x1 String) (x3 Int)) String (str.substr x1 0 x3))

[test.sl.zip](https://github.com/CVC4/CVC4/files/3032290/test.sl.zip)

**Comment by ajreynol** [comment]
Thanks again for these examples.
This is again related to partial operators in the PBE solver. Your benchmark is now solved with/without PBE in my latest PR.
