### ISSUE TITLE
[Bug] Wrong result, probably bug in `ite`

### ISSUE THREAD

**Issue by pkreutzer** [CVC4/CVC4#2947]
Hi there,

the current version of CVC4 reports `sat` for the following (already reduced) SMT-LIB v2 script, but the correct result it `unsat` (both z3 and Boolector report the correct result):

```
(set-logic QF_UFBV)
(declare-fun f (Bool) Bool)
(assert
  (not (f true))
)
(assert
  (f (ite (f true) true (f false)))
)
(check-sat)
(exit)
```

When asked for a model, CVC4 reports the following:

```
(model
(define-fun f ((BOUND_VARIABLE_291 Bool)) Bool false)
)
```

This is obviously wrong, since it invalidates the second `assert`.

The bug seems to be related to the `ite` operation. If needed, we can provide more, similar examples that also lead to a wrong result.

**Comment by 4tXJ7f** [comment]
Thank you very much for this report, we will fix this ASAP. Btw. I can also reproduce the issue with CVC4 1.6.

**Comment by pkreutzer** [comment]
Sorry, I should have mentioned that the bug is also present in the last stable release. FWIW, CVC4 1.5 does not seem to have this bug.

**Comment by ajreynol** [comment]
Thanks for the report, it was very helpful. This is fixed in my latest PR.
