### ISSUE TITLE
Enable fast evaluator for problems without PBE solver

### ISSUE THREAD

**Issue by ajreynol** [CVC4/CVC4#2972]
The example https://github.com/zhanghongce/inv-syn-examples/blob/master/aes-sygus/wrapper.smt2
is much faster when using `--sygus-pbe` despite the PBE solver not being the required solver (due to a lack of ITE in the grammar).  Regardless, we should be using fast evaluation in the standard CEGIS loop when it is possible. This mainly applies to PBE conjectures without ITEs in the grammar.

This was brought up on #2911.

**Comment by zhanghongce** [comment]
Thank you, Andrew!

**Comment by ajreynol** [comment]
@zhanghongce , btw, one strange thing I found in your problem, you have a non-terminal symbol:

```
   (IMP Bool (implies PreCond PostCond))
```
The right syntax here is:
```
   (IMP Bool ((=> PreCond PostCond)))
```

**Comment by zhanghongce** [comment]
Hi Andrew, 
Thank you for the info...  sorry about this!
I should have use `=>` instead of `implies`

**Comment by ajreynol** [comment]
Yes, but more importantly, don't forget the parentheses. :)
