### ISSUE TITLE
Compilation with old glibc

### ISSUE THREAD

**Issue by kanigsson** [CVC4/CVC4#2978]
Hello,

We have one build machine with a very old glibc (2.12). Cvc4 compiles thanks to the recent fix on #2854, and works in most cases. We do a static build (--static --no-static-binary).

But on one machine (up to now) with a Debian system we see segfaults with this binary, with a message "vsyscall attempted with vsyscall=none" in the system log. It seems that glibc prior 2.14 was using a kernel mechanism called vsyscall, but this mechanism is disabled on some modern systems (but by far not all apparently).

To summarize, the issue will appear when fully static cvc4 is compiled on a system with glibc < 2.14, and run on a system without support for vsyscall.

What do you advise us to do? The best option in my view would be a build where the libc is linked dynamically. But when I remove the --static and --static-binary options (need to remove both to make a difference), cvc4 attempts to dynamically link gmp and antlr. Is there a way to have only libc dynamically linked?

The other option would be that cvc4 somehow supports old glibc with static builds, but it seems difficult. Maybe configure.sh could detect this situation and abort or at least emit a warning?

In parallel I will ask our IT if we can move our cvc4 build to a machine with a more recent glibc.

**Comment by 4tXJ7f** [comment]
Thanks for the report. If you choose `--static --no-static-binary` then all libraries but libc and the C++ standard library should be linked statically.

> But on one machine (up to now) with a Debian system we see segfaults with this binary, with a message "vsyscall attempted with vsyscall=none" in the system log. It seems that glibc prior 2.14 was using a kernel mechanism called vsyscall, but this mechanism is disabled on some modern systems (but by far not all apparently).

To make sure that I understand this correctly: You compiled on a machine with an older version and then ran the binary on a machine with a newer version of glibc?

> The other option would be that cvc4 somehow supports old glibc with static builds, but it seems difficult. Maybe configure.sh could detect this situation and abort or at least emit a warning?

A warning may be a good idea. To avoid the issue, it sounds like we'd have to omit certain calls to glibc, which may be difficult to do but we could look into it.

**Comment by kanigsson** [comment]
> Thanks for the report. If you choose --static --no-static-binary then all libraries but libc and the C++ standard library should be linked statically.
Ok then this is maybe the real source of the issue. Building cvc4 with these switches in our setup results in a fully static build:
```$ ldd cvc4
        not a dynamic executable```
while the older configure-based build was as expected:
```$ ldd cvc4
        linux-vdso.so.1 (0x00007fffd8966000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fc9ea804000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fc9ea502000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc9ea157000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fc9eaa2c000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fc9e9f3a000)
```
Our call to configure.sh:
```./configure.sh production --symfpu --static --static-binary --optimized --no-debug-symbols --no-proofs --antlr-dir=... --gmp-dir=... --prefix=...
[...]
Shared libs          : off
Static binary        : on```

>  To avoid the issue, it sounds like we'd have to omit certain calls to glibc
As far as I saw, gettimeofday() is one of those calls, so that seems difficult to avoid?

**Comment by 4tXJ7f** [comment]
Oh, it looks like you configured with `--static --static-binary` but it should be `--static --no-static-binary`. Could you try again with `--static --no-static-binary`?

> As far as I saw, gettimeofday() is one of those calls, so that seems difficult to avoid?

Yes, that may be a bit challenging.

**Comment by kanigsson** [comment]
Thanks, I missed the `no` in your first message! Adding `--no-static-binary` instead of `--static-binary` works. I noticed that specifying only `--static` has the same effect as `--static --static-binary`, is that intended?
I don't have access right now to the machine where we had the issue, but I'm pretty sure this should be solved now.
