### ISSUE TITLE
No java bindings installed with CVC4-1.7

### ISSUE THREAD

**Issue by GerhardSchellhorn** [CVC4/CVC4#2990]
I just tried to install CVC4-1.7 with java bindings under Ubuntu 18.04.

so I called (after installing antlr)

./configure.sh --prefix=<somedir> --language-bindings=java

The build works fine, but make install does not copy
the generated CVC.jar and libcvc4jni.so file. Instead <somedir>/share/cvc4 contains
some ".plf" files.

I can find the CVC4.jar and the so-libraries in build/src/binding/java
so this is not an urgent problem.

**Comment by GerhardSchellhorn** [comment]
Hmm seems there are some syntax restrictions about using less/greater symbols here:
The call was 
./configure.sh --prefix="somedir" --language-bindings=java

**Comment by 4tXJ7f** [comment]
Thank you for the report @GerhardSchellhorn. @mpreiner fixed the issue on master. Please let us know if you run into other issues!
