### ISSUE TITLE
trivial crash (not important)

### ISSUE THREAD

**Issue by GerhardSchellhorn** [CVC4/CVC4#2991]
With cvc4-1.7 under kubuntu 18.04

bin/cvc4 --force-logic help

crashes

**Comment by nafur** [comment]
By now, cvc4 give the following error:

> $ bin/cvc4 --force-logic help
> (error "Illegal argument detected
> void CVC4::LogicInfo::setLogicString(std::string)
> 
>   `logicString' is a bad argument
> LogicInfo::setLogicString(): cannot parse logic string: help")

We would not expect `--force-logic help` to give more information here, in particular as it is marked as "for experts only". I thus close the issue.
