### ISSUE TITLE
Soğuk Oda Kurulumu Hakkında

### ISSUE THREAD

**Issue by 3aturan** [CVC4/CVC4#2997]
Soğuk oda kurulumu ve montajı asla hata kabul etmeyen bir sistemdir, gözden kaçan küçük bir hata bile bazen çok büyük ve telafisi olmayan sonuçlara yol açabiliyor. 3A Endüstriyel Soğutma bütün bilgi birikimi ve yaşamış olduğu tecrübeleri birleştirerek sürekli arge çalışmalrı yaparak sıfır hata ile [soğuk oda](https://www.3ateknik.com) ve soğuk hava depolarınızın kurulumunu yapmaktadır

**Comment by martin-cs** [comment]
Please can you stop posting Turkish spam?

**Comment by 3aturan** [comment]
this is not spam

**Comment by 3aturan** [comment]
> Please can you stop posting Turkish spam?

this is not spam 
please open again

**Comment by martin-cs** [comment]
We only accept issues that are in English and are relevant to the project.

**Comment by martin-cs** [comment]
Why do you keep doing this?
