### ISSUE TITLE
Crash when piping from stdin

### ISSUE THREAD

**Issue by florianschanda** [CVC4/CVC4#2999]
Hi, when processing this file everything works. When piping the contents I get an exception. The culprit seems to be a multi-line symbol that includes double quotes.

```
(set-info :smt-lib-version 2.6)
(set-logic QF_FP)
(set-info :source |
A "helpful" bug report.
|)

(check-sat)
(exit)
```

This is what I get with cvc4 3b407342c06d89910e19373e3c486155464843a7
```
$ ./cvc4_2019_05_14 --lang=smt2 potato.smt2
unsat
$ ./cvc4_2019_05_14 --lang=smt2 < potato.smt2
(error "Parse Error: <stdin>:4.1: basic_string::_M_create")
```

This is breaking my benchmarking scripts and I was finally able to track it down. :/

**Comment by 4tXJ7f** [comment]
Thanks for reporting this issue @florianschanda. This is a known issue (see #791) and unfortunately not trivial to fix. I'll try to take another look but it may take a while to get this fixed properly.

**Comment by florianschanda** [comment]
Oh, OK. Thanks. I have a workaround (don't use pipes) but its not really ideal.

**Comment by ajreynol** [comment]
Closing since duplicate.
