### ISSUE TITLE
crash with option --stats after reporting a parse error

### ISSUE THREAD

**Issue by kanigsson** [CVC4/CVC4#3019]
This is with the official release binary cvc4 1.7 for Linux x86_64. On the reproducer [repr.smt2.txt](https://github.com/CVC4/CVC4/files/3201600/repr.smt2.txt), cvc4 reports an error (looks correct to me) and then crashes with a segfault, if the --stats option is provided:
```
cvc4-1.7 --stats repr.smt2
(error "Parse Error: repr.smt2:551.51: Symbol 'error' not declared as a variable

  ...= (= (nth8_stream stream pos) true) (= (error) true))) :pattern (
                                             ^
")
CVC4 suffered a segfault.
Offending address is 0x0
Looks like a NULL pointer was dereferenced.
Segmentation fault (core dumped)
```
This isn't an important issue as the workaround is to fix the input file.

**Comment by 4tXJ7f** [comment]
Thank you for the report, I will take a look.

**Comment by claudemarche** [comment]
I'd like to report that I experienced a similar behaviour. It is not a blocking issue but the segmentation fault shadows a normal error and it is annoying when CVC4 are used by front-end tools like Spark or Why3.

**Comment by nafur** [comment]
It appears this has been fixed in the meantime. On current master, the solver prints the parse error, prints the statistics and exits fine (with `debug --asan --ubsan`).
