### ISSUE TITLE
Java bindings don't build with CLN

### ISSUE THREAD

**Issue by myfreeweb** [CVC4/CVC4#3044]
```
javac: file not found: /usr/ports/math/cvc4/work/.build/src/bindings/java/SWIGTYPE_p_mpq_class.java
```

I guess it's trying to use a GMP specific file.. when CLN is selected, there's instead `SWIGTYPE_p_cln__cl_I.java` and `SWIGTYPE_p_cln__cl_RA.java`.

**Comment by 4tXJ7f** [comment]
I have been able to reproduce this issue and I will take a closer look.
