### ISSUE TITLE
Lacking string comparison operators

### ISSUE THREAD

**Issue by pjljvandelaar** [CVC4/CVC4#3069]
As a user I would like to reason lexically over strings, like "Monkey" > "Ashtray".
However,
```
(get-info :name)
(get-info :version)
(set-logic ALL)
(set-option :produce-models true)
(set-info :smt-lib-version 2.5)

(declare-fun s1() String)
(declare-fun s2() String)
(assert (< s1 s2))
(check-sat)
(get-model)
```
yields
```
PS C:\experiments\z3> cvc4 --strings-exp .\stringCompare.smt2
(:name "cvc4")
(:version "1.7")
(error "expecting an arithmetic term on the left-hand-side")
```
Could support for comparison for strings be added?

At http://cvc4.cs.stanford.edu/wiki/Strings, I read about the str.to.int function: Does this mapping agree with the lexical mapping and should that be used to solve my issue?

See also TorXakis/TorXakis#883 and https://github.com/Z3Prover/z3/issues/2360

**Comment by 4tXJ7f** [comment]
The `<` operator is for integers and rationals only. To compare strings w.r.t. lexical order, you can use `str.<` (the documentation needs to be updated to reflect that). `str.to.int` converts a string representing a number to an integer, e.g. `str.to.int("123") = 123`. The semantics correspond to `str.to_int` in the current [draft of the SMT-LIB standard for the theory of strings](http://smtlib.cs.uiowa.edu/theories-UnicodeStrings.shtml).

I hope this helps! Please let us know if you run into any issues with `str.<`. The feature is fairly new and there aren't that many benchmarks to test it with.

**Comment by martin-cs** [comment]
On Mon, 2019-06-24 at 06:49 -0700, pjljvandelaar wrote:
> As a user I would like to reason lexically over strings, like
> "Monkey" > "Ashtray".

Out of interest; which sorting relation do you want?  There are many
possibilities.  Is it OK to give you whatever sort is convenient or do
you want the ASCII? Unicode? Binary based on UTF-? encoding?  Does your
application need a particular sort or is it sufficient to have a sort?

**Comment by ajreynol** [comment]
Actually, we do support `str.<=` and `str.<`. :)

Their semantics is provided in http://smtlib.cs.uiowa.edu/theories-UnicodeStrings.shtml.

Examples are in these regression tests:  https://github.com/CVC4/CVC4/blob/master/test/regress/regress1/strings/strings-lt-simple.smt2
https://github.com/CVC4/CVC4/blob/master/test/regress/regress1/strings/strings-lt-len5.smt2
