### ISSUE TITLE
CVC4 unknown result on NRA formula

### ISSUE THREAD

**Issue by muchang** [CVC4/CVC4#3082]
```
(declare-fun b () Real)
(declare-fun c () Real)
(declare-fun d () Real)
(declare-fun i () Real)
(declare-fun e () Real)
(declare-fun f () Real)
(declare-fun j () Real)
(assert (not (exists ((g Real)) (=> (<= c 0) (not (= (<= g i) (<= g 0)))))))
(assert (not (exists ((h Real)) (= (and (and (< ( *(* e 0.5) (* b (- b))) d) (<= f j)) (< d 0)) (<= (+ (* (- e 2.0) c) f) j)))))
(check-sat)
```
CVC4 returns `unknown` for this formula which is satisfiable. While Z3 reports `sat` in a second, it may not be a difficult case for solvers. Is it a bug in CVC4?

OS: Ubuntu 18.04
Revision: 2c289524f23a2ec481224b2ea569397acbb5e39e

**Comment by ajreynol** [comment]
CVC4's support for the logic NRA is fairly limited.

Like #3083, one option that is able to solve this benchmark is `--sygus-inference`.

**Comment by ajreynol** [comment]
Going to close this since it can be solved by the above option.
