### ISSUE TITLE
Parser bug? CVC4 rejects valid formulae

### ISSUE THREAD

**Issue by wintered** [CVC4/CVC4#3130]
CVC4 rejects this trivial but well-formed formula 
```` 
(declare-fun lambda () Bool)
(check-sat)  
````

This is the error message 

````
(error "Parse Error: cvc4_crash.smt2:1.18: Unexpected token: 'lambda'.
  (declare-fun lambda () Bool)
               ^
````

OS: Ubuntu
Revision: c9fa0516fd28b48940edf2a714e33bee6eacc396

**Comment by 4tXJ7f** [comment]
The "issue" is that CVC4 supports higher-order reasoning, including reasoning about lambdas. If no logic is chosen, support for higher-order reasoning is enabled and `lambda` is a reserved keyword.

The following works as expected:
```
(set-logic QF_BV)
(declare-fun lambda () Bool)
(check-sat)  
```

I hope that helps.
