### ISSUE TITLE
CVC4 hangs on NRA formula

### ISSUE THREAD

**Issue by muchang** [CVC4/CVC4#3184]
Hi,
For this NRA formula:
```
(declare-fun a () Real)
(assert
    (not (exists ((h Real)) 
            (=>  
                (>= (+ (* a h) 1) 0) 
                false))))
(check-sat)    
```
CVC4 will hang on it, while z3 gives `sat` result in a second.

Command: cvc4 file.smt2
OS: Ubuntu 18.04
Revision: 01e84d511e40604b01328b1e96ecdbe2b818b3c3

**Comment by ajreynol** [comment]
Thanks for the benchmark. Notice that `cvc4 --sygus-inference` is able to get SAT on this benchmark quickly.
What is your application for these benchmarks? With a larger set of benchmarks, I can provide some general advice on what set of cvc4 options may work best in general.

**Comment by muchang** [comment]
Thanks for your reply! CVC4 works well with `--sygus-inference`. 

Actually, these formulae were constructed by a fuzzer for testing SMT solvers. We hope to help make CVC4 more reliable and robust. We very much appreciate your prompt responses!

**Comment by ajreynol** [comment]
No problem, thanks again for sending the benchmark.

I'm going to mark this as a duplicate of #3106 and close this one.
