### ISSUE TITLE
Does timeout return CVC4::Result::SAT_UNKNOWN?

### ISSUE THREAD

**Issue by leonardoalt** [CVC4/CVC4#3194]
If I give the solver a timeout and it times out during a query, does it then return CVC4::Result::SAT_UNKNOWN or an exception?

**Comment by yoni206** [comment]
Yes, this should be the case (thanks @4tXJ7f ):

https://github.com/CVC4/CVC4/blob/b967cc5c8d84023c1b821c59b7bca736ffda6bed/src/smt/smt_engine.cpp#L3816
