### ISSUE TITLE
 Assertion failure using --sygus-inference 3

### ISSUE THREAD

**Issue by roxaaams** [CVC4/CVC4#3201]
Hello, 

For this formula:
```
(set-logic ALL)
(declare-fun v () Bool)
(assert false)
(assert v)
(check-sat)
(exit)
```

CVC4 returns the following assertion failure using the option --sygus-inference:

```
 cvc4 --sygus-inference small.smt2

(error "Assertion failure.
CVC4::Node CVC4::theory::quantifiers::CegSingleInv::getSolution(unsigned int, CVC4::TypeNode, int&, bool)
/home/user/software/CVC4/src/theory/quantifiers/sygus/ce_guided_single_inv.cpp:455:
  !d_inst.empty()
")
```

OS: Linux 4.15.0-58-generic #64-Ubuntu SMP
Revision: cvc4 1.8-prerelease [git master 16c2fe5e] assertions:on

**Comment by ajreynol** [comment]
Thanks for the benchmarks, `--sygus-inference` wasn't well tested for quantifier-free problems previously.

These issues are fixed in my latest commit.
