### ISSUE TITLE
InternalError: unhandled language 

### ISSUE THREAD

**Issue by roxaaams** [CVC4/CVC4#3206]
Hello,

For this command `cvc4 test` CVC4 returns the following internal error:

```
CVC4 Error:
internal error: unhandled language LANG_AUTO in AntlrInput::newInput
```

OS: Linux 4.15.0-58-generic #64-Ubuntu SMP
Revision: b967cc5

**Comment by ajreynol** [comment]
By default, CVC4 will use the file extension of the input to determine how to parse it.  In this case, `test` has no file extension so that error is given. You can try e.g. `--lang=smt2` if test is an smt2 file.
