### ISSUE TITLE
Incorrect sat result on QF_S formula

### ISSUE THREAD

**Issue by muchang** [CVC4/CVC4#3217]
Hi, 
On the latest reversion of CVC4:
```
(declare-fun a () String)
(declare-fun b () String)
(declare-fun c () String)
(declare-fun d () String)
(assert 
    (or 
        (not (= ( str.suffixof "B" ( str.replace "A" b "B")) (= ( str.substr a 0 (str.len b)) "A"))) 
        (not (= (not (= c "A")) ( str.suffixof "A" ( str.replace "A" c "B"))))))
(assert (= a (str.++ (str.++ b "") d)))
(check-sat)     
(get-model) 
```
CVC4 will report `sat` on this formula, and give a model:
```
(model
(define-fun a () String "")
(define-fun b () String "")
(define-fun c () String "")
(define-fun d () String "")
)
```
If I feed this model to the formula, CVC4 will report `unsat`

OS: Ubuntu 18.04
Reversion: b58bdc9c5672430cf15914c64129136b24050152
Commandline: cvc4 --strings-exp --produce-model file.smt2

**Comment by ajreynol** [comment]
Another excellent find, thanks a lot.

This is fixed in my latest PR.
