### ISSUE TITLE
Assertion Failure Using CVC4 API

### ISSUE THREAD

**Issue by evmaus** [CVC4/CVC4#3237]
Hey:

I'm running into an assertion failure when I execute the following code when CVC4 is built with assertions:

```
#include <cvc4/cvc4.h>
  
int main() {
  CVC4::ExprManager mgr;
  CVC4::SmtEngine smt(&mgr);
  smt.setLogic("QF_NRA");
  // Setup two terms
  {
    auto term1 = mgr.mkBoundVar("name1", mgr.realType());
    auto term2 = mgr.mkBoundVar("name2", mgr.realType());
    auto const1 = mgr.mkConst(CVC4::Rational(static_cast<unsigned long>(150)));
    auto const2 = mgr.mkConst(CVC4::Rational::fromDouble(0.05).value());
    auto equal_term1 = mgr.mkExpr(CVC4::Kind::EQUAL, term1, const1);
    auto equal_term2 = mgr.mkExpr(CVC4::Kind::EQUAL, term2, const2);
    auto and_term1 = mgr.mkExpr(CVC4::Kind::AND, equal_term1, equal_term2);
    smt.assertFormula(and_term1);
  }       
         
  {     
    auto term3 = mgr.mkBoundVar("name3", mgr.realType());
    auto term4 = mgr.mkBoundVar("name4", mgr.realType());
    auto const3 = mgr.mkConst(CVC4::Rational(static_cast<unsigned long>(150)));
    auto const4 = mgr.mkConst(CVC4::Rational::fromDouble(0.05).value());
    auto equal_term3 = mgr.mkExpr(CVC4::Kind::EQUAL, term3, const3);
    auto equal_term4 = mgr.mkExpr(CVC4::Kind::EQUAL, term4, const4);
    auto and_term2 = mgr.mkExpr(CVC4::Kind::AND, equal_term3, equal_term4);
    smt.assertFormula(and_term2); 
  } 
  smt.push();
    
  return 0;
}   
```

Is this expected?

Thanks,
Everett Maus

**Comment by ajreynol** [comment]
Hi, can you try using `mkVar` instead of `mkBoundVar`?  The call `mkBoundVar` is intended to variables that can be used as bound variables in quantified formulas.

**Comment by evmaus** [comment]
I can try it (and it doesn't fail), but I don't think in general I can swap over to it--basically, I may want to later use the variable in a quantified formula.

The issue is basically that this is an unrolled snippet from a much larger case that goes through a few layers of APIs before hitting CVC4.  One of the intermediate APIs doesn't know if a variable will be used in a quantifier or not when it's created, hence why I think it used mkBoundVariable.

I also know this works with older versions of CVC4 (e.x. one from 2018), so it seems like a regression if it no longer works/is supported.  :)

**Comment by ajreynol** [comment]
Just to be clear here, if you use `mkVar`, you can use the variable within a quantified formula, it just cannot be the variable that is bound *by* the quantified formula.

In other words, we do not support constructing queries:
`x>0` 
then later:
`x>=0 AND forall x. ...`
where `x` is the same expression.

Do you really need that you want to maybe use a variable as the *bound variable* for a quantified formula later after using it outside of a quantified formula?

**Comment by evmaus** [comment]
Hm.  Digging deeper into the use case, they do not.  I think we can resolve this ourselves.

It's interesting that this was working with a previous version of CVC4, though.  :)

One question:  why would this work fine without assertions turned on?  It seems odd that you need to turn on assertions to figure out you're calling the API wrong in this way--with assertions off this  seems to succeed silently.

**Comment by ajreynol** [comment]
We recently improved the assertions in CVC4 to catch this case. The previous version was indeed succeeding silently.

You're right about it being unintuitive that the error being triggered only when assertions are enabled, this is a good point.  

Btw, we are in the processing of revamping the API. I will reference this issue on that project.

**Comment by evmaus** [comment]
Awesome, thank you so much for your help!
