### ISSUE TITLE
feature request: set comprehensions

### ISSUE THREAD

**Issue by florianschanda** [CVC4/CVC4#3251]
Hi,

I've looked at http://cvc4.cs.stanford.edu/wiki/Sets and while I could work out how to do most things I am a missing set comprehensions.

So what I want to do is something like this, to build the set of all positive even integers:
```
{ i : Int | i >= 0 @ i * 2 }
```

Perhaps syntax like this: `(comprehension (DECLARATIONS) PREDICATE EXPRESSION)`

For example the above I could write as:
```
   (comprehension ((i Int)) (>= i 0) (* 2 i))
```

Or the set of prime numbers could be:
```
   (define-const n2 (Set Int) (comprehension ((i Int)) (>= i 2) i))
   (define-const primes (Set Int)
     (setminus n2
       (comprehension ((a Int) (b Int)) (and (member a n2) (member b n2)) (* a b))))
```

The use case here is that I am thinking about translating the Z notation to SMT-LIB, and the set comprehension is a very common concept there.

**Comment by florianschanda** [comment]
I you want more examples and/or benchmarks for this I am happy to provide them.

**Comment by ajreynol** [comment]
Hi Florian,
It looks like you are suggesting a 3 child comprehension.  One recommendation here would be to make comprehension have 2 children and have the second be a valid SMT formula, meaning you'd have to write: 
```
(comprehension ((i Int)) (and (>= i 0) (exists ((k Int)) (= i (* 2 k)))
```
Would this be okay?
My concern is that I would prefer if `comprehension` did not depend on any concrete theory e.g. arithmetic.
-Andy

**Comment by florianschanda** [comment]
I guess that would work (I mean it's easy enough to automatically rewrite to that pattern). Is there any loss of expressiveness that is not obvious? It is definitely more ugly to look at :)

I am maybe missing a finer point, but how would the first version be dependent on a theory any more than `ite`?

**Comment by ajreynol** [comment]
Perhaps I misunderstood the original intention of the 3rd argument of the comprehension.  Certainly, if the 3rd argument always had integer type, then this would depend on a theory with integers being enabled, but I see how can be theory-independent.

So to confirm, for example:

```
(declare-fun a () (Set T))
(assert (= a (comprehension (X) P E)))
```

is syntax sugar for:

```
(declare-fun a () (Set T))
(declare-fun b () (Set T))
(assert (= a b))
(assert (forall (X) (=> P (member E b))))
```
assuming E has type T?

**Comment by florianschanda** [comment]
Specifically, I think
```
(define-const factors (Set Int)
  (comprehension ((a Int) (b Int))
                 (and (>= a 2) (>= b 2))
                 (* a b)))
```

Could maybe be re-written to:
```
(declare-const factors (Set Int))
(assert (forall ((a Int) (b Int))
                (=> (and (>= a 2) (>= b 2))
                    (member (* a b) factors))))
(assert (forall ((x Int))
                (=> (not (exists ((a Int) (b Int))
                                 (and (>= a 2)
                                      (>= b 2)
                                      (= x (* a b)))))
                    (not (member x factors)))))
```

But I am not sure I got all the logic right. Part of this is *why* I think a nice set comprehension would be a great idea for users :)

**Comment by ajreynol** [comment]
Ah yes, you're right about negative membership.  What you wrote about I think could be simplified to:
```
(assert (forall ((x Int))
                (= (exists ((a Int) (b Int))
                                 (and (>= a 2)
                                      (>= b 2)
                                      (= x (* a b))))
                   (member x factors))))
```
I'll think a bit more about this.

**Comment by florianschanda** [comment]
Yes, you're right that is much simpler indeed :)
I see you have a pull request open for this, awesome! I will give it a spin...
