### ISSUE TITLE
Benchmark for performance on simple ADT problems

### ISSUE THREAD

**Issue by pjljvandelaar** [CVC4/CVC4#3266]
As a user of CVC4, I like to get its output fast.
One of the use cases in which I use CVC4 is with data types.
I have attached a smt2.5 file in which I define a number of data types.
For each data type I introduce a variable
  and for each constructor of the data type, 
       I ask CVC4 whether I can make a data instance with this constructor (it should) and when that is the case I ask for a model.

CVC4 gives the right answers, yet its performance is slow.
[performanceADT.txt](https://github.com/CVC4/CVC4/files/3596135/performanceADT.txt)

I hope this file can help to improve the performance of CVC4 even further.

Note, if wanted I can provide a wide variety of these kind of files: they are generated as part of the unit tests of the new TorXakis version (under development).

**Comment by ajreynol** [comment]
Thanks for the benchmark, it is helpful.  I should be able to make CVC4 much faster for this soon, will keep you posted.

**Comment by ajreynol** [comment]
This benchmark is now solved in 0.03 seconds with my latest PR.
