### ISSUE TITLE
CVC4 hangs on NRA formula

### ISSUE THREAD

**Issue by muchang** [CVC4/CVC4#3286]
Hi, 
For this NRA formula:
```
(set-logic NRA)
(assert
 (exists ((a Real))
  (forall ((b Real))
   (exists ((c Real))
    (and
     (< (+ a (* c c)) 0)
     (or (not (= a 0)) (< b 0))
     (not (= (+ b c) 0))
     (> c 0)
     )
    )
   )
  )
 )
(check-sat)   
```
CVC4 will hang on it:
```
$ timeout -s 9 120 cvc4 test.smt2
Killed
```

OS: Ubuntu 18.04
Revision: a90b9e2b70be427d1380cb5e65dc33c86e4a63b2

**Comment by ajreynol** [comment]
Thanks for the benchmark. Note that CVC4 does have a decision procedure for this fragment, so it is expected that it will hang for some (simple) examples in this logic.  We will keep this example in mind when further developing the NRA solver.
