### ISSUE TITLE
Assertion failure on bad formula

### ISSUE THREAD

**Issue by muchang** [CVC4/CVC4#3287]
Hi,
For this bad formula:
```
(set-logic ALL)
(declare-fun a () Int)
(assert (= a 0 true))
```
CVC4 will throw out this assertion failure: 
```
$ cvc4 test.smt2 
(error "Assertion failure.
CVC4::theory::arith::Comparison::Comparison(CVC4::TNode)
/home/zhangche/smtfuzzer/solvers/CVC4/src/theory/arith/normal_form.cpp:689:

  isNormalForm()
")
```
CVC4-1.7 stable version can reject this formula properly:
```
$ ./cvc4-1.7-x86_64-linux-opt test.smt2 
(error "Cannot typecheck the expansion of chained operator `=':
| Error during type checking: expecting a Boolean subexpression
| (and (= a 0) 0)
| The ill-typed expression: (and (= a 0) 0)")
```

OS: Ubuntu 18.04
Revision: a90b9e2 (compiled with assertions)

**Comment by ajreynol** [comment]
Can you share your exact configuration?
I am getting these errors in my configurations of production (`./configure.sh production --name="/tmp/ajreynol/cmake/prod/" --prefix="/space/ajreynol/" --static --tracing --symfpu`):
```
(error "Cannot typecheck the expansion of chained operator `=':
| Error during type checking: expecting a Boolean subexpression
| (and (= a 0) 0)
| The ill-typed expression: (and (= a 0) 0)")
```
and debug (`./configure.sh debug --name="/tmp/ajreynol/cmake/debug/" --prefix="/space/ajreynol/" --static --tracing --no-unit-testing --cxxtest-dir="/space/ajreynol/cxxtest/" --program-prefix="d-" --symfpu`):
```
(error "Parse Error: issue3287.smt2:3.20: Cannot typecheck the expansion of chained operator `=':

  (assert (= a 0 true))
                 ^

| Error during type checking: Subexpressions must have a common base type:
| Equation: (= 0 true)
| Type 1: Int
| Type 2: Bool
| 
| (= 0 true)
| The ill-typed expression: (= 0 true)")
```

**Comment by muchang** [comment]
Hi Andrew, 
The configuration we used is 
```
./configure.sh --assertions
```

**Comment by nafur** [comment]
I've built with `./configure.sh --assertions` and get
```
$ bin/cvc4 test.smt2 
(error "Parse Error: test.smt2:3.20: Subexpressions must have a common base type:
Equation: (= 0 true)
Type 1: Int
Type 2: Bool
")
```
I thus assume that the issue is fixed. Please come back to use if it persists for you...
