### ISSUE TITLE
Accessing algebraic reals

### ISSUE THREAD

**Issue by LeventErkok** [CVC4/CVC4#3300]
For this benchmark:

```
(set-option :produce-models true)
(set-logic ALL)
(declare-fun x () Real)
(assert (= (* x x) 2))
(check-sat)
(get-value (x))
```

cvc4 says:

```
sat
((x (/ (- 741455) 524288)))
```

This is very confusing, as obviously square-root of 2 is not rational. The output of `get-model` is much more helpful:

```
sat
(model
(approximation (and (>= x (/ (- 1482917) 1048576)) (>= (* (- 1.0) x) (/ 741455 524288))))
(define-fun x () Real (/ (- 741455) 524288))
)
```

As an up-stream tool, I simply do a `get-value` on my variables; and it's not even clear how to access this "approximation" using the SMTLib interface without getting the whole model. Nor it is clear how to robustly parse that information.

Would it be worth considering an alternative design where `get-value` returns some indication that the value is only approximate?

For reference, this is what z3 prints for this benchmark:

```
sat
((x (root-obj (+ (^ x 2) (- 2)) 1)))
```

which makes it clear to the up-stream solver that there is an approximation going on.

What's the recommended way of accessing this info in CVC4? Would be great if CVC4 and z3 agreed on the presentation to simplify up-stream tools, though I should emphasize that I'm not advocating one way or the other; just something that both tools can standardize on.

**Comment by ajreynol** [comment]
Thanks for the report.

Indeed, the approximations are only available if you get the entire model via the smt2 interface, or if you have a pointer to CVC4's model object via the API (https://github.com/CVC4/CVC4/blob/master/src/smt/model.h#L98).

Notice that the algorithms used by CVC4 and Z3 are different for non-linear real arithmetic. While Z3 uses methods that produce algebraic numbers in models, CVC4 uses alternative methods based on approximation.  Thus the kinds of solutions produced by the two solvers are inherently going to be quite different. This is indeed a bit unfortunate.

Regardless, you make a good point that CVC4's response to `get-value` in isolation is not ideal, since the up-stream tool is blind to whether the value is approximate.

Thinking about this a bit more, there is a clean way to represent approximations as the results of `get-value`. My recommendation is to use the notion of a "choice" function, so for the previous example, cvc4 would return:
`((x (choice ((z Real)) (and (>= z (/ (- 1482917) 1048576)) (>= (* (- 1.0) z) (/ 741455 524288))))))`
This states that the value of `x` is some `z` that satisfies that formula, which states an interval for `z`.  Notice that when CVC4 says "sat" and has an approximation, it has made the determination that the input is definitely satisfiable for *some* value of x in that range.

I will update the behavior to do this in a PR soon.

**Comment by LeventErkok** [comment]
@ajreynol That'd be great.

Is the choice guaranteed to be always of this form?

```
(and (>= z constant1) (>= constant2 >= z))
```

If so, then upstream tool can extract a witness easily and that would work out. If not, or if the choice can be more complicated, then perhaps also provide a witness value to simplify interaction? Perhaps something like:


```
((x ((witness constat)) (choice ((z Real)) ...complicated-condition...))
```

or something along these lines?

**Comment by ajreynol** [comment]
The choice is always in the form of an interval, yes.  I don't foresee the conditions being more complicated for non-linear arithmetic in the near-term.

Regarding witness constant, if I understand correctly, notice that the witness constant wouldn't necessarily be the true value of `x`.  For example, in the square root of two example, I would provide `(/ (- 741455) 524288)`.  Would this be useful?

**Comment by LeventErkok** [comment]
Yes; witness is probably the wrong name here. Perhaps "approximate" is a better one. Something that satisfies the choice function and is an approximation of the actual value. That would be really useful.

**Comment by ajreynol** [comment]
Ah, I see.  Perhaps this could be done via an annotation:
`(choice ((z Real)) P :witness c)`
Another option would be another command `get-approximate-value`, which would return `c` directly.
Which sounds better to you?

**Comment by LeventErkok** [comment]
Annotation via `:approximate-witness` would fit the bill very nicely. Thanks!

**Comment by martin-cs** [comment]
> Would be
> great if CVC4 and z3 agreed on the presentation to simplify up-stream 
> tools, though I should emphasize that I'm not advocating one way or
> the other; just something that both tools can standardize on.

This is a popular request for SMT-LIB and should probably be discussed
there as CVC4 and Z3 are far from the only solvers who should be
involved.  Two of the reasons that the format of models has not (yet)
been standardised are:

1. Model presentation is very tightly linked to data representation
within a solver.  For example 'root-of' makes a lot of sense if you are
working with algebraic number fields but it is a significant amount of
extra work for an interval based solver.  SMT-LIB tries very hard to
not constrain algorithmic or implementation choices.

2. A reasonable design criteria for get-model is that it should be
possible to assert the model, or parts of it, back to the solver.  For
theories where every ground term in the model is expressible as a
constant, such as bit-vectors and floating-point, this is fine.  For
things like arrays, uninterpreted functions, reals and (especially)
quantifiers, it is much harder and extensions to SMT-LIB are needed. 
SMT-LIB 3.0 will have some features to make this easier.

Proposals for the standardisation of get-model that work with these,
esp. from a user / integrator point of view, would no doubt be welcome
at the SMT-LIB workshop.

HTH

**Comment by ajreynol** [comment]
Sorry for the long delay on this.

The current proposal was to return something like this:
`(choice ((z Real)) P :approximate-witness c)`

I looked into implementing this.  While it is fairly straightforward to do this in the text interface, one issue that is not ideal here is that if users of the API want access to this information as well, then we would need to add support for this annotation within our Term data structure.  This would require a significant extension to our API.

I was wondering if a more lightweight solution would suffice, say, under a given option, the choice functions returned by CVC4 were always of this form:
`(choice ((z Real)) (or (= z c) P))`
and more generally ensured that all choice functions were in this form?  This would not require any additional infrastructure to be added to CVC4 and hopefully would be simple enough to parse.

Let me know if this.

**Comment by LeventErkok** [comment]
So long as it's always of the form 

```
(choice ((VAR Real)) (or (= VAR constant) P))
```

then yes, I think this is quite workable. It might be confusing to a tool that wasn't expecting a complicated response for a `get-value` call, but then again the specific name `choice` makes it clear the equality may or may not hold.

Not sure if you want to run this by the SMTLib folks to get their opinion on it, but I can definitely make it work for my purposes. Thanks for looking into this!

**Comment by ajreynol** [comment]
I've added the option (--model-witness-choice) to ensure choice functions are in the form mentioned above.  Do let me know if you have any further issues.

**Comment by LeventErkok** [comment]
@ajreynol 

Thanks Andrew! I'd really like to try this, but I'm unable to get CVC4 compiled on my box right now. Reported the issue here: https://github.com/CVC4/homebrew-cvc4/issues/37

Is there a workaround for the build issues?

**Comment by LeventErkok** [comment]
@ajreynol 

Thanks! I got around to playing with this and it indeed works as advertised.

One issue is if there's a way for the user to tell back to CVC4 to give back a different value than what's reported in an approximation. The typical way to do this is to assert a new constraint saying the value is different from what you reported in the previous `(check-sat)` call. But I don't see how to do that with an approximation like this, as there's no real way to cast it back in SMTLib to ask for a different one.

I don't think this is a big deal, but wondering if you've any thoughts on this.

**Comment by ajreynol** [comment]
I think the way would be to assert that the next value does not satisfy the body of the choice.

In other words, if a model `M` is such that `M(x) = (choice ((z)) (P z)`, you would assert `(not (P x))`.  Notice that this is different from `(not (= x (choice ((z)) (P z)))`, which states that `x` is different from *some* element such that `P` is true.  Instead  `(not (P x))` says that `x` is different from all elements such that `P` is true.  Would this suffice?

**Comment by LeventErkok** [comment]
That's interesting. So, when I get an interval in `choice`, CVC4 makes sure that the interval has precisely one solution contained in it?

Is this an invariant of the model generator? I'm curious if there might be a case that there are two or more distinct solutions within the specified interval. Does that never happen?

**Comment by ajreynol** [comment]
The interval may have more than one solution. 

Based on what I suggested above, the idea would be if you got a stream of models where `x` was assigned choice terms, the values for `x` would actually describe "regions" of the search space.  Excluding a solution using what I suggested above would potentially rule out more than one model, but would correspond precisely to the region described by the current model.

Unfortunately it would be quite challenging to ensure the "uniqueness" property of the models (e.g. have CVC4 find an approximation that was tight enough to contain only one solution), if that were needed.  This is an interesting research question.

**Comment by LeventErkok** [comment]
Thanks @ajreynol 

That makes sense. So, in a "find all satisfying solutions"  scenario this wouldn't really work. But it's a nice trick nonetheless and might come in handy.

**Comment by ajreynol** [comment]
FYI @LeventErkok , the syntax for choice functions has been changed in a recent commit to CVC4 master (https://github.com/CVC4/CVC4/commit/c8f149fa83fa16f821f37687fedfa778808809bd): `choice` is now `witness`.

**Comment by LeventErkok** [comment]
Thanks for the heads-up @ajreynol 

My reading is that the meaning and the functionality is exactly the same aside from the renaming of `choice` to `witness`?

**Comment by ajreynol** [comment]
Yes, the meaning is the same as before.  We use `witness` to avoid confusion with the HIlbert "choice" operator (https://planetmath.org/hilbertsvarepsilonoperator), which requires that `choice x. F = choice x. G` whenever formula `F` is equivalent to `G`. However, for the purposes of arithmetic models, when two variables are given the same interval, they are not necessarily required to have the same value.

**Comment by LeventErkok** [comment]
Thanks for the explanation. This is all good!
