### ISSUE TITLE
unknow(incomplete) on array theory 

### ISSUE THREAD

**Issue by XiaoLi0614** [CVC4/CVC4#3321]
Hi,

I'm trying to use CVC4 to check the validity of an assertion in array theory. It's a really simple use-case with employees array and departments array. I1 is referential integrity and IM1 is invariant integrity on the third field of the employees' array. 

I expect to get valid for the "QUERY" operation. But CVC4 keeps giving me "unknown(incomplete)". Is there any way I can get a reasonable result from CVC4 in this specific context?

[Example.txt](https://github.com/CVC4/CVC4/files/3659880/Example.txt)

**Comment by ajreynol** [comment]
What version of cvc4 are you using?  I am getting "valid" for this example both in 1.7 and on 923abd7000a2ab6e3c0776c59d159bdc3a4d9a52.

**Comment by XiaoLi0614** [comment]
I was using cvc4 1.6 and switching to 1.7 solves the issue. Thank you so much.
