### ISSUE TITLE
Set-logic cannot be used again after reset

### ISSUE THREAD

**Issue by iwob** [CVC4/CVC4#3353]
Hello, in my tool I repeatedly query CVC4 in the interactive mode with different problems, and reset the state of the solver after each problem is solved. Unfortunately, I now get "Parse Error: tmp.smt2:14.14: Only one set-logic is allowed.". This behavior has changed since January, when I was last testing this.

Example script:
```
(set-logic NRA)
(set-option :produce-models true)
(define-fun f ((x Real)) Real (* x x))
(declare-fun x () Real)
(assert (not (and (forall ((x Real)(cdgp.P1.x Real)) (=> (> cdgp.P1.x x) (>= (f cdgp.P1.x) (f x)))))))
(check-sat)
(get-value (x))

(reset)

(set-logic NRA)
(set-option :produce-models true)
(define-fun f ((x Real)) Real x)
(define-fun x () Real (- 2.0))
(assert (and (forall ((x Real)(cdgp.P1.x Real)) (=> (> cdgp.P1.x x) (>= (f cdgp.P1.x) (f x))))))
(check-sat)
(reset)
```

**Comment by 4tXJ7f** [comment]
Thank you for your report. This is indeed a bug (see [SMT-LIB standard](http://smtlib.cs.uiowa.edu/papers/smt-lib-reference-v2.6-r2017-07-18.pdf), page 52). Which version were you running in January?

**Comment by iwob** [comment]
I was using nightly build cvc4-2019-01-14-x86_64-linux-opt

**Comment by 4tXJ7f** [comment]
Awesome, thank you.

**Comment by 4tXJ7f** [comment]
@iwob I've been trying to reproduce the issue on current master but haven't been able to (neither by passing the file to the solver nor by piping the file into it). Are you still experiencing the issue with the current nightly builds? If yes, it would be great if you could provide some additional details on how you invoke the solver. Thanks!

**Comment by iwob** [comment]
Yes, the error still is present. Even when I run CVC4 without any parameters, the provided script generates an error.
```
COMMAND: ./cvc4-2019-11-12-x86_64-linux-opt tmp.smt2 
sat
((x (/ 0 1)))
(error "Parse Error: tmp.smt2:11.14: Only one set-logic is allowed.

  (set-logic NRA)
   ^
")

```

When I run the previous version I get:
```
COMMAND: ./cvc4-2019-01-14-x86_64-linux-opt tmp.smt2 
sat
((x (/ 0 1)))
sat
```

**Comment by 4tXJ7f** [comment]
Thank you for your reply. I have been able to reproduce the issue and submitted a PR with a fix.
