### ISSUE TITLE
CVC4 rejects valid fomula with set-logic

### ISSUE THREAD

**Issue by muchang** [CVC4/CVC4#3354]
Hi,
For this formula:
```
(set-logic QF_S)(assert (<= 0 0))(check-sat) 
```
CVC4 will reject the formula with following error massage:
```
(error "Parse Error: test.smt2:1.31: Symbol '<=' not declared as a variable")
```
If I remove `(set-logic QF_S)`, cvc4 will accept it.

Commandline: `cvc4 --strings-exp test.smt2` and `cvc4 test.smt2`
OS: Ubuntu 18.04
Revision: 472c5a5

**Comment by 4tXJ7f** [comment]
This is actually expected: `<=` is defined by the theory of integers and `QF_S` does not include those function symbols. To get `<=`, the logic has to be `QF_SLIA`. When no logic is specified, CVC4 assumes the most general logic (equivalent to saying `(set-logic ALL)`), so the symbol is included as well.

I hope this makes sense. Please let us know if you think that there is still an issue.

**Comment by muchang** [comment]
Thanks Andres! Your explanation makes much sense.
