### ISSUE TITLE
gmpxx header not found when running make.

### ISSUE THREAD

**Issue by shmorcel** [CVC4/CVC4#3368]
When running the make command to compile the library, I get the error: fatal error: gmpxx.h: No such file or directory  #include <gmpxx.h>

I don't know where to get this header, so I tried installing the library in the following link: https://gmplib.org/

I noticed in the build dependency that GMP 4.2 is needed, I got 6.1.2.

The problem persists.

What can I do now, and do I need to compile this to use it in Java? (I suspect so because it's just a Java binding).
Is there a way to just start using it in Java without compiling, or is it a rite of passage?

**Comment by 4tXJ7f** [comment]
I am using GMP 6.1.2 as well and it works fine. Which OS are you running? If you are using Ubuntu, you may have to install the dev version of GMP (`libgmp-dev`) to get the headers.

The issue should be independent of whether the Java bindings are being built or not.

>  Is there a way to just start using it in Java without compiling, or is it a rite of passage?

Unless you are using a Linux distribution with a prebuilt package that comes with the Java bindings, you unfortunately have to compile it yourself for the time being. We are working towards making this easier in the future.

**Comment by shmorcel** [comment]
You got it spot on! I was using Ubuntu and installing libgmp-dev did it for me! Thanks!

I have a small question though. I am looking for the jar file that I can include into my project. I can't seem to find it. Can you help me with that? The documentation seems to skip the Java API part.

**Comment by shmorcel** [comment]
Got it! I had to set that as an option in configure.sh: 
`./configure.sh --language-bindings=java`

and then `make` again. The jar files will be in `build/src/bindings/java`. Pretty cool!

Thanks 4tXJ7f! I appreciate your help!

Cheers.

**Comment by 4tXJ7f** [comment]
Awesome, glad that it all worked out! Please let us know if you run into any other issues.
