### ISSUE TITLE
Memory & Behavior of SMT Solver Reuse?

### ISSUE THREAD

**Issue by evmaus** [CVC4/CVC4#3404]
Hey:

So for our application we're currently seeing some odd memory behavior while reusing the same SMT Solver instance.

In particular, after extended use, a Push() wound up allocating ~800mb.  It's particularly odd to us that this particular Push() would wind up allocating anything, as it's immediately preceded by a Pop() to clear the expression stack entirely (there should be nothing asserted when this Push() is called).

What's the best way to handle this?  Is this expected behavior?  We're happy to re-create a new solver each time we need to use it rather than using the same copy of the solver if that's likely to be more productive and avoid this behavior.

Thanks,
Everett

**Comment by 4tXJ7f** [comment]
If you don't need any of the earlier assertions, you can use `SmtEngine::reset()`, which essentially recreates a new solver and should be better in terms of memory usage. While this approach should be better in terms of memory usage, it would be good to have a better understanding where the high memory usage is coming from. Is there any additional information about your use case that you can share with us? Thanks!

**Comment by evmaus** [comment]
So we're generating data to fit a schema, and largely using the SMT solver as a constraint checking engine.

I expect a lot of the memory pressure comes from the fact that we repeatedly generate a number of slightly different assertions, pushing and popping as we go.  If push/pop isn't guaranteed to release old assertions, that would build up memory pressure quickly, especially since it seems like push() in particular does some extra work that isn't just pushing the state.

Thoughts?

**Comment by evmaus** [comment]
Hey all:

Just closing the loop here.  Switching to reset over push/pop seems to have resolved our memory pressure issues.

HTH,
Everett
