### ISSUE TITLE
Assertion failure -- CVC4 HO with finite-model-find

### ISSUE THREAD

**Issue by ahmed-irfan** [CVC4/CVC4#3405]
```
./cvc4 --uf-ho --finite-model-find tmp.smt2
(error "Assertion failure.
void CVC4::TheoryEngine::check(CVC4::theory::Theory::Effort)
/home/irfan/work/projects/CVC4/src/theory/theory_engine.cpp:678:

  d_curr_model->isBuiltSuccess()
")
```
[tmp.zip](https://github.com/CVC4/CVC4/files/3774502/tmp.zip)

**Comment by ajreynol** [comment]
We have some issues with subtyping functions.

f can be assigned (lambda x:U. 0.0)
which is the same as (lambda x:U. 0).

`(-> Int Real)` has different type from `(-> Int Int)`.
