### ISSUE TITLE
CVC4 rejects variable declaration 

### ISSUE THREAD

**Issue by muchang** [CVC4/CVC4#3406]
Hi,
For this formula:
```
(set-logic LRA) 
(declare-fun as () Real)
```
CVC4 rejects the formula with the following error message:
```
(error "Parse Error: test.smt2:2.15: Unexpected token: 'as'.
  (declare-fun as () Real)
               ^
")
```

Commandline: cvc4 file.smt2
OS: Ubuntu 18.04
Revision: 64cef99

**Comment by 4tXJ7f** [comment]
`as` is a reserved word, see the [SMT-LIB standard, page 95](http://smtlib.cs.uiowa.edu/papers/smt-lib-reference-v2.6-r2017-07-18.pdf), so this is expected.

**Comment by muchang** [comment]
I see, thanks for pointing out!
