### ISSUE TITLE
Invalid model on NRA formula

### ISSUE THREAD

**Issue by muchang** [CVC4/CVC4#3407]
Hi,
For this formula:
```
(set-logic NRA)
(declare-fun a () Real)
(declare-fun b () Real)
(assert (= (* a b) 1))
(check-sat)
(get-model)
```
CVC4 will give an invalid model:
```
(model
(define-fun a () Real (/ (- 3) 2))
(define-fun b () Real (/ (- 1) 2))
)
```
which does not satisfy the formula.

OS: Ubuntu 18.04
Revision: 64cef99

**Comment by ahmed-irfan** [comment]
Indeed, it is a bug...

However, if you change the logic to `QF_NRA`, you will get a correct result

**Comment by ajreynol** [comment]
This is a bug.
