### ISSUE TITLE
CVC4 gives UNSAT on SAT formula

### ISSUE THREAD

**Issue by muchang** [CVC4/CVC4#3412]
Hi,
For this formula:
```
(declare-fun a () Int)
(declare-fun c () Int)
(assert (= (div a c) (- 1)))
(check-sat)
(get-model)
```
CVC4 reports `unsat`. While Z3 reports this model:
```
(define-fun a () Int
    1)
(define-fun c () Int
    (- 1))
```
If I feed this model to the formula, CVC4 still reports `unsat`. Is it expected?

OS: Ubuntu 18.04
Revision: 3af2dfe

**Comment by 4tXJ7f** [comment]
Which options did you use to get `unsat`? I can't seem to reproduce it here. This would definitely be a bug.

**Comment by muchang** [comment]
Sorry, I made a mistake here: 
For the formula without feeding the model, CVC4 can correctly report `sat`.
But if I feed the z3 valid model to the formula:
```
(define-fun a () Int 1)
(define-fun c () Int (- 1))
(assert (= (div a c) (- 1)))
(check-sat)
(get-model)
```
CVC4 will report unsat.

**Comment by 4tXJ7f** [comment]
I can reproduce this issue and will look into it.
