### ISSUE TITLE
CVC4 reports unknown when there is no free variable

### ISSUE THREAD

**Issue by muchang** [CVC4/CVC4#3428]
Hi, 
For this formula:
```
(assert (<= (* (/ 0 0) (/ (- (/ 1 2)) 0 (- (/ 1 2)))) (/ (- 1) 4)))
(check-sat)
```
CVC4 will report unknown while this formula doesn't have free variable

OS: Ubuntu 18.04
Revision: c547bd5

**Comment by 4tXJ7f** [comment]
Interesting, it looks like this is due to `(/ 0 0)` and it also happens when the logic is explicitly set to `QF_NRA`.

**Comment by ajreynol** [comment]
Non-linear arithmetic is an undecidable problem. This is expected behavior.

The input implicitly has free variables since you are dividing by zero, which by SMT-LIB semantics is treated as an unconstrained function.  For more information, see http://smtlib.cs.uiowa.edu/theories-Reals.shtml.
