### ISSUE TITLE
Info on new CVC4 releases

### ISSUE THREAD

**Issue by pjljvandelaar** [CVC4/CVC4#3453]
I can subscribe to be informed about new CVC4 releases using `watch releases`.
I can however nowhere find when new releases are planned.
I would like this info, since I am maintaining a [tool](https://github.com/TorXakis/TorXakis) that uses problem solvers.
Based on this information, I could better decide 
* whether upgrading to the latest officially released CVC4 version is worthwhile,
* and when to release our tool.

Can this information be provided? For example, as time line on the wiki?

See for example our [tools' planned releases page](https://github.com/TorXakis/TorXakis/wiki/Planned-Releases)

**Comment by barrettcw** [comment]
We typically release new versions of CVC4 annually, usually over the summer.
We sometimes cut a release more than once a year if there is a strong reason to do so, but this happens rarely.
You can find our release history here: https://github.com/CVC4/CVC4/releases.
