### ISSUE TITLE
Flags to reproduce SyGus comp result

### ISSUE THREAD

**Issue by ychen306** [CVC4/CVC4#3460]
In order to reproduce the result from sygus comp, do we just do `cvc4 x.sl` or there are other flags we should use?

**Comment by 4tXJ7f** [comment]
You can find the scripts used for the SyGuS-COMP [here](https://github.com/CVC4/CVC4/tree/master/contrib/competitions/sygus-comp) (the ones starting with `run-script-sygusComp2019`). There is one script per configuration/track pair.

Please let us know if you have any other questions.
