### ISSUE TITLE
Does the SyGuS solver support custom datatypes and records?

### ISSUE THREAD

**Issue by tjknoth** [CVC4/CVC4#3461]
```
(set-logic ALL_SUPPORTED)

(declare-datatype Doc ((D (owner Int) (body Int))))

(declare-datatype Policy 
  ((p (principal Int)) 
   (por (left Policy) (right Policy))))

(synth-fun mkPolicy ((d Doc)) Policy
  ((Start Policy (Q))
   (Q Policy ((p 0) (p 1) (por Q Q))))
)

(check-synth)
```

Should something like this synthesize? I see a "operator does not have function type" error. It seems like there might be some issues around synthesizing functions over custom data types. In the future we would like to be able to include the record selectors in the grammar as well.

**Comment by ajreynol** [comment]
We have recently improved our support for synthesis of datatype expressions in CVC4's SyGuS solver, so yes this should be handled.

There is an issue with the sygus version 1 parser that is causing the spurious error.  I will submit a fix for this soon.

As a workaround, you can use the sygus version 2 format using command line option `--lang=sygus2`. Notice this format is planned to be the default format accepted by cvc4 in its next stable release.

Here is the version of your benchmark in sygus version 2 format (almost identical except a "predeclaration" is added prior to specifying grammar):

```
(set-logic ALL_SUPPORTED)

(declare-datatype Doc ((D (owner Int) (body Int))))

(declare-datatype Policy 
  ((p (principal Int)) 
   (por (left Policy) (right Policy))))

(synth-fun mkPolicy ((d Doc)) Policy
  ((Start Policy) (Q Policy))
  ((Start Policy (Q))
   (Q Policy ((p 0) (p 1) (por Q Q))))
)

(check-synth)
```

CVC4 answers quickly for this benchmark using `--lang=sygus2`:
```
unsat
(define-fun mkPolicy ((d Doc)) Policy (p 0))
```

For more details on the new format, see https://sygus.org/language/.

**Comment by tjknoth** [comment]
Perfect, thanks!
