### ISSUE TITLE
Smallest solutions first with --sygus-stream

### ISSUE THREAD

**Issue by BillHallahan** [CVC4/CVC4#3479]
I have a SyGuS problem that I want to find the smallest solution too.  The problem involves synthesizing two functions, so by smallest solution, I mean the solution that minimizes the sum of the sizes of both function ASTs:
```
(set-logic ALL)
(declare-datatype Sort_0 ((DT_0 (prop Int))))
(synth-fun f ((x0 Sort_0) (r Sort_0)) Bool 
	((B Bool) (I Int) (G0 Sort_0))
	(
		(B Bool (true (= I I) (< I I) (<= I I) (=> B B) (and B B)))
		(I Int ((Variable Int) 0 (+ I I) (- I I) (mod I I) (prop G0)))
		(G0 Sort_0 ((Variable Sort_0)))
	)
)
(synth-fun g ((x0 Sort_0) (r Int)) Bool
	((B Bool) (I Int) (G0 Sort_0))
	(
		(B Bool ((Variable Bool) true (= I I) (< I I) (<= I I) (=> B B) (and B B)))
		(I Int ((Variable Int) 0 (+ I I) (- I I) (mod I I) (prop G0)))
		(G0 Sort_0 ((Variable Sort_0)))
	)
)
(constraint (and (f (DT_0 0) (DT_0 0))))
(constraint (and (f (DT_0 1) (DT_0 1))
				 (g (DT_0 1) 0)
		    )
)
(constraint (not (and (f (DT_0 0) (DT_0 8)) 
					  (g (DT_0 0) 0)
				 )
			)
)
(constraint (and (f (DT_0 1) (DT_0 1))
				 (g (DT_0 1) 2)
			)
)
(check-synth)
```

I have an additional restriction, that the solution I get for each function must either (1) be a constant or (2) make use of the `r` variable.  As this seems like a hard restriction to enforce with a grammar, I decided to use `--sygus-stream` to enumerate the solutions to the problem, and pick the first one that meets my restrictions.

Unfortunately, running `cvc4 test.sy --lang=sygus2 --sygus-stream` does not give the smallest solutions first, nor does adding `--sygus-active-gen=[X]` work, for any of the enumeration modes.  For example, this is 3 solutions, output in this order with `X=none` (takes <5 seconds if you want to reproduce):

```
(define-fun f ((x0 Sort_0) (r Sort_0)) Bool (<= (prop r) (prop x0)))
(define-fun g ((x0 Sort_0) (r Int)) Bool (<= 0 r))
...
(define-fun f ((x0 Sort_0) (r Sort_0)) Bool (<= (prop r) (prop x0)))
(define-fun g ((x0 Sort_0) (r Int)) Bool (<= r (+ (prop x0) r)))
...
(define-fun f ((x0 Sort_0) (r Sort_0)) Bool (<= (prop r) (prop x0)))
(define-fun g ((x0 Sort_0) (r Int)) Bool true)
```

Notice that the last solution (in particular, the solution for `g`)  is smaller than the two above it.  Is there any combination of settings that will give me the solutions in the order I want?  Thanks!

**Comment by ajreynol** [comment]
I think there is an option that does what you need, try: `--no-sygus-fair-max`.

To explain, by default, CVC4 enforces fairness by searching for solutions where the *maximum size* of any function is no greater than 1,2,3,4...etc.  Another alternative (which is harder to enforce, in general) is to search for solutions where the *sum of sizes* of the functions is no greater than 1,2,3,4.... The option  `--no-sygus-fair-max` enables the latter.  On your example, I'm getting:
```
(define-fun f ((x0 Sort_0) (r Sort_0)) Bool true)
(define-fun g ((x0 Sort_0) (r Int)) Bool (< 0 (prop x0)))
(define-fun f ((x0 Sort_0) (r Sort_0)) Bool true)
(define-fun g ((x0 Sort_0) (r Int)) Bool (< 0 (+ (prop x0) r)))
(define-fun f ((x0 Sort_0) (r Sort_0)) Bool (<= (prop r) (prop x0)))
(define-fun g ((x0 Sort_0) (r Int)) Bool true)
(define-fun f ((x0 Sort_0) (r Sort_0)) Bool (= (prop r) (prop x0)))
(define-fun g ((x0 Sort_0) (r Int)) Bool true)
(define-fun f ((x0 Sort_0) (r Sort_0)) Bool (<= (prop r) (prop x0)))
(define-fun g ((x0 Sort_0) (r Int)) Bool (<= 0 r))
(define-fun f ((x0 Sort_0) (r Sort_0)) Bool (= (prop r) (prop x0)))
(define-fun g ((x0 Sort_0) (r Int)) Bool (<= 0 r))
(define-fun f ((x0 Sort_0) (r Sort_0)) Bool (<= 0 (prop r)))
(define-fun g ((x0 Sort_0) (r Int)) Bool (< 0 (prop x0)))
(define-fun f ((x0 Sort_0) (r Sort_0)) Bool (<= 0 (prop x0)))
(define-fun g ((x0 Sort_0) (r Int)) Bool (< 0 (prop x0)))
...
```

Let me know if that works for you.

**Comment by BillHallahan** [comment]
Yep, this does seem like what I need.  I'll close the issue then. Thanks you!
