### ISSUE TITLE
Threading Issue in src/theory/rewriter.h/cpp

### ISSUE THREAD

**Issue by evmaus** [CVC4/CVC4#3491]
Hey:

It appears that the theory rewriter (src/theory/rewriter.h) is static, but not implemented in a completely threadsafe manner.  In particular, TSAN picks up that d_iterationcount can be overwritten by other threads in RewriteTo.

From looking at the code, though, I'm not sure that d_iterationcount does anything currently--it's only ever set to zero or checked against a modulus to set it to zero, and never incremented.  That may itself be a bug.  :)

This may be innocuous, but it remains undefined behavior--it'd be good for us to get this fixed, if for no other reason than its presence will prevent us from finding any other TSAN issues that may be less innocuous.  I'm happy to send a PR removing d_iterationcount if that seems safe to you all and it being unused isn't a bug, or help look into making Rewriter non-static or threadsafe if that seems more appropriate.

Thanks,
Everett

**Comment by aniemetz** [comment]
Good catch! @4tXJ7f can you look into this?

We're currently in the process of refactoring/redesigning the whole rewriting architecture, with one of the goals to not have static member functions in the future. This might take a while, though.

**Comment by 4tXJ7f** [comment]
Heh, I actually found the same issue recently and been working on a fix
(together with other similar fixes). I hope to submit a PR soon.

**Comment by evmaus** [comment]
Excellent!  Do you have a rough ETA?  That'll help me plan our import on our side.

Thanks,
Everett

**Comment by 4tXJ7f** [comment]
PR #3547 should fix this specific issue. However, TSan reports some other issues, which will be fixed in another PR that I'll try to get submitted today as well.
