### ISSUE TITLE
Is it possible to define a grammar that introduces a new variable? 

### ISSUE THREAD

**Issue by tjknoth** [CVC4/CVC4#3503]
I'd like to be able to use the SYGUS solver to synthesize simple pattern-matching expressions. 
My only attempt has been to define a grammar like:
```
Prog ::= Exp | (match x ((nothing Exp) ((just y) Exp2)))
Exp ::= ...
Exp2 ::= y | ...
```
Here, the `Exp2` production rule essentially defines the same expression language as 
the `Exp` rule, but extended with the (hard-coded) binder `y` from the match expression in the top-level production rule.
Hard-coding the binder is definitely a hack but I shouldn't need more than one level of 
pattern matching so this approach seemed sufficient.

However, I get a "Symbol y is not declared" error when i include y in the extended expression grammar. Is there a way to make this work?

**Comment by ajreynol** [comment]
Unfortunately the SyGuS solver does not have ways of reasoning about binders within grammars.  This is a fairly challenging problem. We may pursue this in the future, but unfortunately the current solver (and SyGuS language standard) prohibit binders within SyGuS grammars, including the SMT-LIB 2.6 match construct.

Can you send me the SyGuS file you are getting the error on? I can recommend an alternative version that avoids the error.

**Comment by tjknoth** [comment]
Yeah, I figured binders wouldn't work in general but was hoping to hack my way around it for some constrained cases. Here's a small example of what I've been trying to accomplish:

```
(set-logic ALL_SUPPORTED)

;; Monomorphic maybe type
(declare-datatype MaybeInt ((just (get Int)) (nothing)))

(synth-fun mkSet((x MaybeInt)) (Set Int)

 ((Prog (Set Int)) (PSet (Set Int)) (PSetExt (Set Int)) (Z Int) (ZExt Int) (Mb MaybeInt)) 

 ((Prog (Set Int) (PSet (match Mb ((nothing PSet) ((just mb) PSetExt)))))
  (PSet (Set Int) ((as emptyset (Set Int))
                   (singleton Z) 
                   (insert Z PSet) 
                   (union PSet PSet)))
  (PSetExt (Set Int) ((as emptyset (Set Int))
                      (singleton ZExt) 
                      (insert ZExt PSetExt) 
                      (union PSet PSetExt)))
  (Z Int ((Constant Int)))
  (ZExt Int (mb (Constant Int)))
  (Mb MaybeInt (x))))


(constraint (member 0 (mkSet (just 0))))
(constraint (not (member 1 (mkSet (just 0)))))
(constraint (not (member 0 (mkSet nothing))))

(check-synth)
```
From this file, I get a parse error "symbol mb is not declared" with CVC4 1.8

**Comment by ajreynol** [comment]
In the end, notice that `match` is just syntax sugar for an ITE, i.e. (ite ((_ is nothing) Mb) PSet PSet) in this case.  Additionally you can extend the grammar to use `get`.  Here is a version of the benchmark:
```
(set-logic ALL_SUPPORTED)

;; Monomorphic maybe type
(declare-datatype MaybeInt ((just (get Int)) (nothing)))

(synth-fun mkSet((x MaybeInt)) (Set Int)

 ((Prog (Set Int)) (PSet (Set Int)) (PSetExt (Set Int)) (Z Int) (ZExt Int) (Mb MaybeInt)) 

 ((Prog (Set Int) (PSet (ite ((_ is nothing) Mb) PSet PSet)))
  (PSet (Set Int) ((as emptyset (Set Int))
                   (singleton Z) 
                   (insert Z PSet) 
                   (union PSet PSet)))
  (PSetExt (Set Int) ((as emptyset (Set Int))
                      (singleton ZExt) 
                      (insert ZExt PSetExt) 
                      (union PSet PSetExt)))
  (Z Int ((Constant Int)))
  (ZExt Int ((get Mb) (Constant Int)))
  (Mb MaybeInt (x))))


(constraint (member 0 (mkSet (just 0))))
(constraint (not (member 1 (mkSet (just 0)))))
(constraint (not (member 0 (mkSet nothing))))

(check-synth)
```
I get this solution:
```
(define-fun mkSet ((x MaybeInt)) (Set Int) (ite ((_ is nothing) x) (as emptyset (Set Int)) (singleton 0)))
```

**Comment by tjknoth** [comment]
Oh, cool, thanks! Didn't realize this `_ is` syntax exists, it's working for me with less trivial ADTs as well, this is exactly what I needed.

**Comment by tjknoth** [comment]
Quick followup question -- is it possible to put constraints on the interpretation of the record selectors when applied to the wrong constructor? 
For example, continuing from the simple case above, I'd like to be able to define `some nothing = foo`. I tried using `assert` and putting it in the synthesis `constraint` but neither seemed to work.

**Comment by ajreynol** [comment]
I would probably just define a custom selector that enforces that semantics, and then use that function instead of the selector, e.g.:
```
(define-fun myGet ((x MaybeInt)) Int (ite ((_ is nothing) x) foo (get x)))
```
In general, you should be careful not to allow wrongly applied selectors in your grammar or constraints, since their semantics is unconstrained.

**Comment by tjknoth** [comment]
Gotcha, that makes a lot of sense, thanks.
