### ISSUE TITLE
CVC4 reports unknown when check-unsat-cores is enabled

### ISSUE THREAD

**Issue by muchang** [CVC4/CVC4#3505]
Hi,
For this formula,
```
(set-logic ALL)
(declare-fun a () Int)
(declare-fun b () Int)
(assert (< b 0))
(assert (= (/ 3 b a) 1))
(assert (= a (- 2)))
(check-sat)
```
With command `cvc4 small.smt2`, cvc4 reports `unsat`.
However, if we enable check-unsat-cores `cvc4 --check-unsat-cores small.smt2`, cvc4 will report `unknown`.
Is this expected?

OS: Ubuntu 18.04
Version: 5e2d39c

**Comment by ajreynol** [comment]
Yes, this problem involves non-linear arithmetic and hence the techniques are heuristic.  Setting `--check-unsat-cores` will impact which options are used, hence you may see a benchmark go unsat -> unknown. In general, you can use `--nl-ext-tplanes` to avoid CVC4 answering "unknown" with non-linear arithmetic (it answers unsat with `--nl-ext-tplanes --check-unsat-cores`).
