### ISSUE TITLE
Sygus inference, exp soundness bug 

### ISSUE THREAD

**Issue by wintered** [CVC4/CVC4#3564]
Hi,
for the following formula CVC4 with `--sygus-inference` return `unsat` but `sat` without that option.  

```
(assert (or (< 60.3 (exp 4.1) 60.4) (< (exp 5.1) 164.1)))
(check-sat)
```
Revision: 8afa8a8
OS: Ubuntu 18.04

**Comment by ajreynol** [comment]
As an internal note, the same behavior can be observed by `--decision=internal`.
