### ISSUE TITLE
bug with `to_fp_unsigned`

### ISSUE THREAD

**Issue by robdockins** [CVC4/CVC4#3582]
As far as I can tell, the following script should be accepted without error and return unsat.  It seems to be a problem with promoting a 1-bit vector do a floating point value.  Promoting a value at least 2-wide does not fail.

```
$ cat cvc4-bug-minimal.smt2
(set-logic ALL_SUPPORTED)

(declare-fun bv () (_ BitVec 1))

(define-fun x () (_ FloatingPoint 11 53) ((_ to_fp_unsigned 11 53) RNE bv))

(assert (fp.isNaN x))

(check-sat)

$ cvc4 --lang=smt2 cvc4-bug-minimal.smt2
(error "Illegal argument detected
CVC4::FloatingPointSize::FloatingPointSize(unsigned int, unsigned int)

  `_s' is a bad argument; expected validSignificandSize(_s) to hold
Invalid significand size : 1")

$ cvc4 --version
This is CVC4 version 1.7-prerelease [git master 1955e4b5]
compiled with GCC version 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.10.44.2)
on Oct 26 2018 15:21:43
```

**Comment by martin-cs** [comment]
This is a SymFPU bug.  Specifically it is here:

https://github.com/martin-cs/symfpu/blob/master/core/convert.h#L202

**Comment by martin-cs** [comment]
Correction -- that is one of the SymFPU bugs.  It also runs into the well known "SymFPU doesn't handle insane formats" issue.  I can fix but as with https://github.com/CVC4/CVC4/issues/3696 it's not the highest priority.
