### ISSUE TITLE
Scoping issue in incremental mode

### ISSUE THREAD

**Issue by wintered** [CVC4/CVC4#3584]
Hi, 
consider the following formula.

```
(declare-fun a () Int)
(declare-fun b (Int) Bool)
(assert (= (or (= 0 0)) (b 0)))
(push)
(assert (= true (distinct true (distinct false (= a 0)) (= false (b 0)))))      
(check-sat)
(get-model)
```
CVC4 returns `sat` here although the second assert is clearly unsatisfiable. It seems like CVC4 dropped the second assert. When I feed the model to the formula, CVC4 returns `unsat`.

OS: Ubuntu 18.04
Revision: b3471b7

**Comment by 4tXJ7f** [comment]
Interesting, I can't seem to reproduce this. CVC4 is answering `unsat` for me (running with just `--incremental`). Which options did you use?

**Comment by wintered** [comment]
I'm sorry, I was mistaken. This is not a CVC4 issue. It is a bug in Z3 https://github.com/Z3Prover/z3/issues/2830.
