### ISSUE TITLE
strings-exp enabled changes result

### ISSUE THREAD

**Issue by wintered** [CVC4/CVC4#3587]
Consider the following formula.

```
(declare-sort a 0) 
(declare-datatypes ((prod 0)) (((Pair (gx a) (gy a))))) 
(declare-fun p () prod) 
(assert (forall ((x a) (y a)) (not (= p (Pair x y))))) 
(check-sat)                
```
If I understand correctly, this formula should be `unsat`, which is what CVC4 reports with `--finite-model-find`. However, if I only put `--strings-exp`, then I get `sat`.

OS: Ubuntu 18.04
Revision: b3471b7

**Comment by ajreynol** [comment]
Thanks for the report, this is fixed in my latest PR.
