### ISSUE TITLE
SyGuS-IF 2.0?

### ISSUE THREAD

**Issue by zhanghongce** [CVC4/CVC4#3588]
Hi

1. For bit-vectors, can I suggest to output the sort with the underscore, namely `(_ BitVec 2)` instead of `(BitVec 2)`?

2. I'm surprised that it seems that you can not have `let` in the definitions of functions, in the form of
`(let ((Variable Expression)+) Expression)`

Example: Although the following works:
```
(set-logic BV)
(define-fun AllEq 
   ((A (_ BitVec 2))
    (B (_ BitVec 2))
    (C (_ BitVec 2))
   ) Bool
   (and (= A B) (= B C))
)

(synth-fun INV 
   ((A (_ BitVec 2))
    (B (_ BitVec 2))
    (C (_ BitVec 2))
   ) 
   Bool
  (
    (Start Bool (Conj))
    (Conj Bool (Disj 
                (and Disj Conj)))
    (Disj Bool (Literal 
                (or Literal Disj)))
    (Literal Bool (Atom
                (not Atom)))
    (Atom Bool ((= E2 E2)))
    (E2 (_ BitVec 2) (V2 C2 (bvadd E2 E2)))
    (V2 (_ BitVec 2) (A B C))
    (C2 (_ BitVec 2) (#b00 #b01 #b10 #b11))
   ))

(declare-var a (_ BitVec 2))
(declare-var b (_ BitVec 2))
(declare-var c (_ BitVec 2))

(constraint (INV #b00 #b01 #b01))
(constraint (not (INV #b10 #b01 #b01)))
(constraint (=> (AllEq a b c) (INV a b c)))

(check-synth)
```

If I change the definition of `AllEq` to 
```
(define-fun AllEq
   ((A (_ BitVec 2))
    (B (_ BitVec 2))
    (C (_ BitVec 2))
   ) Bool
   (let ((c1 (= A B)))
    (let ((c2 (= B C)))
      (let ((c3 (and c1 c2)))
        c3
    )))
)
```
it will not work.

```
CVC4 Error:
Parse Error: cnt-let.sygus:18.17: Symbol 'A' not declared as a type

     (let ((c1 (= A B)))
```
From the error message it seems that CVC4 is expecting the let in the form of
`(let ((Variable Sort Expression)+) Expression)`, and indeed that works
 but I was wondering is this compatible with SMT-LIB2?

**Comment by zhanghongce** [comment]
Sorry, I found that with option `--lang=sygus2` it will be solved.
Thank you!

**Comment by ajreynol** [comment]
Right, using that option is the correct fix.
FYI, we are planning to make sygus language 2.0 the default sygus language in the next stable release of CVC4.

**Comment by zhanghongce** [comment]
Thank you, Andrew!
