### ISSUE TITLE
Bug? Clarification about the implementation of ^

### ISSUE THREAD

**Issue by wintered** [CVC4/CVC4#3592]
Hi, 
consider the following formula:

```
(assert (distinct 1.0 (^ 0.0 0.0)))
(check-sat)
```
CVC4 reports `unsat` for this formula, although I'd assume that, similar to the division by zero,  `(^ 0.0 0.0)` is uninterpreted. I have looked at the SMT Lib standard ( http://smtlib.cs.uiowa.edu/logics-all.shtml) where the `(^` operator is not mentioned while in the spec for the theory of Reals it is
(c.f.http://smtlib.cs.uiowa.edu/theories-Reals.shtml). Z3, btw, gives ``sat` on this formula.

OS: Ubuntu 18.04
Revision: e3e6f0d

**Comment by ajreynol** [comment]
`^` is interpreted as the power operator in CVC4. It is not a standard SMT-LIB operator.  I believe that 0 to the power of 0 is commonly interpreted as 1, right?  Thus I'm not sure about the correctness of Z3 in this case.
