### ISSUE TITLE
Unable to catch `TypeCheckingExceptionPrivate` via Python

### ISSUE THREAD

**Issue by andrewvaughanj** [CVC4/CVC4#3616]
For some "API errors", it seems that we get SWIG-wrapped exceptions that report things nicely.

For example, building an `Expr` incorrectly might give you:

```
Wrong number or type of arguments for overloaded function 'ExprManager_mkExpr'.
  Possible C/C++ prototypes are:
    CVC4::ExprManager::mkExpr(CVC4::Kind,CVC4::Expr)
    CVC4::ExprManager::mkExpr(CVC4::Kind,CVC4::Expr,CVC4::Expr)
    CVC4::ExprManager::mkExpr(CVC4::Kind,CVC4::Expr,CVC4::Expr,CVC4::Expr)
    CVC4::ExprManager::mkExpr(CVC4::Kind,CVC4::Expr,CVC4::Expr,CVC4::Expr,CVC4::Expr)
    CVC4::ExprManager::mkExpr(CVC4::Kind,CVC4::Expr,CVC4::Expr,CVC4::Expr,CVC4::Expr,CVC4::Expr)
    CVC4::ExprManager::mkExpr(CVC4::Kind,std::vector< CVC4::Expr,std::allocator< CVC4::Expr > > const &)
    CVC4::ExprManager::mkExpr(CVC4::Kind,CVC4::Expr,std::vector< CVC4::Expr,std::allocator< CVC4::Expr > > const &)
    CVC4::ExprManager::mkExpr(CVC4::Expr)
    CVC4::ExprManager::mkExpr(CVC4::Expr,CVC4::Expr)
    CVC4::ExprManager::mkExpr(CVC4::Expr,CVC4::Expr,CVC4::Expr)
    CVC4::ExprManager::mkExpr(CVC4::Expr,CVC4::Expr,CVC4::Expr,CVC4::Expr)
    CVC4::ExprManager::mkExpr(CVC4::Expr,CVC4::Expr,CVC4::Expr,CVC4::Expr,CVC4::Expr)
    CVC4::ExprManager::mkExpr(CVC4::Expr,CVC4::Expr,CVC4::Expr,CVC4::Expr,CVC4::Expr,CVC4::Expr)
    CVC4::ExprManager::mkExpr(CVC4::Expr,std::vector< CVC4::Expr,std::allocator< CVC4::Expr > > const &)
```

the class of this exception is `NotImplementedError`, which is then catchable/recoverable from in Python.

However, if you build an `Expr` correctly, but it has the wrong types (e.g., using bit-vector operations with floating point expressions), then you might get something like:

```
terminate called after throwing an instance of 'CVC4::TypeCheckingException'
  what():  expecting bit-vector terms
Aborted
```

which, because it is a "raw" C++ exception, is uncatchable from Python.

I have no idea if this is a WONTFIX because of the impending Cython API, but the fact that CVC4.so raises an "uncatchable" exception is quite "user-hostile".

As an aside, it seems that the Java CVC4 bindings have explicit code to catch some of CVC4's internal exceptions and make sure they're raised correctly; not sure if that's what's needed here.

**Comment by 4tXJ7f** [comment]
Closing since this is resolved in the new API: https://github.com/CVC4/CVC4/blob/master/examples/api/python/exceptions.py
