### ISSUE TITLE
--fp-exp Fatal failure at  at CVC4/src/util/floatingpoint.cpp:454

### ISSUE THREAD

**Issue by muchang** [CVC4/CVC4#3623]
Hi,
For this formula,
```
(declare-fun a () (Array Int (_ FloatingPoint 53 78)))
(assert (= (select a 0) (select a 1)))
(check-sat)
```
`cvc4 --fp-exp` throws out an fatal failure:
```
Fatal failure within static void CVC4::symfpuLiteral::traits::invariant(const prop&) at CVC4/src/util/floatingpoint.cpp:454
Check failure
 p
Aborted
```

OS: Ubuntu 18.04
Revision: c3bc4ac

**Comment by aniemetz** [comment]
@muchang option `--fp-exp` is experimental and not intended for general usage. It is experimental for a reason and we expect it to trigger problems, which we already work on to resolve. Please do not submit issues you encounter with `--fp-exp`.
