### ISSUE TITLE
--strings-exp Fatal failure at CVC4/src/theory/quantifiers/equality_query.cpp:171 

### ISSUE THREAD

**Issue by muchang** [CVC4/CVC4#3626]
Hi,
For this formula,
```
(assert (forall ((a Int)) (or (distinct (/ 0 0) a) (= (/ 0 a) 0))))
(check-sat)
```
`cvc4 --strings-exp` throws out a fatal failure although the formula does not involve any strings:
```
Fatal failure within CVC4::Node CVC4::theory::quantifiers::EqualityQueryQuantifiersEngine::getInternalRepresentative(CVC4::Node, CVC4::Node, int) at CVC4/src/theory/quantifiers/equality_query.cpp:171
Check failure
 r_best.getType().isSubtypeOf(v_tn)
Aborted
```

Moreover, z3 complains about the sort mismatch of this formula:
```
(error "line 1 column 50: Sort mismatch between first argument and argument 2")
sat
```
while cvc4 without --strings-exp does not complain.

If I change `or` to `and`, cvc4 without --strings-exp hangs on it:
```
[565] % timeout -s 9 60 cvc4 --quiet small.smt2
Killed
[566] % cat small.smt2
(assert (forall ((a Int)) (and (distinct (/ 0 0) a) (= (/ 0 a) 0))))
(check-sat)
```

OS: Ubuntu 18.04
Revision: c3bc4ac

**Comment by ajreynol** [comment]
For some detail, `--strings-exp` enables bounded integer quantification (which is required for solving some kind of string constraints which are equivalent to quantified formulas).  Thus even though the problem does not have strings, you are likely finding a bug in the bounded integer quantifiers module.  You can also try `--fmf-bound` to find bugs like this.
