### ISSUE TITLE
--produce-models Fatal failure at CVC4/src/smt/smt_engine.cpp:4284

### ISSUE THREAD

**Issue by muchang** [CVC4/CVC4#3628]
Hi,
For this formula
```
(declare-fun a () Real)
(declare-fun b () Real)
(declare-fun c () Real)
(declare-fun d () Real)
(declare-fun e () Real)
(assert (let ((f (exists ((g Real))
             (= (< 0.0 (* b d)) (distinct (* (to_real 1) a c) 1.0)))))
  (not f)))
(assert (= a (* c e)))
(check-sat)
(get-model)
```
`cvc4 --produce-models` throws out a fatal failure:
```
Fatal failure within CVC4::Expr CVC4::SmtEngine::getValue(const CVC4::Expr&) const at CVC4/src/smt/smt_engine.cpp:4284
Check failure
 resultNode.getKind() == kind::LAMBDA || resultNode.getKind() == kind::CHOICE || resultNode.isConst()
Aborted
```

OS: Ubuntu 18.04
Revision: 2f46d30

**Comment by ajreynol** [comment]
The assertion that fails is not written to handle terms involving (strict) subterms involving choice functions e.g.:
`(* (/ 1 4) (choice ((BOUND_VARIABLE_1421 Real)) (and (>= BOUND_VARIABLE_1421 (/ (- 1048579) 524288)) (>= (* (- 1.0) BOUND_VARIABLE_1421) (/ 2097143 1048576)))))
`

**Comment by muchang** [comment]
Here is another simpler case that triggers the same check failure:
```
(declare-fun a () Real)
(assert (= a (sin 1)))
(check-sat)
(get-model)
```
