### ISSUE TITLE
incorrect synthesis result when using quantifiers

### ISSUE THREAD

**Issue by polgreen** [CVC4/CVC4#3649]
I know quantifiers aren't officially supported in SyGuS-IF, but this is an instance of CVC4 returning an incorrect answer (as oppose to unknown, an exception, or just not returning an answer).

This isn't a very minimal example, but for the file below cvc4 produces the answer `false`, which isn't a valid solution (as double checked with z3 and cvc4 as an smt solver):
~~~
unsat
(define-fun inv-fn ((i Int) (x (Array Int Int)) (c Int)) Bool false)
~~~
The sygus file:
~~~
(set-logic ALL)
(synth-fun inv-fn ((i Int) (x (Array Int Int)) (c Int)) Bool)
(declare-var x (Array Int Int))
(declare-var x! (Array Int Int))
(declare-var i Int)
(declare-var i! Int)
(declare-var c Int)

(define-fun init-fn ((i Int) (x (Array Int Int)) (c Int)) Bool 
	(and (= i 0)
	(= (select x 10) c)))

(define-fun post-fn ((i Int) (x (Array Int Int))(c Int)) Bool 
	(exists ((index Int)) (and (= (select x index) c)
	(forall ((index2 Int)) (=> (< index2 index) (not (= (select x index) c)))))))

(constraint (=> (init-fn i x c) (inv-fn i x c)))
(constraint (=> (inv-fn i x c) (post-fn i x c)))
(check-synth)
~~~

**Comment by ajreynol** [comment]
Something looks a bit odd with the quantifier:
`(forall ((index2 Int)) (=> (< index2 index) (not (= (select x index) c))))`
Should this be
`(forall ((index2 Int)) (=> (< index2 index) (not (= (select x index2) c))))` ?
In the benchmark above, I believe `post-fn` is equivalent to `false`.
Regardless, I do believe there is a bug (the correct solution actually should be`inv-fn = true`).  I will fix this soon.

**Comment by polgreen** [comment]
Ah, yes, that was a typo in the quantifier. Thanks for the quick fix!
