### ISSUE TITLE
resource limit and steps increments

### ISSUE THREAD

**Issue by kanigsson** [CVC4/CVC4#3751]
I'm trying to tune cvc4 resource limits using the various *step switches on the command line:
```
  --bitblast-step=N      
  --bv-sat-conflict-step=N
  --cnf-step=N           
  --decision-step=N      
  --lemma-step=N         
  --parse-step=N         
  --preprocess-step=N    
  --quantifier-step=N    
  --restart-step=N       
  --rewrite-step=N       
  --sat-conflict-step=N  
  --theory-check-step=N  
```
I am assuming these switches influence how the internal counter is incremented for each of these submodules. This internal counter is output with the `--stats` switch as `smt::SmtEngine::resourceUnitsUsed`. (correct?)

To improve our tuning of the resource limits, I would like to know how many times each of these separate increments was hit (e.g. how many times the `rewrite_step` increment was done). Is this information available in the output of `--stats`? If not, could it be added? Otherwise it seems impossible to use these switches other than guessing and checking the outcome.

**Comment by mpreiner** [comment]
That's a good point, we don't have any detailed statistics for each resource step right now. I'll have a look and add a statistics for each resource.

**Comment by kanigsson** [comment]
Thanks!
