### ISSUE TITLE
`fPIC`-related link issues when building on CentOS 8

### ISSUE THREAD

**Issue by andrewvaughanj** [CVC4/CVC4#3784]
I just set up a fresh CentOS 8 VM to build CVC4 on, however this failed with a link-time issue related to GMP.

Machine specifics (pretty much a "stock" CentOS 8 install):

```
uname -a
Linux avjcentos8 4.18.0-147.3.1.el8_1.x86_64 #1 SMP Fri Jan 3 23:55:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/redhat-release
CentOS Linux release 8.1.1911 (Core)

gcc --version
gcc (GCC) 8.3.1 20190507 (Red Hat 8.3.1-4)

ld --version
GNU ld version 2.30-58.el8.0.1

ld.gold --version
GNU gold (version 2.30-58.el8.0.1) 1.15
```

CVC4 build command (`cadical`/`symfpu` are irrelevant, but that's the configuration I'm building):

```
rm -rf deps && \
 ./contrib/get-antlr-3.4 && \
 ./contrib/get-gmp && \
 ./contrib/get-cadical && \
 ./contrib/get-symfpu && \
 ./configure.sh --cadical --symfpu --python2 && \
 cd build && \
 make -j12
```

This then gives me:

```
/usr/bin/ld.gold: error: ../../deps/install/lib/libgmp.a(mp_get_fns.o): requires dynamic R_X86_64_PC32 reloc against '__gmp_allocate_func' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: ../../deps/install/lib/libgmp.a(lt2-add.o): requires dynamic R_X86_64_PC32 reloc against '__gmpz_realloc' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: ../../deps/install/lib/libgmp.a(and.o): requires dynamic R_X86_64_PC32 reloc against '__gmpz_realloc' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: ../../deps/install/lib/libgmp.a(cdiv_q.o): requires dynamic R_X86_64_PC32 reloc against '__gmp_tmp_reentrant_alloc' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: ../../deps/install/lib/libgmp.a(cfdiv_q_2exp.o): requires dynamic R_X86_64_PC32 reloc against '__gmpz_realloc' which may overflow at runtime; recompile with -fPIC
... snip ...
```

times _a lot_ -- there's 140 instances of this! Setting both `CFLAGS`/`CXXFLAGS` to be `-fPIC` does not fix anything (same number of errors).

However, trying with `MAKE_CFLAGS=-fPIC` reduces this down to 6:

```
/usr/bin/ld.gold: error: ../../deps/install/lib/libgmp.a(mod_1_1.o): requires dynamic R_X86_64_PC32 reloc against '__gmpn_invert_limb' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: ../../deps/install/lib/libgmp.a(mod_1_2.o): requires dynamic R_X86_64_PC32 reloc against '__gmpn_invert_limb' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: ../../deps/install/lib/libgmp.a(mod_1_4.o): requires dynamic R_X86_64_PC32 reloc against '__gmpn_invert_limb' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: ../../deps/install/lib/libgmp.a(gcd_1.o): requires dynamic R_X86_64_PC32 reloc against '__gmpn_mod_1' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: ../../deps/install/lib/libgmp.a(divrem_1.o): requires dynamic R_X86_64_PC32 reloc against '__gmpn_invert_limb' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: ../../deps/install/lib/libgmp.a(divrem_2.o): requires dynamic R_X86_64_PC32 reloc against '__gmpn_invert_limb' which may overflow at runtime; recompile with -fPIC
```

What _does_ fix this is this:

```
diff --git a/contrib/get-gmp b/contrib/get-gmp
index 678103cf4..d6274e90c 100755
--- a/contrib/get-gmp
+++ b/contrib/get-gmp
@@ -25,7 +25,7 @@ echo "Setting up GMP $GMPVERSION..."
 echo
 setup_dep "https://gmplib.org/download/gmp/gmp-$GMPVERSION.tar.bz2" "$GMP_DIR"
 cd "$GMP_DIR"
-./configure ${HOST} --prefix="$INSTALL_DIR" --enable-cxx ${BUILD_TYPE}
+./configure ${HOST} --prefix="$INSTALL_DIR" --enable-cxx ${BUILD_TYPE} --with-pic
 make \
   CFLAGS="${MAKE_CFLAGS}" \
   CXXFLAGS="${MAKE_CXXFLAGS}" \
```

That is, passing in `--with-pic` to GMP's `configure`.

Is a change to `get-gmp` like this acceptable? Windows does not have `fPIC` (all code is PI on Windows), but I don't know how this might impact static builds of CVC4.

**Comment by 4tXJ7f** [comment]
The `contrib/get-gmp` script is a bit confusing and we should maybe change it. The idea of the script is to have an easy way to to compile a _static_ version of GMP because some distributions (for example Arch Linux) don't ship static libraries. We usually recommend that you use the GMP version provided by the OS package manager. One possible solution would be to have the script compile both versions of the libraries or to use the `--with-pic` flag as you suggested. I will discuss this with the others and we'll get back to you soon.

**Comment by mpreiner** [comment]
@andrewvaughanj was there a reason why you used the script instead of using the CentOS version? The comment in https://github.com/CVC4/CVC4/blob/master/contrib/get-gmp#L3 should make it clear that you should only use this script if all else fails.

**Comment by andrewvaughanj** [comment]
@mpreiner a little bit yes and a little bit no :)

For my "yes" reason, I typically need to _not_ depend on distro versions of libraries, and build them myself, _but I do this outside of CVC4_ and set things like CFLAGS/CXXFLAGS/LDFLAGS to point to my "fake root".

So, I was being lazy here, and just thought "oh, CVC4 has a script to build this GMP, why not use that?" (I've been spoilt by the reliability of other solver's `contrib` scripts, you see :p). This means that the answer is "no" (in this instance).

Had I realised that I wasn't supposed to use that script (which I might have done, if I read the comment!), then I probably wouldn't have opened this issue ...

**Comment by 4tXJ7f** [comment]
Commit 5ec4b57ba3f79db76c5544b3ee37b917f7f0b58e added a warning to the script and additional information about the GMP script in INSTALL.md, so I am closing this issue for now.
