### ISSUE TITLE
CVC4 "developer guide" does not list the minimum version of `clang-format`

### ISSUE THREAD

**Issue by andrewvaughanj** [CVC4/CVC4#3785]
I've just tried to run `clang-format` on two separate machines:

CentOS 8:
```
clang-format --version
clang-format version 8.0.1 (Red Hat 8.0.1-1.module_el8.1.0+215+a01033fb)
```

CentOS 7.7:

```
clang-format --version
clang-format version 5.0.1 (tags/RELEASE_501/final)
```

and both of these give the following error:

```
YAML:9:19: error: unknown key 'AfterCaseLabel'
  AfterCaseLabel: true
                  ^~~~
Error reading /home/avj/CVC4/.clang-format: Invalid argument
```

This is because `clang-format` is not "forwards compatible" (so older versions of `clang-format` rightly reject newer options).

Looking at the clang repo (https://github.com/llvm-mirror/clang/commit/764bd63e5b6b19051d14a3172ee82fb3e83b8857) it seems that `AfterCaseLabel` was added in April 2019, which means the _minimum_ version of `clang-format` required for CVC4 is  `clang9`.

**Comment by aniemetz** [comment]
@andrewvaughanj you're right, I had to add this option because without it, formatting broke with clang >= 9 (and I'm on Arch and typically have the newest version of the team). I forgot to add this to the dev guide though, good catch! Will add shortly.

**Comment by aniemetz** [comment]
https://github.com/CVC4/CVC4/wiki/Developer-Guide#formatting-with-clang-format
