### ISSUE TITLE
No recent development versions available 

### ISSUE THREAD

**Issue by pjljvandelaar** [CVC4/CVC4#3805]
As a user, I would like recent development versions to experiment with the latest features.
As bug reporter, I would like recent development versions to check asap that issues are indeed solved.
CVC4 also provides recent development versions at https://cvc4.cs.stanford.edu/downloads/ .

However, 
https://cvc4.cs.stanford.edu/downloads/builds/src/unstable/ contains no updates since 2018-09-18.
https://cvc4.cs.stanford.edu/downloads/builds/x86_64-linux-opt/unstable/ and https://cvc4.cs.stanford.edu/downloads/builds/win64-opt/unstable/ contain no updates since 2020-02-13.

So I wonder whether some automatic build or upload mechanism is no longer functioning.
Could you please look into this?

**Comment by 4tXJ7f** [comment]
Thank you for reporting this. The builds seem to have gone through but it looks like the binaries were not copied to the appropriate places. We will look into it ASAP.

**Comment by mpreiner** [comment]
This is fixed now, nightly binaries are uploaded again.

**Comment by pjljvandelaar** [comment]
Is it a conscious decision that source archives of recent development versions are no longer supported? 
https://cvc4.cs.stanford.edu/downloads/builds/src/unstable/ still hasn't a recent version.

**Comment by mpreiner** [comment]
Yes, it is. The code is available on GitHub.
