### ISSUE TITLE
sygus-inference incorrect answer on QF_NIA formula 

### ISSUE THREAD

**Issue by muchang** [CVC4/CVC4#3839]
Hi,
For this formula:
```
(declare-fun a () Int)
(declare-fun b () Int)
(assert (xor (> a 0) (not (and (ite (= a b) (> (* 4 a b) 1) true) (> (* a a) 0)))))
(assert (= a b))
(assert (> (* a b) 0))
(check-sat)
```
CVC4 --sygus-inference incorrectly gives unsat, while this formula should be sat.

OS: Ubuntu 18.04
Commit: 5c844f0

**Comment by ajreynol** [comment]
Due to the rewriting pass `--cond-rewrite-quant`, will fix this soon.
