### ISSUE TITLE
UFNRA instance SmtEngine::checkModel(): cannot check simplified assertion 

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#3912]
Hi,
For this formula,
[cvc336.txt](https://github.com/CVC4/CVC4/files/4285619/cvc336.txt)

cvc4-nightly (http://cvc4.cs.stanford.edu/downloads/builds/x86_64-linux-opt/unstable/cvc4-2020-03-03-x86_64-linux-opt) incremental mode
issues a warning 
~~~~
Warning : SmtEngine::checkModel(): cannot check simplified assertion : (forall ((q20 Bool)) (= (= (= ...
~~~~

OS: Ubuntu 16.04

**Comment by ajreynol** [comment]
This is expected behavior.  This is related to https://github.com/CVC4/cvc4-wishues/issues/43.
