### ISSUE TITLE
NRA instances fatal failure within CVC4::Node CVC4::preprocessing

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#3914]
Hi,
For the following formulas,
[dbz2.txt](https://github.com/CVC4/CVC4/files/4285833/dbz2.txt)
[dbz1.txt](https://github.com/CVC4/CVC4/files/4285831/dbz1.txt)

cvc4-nightly (http://cvc4.cs.stanford.edu/downloads/builds/x86_64-linux-opt/unstable/cvc4-2020-03-03-x86_64-linux-opt) incremental mode
crashed
~~~~
Fatal failure within CVC4::Node CVC4::preprocessing::passes::ApplyToConst::rewriteApplyToConst(CVC4::
TNode, CVC4::preprocessing::passes::NodeMap&) at /barrett/scratch/cvc4-nightly/src/cvc4-2020-03-03/src/preprocessing/passes/apply_to_const.cpp:70
Unhandled case encounteredThe rewrite-apply-to-const preprocessor is currently limited;
it only works if all function symbols are unary and with Integer domain, and all applications are to integer values.
Found application: (divByZero (* (- 1.0) r7))
Aborted (core dumped)
~~~~

OS: Ubuntu 16.04

**Comment by 4tXJ7f** [comment]
Thank you for reporting this issue. I think that the issue is that we expand definitions before the apply-to-const. Expanding the definitions introduces UFs for division, which are not handled correctly by apply-to-const.

**Comment by 4tXJ7f** [comment]
It turns out that the preprocessing pass enabled by this flag was not particularly useful because of its very narrow scope, so we've decided to remove it.
