### ISSUE TITLE
Fatal failure for UFNIA instance at src/smt/smt_engine.cpp:4808

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#3915]
Hi,
For this formula,
[checkmodel1.txt](https://github.com/CVC4/CVC4/files/4286447/checkmodel1.txt)

--minimized test case--
[checkmodel1-minimized.txt](https://github.com/CVC4/CVC4/files/4288106/checkmodel1-minimized.txt)

cvc4-nightly (http://cvc4.cs.stanford.edu/downloads/builds/x86_64-linux-opt/unstable/cvc4-2020-03-03-x86_64-linux-opt) incremental mode
crashed with the information:

~~~~
Fatal failure within void CVC4::SmtEngine::checkModel(bool) at /barrett/scratch/cvc4-nightly/src/cvc4-2020-03-03/src/smt/smt_engine.cpp:4808 
Internal error detectedSmtEngine::checkModel(): ERRORS SATISFYING ASSERTIONS WITH MODEL: model value for __realToIntInternal_var_5 is false
value type is Bool
should be of type Int
~~~~

OS: Ubuntu 16.04

**Comment by ajreynol** [comment]
Hi, thanks for the benchmark.  For this (and the other issues you've opened), it would help if you could minimize the number of calls to set-option.  Would it be possible to do this?

In general, we conjecture that many options are incompatible with one another in CVC4. It is in fact ongoing work to determine dependencies between options. At the moment, I would expect that it is indeed possible to find similar errors by finding incompatible combinations of options.

Regardless, it would help me address these quickly if these were minimized.

**Comment by rainoftime** [comment]
Thanks for the reply!
I have manually minimized the number of options. Please check the following file (also updated in the issue)
[checkmodel1-minimized.txt](https://github.com/CVC4/CVC4/files/4288096/checkmodel1-minimized.txt)
