### ISSUE TITLE
Fatal failure for QF_UFNIA instance at /theory/arith/normal_form.cpp:760

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#3938]
Hi,
For this formula,
[normalform760.txt](https://github.com/CVC4/CVC4/files/4301900/normalform760.txt)

cvc4-nightly (http://cvc4.cs.stanford.edu/downloads/builds/x86_64-linux-opt/unstable/cvc4-2020-03-07-x86_64-linux-opt) incremental mode
crashed with the information:

~~~~
Fatal failure within CVC4::theory::arith::Polynomial CVC4::theory::arith::Comparison::normalizedVaria
blePart() const at /barrett/scratch/cvc4-nightly/src/cvc4-2020-03-07/src/theory/arith/normal_form.cpp:760
Unhandled case encounteredUNDEFINED_KIND
Aborted (core dumped)
~~~~

OS: Ubuntu 16.04

**Comment by ajreynol** [comment]
The options in this need to be minimized.

**Comment by rainoftime** [comment]
In the master branch, CVC4 can solve correctly.
