### ISSUE TITLE
snorm-infer-eq fatal failure at src/theory/quantifiers/equality_infer.cpp:144

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#3955]
Hi,
For this formula:
[equality_infer144.txt](https://github.com/CVC4/CVC4/files/4304351/equality_infer144.txt)

CVC4 incremenal mode throws out a fatal failure:
~~~~
Fatal failure within void CVC4::theory::quantifiers::EqualityInference::eqNotifyNewClass(CVC4::TNode) at /home/peisen/test/tofuzz/CVC4/src/theory/quantifiers/equality_infer.cpp:144
Check failure

 !eqci->d_valid.get()

Aborted (core dumped)
~~~~

OS: Ubuntu 16.04
Commit: a0b35a8

**Comment by ajreynol** [comment]
Caused by getting a duplicate eqNotifyNewEqClass notification from the congruence manage of arithmetic.
