### ISSUE TITLE
Unknown on simple SyGuS problem

### ISSUE THREAD

**Issue by BillHallahan** [CVC4/CVC4#3960]
**Describe the bug**
CVC4 returns `unknown` on the below SyGuS problem:
```
(set-logic ALL)
(synth-fun f 
	((x Int) (y Int) (r Int)) Bool 
	((B Bool) (I Int))
	(
		(B Bool ((= I I) (< I I) (<= I I))) 
		(I Int ((Variable Int)))
	)
)
(synth-fun int_const
	() Int 
	((IConst Int))
	(
		(IConst Int ((Constant Int)))
	)
)
(constraint (and (f 0 0 int_const)))
(constraint (not (f 0 0 1)))
(constraint (not (f 0 0 (- 1))))
(check-synth)
```

Removing either the `<=` or `<` terminal from the grammar for `f` let's CVC4 solve the problem in under a second:
```
(define-fun f ((x Int) (y Int) (r Int)) Bool (= y r))
(define-fun int_const () Int 0)
```

**CVC4 version/commit**:
This is CVC4 version 1.8-prerelease [git fix3802 40eddfe0]
compiled with GCC version 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.17)
on Feb 24 2020 23:06:32

**Operating system**: MacOS

**Comment by ajreynol** [comment]
I'm not able to reproduce on master (https://github.com/CVC4/CVC4/commit/76c1710e99f2e9ca2109762394eaefcbc4a5557c) on my linux machine. Can you confirm this behavior also occurs on latest master for you?

**Comment by BillHallahan** [comment]
Yep, it works for me with the latest version too.  Sorry for wasting your time!
