### ISSUE TITLE
Invalid model for QF_UFNIA instance at theory_model_builder.cpp:1166 DIV in check-model

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#3967]
Hi,
For this formula:
~~~~
(set-logic QF_UFNIA)
(set-option :check-models true)
(declare-const i6 Int)
(assert (< 104 (mod (* 6 i6 i6 i6 95) 647)))
(check-sat)
~~~~

CVC4 throws out a fatal failure:
~~~~
Fatal failure within void CVC4::theory::TheoryEngineModelBuilder::debugCheckModel(CVC4::theory::TheoryModel*) at /home/peisen/test/tofuzz/CVC4/src/theory/theory_model_builder.cpp:1166
Check failure

 tm->getValue(*eqc_i) == rep
run with -d check-model::rep-checking for details
~~~~

OS: Ubuntu 16.04
Commit: a0b35a8

**Comment by ajreynol** [comment]
Division is eliminated at preprocessing time but is still being checked during --check-model. 

A solution here is to eliminate division at expand definitions using choice, thus there would be no concern for debug check-model failures like this one.

**Comment by 4tXJ7f** [comment]
I have confirmed that 52082c72d78eee219e3049285d5df559dacac8b5 fixes this issue (note that `--debug-check-models` was required to trigger the issue on the commit just before 52082c72d78eee219e3049285d5df559dacac8b5).
