### ISSUE TITLE
Fatal failure for QF_NIA instance at theory_arith_private.cpp:4099

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#3971]
Hi,
For this QF_NIA formula:
[theory_arith_private4096.txt](https://github.com/CVC4/CVC4/files/4306955/theory_arith_private4096.txt)

Without any other options, CVC4 incremental mode throws out a fatal failure:
~~~~
sat
Fatal failure within CVC4::Node CVC4::theory::arith::TheoryArithPrivate::explain(CVC4::TNode) at /home/peisen/test/tofuzz/CVC4/src/theory/arith/theory_arith_private.cpp:4096
Check failure

 !c->isAssumption()
~~~~

OS: Ubuntu 16.04
Commit: 7d3df3b642aa1b

**Comment by rainoftime** [comment]
After removing the first line `(set-logic QF_NIA)` of the constraint,
CVC4 can solve correctly.

**Comment by ajreynol** [comment]
Appears to be due to arithmetic being asked to an unexpected literal during incremental solving.

**Comment by rainoftime** [comment]
A minimized test case 
~~~~
(set-logic QF_NIA)
(declare-const i4 Int)
(declare-const i8 Int)
(declare-const i15 Int)
(assert (= (<= i8 i15) true true true true true (= (- i8) 36) true))
(check-sat)
(assert (xor (not (< (div i4 i8) 79)) (> (- 888) i15) true true true true true))
(check-sat)
~~~~
