### ISSUE TITLE
dump-unsat-cores: fatal failure at theory/theory_engine.cpp:1728

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#3991]
Hi,
For this formula:
[theoryengine1728.txt](https://github.com/CVC4/CVC4/files/4310194/theoryengine1728.txt)

---minimized input----
~~~~
(set-logic NIA)
(set-option :dump-unsat-cores true)
(declare-const i7 Int)
(check-sat)
(declare-const v18 Bool)
(assert (and (= i7 93) (or (> 19 i7) v18) v18))
(check-sat)
(check-sat)
(assert (> 19 i7))
(assert (> (div i7 0) 0))
(check-sat)
~~~~

CVC4 incremental mode throws out a fatal failure:
~~~~
sat
sat
sat
Fatal failure within CVC4::Node CVC4::TheoryEngine::getExplanationAndRecipe(CVC4::TNode, CVC4::LemmaProofRecipe*) at /home/peisen/test/tofuzz/CVC4/src/theory/theory_engine.cpp:1728
Check failure

 d_propagationMap.find(toExplain) != d_propagationMap.end()
~~~~

OS: Ubuntu 16.04
Commit: 7d3df3b642

**Comment by aniemetz** [comment]
@rainoftime can you please only submit input that has been minimized, for example, with [ddsmt](https://github.com/aniemetz/ddSMT).

**Comment by rainoftime** [comment]
> @rainoftime can you please only submit input that has been minimized, for example, with [ddsmt](https://github.com/aniemetz/ddSMT).

Thanks! I will try
