### ISSUE TITLE
Error information "Property is not handled by single invocation" (cegqi-si-abort, sygus-query-gen, sygus-inference)

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#4261]
Hi, for the following instance,
~~~~
(set-logic ALIA)
(declare-fun _substvar_1_ () Bool)
(set-option :cegqi-si-abort true)
(set-option :sygus-query-gen true)
(set-option :sygus-inference true)
(assert _substvar_1_)
(check-sat)
~~~~
cvc4 issues a warning/error:
~~~~
(error "Property is not handled by single invocation.
")
~~~~

Do the above parameters have some conflcits?  Thank you!

**Comment by ajreynol** [comment]
Yes, there are several reasons why this combination of options is conflicting, including that option `cegqi-si-abort` must be used with `cegqi-si=all`, and `sygus-query-gen` should not be used with the other two options. The error message is expected.
