### ISSUE TITLE
Unknown on SyGuS problem

### ISSUE THREAD

**Issue by BillHallahan** [CVC4/CVC4#4383]
**Describe the bug**
CVC4 returns unknown on the below SyGuS problem, despite the lack of `Constant` and the simplicity of the grammar:
```
(set-logic ALL)
(synth-fun args_0_refinement_0 
	((r Int)) Bool 
	((fv_B Bool)) 
	(
		(fv_B Bool (true)) 
	)
)
(synth-fun ret_refinement_0 
	((x0 Int) (r Bool)) Bool 
	((fv_B Bool) (B Bool) (I Int)) 
	(
		(fv_B Bool (r true (=> B fv_B))) 
		(B Bool ((Variable Bool) (= I I))) 
		(I Int ((Variable Int) 1)) 
	)
)
(constraint (ret_refinement_0 1 true))
(constraint (not (ret_refinement_0 1 false)))
(constraint (and (ret_refinement_0 0 false)))
(check-synth)
``` 
If you remove the `synth-fun args_0_refinement_0` command or removing `true` from the grammar for `ret_refinement_0`, CVC4 finds a solution for `ret_refinement_0`.

**Command line arguments**: --lang=sygus2
**CVC4 version/commit**:
cvc4 --version
This is CVC4 version 1.8-prerelease [git master 1cacd328]
compiled with GCC version 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.32.59)
on Apr 23 2020 22:14:35

**Operating system**: MacOS

**Comment by ajreynol** [comment]
Thanks a lot for this report, it was helpful.  It is fixed in my latest PR.
