### ISSUE TITLE
(arrays-weak-equiv) Soundness bug on formula with arrays 

### ISSUE THREAD

**Issue by muchang** [CVC4/CVC4#4396]
Hi,
For this case, CVC4 --arrays-weak-equiv gives an incorrect answer:
```
[797] % z3 small.smt2
unsat
[798] % cvc4 -q small.smt2
unsat
[799] % cvc4 -q --arrays-weak-equiv small.smt2
sat
[800] % 
[800] % cat small.smt2
(declare-const a (Array Int Int))
(declare-const b (Array Int Int))
(assert (= b ((as const (Array Int Int)) 0)))
(assert (= (store a 1 1) (store b 2 1)))
(check-sat)
[801] %
```
Feeding the model leads to unsat:
```
[809] % cvc4 -q --arrays-weak-equiv --produce-models t.smt2
sat
(model
(define-fun a () (Array Int Int) ((as const (Array Int Int)) 0))
(define-fun b () (Array Int Int) ((as const (Array Int Int)) 0))
)
[810] % cvc4 -q --arrays-weak-equiv --produce-models s.smt2
unsat
(error "Cannot get model unless immediately preceded by SAT/NOT_ENTAILED or UNKNOWN response.")
[811] % 
[811] % cat t.smt2 
(declare-const a (Array Int Int))
(declare-const b (Array Int Int))
(assert (= b ((as const (Array Int Int)) 0)))
(assert (= (store a 1 1) (store b 2 1)))
(check-sat)
(get-model)
[812] % cat s.smt2 
(define-fun a () (Array Int Int) ((as const (Array Int Int)) 0))
(define-fun b () (Array Int Int) ((as const (Array Int Int)) 0))
(assert (= b ((as const (Array Int Int)) 0)))
(assert (= (store a 1 1) (store b 2 1)))
(check-sat)
(get-model)
[813] %
```

OS: Ubuntu 18.04
Commit: 8476f38

**Comment by barrettcw** [comment]
This bug report uses an experimental option, arrays-weak-equiv.  We do not provide any support or guarantees for experimental options.  Please refer to our fuzzing guidelines here:
https://github.com/CVC4/CVC4/wiki/Fuzzing-CVC4
and only report issues that follow the guidelines there.

**Comment by zhendongsu** [comment]
@barrettcw @ajreynol   
Andrew and Clark, this bug seems more serious than many of the others.  Would you want to at least transfer it to https://github.com/CVC4/cvc4-projects/issues, rather than simply closing it?   Thank you.

**Comment by barrettcw** [comment]
arrays-weak-equiv is not compatible with constant arrays.  We have no immediate plans to remedy that as, like I said before, this option is experimental and not supported for use by users.  Note also that constant arrays are not part of the SMT-LIB standard, but are also extensions, experimental in the case of CVC4.  So you are mixing two experimental options whose combination we do not claim or plan to support.

**Comment by zhendongsu** [comment]
Okay, thanks for the further information, Clark.  We'll ignore --arrays-weak-equiv from our future testing then, and follow the guide you referenced above, which is very useful btw.

**Comment by barrettcw** [comment]
Great - and our goal will be over time to extend the list of approved options as they become more robust and less experimental.  It's important though that we have a platform for experimenting without getting flooded with bug reports for features that are not yet robust.
