### ISSUE TITLE
Soundness bug on QF_S formula (assert (= "\x00" "\u{5c}x00"))

### ISSUE THREAD

**Issue by muchang** [CVC4/CVC4#4410]
Hi,
For this case, CVC4  gives an incorrect answer:
```
[611] % cvc4-1.7 -q small.smt2
unsat
[612] % z3 small.smt2
unsat
[613] % cvc4 -q small.smt2
sat
[614] % 
[614] % cat small.smt2
(assert (= "\x00" "\u{5c}x00"))
(check-sat)
[615] %
```
The result of CVC4 seems to be changed to `sat` in recent commits. 

OS: Ubuntu 18.04
Commit: ad0b69e

**Comment by ajreynol** [comment]
We have recently updated to the Unicode standard for strings: http://smtlib.cs.uiowa.edu/theories-UnicodeStrings.shtml.

The answer of "sat" is correct for a solver that is compliant with this standard.  The right hand side of the equality uses a standard escape sequence '\u{5c}' which specifies the character '\'.  My guess is the version of z3 you are using does not implement these escape sequences.
