### ISSUE TITLE
Different answer to Z3 on QF_BV formula with :smt-lib-version 2.5

### ISSUE THREAD

**Issue by muchang** [CVC4/CVC4#4411]
Hi,
For this case, CVC4  gives a different answer to Z3:
```
[770] % z3 small.smt2
unsat
[771] % cvc4 -q small.smt2
sat
[772] % cat small.smt2
(set-info :smt-lib-version 2.5)
(declare-fun a () (_ BitVec 7))
(assert (distinct (bvudiv a ((_ sign_extend 6) (_ bv0 1))) (bvnot (_ bv0 7))))
(check-sat)
[773] %
```
With 2.6, both z3 and cvc4 say unsat.
Boolector also reports unsat on the given formula

OS: Ubuntu 18.04
Commit: ad0b69e

**Comment by ajreynol** [comment]
In smt lib version 2.5, `bvudiv` had a different semantics than in 2.6. 

CVC4 uses the 2.5 *semantics* when you specify the input syntax as 2.5. Thus, "sat" is the expected response in CVC4 when the input language is 2.5 (and "unsat" when 2.6).  Z3 and Boolector likely implement a uniform semantics where they do not distinguish 2.5 and 2.6.

I believe we have had this discussion before.
