### ISSUE TITLE
Fatal failure at theory/arrays/theory_arrays_rewriter.h:94 (produce-abducts, abstract-values, ext-rewrite-quant)

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#4442]
Hi,
For the following formula:
[94.txt](https://github.com/CVC4/CVC4/files/4574340/94.txt)

CVC4 throws out a fatal failure:
~~~~
 Fatal failure within static CVC4::Node CVC4::theory::arrays::TheoryArraysRewriter::normalizeConstant(CVC4::TNode, CVC4::Cardinality) at /home/peisen/test/tofuzz/CVC4/src/./theory/arrays/theory_arrays_rew
riter.h:94
 Check failure
 
  store.getKind() == kind::STORE_ALL
 

/tmp/res-cvc/crash/cvc_input-52_108_ncnf_43_181_QF_AUFNRA.smt2
~~~~

OS: Ubuntu 16.04
Commit: ad7907adf

**Comment by barrettcw** [comment]
This example uses experimental options.  We do not support experimental options. 
Please follow the guidelines here: https://github.com/CVC4/CVC4/wiki/Fuzzing-CVC4
