### ISSUE TITLE
Fatal failure at theory/type_enumerator.h:159 (produce-abducts, uf-ho, sygus-rr-verify, sygus-sym-break-lazy)

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#4443]
Hi,
For the following formula:
[159.txt](https://github.com/CVC4/CVC4/files/4574132/159.txt)

CVC4 throws out a fatal failure:
~~~~
 Fatal failure within CVC4::Node CVC4::theory::TypeEnumerator::operator*() at /home/peisen/test/tofuzz/CVC4/src/./theory/type_enumerator.h:159
 Check failure
 
  n.isConst()

~~~~

OS: Ubuntu 16.04
Commit: ad7907adf

**Comment by zhendongsu** [comment]
See the comments in https://github.com/CVC4/CVC4/issues/4396 and https://github.com/CVC4/CVC4/wiki/Fuzzing-CVC4 

I think the CVC4 folks would also like the tests reduced regardless.
