### ISSUE TITLE
Fatal failure at theory/quantifiers/instantiate.cpp:176 (produce-abducts, fs-interleave, quant-cf, full-saturate-quant, uf-ho)

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#4447]
Related https://github.com/CVC4/CVC4/issues/4275

---

Hi,
For the following formula:
[176.txt](https://github.com/CVC4/CVC4/files/4574315/176.txt)

CVC4 throws out a fatal failure:
~~~~
 Fatal failure within bool CVC4::theory::quantifiers::Instantiate::addInstantiation(CVC4::Node, std::vector<CVC4::NodeTemplate<true> >&, bool, bool, bool) at /home/peisen/test/tofuzz/CVC4/src/theory/quantifiers/instantiate.cpp:176
 Check failure
 
  false

~~~~

OS: Ubuntu 16.04
Commit: ad7907adf

**Comment by ajreynol** [comment]
This example uses an experimental option. We are not supporting issues with experimental options. Please refer to the guidelines here: https://github.com/CVC4/CVC4/wiki/Fuzzing-CVC4
