### ISSUE TITLE
Invalid model on AUFNIRA formula

### ISSUE THREAD

**Issue by wintered** [CVC4/CVC4#4449]
[692] % cvc4-1.7 --check-models small.smt2
sat
[693] % cvc4 --check-models small.smt2
Fatal failure within void CVC4::TheoryEngine::checkTheoryAssertionsWithModel(bool) at src/theory/theory_engine.cpp:2283
Internal error detectedTHEORY_UF has an asserted fact that the model doesn't satisfy.
The fact: (= termITE_2 (/ (modZero (/ 1 2)) 1))
Model value: false
Aborted
[694] % 
[694] % cat small.smt2
(set-logic AUFNIRA)
(declare-fun a () Int)
(define-fun b () Int 2)
(define-fun c ((d Int)) Int (/ d b))
(define-fun e ((d Int) (g Int)) Int (c (+ d g)))
(declare-fun f () Int)
(define-fun g ((d Int) (g Int)) Int (c (mod d g)))
(declare-fun h () Int)
(assert (xor (<= 0 a) (<= a b)))
(assert (distinct 0 (mod 1 0)))
(assert (distinct h (g (e 0 1) f)))
(assert (not (= a h)))
(check-sat)
[695] %
OS: Ubuntu 18.04
Commit: 8236d7f

**Comment by 4tXJ7f** [comment]
It looks like this issue has been fixed with 52082c72d78eee219e3049285d5df559dacac8b5.
