### ISSUE TITLE
Convert [signed]Int <-> BV in the C++ API

### ISSUE THREAD

**Issue by leonardoalt** [CVC4/CVC4#4492]
In the API files I see
```
      {INT_TO_BITVECTOR_OP, CVC4::Kind::INT_TO_BITVECTOR_OP},
      {INT_TO_BITVECTOR, CVC4::Kind::INT_TO_BITVECTOR},
      {BITVECTOR_TO_NAT, CVC4::Kind::BITVECTOR_TO_NAT},
```
so I assume the way to convert an Integer `x` to BV of size `s` would be
`mkTerm(INT_TO_BITVECTOR, mkTerm(INT_TO_BITVECTOR_OP, s), x)`?
Does that work if `x` is signed?

Similarly, I see `BITVECTOR_TO_NAT`, but is there a way to convert a BV to a signed Integer?

**Comment by 4tXJ7f** [comment]
With the [new API](https://github.com/CVC4/CVC4/blob/master/src/api/cvc4cpp.h), the way to use indexed operators is: `solver.mkTerm(solver.mkOp(INT_TO_BITVECTOR, s), x)`.

`BITVECTOR_TO_NAT` always assumes that the bit-vector is unsigned (bit-vector sorts are agnostic to whether they store signed or unsigned values). If you want to treat a bit-vector as signed, you'd have to something like:

```
mkTerm(ITE,
  mkTerm(EQUAL, mkTerm(mkOp(BITVECTOR_EXTRACT, s - 1, s - 1), b), mkBitVector(s, 0)),
  mkTerm(BITVECTOR_TO_NAT, b),
  mkTerm(UMINUS, mkTerm(BITVECTOR_TO_NAT, mkTerm(BITVECTOR_NEG, b)))
```

For `INT_TO_BITVECTOR`, I took a brief look at our encoding and if I am not mistaken, you just get the absolute value of the integer as a bit-vector (modulo 2^s), so you'd have to do something similar, where you have an ite that checks whether the integer is negative or not and does a `BITVECTOR_NEG` if the integer is negative.

Please note that those operators are non-standard and similar operators in other solvers may implement different semantics.

Hope this helps. Please let us know if you have any other questions.

**Comment by leonardoalt** [comment]
Cool, thanks @4tXJ7f !

**Comment by leonardoalt** [comment]
Actually one follow up question: I'm currently using `CVC4::SmtEngine`. Should I be using `CVC4::Solver` instead?

**Comment by leonardoalt** [comment]
Oh, when you mentioned the new API, it's actually quite different, isn't it? I might be confused, but I'm using 1.7 and I think I don't have access to `Term` nor `Solver`?

**Comment by leonardoalt** [comment]
@4tXJ7f I see now what the issue is. As you correctly mentioned, the latest (`master`) version of the API indeed works as you described. However, in the latest release, `Solver` doesn't have method `mkOp`, and `mkTerm` only accepts `Kind`.
Is there a way to do the same in the latest release instead of `master`?

**Comment by leonardoalt** [comment]
This doesn't look the nicest, but works:
`s.mkTerm(CVC4::api::Kind::INT_TO_BITVECTOR, s.mkOpTerm(CVC4::api::Kind::INT_TO_BITVECTOR, size), arguments[0]).getExpr();`
I guess it'll change with the next release
