### ISSUE TITLE
Defined functions screwy in DeclarationScope (Bugzilla #231)

### ISSUE THREAD

**Issue by mpreiner** [CVC4/CVC4#451]
**Imported from Bugzilla**
Reporter: *Morgan Deters*
Status: *NEW*
Severity: *enhancement*
Assigned to: *Clark Barrett*
Component: *{Internals} Expression package*
Milestone: *1.6*
Version: *master*
Platform: *All*
OS: *All*

On 2010-10-31 09:42:59 -0700, Morgan Deters wrote:
> Defined functions, as implemented, are a little strange.  The set of functions are kept as expression bodies (rather than names) in a CDSet<>.  So that means if you have a defined function f()\=x\+y and a let binding e\=x\+y, then e is considered a defined function?
> 
> Need to review this, and clean this up.

**Comment by ajreynol** [comment]
DeclarationScope was renamed to SymbolTable here: https://github.com/CVC4/CVC4/commit/b0deae79d8bae5051a85dc15e43e7b83bc8cf9ab#diff-f80c52c03fa85b1979ec8d7f9ce3221a
