### ISSUE TITLE
Discrepancy between Windows and Linux releases in handling of floating-point literals

### ISSUE THREAD

**Issue by zvonimir** [CVC4/CVC4#4523]
Windows release v1.7 (binary) reports an error, while Linux release v1.7 (binary) does not report an error on the following file: 
[float.txt](https://github.com/CVC4/CVC4/files/4670413/float.txt)

This is the error that gets reported by the Windows release, and judging from the description of the error, this is a strange discrepancy between the two versions (Windows vs Linux):
```
(error "Unimplemented code encountered
void CVC4::FloatingPointLiteral::unfinished() const
/home/nightly/CVC4-master/src/util/floatingpoint.cpp:462
Floating-point literals not yet implemented.")
```

I did not manage to minimize the file since it appears that ddSMT does not work on Windows.

**Command line arguments**: `--lang=smt --no-strict-parsing --no-condense-function-values --incremental --produce-models`
**Operating system**: Windows 10 and Ubuntu 18.04

**Comment by 4tXJ7f** [comment]
It looks like we are currently building CVC4 without floating-point support. We will fix this for the nightlies and the new release.

**Comment by zvonimir** [comment]
Got it, thanks!

**Comment by 4tXJ7f** [comment]
Our nightly Windows builds are now built with floating-point support. I've tried [today's version](http://cvc4.cs.stanford.edu/downloads/builds/win64-opt/unstable/cvc4-2020-05-29-win64-opt.exe) on Windows and it seemed to work as expected. Please let us know if you encounter any further issues.
