### ISSUE TITLE
Reset assertions still don't work

### ISSUE THREAD

**Issue by MrChico** [CVC4/CVC4#4552]
I see that #3988 recently highlighted a problem with `(reset-assertions)`, but I'm on `b826fc8a` and it is still giving me the wrong results:
```
(set-option :global-declarations true)
(define-fun a () Bool true)
(assert a)
(check-sat)
(reset-assertions)
(assert (not a))
(check-sat)
```
returns SAT, SAT.

I'm also not getting the expected results running the regression test https://github.com/CVC4/CVC4/blob/e9f4cec2cad02e270747759223090c16b9d2d44c/test/regress/regress0/smtlib/reset-assertions-global.smt2 that was added in #3988, (I'm getting sat, sat, unsat). Are these tests not being run?

**Comment by 4tXJ7f** [comment]
For your input `sat`, `sat` is actually the expected outcome (for the first call `a` is `true` and for the second call `a` is `false`). Your case is essentially equivalent to:

```
(set-option :global-declarations true)
(define-fun a () Bool true)
(push)
(assert a)
(check-sat)
(pop)
(push)
(assert (not a))
(check-sat)
(pop)
```

I've checked and the regression test is being run and I am getting `unsat`, `sat`, `unsat` as expected. Which version of CVC4 did you try this with?

**Comment by MrChico** [comment]
> For your input sat, sat is actually the expected outcome (for the first call a is true and for the second call a is false). Your input is essentially equivalent to:

I'm confused. `a` is defined as `true` on the second line.

I'm running:
```
  ~ cvc4 --version
This is CVC4 version 1.8-prerelease [git master b826fc8a]
compiled with GCC version 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.10.44.4)
on Jun  2 2020 17:44:30
```

**Comment by MrChico** [comment]
FWIW, your rewrite in terms of `pop` and `push` yields `sat`, `unsat` for me, which indeed is the expected result. But using `(reset-assertions)` I still get `sat` `sat`.

**Comment by 4tXJ7f** [comment]
Oh sorry, I missed the `define-fun` there---I parsed it as a `declare-fun`. You are right, this is wrong. Thanks for the report, I will take a look.

**Comment by MrChico** [comment]
Thanks for the fix!

**Comment by rainoftime** [comment]
An refutation soundness issues
cvc4 3075a8e20dba6a78431 yields `unsat` on the following query.
~~~~
(set-logic QF_AUFBV)
(assert (= (_ bv0 8) #x22 (bvmul #x22 #x22) #x22 #x22))
(reset-assertions)
(check-sat)
~~~~
