### ISSUE TITLE
unsoundness using push and pop

### ISSUE THREAD

**Issue by MrChico** [CVC4/CVC4#4555]
The following query:
```
(set-option :global-declarations true)
(set-logic ALL) ; external query, using all logics.

(push 1)

(define-fun a () Bool (not true))
(assert a)
(check-sat)
(pop 1)

(push 1)
(assert a)
(check-sat)
(pop 1)
```

yields `UNSAT, SAT` where `UNSAT, UNSAT` is expected. Moving the definition of `a` up to before the `push` yields the correct result.
This is using:
```
This is CVC4 version 1.8-prerelease [git master b826fc8a]
compiled with GCC version 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.10.44.4)
on Jun  2 2020 17:44:30
``

**Comment by 4tXJ7f** [comment]
Thanks for the report @MrChico. This is actually related to #4552 (`define-fun` is not correctly treated with `global-declarations`). I am about to submit a PR fixing this issue.
