### ISSUE TITLE
Support `libedit` over `readline`

### ISSUE THREAD

**Issue by andrewvaughanj** [CVC4/CVC4#4571]
I recently modified OpenSMT to be able to link against `libedit` vs `readline`. See https://github.com/usi-verification-and-security/opensmt/pull/119 and https://github.com/usi-verification-and-security/opensmt/pull/120.

I did this purely to ensure that OpenSMT could actually claim to be MIT-licensed, rather than "MIT-licensed code, GPL-licensed binary", which I think was totally overlooked (you couldn't the OpenSMT API without being GPL, given how the shared objects were linked).

I discussed this with @mpreiner and he suggested this could be useful for CVC4 as well!

Given that `libedit` is pretty-much a drop-in replacement for `readline` (and I already did the same task for OpenSMT), I am more than happy to volunteer to take a look at this for CVC4.

**Comment by andrewvaughanj** [comment]
Any opinions on if we want both `readline` and `libedit`, or should we just replace `readline` entirely with `libedit`?

`libedit` could still be optional (i.e., in the same way as `readline` currently), but I am just wondering if we want to preserve the ability to still (optionally) link `readline`.

Why do I care? Well, if you say "get rid of `readline`", I can just replace `readline` with `libedit`. If you say, "we want both", I have to duplicate the `readline` stuff to be `editline`. The former is easier.

**Comment by mpreiner** [comment]
Support added in https://github.com/CVC4/CVC4/pull/4579
