### ISSUE TITLE
Invalid model for incremental QF_LIA formula

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#4598]
Hi, for the following formula
~~~~
(set-logic QF_LIA)
(declare-const v0 Bool)
(declare-const v5 Bool)
(declare-const i1 Int)
(declare-const i3 Int)
(push 1)
(assert (= (distinct (< i3 14) true) true true (=> v5 v0) true true true true true true))
(assert (>= i1 (+ i3 i3 (abs i1) (abs i1))))
(check-sat)
(pop 1)
(assert (not (distinct i3 81)))
(check-sat)
~~~~

cvc4 40fd0e4c throws an assertion violation
~~~~
unsat
Fatal failure within void CVC4::TheoryEngine::checkTheoryAssertionsWithModel(bool) at /home/CVC4/src/theory/theory_engine.cpp:2290
Internal error detectedTHEORY_ARITH has an asserted fact that the model doesn't satisfy.
The fact: (not (>= i3 15))
Model value: false

Aborted
~~~~

**Comment by 4tXJ7f** [comment]
Thanks for the report. I can't seem to reproduce this issue on my machine. What arguments did you pass to CVC4? How did you configure it when building it?

**Comment by rainoftime** [comment]
I build CVC4 with
`./configure debug --asan --ubsan`

and run the file with
` --incremental --debug-check-models`

**Comment by ajreynol** [comment]
This uses the experimental option `debug-check-models`, which is not an option allowed by our fuzzing guidelines (https://github.com/CVC4/CVC4/wiki/Fuzzing-CVC4).
