### ISSUE TITLE
Possible infinite loop in compressTerm function

### ISSUE THREAD

**Issue by spamdaemon** [CVC4/CVC4#4610]
A code inspection turned up this problem in 

https://github.com/CVC4/CVC4/blob/60ed666d657bfcd69f48821c78a34696796df5fb/src/preprocessing/util/ite_utilities.cpp#L452-L453

The branch variable is not used and instead, it recurses on the argument again. I did not try a test case for this.

**Comment by ajreynol** [comment]
This does look suspicious, I agree `branch` is probably what was intended.  Note that this code is not hit by our nightly code coverage: https://cvc4.cs.stanford.edu/downloads/builds/coverage/cvc4-2020-06-15/index.src_preprocessing_util_ite_utilities.cpp.html and may in fact be dead code.
