### ISSUE TITLE
(--ext-rewrite-quant) Refutational soundness bug on NIA formula with exists and div operators

### ISSUE THREAD

**Issue by muchang** [CVC4/CVC4#4620]
Hi,
For this formula, CVC4 with --ext-rewrite-quant gives an incorrect answer:
```
[516] % z3release small.smt2 
sat
[517] % cvc4 small.smt2 
sat
[518] % cvc4 --ext-rewrite-quant small.smt2 
unsat
[519] % cat small.smt2 
(set-logic NIA)
(assert (exists ((x Int)) (= (div 1 x x) x)))
(check-sat)
[520] %
```

OS: Ubuntu 18.04
Commit: e5f880a

**Comment by ajreynol** [comment]
Thanks for the report.  The unsoundness is due to the option `--ext-rewrite-quant` combined with non-standard operators like `div` in quantifier bodies.  This is fixed in my latest PR.

**Comment by zhendongsu** [comment]
Thanks for the fix, Andrew!
