### ISSUE TITLE
(simplification=none) Refutational soundness bug on set logic formula (sets subtyping)

### ISSUE THREAD

**Issue by wintered** [CVC4/CVC4#4631]
Hi, 
the following trace exhibits a refutational soundness bug in CVC4.

```
[625] % cvc4 small.smt2
sat
[626] % cvc4 --simplification=none small.smt2
unsat
[627] % 
[627] % cat small.smt2
(set-logic ALL)
(declare-fun a () (Set Real))
(declare-fun b () (Set Int))
(assert (distinct b (intersection a (singleton 0.5))))
(assert (= b (as emptyset (Set Real))))
(check-sat)
[628] %
```
OS: Ubuntu 18.04
Commit: c7522585

**Comment by ajreynol** [comment]
This involves set subtyping (constraints that compare (Set Int) with (Set Real)).  I believe we should eliminate this feature, which would make this benchmark ill-typed.  I will look into this more.
