### ISSUE TITLE
POW(^) operator complains about natural number in exponent

### ISSUE THREAD

**Issue by johndoe888** [CVC4/CVC4#4698]
Executing the following smt2 code 

```
(set-logic ALL)
(declare-const sqrt2 Real)
(assert (= sqrt2 1.414213))
(declare-const k Int)
(assert (<= 2 k))
(assert (<= k 8))
(declare-const a Real)
(assert (= a (^ sqrt2 k)))
(check-sat)
```
yields the following error message
```
(error "The POW(^) operator can only be used with a natural number in the exponent.  Exception occurred in:
  (^ sqrt2 (/ k 1))")
```
It says that the exponent should be a natural number. As seen in the code it is declared as an integer. So this should be fine, shouldn't it?

**CVC4 version/commit**: This is CVC4 version 1.9 [git master 733083c3]. Although the binary is called cvc4-1.8-x86_64-linux-opt?!
**Operating system**: Debian GNU/Linux 10 (buster)

**`configure.sh` options**
Binary download

**`configure.sh` output**
Binary download

**Comment by andrewvaughanj** [comment]
> Although the binary is called cvc4-1.8-x86_64-linux-opt?!

Probably related to this: https://github.com/CVC4/CVC4/pull/4696 and/or https://github.com/CVC4/CVC4/issues/4697

**Comment by nafur** [comment]
I think the error message actually means "natural number **constant**". I don't think that you can use exponents that involve variables, but only constant rationals.

**Comment by andrewvaughanj** [comment]
For your main issue, it is worth looking at this as well: https://github.com/CVC4/CVC4/issues/4692

**Comment by nafur** [comment]
For full details, you probably want to look here: https://github.com/CVC4/CVC4/blob/master/src/theory/arith/arith_rewriter.cpp#L224
To summarize, `pow()` will accept exponents that are constant numbers that are zero (`exp.sgn() == 0`) or positive integral numbers that are below the `INT_MAX` constant.

Note that there is no symbolic handling of `pow` in CVC4, but it is simply expanded to a n-ary multiplication, which probably explains all these restrictions.

**Comment by ajreynol** [comment]
Yes, I can confirm that @nafur is correct. Our current support for POW is quite limited, we currently accept only constant exponents and expand them using multiplication.
