### ISSUE TITLE
"CVC4 suffered a segfault" when printing `synth-fun`/`synth-inv`

### ISSUE THREAD

**Issue by andrewvaughanj** [CVC4/CVC4#4699]
**Describe the bug**

In trying to fix something else, I came across some code in [`toStream(std::ostream& out, const SynthFunCommand* c)`](https://github.com/CVC4/CVC4/blob/master/src/printer/smt2/smt2_printer.cpp#L2058) that appears to use `NodeManager::currentNM()` in a way that leads to a crash:

```
[avj@tempvm build]$ ./bin/cvc4 --version
This is CVC4 version 1.9-prerelease [git master 2faf908e]
[avj@tempvm build]$ ./bin/cvc4 -vvv ../test/regress/regress1/sygus/array_sum_2_5.sy
Invoking: (set-option :incremental false)
Invoking: (set-logic LIA)
CVC4 suffered a segfault.
Offending address is 0x38
Looks like a NULL pointer was dereferenced.
Aborted (core dumped)
```

This happens on both a production and a debug build.

A very rough test suggests at least 80 files in `test/regress/regress1/sygus` all crash in this way.

- **Command line arguments**: `./bin/cvc4 -vvv ../test/regress/regress1/sygus/array_sum_2_5.sy`

- **CVC4 version/commit**: 2faf908e

- **Operating system**: CentOS 8

**Comment by ajreynol** [comment]
Coincidentally, this was fixed by https://github.com/CVC4/CVC4/commit/6b673474218c300576cae43388b513c7fc8448f8 I believe.
