### ISSUE TITLE
Sygus ite performance issue

### ISSUE THREAD

**Issue by santolucito** [CVC4/CVC4#4790]
**Describe the bug**
Using sygus mode, the ite operator times out with a nonterminal as a parameter, even is that nonterminal is a single terminal symbol.

This sygus query times out
```
(set-logic NIA)
(synth-fun patternGen ((i Int)) Int
((ITE Int) (CONST Int) (I Int)  (B Bool))
( (ITE Int (
    (ite (<= i CONST) I I)
    
  ))
  (CONST Int (0))
  (I Int (i 1
    (+ I I) (- I I) (* I I)
  ))
  (B Bool (
    (<= I I)
  ))
)
)
(declare-var i Int)
(constraint (= (patternGen 0) 1))
(constraint (= (patternGen 1) 1))
(constraint (= (patternGen 2) 1))
(check-synth)
```

But when the CONST in the ite is replaced with the nontermial 0 directly (i.e ```(ite (<= i 0) I I)```), it finishes immediately and returns  ```(define-fun patternGen ((i Int)) Int (ite (<= i 0) 1 1))```. The same thing happens if CONST is a list of lots of nonterminal ints - it times out with CONST, but terminates if I just define ITE be ```(ite (<= i 0) I I) (ite (<= i 1) I I) (ite (<= i 2) I I) ...```.

**CVC4 version/commit**:  1.7
**Operating system**: Ubuntu Linux

**Comment by ajreynol** [comment]
Thanks for the report.  There is an issue with our strategy for setting up decision tree learning on this example (--no-sygus-pbe works fine on this example).  I will look into fixing soon.
