### ISSUE TITLE
Parsing issue with datatypes

### ISSUE THREAD

**Issue by LeventErkok** [CVC4/CVC4#4798]
For this input:

```
(set-logic ALL)
(declare-datatypes ((SBVMaybe 1)) ((par (T)
                                    ((nothing_SBVMaybe)
                                     (just_SBVMaybe (get_just_SBVMaybe T))))))
(declare-fun s0 () (SBVMaybe Int))
(define-fun s1 () Bool ((_ is (nothing_SBVMaybe () (SBVMaybe Int))) s0))
```

CVC4 says:

```
(error "Parse Error: a.smt2:6.50: Unexpected token: '('.")
```

I'm using:

```
$ cvc4 --version
This is CVC4 version 1.9-prerelease [git master ffed1a0c]
```

Z3 accepts it without complaint, and I believe the ascription is correct. Is there a reason why CVC4 is not liking it?

**Comment by ajreynol** [comment]
I'm not sure I understand the syntax `(_ is (nothing_SBVMaybe () (SBVMaybe Int)))`.  My reading of the standard is that this should be `(_ is nothing_SBVMaybe)`: `is` is an indexed symbol whose index is a constructor symbol.  Notice that only numerals and symbols are accepted as arguments to indexed symbols (see 3.3. of http://smtlib.cs.uiowa.edu/papers/smt-lib-reference-v2.6-r2017-07-18.pdf).
Thus I think this is the correct syntax, which cvc4 and z3 accept:
```
(set-logic ALL)
(declare-datatypes ((SBVMaybe 1)) ((par (T)
                                    ((nothing_SBVMaybe)
                                     (just_SBVMaybe (get_just_SBVMaybe T))))))
(declare-fun s0 () (SBVMaybe Int))
(define-fun s1 () Bool ((_ is nothing_SBVMaybe) s0))
```

**Comment by LeventErkok** [comment]
@ajreynol I believe the issue is that upon seeing the `nothing_SBVMaybe` the type-checker has no idea what type that is, since it doesn't have any fields. The extra `() (SBVMaybe Int)` helps with that. I'll see if I can dig up more info.

**Comment by LeventErkok** [comment]
Ah, looks like we discussed this issue here: https://github.com/Z3Prover/z3/issues/2135

I'll see if I can simplify the output, maybe z3 improved in the mean time and this is no longer an issue.

**Comment by LeventErkok** [comment]
@ajreynol 

Looking at this in more detail. In https://github.com/CVC4/CVC4/issues/2832#issuecomment-462350582, you claim _This version of the benchmark goes through with cvc4:_

```
(set-option :produce-models true)
(set-logic ALL)
(declare-datatypes ((SBVEither 2)) ((par (T1 T2)
                                    ((left_SBVEither  (get_left_SBVEither  T1))
                                     (right_SBVEither (get_right_SBVEither T2))))))

(declare-fun s0 () (_ BitVec 8))
(define-fun s1 () (SBVEither (_ BitVec 8) (_ BitVec 8)) (as (left_SBVEither s0) (SBVEither (_ BitVec 8) (_ BitVec 8))))
(check-sat)
(get-model)
```

However, I currently get:

```
(error "Parse Error: b.smt2:8.78: Unexpected token: 'left_SBVEither'.

  ...itVec 8) (_ BitVec 8)) (as (left_SBVEither s0) (SBVEither (_ BitVec 8)...
                                 ^
")
```

I have:

```
$ cvc4 --version
This is CVC4 version 1.9-prerelease [git master ffed1a0c]
```

Can you confirm this? i.e., I think this used to work fine at the time of that ticket (i.e., https://github.com/CVC4/CVC4/issues/2832, on Feb 11, 2019), but CVC4 is no longer happy with it for some reason.

If that's the case, I wonder what happened in the meantime that CVC4 no longer accepts these.

**Comment by LeventErkok** [comment]
After some more digging, this is what I found. The issue here is really trying to find a rendering that can work with both CVC4 and z3. It comes to the following. 

CVC4 likes this, but z3 doesn't:
```
((_ is nothing_SBVMaybe) s1)
```

Z3 likes this, but CVC4 doesn't:
```
((_ is (nothing_SBVMaybe () (SBVMaybe Int))) s1))
```

It's been a struggle to find something that works for both solvers. So, I'm giving up and producing the output that each solver likes in these cases.

If there's a lesson to learn here and maybe inform the SMT-Lib folks so it can be emphasized what the correct thing to do is, perhaps that's a worthwhile pursuit. For the time being, I'm OK with this compromise, so I'll close this ticket.

Thanks for all the help and sorry about the noise!
