### ISSUE TITLE
Python SWIG List Bindings 

### ISSUE THREAD

**Issue by bdrodes** [CVC4/CVC4#4897]
I'm using pysmt as an interface to CVC4. I'm experimenting with upgrading CVC4 to the latest release in pysmt on my own fork, but the latest CVC4 (1.8) results in SWIG conversion issues. Passing python lists into `mkExpr` no longer works. 

At this SWIG call: 
```
    def mkExpr(self, *args):
        return _CVC4.ExprManager_mkExpr(self, *args)
```

Results in the following exception if any expression attempts to pass a python list

```
    CVC4::ExprManager::mkExpr(CVC4::Kind,CVC4::Expr)
    CVC4::ExprManager::mkExpr(CVC4::Kind,CVC4::Expr,CVC4::Expr)
    CVC4::ExprManager::mkExpr(CVC4::Kind,CVC4::Expr,CVC4::Expr,CVC4::Expr)
    CVC4::ExprManager::mkExpr(CVC4::Kind,CVC4::Expr,CVC4::Expr,CVC4::Expr,CVC4::Expr)
    CVC4::ExprManager::mkExpr(CVC4::Kind,CVC4::Expr,CVC4::Expr,CVC4::Expr,CVC4::Expr,CVC4::Expr)
    CVC4::ExprManager::mkExpr(CVC4::Kind,std::vector< CVC4::Expr,std::allocator< CVC4::Expr > > const &)
    CVC4::ExprManager::mkExpr(CVC4::Kind,CVC4::Expr,std::vector< CVC4::Expr,std::allocator< CVC4::Expr > > const &)
    CVC4::ExprManager::mkExpr(CVC4::Expr)
    CVC4::ExprManager::mkExpr(CVC4::Expr,CVC4::Expr)
    CVC4::ExprManager::mkExpr(CVC4::Expr,CVC4::Expr,CVC4::Expr)
    CVC4::ExprManager::mkExpr(CVC4::Expr,CVC4::Expr,CVC4::Expr,CVC4::Expr)
    CVC4::ExprManager::mkExpr(CVC4::Expr,CVC4::Expr,CVC4::Expr,CVC4::Expr,CVC4::Expr)
    CVC4::ExprManager::mkExpr(CVC4::Expr,CVC4::Expr,CVC4::Expr,CVC4::Expr,CVC4::Expr,CVC4::Expr)
    CVC4::ExprManager::mkExpr(CVC4::Expr,std::vector< CVC4::Expr,std::allocator< CVC4::Expr > > const &)
```

I admit to being new to SWIG, so I'm uncertain as to whether this is a pysmt issue or a CVC4 binding issue, but I would assume this is on the CVC4 side. 

Any ideas how this can be resolved?

**Comment by bdrodes** [comment]
@4tXJ7f I noticed you self assigned. Is this issue easily solvable? I'm looking at possible workaround but maybe that's moot?

**Comment by 4tXJ7f** [comment]
I need to find time to take a closer look. Since you are upgrading the CVC4 version in pySMT, it may be worth considering switching to the new Python API that debuted with the 1.8 release (see the [examples](https://github.com/CVC4/CVC4/tree/5247901077efbc7b9016ba35fded7a6ab459a379/examples/api/python)). That API is handwritten in Cython instead of using SWIG and should feel a bit more "native" as a result. We are also not going to include the SWIG Python API in future releases (in fact, it already doesn't exist on current `master` anymore), so switching to the new API now will make updates easier in the future.

**Comment by bdrodes** [comment]
Oh interesting. I'll have to look into that and see how much of a pull that would be for pysmt.

**Comment by bdrodes** [comment]
@4tXJ7f is there a procedure for installing the python API? I admit to having no prior experience with Cython, so pardon my ignorance. I naively tried a fresh local build and install but I can't import pycvc4.

**Comment by 4tXJ7f** [comment]
How did you configure the build and which version of CVC4 did you build? `master` or the `1.8` release?

**Comment by bdrodes** [comment]
I used master, I didn't pass any flags to configure, just ./configure.

**Comment by 4tXJ7f** [comment]
Ok, if you pass `--python-bindings` to `configure.sh`, the Python bindings should be built and installed when you do a `make install`. Please let me know if that helps.

**Comment by bdrodes** [comment]
That did the trick, but I'm finding its a bit more of a challenge than I thought to use the new API in pysmt. I've started to crank on a refactor in my own fork, but if in the short term there is a way you can get the prior SWIG interface working to understand the conversion between python lists and vectors for mkExpr, that will still be my best bet for now. Thanks.

**Comment by aniemetz** [comment]
@bdrodes the Swig bindings for Python are deprecated and, going forward (as @4tXJ7f mentioned), not supported anymore. Due to limited capacities on our side, I'm afraid that we'll not be able to provide a fix.
