### ISSUE TITLE
(default) Solution soundness issue on QF_SLIA formula

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#4915]
Hi, for the following formula 
~~~~
(set-logic QF_SLIA)
(declare-const Str4 String)
(declare-const Str18 String)
(assert (str.in_re Str18 (re.++ (str.to_re Str4) (str.to_re "ewgysobutx"))))
(assert (>= (str.len (str.substr Str18 0 3)) 937))
(check-sat)
~~~~

cvc4 bcbef9dfa0 yields `sat`, but z3 gives `unsat`.
The model given by cvc4 seems wrong
~~~~
sat
(model
(define-fun Str4 () String "A")
(define-fun Str18 () String "Aewgysobutx")
)
~~~~

**Comment by 4tXJ7f** [comment]
Thanks a lot for the report. It turns out that the issue is a bit less severe (though still pretty bad) than I first thought. The problem is essentially a missing check in our options: using `str.substr` should require the command line option `--strings-exp` but it didn't.
