### ISSUE TITLE
How to create a nested-recursive datatype with Python API

### ISSUE THREAD

**Issue by KevOrr** [CVC4/CVC4#4942]
Hi, I'm trying to translate the following CVC4 datatype declaration to the Python API:

```hs
OPTION "dt-nested-rec" TRUE;

DATATYPE
    MyType =
      Int(int: INT)
    | Bool(bool: BOOLEAN)
    | Array(array: ARRAY INT OF MyType)
END;
```

Here is what I have so far:

```py
def mk_type(slv):
    slv.setOption('dt-nested-rec', 'TRUE')

    Int = slv.mkDatatypeConstructorDecl('Int')
    Int.addSelector('int', slv.getIntegerSort())

    Bool = slv.mkDatatypeConstructorDecl('Bool')
    Bool.addSelector('bool', slv.getBooleanSort())

    Array = slv.mkDatatypeConstructorDecl('Array')
    Array.addSelector('array', slv.mkArraySort(slv.getIntegerSort(), ???))

    return slv.declareDatatype('MyType', [Int, Bool, Array])
```

I see that in [some examples](https://github.com/ajreynol/CVC4/blob/master/test/unit/theory/type_enumerator_white.h#L181), we can use `DatatypeSelfType()` to stand for the type that's currently being defined, but `DatatypeSelfType` doesn't seem to be part of the python API.

In [other examples](https://github.com/ajreynol/CVC4/blob/master/test/unit/api/datatype_api_black.h#L77-L107), we can make uninterpreted sort(s), define the datatypes' constructors to take these uninterpreted sorts as arguments, then tie the knot by using `mkDatatypeSorts`, but this also doesn't seem to be part of the python API.

Is there any other way to pull this off in Python?

**Comment by 4tXJ7f** [comment]
Thank you for the report, @KevOrr. You are right, `mkDatatypeSorts` is currently missing from the Python API. I have a branch that adds support for that, I just need to polish it. I will likely submit a PR for that tomorrow. Please note that support for `dt-nested-rec` is currently fairly limited.
