### ISSUE TITLE
CVC4 Question

### ISSUE THREAD

**Issue by vladi7** [CVC4/CVC4#4949]
Dear CVC4 Community,

I apologize in advance if I am asking a question in the wrong place, please point me where I should ask it if that is the case.

I am new to CVC4 and am working on a project that involves the usage of this software for the last couple of months.  

I have a datatype record: 
(declare-datatypes ((record 0))
   (((rec (a String) (b (Set String)) (c String)))))

I also have a set of this records:

(define-sort SetRec () (Set record ))
(declare-const setRec SetRec )

I assert a few members in this set. I know the cardinality of it and I assert it as well. 

Then, I am able to check whether the set has a member that I need, using "exists", which returns sat if there is such a member and unsat if not:

(assert (exists ((x record )) (and (= x (choose setRec )) (member (mkTuple "Y1" (a x)) Tclosure) (member "Y2" (b x)) (member (mkTuple "Y3" (c x)) Tclosure))))

My question is, can I successfully filter set "setRec" and get another set, which will only have those members that satisfy conditions?

For example, I have 4 members in one setRecA, and I want only 2 of them that satisfy the following: (= "Y1" (a x)) and (= "Y3" (c x)) to be in setRecB.(simplified the conditions to not use tclosures)

I tried using forall but was not successful. That seems very simple for other languages, but with SMT I am not even sure if it is possible(truly hope it is).

I appreciate your time!

**Comment by 4tXJ7f** [comment]
You've come to the right place :) It should be possible to express what you want in SMT. I have some questions/comments about your use case. 

Regarding the following assertion:

```
(assert (exists ((x record )) (and (= x (choose setRec )) (member (mkTuple "Y1" (a x)) Tclosure) (member "Y2" (b x)) (member (mkTuple "Y3" (c x)) Tclosure))))
```

There is no need for a quantifier here. Instead the idiomatic way of writing this in SMT would be:

```
(declare-const x record)
(assert (and (= x (choose setRec )) (member (mkTuple "Y1" (a x)) Tclosure) (member "Y2" (b x)) (member (mkTuple "Y3" (c x)) Tclosure)))
```

From your description, it also sounds like you maybe don't actually want to use `choose` here. Given a set, `choose` always returns the same element, which may cause unexpected results. In other words:

```
(distinct (choose A) (choose A))
```

is `unsat`.

The assertion also seems to mix two sets, `setRec` and `Tclosure` but your description only talks about a single set. Am I missing something?

Maybe it would be helpful if you could tell us a bit more about the problem that you are trying to encode at a high level? How would you write the operations that you are trying to encode in a programming language of your choice?

**Comment by vladi7** [comment]
Dear @4tXJ7f,

I truly appreciate your response. I have 2 goals to achieve. Please ignore Tclosure completely for this issue.

Let's say we have a set of students.

GOAL 1: I need to find out whether a particular student exists in the set. Since I have a data structure that consists of 2 strings and one Set of Strings, I want to make sure that this student is in the set, so I provide 2 strings and one element of the set of strings. 
(Simply put I want to find out whether a student failed any class)

GOAL 2: I need to find the set of students with particular properties.
(Simply put I want to find the set of students that fail the class in the particular school).

Java code for similar problem:

```java 
public class test {
	Set<Student> students = new HashSet<Student>();

	public static void main(String[] args) {
		test app = new test();
		app.students.add(new Student("Vlad", "SMS", new HashSet<String>(Arrays.asList("A", "F", "C"))));
		app.students.add(new Student("Bob", "SMS", new HashSet<String>(Arrays.asList("A", "C"))));
		app.students.add(new Student("Nick", "SMS", new HashSet<String>(Arrays.asList("A", "F"))));

		System.out.println(app.existsInSet());
		System.out.println(app.filterSet());

	}

	// GOAL 1
	private String existsInSet() {
		for (Student s : students) {
			if (s.name.equals("Vlad") && s.school.equals("SMS") && s.grades.contains("F")) {
				return "sat";
			}
		}
		return "unsat";
	}

	// GOAL 2
	private Set<Student> filterSet() {
		Set<Student> output = new HashSet<Student>();
		for (Student s : students) {
			if (s.school.equals("SMS") && s.grades.contains("F")) {
				output.add(s);
			}
		}
		return output;
	}

	private static class Student {
		String name;
		String school;
		Set<String> grades;

		public Student(String name, String school, Set<String> grades) {
			this.name = name;
			this.school = school;
			this.grades = grades;
		}

		@Override
		public String toString() {
			return name + " " + school + " " + grades;
		}
	}
}
```
And the output that I get in this code is:

```
sat
[Nick SMS [A, F], Vlad SMS [A, C, F]]
```

I want to accomplish the exact same thing with CVC4 if possible.


About "choose", I modified this test code: https://github.com/CVC4/CVC4/blob/master/test/regress/regress1/sets/choose1.smt2

So, with the following code, I get "sat" when a=3, "sat" when a=4, "unsat" when a=5. I think with combination of "exists" and "choose" I can achieve my GOAL 1, or am I missing something?

```
(set-logic ALL)
(set-option :produce-models true)
(declare-fun A () (Set Int))
(declare-fun a () Int)
(assert (not (= A (as emptyset (Set Int)))))

(assert (member 3 A))
(assert (member 4 A))
(assert (= 2 (card A)))
(assert (= 3 a))
;(assert (= 4 a))
;(assert (= 5 a))

(assert (exists ((x Int)) (and (= x (choose A)) (= x a))))
(check-sat)
(get-model)
```


Again, thank you for your help! I hope my question makes more sense now.
Vlad

**Comment by vladi7** [comment]
The above example is just to show what I would like to accomplish. I am working on Access Control project, where I need to get all access rights that User has on Object, and consequently check whether a particular access right belongs to that set. 

I believe if I could accomplish things I described in the previous message, I will be able to accomplish the above also.

**Comment by vladi7** [comment]
I was able to use the amazing ability of CVC4 to work on sets to solve all the above problems.
Thank you!
