### ISSUE TITLE
Non standard SMT-LIB v2.6 response with the `(get-model)` command

### ISSUE THREAD

**Issue by timothee-haudebourg** [CVC4/CVC4#4987]
Hi,

I'm using the `--output-lang=smtlib2.6` option with CVC4 1.8 and expect a standard SMT-LIB v2.6 reponse to the `(get-model) command. However the output doesn't seem to comply to the standard (which I've found here http://smtlib.cs.uiowa.edu/papers/smt-lib-reference-v2.6-r2017-07-18.pdf).

For instance, consider the following SMT-LIB v2.6 input:
```
(set-logic QF_UF)
(declare-sort Sort0 0)
(declare-fun f1 (Sort0) Bool)
(check-sat)
(get-model)
```

Here is the CVC4 output for the last command:
```
(model
; cardinality of Sort0 is 1
(declare-sort Sort0 0)
(declare-fun groundTerm_1 () Sort0)
(define-fun f1 ((BOUND_VARIABLE_279 Sort0)) Bool false)
)
```

However according to the SMT-LIB v2.6 spec, the output of the `(get-model)` command should be of the form:
```
<get_model_response> ::= ( <model_response>* )
    <model_response> ::= ( define-fun <function_def> ) | ( define-fun-rec <function_def> )
                         ( define-funs-rec ( <function_dec>^{n+1} ) ( <term>^{n+1} ) )
```
In particular, the `model` keyword should not be here, the `declare-sort` command should not be here, and I don't even understand why a `declare-fun groundTerm_1` appears (which seems to be quite new, it wasn't here with CVC4 1.7 I think).

So am I missing something here? Am I not reading the right spec for the SMT-LIB v2.6 language? Or is CVC4 not compliant? In which case, should it be fixed? Or where can I find the actual language definition used by CVC4?

**Comment by aniemetz** [comment]
No, you didn't miss anything here. Actually, during SMT-COMP this year, the organizers noticed that none of the participating solvers is compliant with the standard here, all output the model starting with the `model` keyword, CVC4 included. There has been discussion with the SMT-LIB maintainers as to how to deal with this (if there is a good reason to change the standard to have the model response start with a keyword or if the current standard is what should actually be enforced), and no conclusion has been reached yet. @tinelli @barrettcw

**Comment by timothee-haudebourg** [comment]
Well I understand that it makes sense to do what everybody else is doing, but it **not** SMT-LIB v2.6 compliant, so it should **not** be advertised as such while using the `--output-lang=smtlib2.6` option. If the standard must be changed, it will probably lead to a new version of SMT-LIB.

**Comment by yoni206** [comment]
Hi, thanks again for opening this issue!

We now:
1. avoid printing the word `model` at the beginning (#5415)
2. avoid declaring sorts by default (#5432)
3. avoid declaring constants by default. Instead we use the SMT-LIB way, using `as` expressions (#5581).

Your benchmark has been added to our regressions.
