### ISSUE TITLE
Python Get Constant Value

### ISSUE THREAD

**Issue by bdrodes** [CVC4/CVC4#5014]
I'm using the new python API.

For constant values, either statically constant before solve, or generated by getValue, I can see there are a const with `istConst` and, I can print out their value using their repr, but I don't see any way to just pull out a constant value (i.e., not the Term representing the constant, but the python type for that constant). 

My current workaround is cast the Term to a string, then convert the string to whatever the sort type is (e.g., `int(str(x))`). Is there a better way?

**Comment by bdrodes** [comment]
Update: The work around mentioned above is a bit more nuanced than suggested since, for example constant `-1` is string `(- 1)` requiring some string parsing before doing the outer cast.

**Comment by 4tXJ7f** [comment]
Thank you for the report. PR #5083, which addresses this issue, has been merged. Please let us know if you run into any issues.
