### ISSUE TITLE
Python API: Strings and Escape Characters

### ISSUE THREAD

**Issue by bdrodes** [CVC4/CVC4#5024]
```
x = slv.mkString("\"test\"")
```

I would expect x to be ""x"", when I print out the term or solve for it, but instead I get 
```
In [24]: x
Out[24]: """test"""
```
Solving for x also results in value being `"""test"""`

I'm not sure if this is a bug or if there is another prescribed mechanism to apply escaped characters when generating strings.

**Comment by bdrodes** [comment]
Addendum: I was also experimenting with newline but had similar issues

```slv.mkString("test\n")``` resulted in the following error

```
RuntimeError: Illegal string character: "
", must use escape sequence
```

**Comment by 4tXJ7f** [comment]
Good point, I think we need an additional method to return a Python string instead of a string that is printed as an SMT-LIB string. Thanks for the report.

**Comment by bdrodes** [comment]
@4tXJ7f Is there a workaround I can easily apply while this feature is being integrated, or is there likely a short turn around?

**Comment by bdrodes** [comment]
@4tXJ7f Just touching base, is there a workaround I can get short term or is a fix forthcoming?

**Comment by bdrodes** [comment]
I hate to keep asking but, any updates? I'll soon have to hack around this specific issue to issue (likely in the next week or so), or modify CVC4 directly in order to make forward progress with CVC4 in my projects. The older swig version doesn't have this issue so I imagine I can pull some inspiration there, but before I sink any engineering time here, I wanted to see if there is any update or suggestions.

**Comment by 4tXJ7f** [comment]
I should be able to submit a PR today to address this issue. I'll keep you posted.
