### ISSUE TITLE
Error when printing models of QF_FPLRA formula

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#5032]
Hi, for the following formula
[printerr.txt](https://github.com/CVC4/CVC4/files/5180717/printerr.txt)

cvc4 3f150596fe21 seems to miss ")" when printing the value of floating pointer variables
~~~~
sat
(model
(define-fun fpv0 () (_ FloatingPoint 8 24) (fp #b0 #b00000000 #b00000000000000000000000)
(define-fun fpv1 () (_ FloatingPoint 8 24) (fp #b0 #b01111111 #b00000000000000000000001)
(define-fun fpv2 () (_ FloatingPoint 8 24) (fp #b0 #b10000001 #b10000000000000000000000)
(define-fun fpv3 () (_ FloatingPoint 8 24) (fp #b1 #b10011111 #b01010000100000010100000)
(define-fun v0 () Bool false)
(define-fun v1 () Bool false)
....
~~~~

**Comment by kanigsson** [comment]
We just hit the same issue, with the commit tagged "1.8".

**Comment by rainoftime** [comment]
~~~~
$ ./cvc4  -q f.smt2
/CVC4/deps/install/include/symfpu/core/unpackedFloat.h:175:38: runtime error: shift exponent 52 is too large for 32-bit type 'int'
Fatal failure within static void CVC4::symfpuLiteral::traits::precondition(const prop&) at /CVC4/src/util/floatingpoint.cpp:445
Check failure

 p

Aborted

$ cat f.smt2
(declare-fun f (Int) (_ FloatingPoint 53 11))
(assert (= (f 1) (_ +oo 53 11)))
(check-sat)
~~~~

**Comment by martin-cs** [comment]
@rainoftime this is a different problem and is unrelated to the original bug, please open a new issue.

Specifically, this is occurring because you are using an 'exotic' floating-point format with 53 exponent bits and only 11 significand bits.  Getting these working is on my TODO list but I am prioritising formats used in applications.  If you have a use case for this format *please* let me know.

**Comment by rainoftime** [comment]
I will notice.
I open a new issue at https://github.com/CVC4/cvc4-projects/issues/228

**Comment by kanigsson** [comment]
Hello,

Is there any chance a new release of cvc4 1.8 (say 1.8.1) could be released with this fix?

Thank you.

**Comment by martin-cs** [comment]
@kanigsson : which issue?  The original one about printing or the later one using an unexpected floating-point format?

**Comment by kanigsson** [comment]
@martin-cs The issue about printing floating-point values without the closing parenthesis.

**Comment by barrettcw** [comment]
At this point, we do not plan to make any additional official releases of cvc4.  Of course, you're welcome to cherry-pick fixes like this one for your own internal use of cvc4.  We hope our users will move to cvc5.  If there are any difficulties with this move that we can help with, let us know.

**Comment by kanigsson** [comment]
Hello Clark, thanks for your answer. It's OK for us.
Just for the context, we in the SPARK team build our own cvc4 and have this patch already cherry-picked. I was asking in fact on behalf of the Why3 team (or others), who use pre-built binaries of provers such as cvc4. I will try to make the context clearer next time when making such requests. In the meantime Why3 has found a workaround for the issue.
Good news for cvc5! For our migration to cvc5, we plan to do it this year, and we started some work on it already.

**Comment by barrettcw** [comment]
Great!  Let us know if any questions come up during the migration!

-Clark
