### ISSUE TITLE
Command line argument tlimit option is not working properly in windows

### ISSUE THREAD

**Issue by mudathirmahgoub** [CVC4/CVC4#5034]
**Describe the bug**
`tlimit` option was working in previous Windows versions. 
```
This is CVC4 version 1.8-prerelease
compiled with GCC version 5.3.1 20160211
on Apr 14 2020 11:41:12
```
With this new version `cvc4-2020-08-18-win64-opt.exe`, the option `tlimit` no longer works with the test file below. It works fine in Linux. 

[test.txt](https://github.com/CVC4/CVC4/files/5182513/test.txt)

**Command line arguments**:
```
cvc4-2020-08-18-win64-opt.exe test.txt --lang=smt2 --tlimit=5000
```
**CVC4 version/commit**:
```
bin>cvc4-2020-08-18-win64-opt.exe --version
This is CVC4 version 1.9-prerelease
compiled with GCC version 5.3.1 20160211
on Aug 18 2020 11:44:08
```
**Operating system**: 
```
>systeminfo

OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19041 N/A Build 19041
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 44 Stepping 2 GenuineIntel ~2395 Mhz
Total Physical Memory:     16,367 MB
Available Physical Memory: 7,530 MB
Virtual Memory: Max Size:  20,904 MB
Virtual Memory: Available: 3,969 MB
Virtual Memory: In Use:    16,935 MB
```
**`configure.sh` options**
```
https://cvc4.cs.stanford.edu/downloads/builds/win64-opt/unstable/cvc4-2020-08-18-win64-opt.exe
```

**`configure.sh` output**
```
https://cvc4.cs.stanford.edu/downloads/builds/win64-opt/unstable/cvc4-2020-08-18-win64-opt.exe
```

**Comment by nafur** [comment]
Thanks for the report. In fact, we have completely rewritten the time limit mechanism. When you say "no longer works", I assume that the solver ignores the time limit and continues running after five seconds?
Could you please check whether the time limit code for windows (starting at https://github.com/CVC4/CVC4/blob/master/src/main/time_limit.cpp#L55) is enabled in your current setup?
