### ISSUE TITLE
Missing functionality: re.loop with no upperbound missing since pull request 4167

### ISSUE THREAD

**Issue by pjljvandelaar** [CVC4/CVC4#5114]
**Describe the bug**
Before pull request 4167, cvc4 was able to solve regular expressions such as X{n,}: in smt2 (re.loop X n).
The string standard has forgotten this functionality, and cvc4 no longer support this functionality! 
However, I still need this functionality.
Could support for this removed functionality be added once more?
I have no problem with a new name like `re.loop_infinite`!

**Comment by ajreynol** [comment]
Unfortunately, the standard indeed has omitted this operator. You can for now use `(re.++ (re.loop R n n) (re.* R))`, which is an equivalent expression.

If the standard updates to include this operator, we will support it in the future.
