### ISSUE TITLE
Bug: Fatal Failure (datatypes parsing)

### ISSUE THREAD

**Issue by nblei** [CVC4/CVC4#5150]
**Describe the bug**
apparently legal smt2 program causes fatal failure in CVC4 version 1.9-prerelease

```
(set-logic ALL)
(declare-datatype Switch ((On (Bool val)) (Off)))

(define-fun CheckSwitch ((s Switch)) Bool
    (match s ((On val) val) (Off false)))
)

(declare-const x Switch)
(assert (= (CheckSwitch x) false))
(check-sat)
```

**CVC4 version/commit**: Paste CVC4 version/commit here.

This is CVC4 version 1.9-prerelease [git master edf2e3ff]
compiled with GCC version 10.2.0
on Sep 12 2020 17:20:51

**Operating system**: Name/version of the operating system.
Linux 5.7.0-2-amd64 #1 SMP Debian 5.7.10-1 (2020-07-26) x86_64 GNU/Linux

**Comment by ajreynol** [comment]
Hi, I believe there are 2 syntax issues with the benchmark:
(1) (Bool val) should probably be "(val Bool)", val is the selector name Bool is the type.
(2) the list of match cases should be enclosed in parentheses (see page 27 of http://smtlib.cs.uiowa.edu/papers/smt-lib-reference-v2.6-r2017-07-18.pdf).
Here is a working version of the benchmark:
```
(set-logic ALL)
(declare-datatype Switch ((On (val Bool)) (Off)))

(define-fun CheckSwitch ((s Switch)) Bool
    (match s (
      ((On val) val) 
      (Off false)
    ))
)
(declare-const x Switch)
(assert (= (CheckSwitch x) false))
(check-sat)
```

**Comment by nblei** [comment]
OK, shouldn't this be a parser error that emits a very clean error message?
