### ISSUE TITLE
Max in Sequence

### ISSUE THREAD

**Issue by bdrodes** [CVC4/CVC4#5189]
I'm looking for general assistance in how I can get a max value out of a sequence of ints using the cvc4 python API. 

Here is my example, it is returning `unknown (INCOMPLETE)`

```
import pycvc4.kinds as kinds 
import pycvc4
slv = pycvc4.Solver()
slv.setLogic("DTSLIRA")
slv.setOption("produce-models","true")
slv.setOption("strings-exp", "true")

seq = slv.mkEmptySequence(slv.getIntegerSort())
seq = slv.mkTerm(kinds.SeqConcat, seq, slv.mkTerm(kinds.SeqUnit, slv.mkReal(100)))
seq = slv.mkTerm(kinds.SeqConcat, seq, slv.mkTerm(kinds.SeqUnit, slv.mkReal(1)))
seq = slv.mkTerm(kinds.SeqConcat, seq, slv.mkTerm(kinds.SeqUnit, slv.mkReal(-1)))
seq = slv.mkTerm(kinds.SeqConcat, seq, slv.mkTerm(kinds.SeqUnit, slv.mkReal(500)))

# Proof Concept: 
# max_int : Int
# assert (max_int in seq) /\ (forall e_unit_var. e_unit_var in seq -> max_int >= e_unit_var)

max_int = slv.mkConst(slv.getIntegerSort(), "max_int")
e_unit_var = slv.mkVar(slv.mkSequenceSort(slv.getIntegerSort()), "e_unit_var")

v_list = slv.mkTerm(kinds.BoundVarList, e_unit_var)
# max_int >= to all elements in seq: forall e_unit_var. e_unit_var in seq -> max_int >= e_unit_var)
max_expr = slv.mkTerm(kinds.Forall, v_list, 
                    slv.mkTerm(kinds.Implies, 
                        slv.mkTerm(kinds.SeqContains, seq, e_unit_var),
                        slv.mkTerm(kinds.Geq, max_int, slv.mkTerm(kinds.SeqNth, e_unit_var, slv.mkReal(0)))))

# max_int is in my sequence: (max_int in seq)
contains_max = slv.mkTerm(kinds.SeqContains, seq, slv.mkTerm(kinds.SeqUnit, max_int))

slv.assertFormula(slv.mkTerm(kinds.And, contains_max, max_expr))

print(slv.checkSat())

```

I'm not sure the SeqNth is what I want here, but it seemed to be the only way to do the comparison without a type mismatch. 

Is there some logic that I am missing here that would get this to solve, or is there a cleaner way of structuring the kind of proof I want?

**Comment by martin-cs** [comment]
Please forgive me if this is a stupid question but if you have a small (finite) sequence of integers (literals or variables) then you could just give a tree of ITEs...

```
(declare-fun max ((left Int) (right Int)) Int (ite (> left right) left right))
(max (max 100 1 ) (max -1 500))
```

( SMT-LIB not Python but the same should work. )

**Comment by bdrodes** [comment]
@martin-cs I'm using a sequence of ints as a demonstration, what I really want to model is a sequence of algebraic types to represent an arbitrary mapping of misc. types -> misc types. I was experimenting with using a sequence for this because it automatically gives me the ability to get the size of my sequence and easily insert. 

Where I was having issue is trying to examine each element of my sequence, in this example, finding a max element. 

Perhaps using a sequence for this purpose isn't correct, and maybe a linked list structure that I think your function approach suggests is better, but I'd need to have all the benefits of a sequence for my use case, i.e., having elements set within the sequence at a given ordered index, arbitrary access, extracting the length, etc.

**Comment by bdrodes** [comment]
To further clarify where I am going, what I really want is an Array of <myType> -> <myType>, and array in a programming language sense, that is a finite sequence where there is a notion of 'length' and I can append and merge arrays. SMT arrays are fully defined over the domain so as far as I can find there is no notion of a length, or appending, or finding a max element (like my example above) etc. 

I'm open to alternative suggestions, but it seems a sequence is what I want know?

**Comment by bdrodes** [comment]
I switched from a universal quantification and attempted to define a recursive function through the python API, but its unclear to me how to use the python API to make a self referential function call. 

Any suggestions? 

Also, I made a simple test of the defineFunRec without any recursion (see below), and the result was also an `UNKNOWN (INCOMPLETE)`. I'm not sure if that's a failure on my part or not. 

```
import pycvc4
import pycvc4.kinds as kinds 
slv = pycvc4.Solver()
slv.setLogic("AUFSLIRA")
slv.setOption("produce-models","true")
slv.setOption('dt-nested-rec', 'true')

n = slv.mkVar(slv.getIntegerSort(), "n")
test_recursive = slv.defineFunRec("test_recursive", {n}, slv.getIntegerSort(), n)

x = slv.mkReal(100)

cnstr = x.eqTerm(slv.mkTerm(kinds.ApplyUf, test_recursive, x))

slv.assertFormula(cnstr)

print(slv.checkSat())
```

**Comment by martin-cs** [comment]
@bdrodes I think the first thing is to work out whether you are using arrays or sequences.  Arrays are simple as they lean heavily on the equality an uninterpreted function support -- they are basically updatable functions.  The usual way of handling length is to have a separate variable or a function `array_type -> index_type`.  Sequences are more complex as they have to handle word-equations and a whole lot of extensions.  Which is best is ... hard to say, it depends on the application.  Can you share anything about your target use?

**Comment by bdrodes** [comment]
I think I found a solution for the recursive self referential. For those that find this in the future:

1) set your solver logic to use 'UF', here's what I'm using for my general tests: `slv = pycvc4.Solver(); slv.setLogic("AUFSLIRA")`
2) You must use the `fmf-fun` option on your solver: `slv.setOption('fmf-fun', 'true`
3) define a function const for your recursive function: `my_rec_fun = slv.mkConst('my_rec_fun' {<func_var_sorts>}, <result_type>)
4) define a recursive function: `my_rec_fun =  slv.defineFunRec(my_rec_fun, {<params>}, <term/body>`

The signature for step 4 I found here `https://github.com/CVC4/CVC4/blob/13cf41801f8f2bac538cb45d53ae7427916041a7/src/api/python/cvc4.pxi#L1016`

**Comment by bdrodes** [comment]
@martin-cs thanks for the response. 

I'm basically modeling a dictionary that I may treat in some ways like an array in a traditional programming sense. So consider an SMT array where the index is some algebraic type and the value is also some algebraic type. I'm experimenting with a sequence of algebraic types that provide a key/value mapping. I therefore use a sequence to quickly assess length, and I can easily iterate over the sequence using the built in sequence integer index. 

The semantics of appending and merging in my dictionary/array will be based index/key types. For example, as per my example above, I may want to append a new element to the end of the array/sequence, but its 'key/index' will be 1 + <current_max>, where current_max assesses all indices of the kevy value mapping that are already in my sequence of key values and where the key is of type int.  

I've struggled to use smt Arrays because they are fully defined over their domain. For example, an array of Integer -> Integer, I may store `Arr[100] = 0; Arr[0] = 1`, what I have seen in these cases is when I solve, the array has no indication that index 100 was ever stored to. Instead it says something like index 0 is 1, and the rest of the domain maps to 0. But in my case, I need to know index 100 was stored to. 

Length, and append/merge have been similar struggles with SMT arrays. Perhaps I'm missing something obvious, but it isn't clear to me how to keep a separate variable for length, as I would need to somehow coordinate length with the actual number  of elements stored.  I feel like if the solution were obvious for that, then I could equally keep track of some notion of the last element, and max index.

**Comment by ajreynol** [comment]
FYI, `fmf-fun` enables a particular strategy for dealing with recursive functions internally described here: https://homepage.divms.uiowa.edu/~ajreynol/ijcar16a.pdf

If you want CVC4 to be able to answer "sat" in the presence of recursive functions, you must use this option.  Otherwise it is likely that CVC4 will say "unknown" instead of "sat".  However, if you are interested in "unsat" responses, this option is not strictly necessary.

The choice of arrays vs sequences is a common one.  There are advantages in either theory, arrays allows a more natural representation of lookups and updates at indices, whereas sequences allow more natural operations for length and appending.  My general opinion is that sequences may be more viable solution (at least in CVC4) since we are actively developing extensions to the signature of sequences.  For instance, it would be interesting to support some native support for getting the max value of a sequence.  Since sequences are agnostic to the element type (a sequence of integers is essentially the same as a sequence of some arbitrary type), max would likely have to be done as some kind of generic fold operation.

**Comment by bdrodes** [comment]
Thanks @ajreynol . I managed to figure out the fmf-fun thing after posting an initial question about it (I removed it from the comment above). It didn't solve my universal quantification problem, but maybe using a recursive function is better over all anyway? My rule of thumb is quantification is bad, but I'm curious if that's well founded, especially if my alternative is a recursive function call.

**Comment by ajreynol** [comment]
Recursive function definitions are essentially the same as universally quantified formulas (in fact SMT-LIB states that the two are semantically equivalent, see page 63 of http://smtlib.cs.uiowa.edu/papers/smt-lib-reference-v2.6-r2017-07-18.pdf).

Recursive functions have the advantage that if the solver has specific techniques (such as --fmf-fun), then it can apply them with the knowledge that youve given a recursive function definition and not an arbitrary quantified formula.

However, it would be even more preferable if there was a way of avoiding both.  Its possible that we could provide native support for an operator for "max in a sequence" without you having to define it, although this may take some time to support.  Using recursive functions is your best bet in the meantime.

**Comment by KevOrr** [comment]
I suppose the next question would be if recursive functions are the way to go, how would one destruct a sequence? Should they use `SEQ_LENGTH` to check if it's empty or not, and then `SEQ_AT` and `SEQ_EXTRACT` to get the head and tail, or is there a different way?

**Comment by ajreynol** [comment]
SEQ_AT and SEQ_EXTRACT will return subsequences of a given sequence.  If you want to extract the element of a sequence, you would use SEQ_NTH. For example (SEQ_NTH (SEQ_UNIT 3) 0) returns 3 while (SEQ_AT (SEQ_UNIT 3) 0) returns (SEQ_UNIT 3).
