### ISSUE TITLE
ARR_TABLE_FUN (Bugzilla #318)

### ISSUE THREAD

**Issue by mpreiner** [CVC4/CVC4#537]
**Imported from Bugzilla**
Reporter: *Tim King*
Status: *NEW*
Severity: *enhancement*
Assigned to: *Clark Barrett*
Component: *Arrays*
Milestone: *1.6*
Version: *master*
Platform: *PC*
OS: *Mac OS*

On 2012-04-12 12:10:03 -0700, Tim King wrote:
> Please justify at a meeting or remove the kind ARR\_TABLE\_FUN from commit 3198. \-\-Dejan

On 2012-04-12 20:15:04 -0700, Clark Barrett wrote:
> ARR\_TABLE\_FUN is used internally to enable quick lookup of array lemmas that are equivalent modulo the current equality context.  It is currently disabled by default as it didn't help much on the simple QF\_AX benchmarks, but I don't want to get rid of it just yet.
> 
> I'd be happy to discuss this in a meeting.

**Comment by ajreynol** [comment]
This seems to be resolved, we kept ARR_TABLE_FUN as a kind.
