### ISSUE TITLE
Missing documentation - How to debug certain regression tests

### ISSUE THREAD

**Issue by DavidScepanovic** [CVC4/CVC4#5387]
Hello,

I'm using the latest stable CVC4 version 1.8. 

1. Is there any way to debug a certain regression test? Information about it seems lacking. 
(EDIT) Currently I'm using --output-on-failure, but that's too poor of a debugging tool. 
2. Additionally is gdb-debugging supported with regression tests and how should I go about it?

PS. (Bonus question)
3. Lastly, what's a safe way to disable proofs for all tests and make them ignore (check-unsat) and similar proof options?

Thanks in advance.
David Scepanovic

**Comment by martin-cs** [comment]
It might help people assist you if you could say a little bit more about what you are trying to do and what is going wrong.

1. All of the regression tests are in the `test` directory and you can just find the test in question and run it independently.  The command-line is at the top of the files.
2. If you have built with gdb support ( I use `./configure.sh debug --static --debug-symbols` ) then you should be able to use `gdb` on these.
3. https://github.com/CVC4/CVC4/blob/master/INSTALL.md shows how to exclude certain tests, I'm not sure there is an option for disabling proof (proofs are not generated by default though...) but with a little `grep` you should be able to find the tests to exclude.

HTH

**Comment by DavidScepanovic** [comment]
@martin-cs , thank you for your fast and informative answer!

I'm a complete beginner when it comes to CVC4. I'm trying to make some adjustments to the MiniSat core and evaluate the performance gain/loss. Doing that I keep failing a few of the regression tests and I would like to debug them.

First of all, I can't seem to find the Debug channel or where the additional debug information is getting printed out. (My only tool at the moment is --output-on-failure and assertions).

Secondly, I can't get gdb to work (even after I used the configure you did). I need to get the test (the one I want to debug) to a gdb-acceptable format and I have no clue on how to do that when it's in .smt2 or similar format. 

Lastly, the documentation is very scarce when it comes to what I need.

Any additional help would be greatly appreciated!
David Scepanovic

**Comment by martin-cs** [comment]
OK.  What you are trying is quite ambitious.  Don't let that put you off but be aware that you might have to learn some about the internals.  Most of the documentation is user-level so, yeah, there isn't too much that will help.  One thing to try would be to get the modified MiniSAT running on DIMACS benchmarks first, that will make it easier to iron out any correctness issues.  Also be aware that CVC4 has options to build with more modern SAT solvers and you may find that these perform better.

`--debug whatever` turns on the debug channel called `whatever`, `--trace other` turns on the trace channel called `other`.  These are the primary tools for getting a high-level view of what is going on inside the solver.

I'm a little confused about your statements about tests.  Each test is a `.smt2` or `.cvc` file.  These are input for the solver and it is run with the command line given at the top of the file.  You run `gdb` on the solver, not on the input file.

**Comment by DavidScepanovic** [comment]
@martin-cs
I've chosen the core-MiniSatSolver as it's the one used by default at the moment if I'm not mistaken. Yes, testing on DIMACS first is a good idea, but it has already been done in a certain form and I'm confident that the problems I have currently are related to CVC4's inner workings. 

Related to the last statement, my bad, what I meant to say is I need to get the solver compiled to a gdb-acceptable format and start a certain test.

Is there a way for commands --debug and --trace to print their output to a certain text file or stdout/stderr? 

Thanks again,
David Scepanovic

**Comment by martin-cs** [comment]
MiniSAT is the default yes, note that the CVC4 MiniSAT is not the stock MiniSAT and does have some modifications.

Compiling with the configuration I gave above should give you a `gdb`-able binary, or, at least, it does not my machine.

`--debug` and `--trace` both default to `stderr` which you can then redirect to a file you want.

**Comment by DavidScepanovic** [comment]
@martin-cs Yes I understand it's not the stock MiniSat.

Well you have been very helpful and this is getting quite embarrassing as I'm still not getting the hang of it. Since I only need to get things going and analyze the MiniSatSolver part of the code (and it's attachments), would you be kind enough to try and help me one final time. I'll close the issue after that since I don't like to be a burden. 

If you still want to help could you from start to finish try to guide me line by line with the commands you would insert to do two things:

1. start a test with gdb (for example - regress2/arith/pursuit-safety-12.smtv1.smt2). I go about this by:
    - calling the configure.sh with the arguments you told me
    - calling make and make check
    - starting the executable cvc4 (And here's the problem, I don't know which arguments to forward to the executable. Could you  for example show me how to start the above-mentioned test (which arguments to forward [options and the input-test to parse]). Can't find any documentation about this)
2. start a test with its debug and tracing information redirected to a file (for example - the above-mentioned test). I go about this by:
    - doing the first two steps above if I haven't already
    - calling :
           ctest -R regress2/arith/pursuit-safety-12.smtv1.smt2 --debug 2> error.txt
      or 
           ctest -R regress2/arith/pursuit-safety-12.smtv1.smt2 --debug stderr 2> error.txt
 but they both fail and my error.txt has only one line:
           /build/cmake-_JRNDx/cmake-3.16.3/Source/cmCTest.cxx:1015 Errors while running CTest

Once again thanks a lot for helping me get through this. I'll close this issue as soon as possible. I hope I haven't been too much of a burden!

David Scepanovic

**Comment by martin-cs** [comment]
1. Configure CVC4 to be built in debug mode.  Add any other flags you usually use to configure.  If you want to install somewhere custom, you will need to configure with `--prefix=/where/you/want/the/install`.

```
./configure.sh debug --static --debug-symbols
```

2. Build CVC4 (I'm assuming you have a clean check-out of the code).  If you want `make` to run faster, add `-jN` where `N` is the number of processes you want to use.

```
cd build
make
```

3. Optionally run `make check` and `make install`.  

4. Get the command line that is at the top of the regression in question, for example:

```
$ head -n 3 ../test/regress/regress2/arith/pursuit-safety-12.smtv1.smt2
; COMMAND-LINE: --no-check-proofs
(set-option :incremental false)
(set-info :source "SAL benchmark suite.  Created at SRI by Bruno Dutertre, John Rushby, Maria
```

5. Start CVC4 in the debugger:

```
gdb /wherever/your/binary/is/cvc4
```

6. Add whatever break-points you want (`catch throw` is always a good start).  Run the benchmark in `gdb`

```
run --no-check-proofs --debug minisat --debug pf::sat --trace smt ../test/regress/regress2/arith/pursuit-safety-12.smtv1.smt2
```

The debug and trace options are just suggestions of things that you might want to see.

HTH.

**Comment by martin-cs** [comment]
I also use https://rr-project.org/ rather than just gdb as I find it easier.
