### ISSUE TITLE
String theory escaping

### ISSUE THREAD

**Issue by robdockins** [CVC4/CVC4#5395]
**Describe the bug**
The behavior of CVC4 with respect to string escape codes seems to have changed with version 1.8.  In version 1.7 (and according to the wiki documentation), escape codes of the form `\xHH` can be used to input nonprintable ASCII characters.  As of 1.8, this no longer seems to work, and output sometimes contains `\u{HH}` escape codes.

Was this change intentional? Where can I find accurate documentation about the current escape codes?

**Command line arguments**:

```
cvc4 --lang=smt2 --strings-exp strings.smt2
```

**CVC4 version/commit**:
This is CVC4 version 1.8 [git master 3bc4a541]
**Operating system**: Name/version of the operating system.
OSX 10.15.7

```smt2
(set-option :produce-models true)
(set-option :global-declarations true)
(set-logic ALL_SUPPORTED)

(declare-fun x!0 () String)
(define-fun x!1 () Bool (str.prefixof x!0 "qwe\x1crtyQQ""QQ"))
(assert x!1)
(declare-fun x!2 () String)
(define-fun x!3 () Bool (str.suffixof x!2 "qwe\x1crtyQQ""QQ"))
(assert x!3)
(declare-fun x!4 () String)
(define-fun x!5 () Bool (str.contains "qwe\x1crtyQQ""QQ" x!4))
(assert x!5)
(define-fun x!6 () Bool (str.contains x!4 "Q"))
(assert (not x!6))
(define-fun x!7 () Bool (str.contains x!4 "q"))
(assert (not x!7))
(define-fun x!8 () Int (str.len x!0))
(define-fun x!9 () Bool (= 9 x!8))
(assert x!9)
(define-fun x!10 () Int (str.len x!2))
(define-fun x!11 () Bool (= 9 x!10))
(assert x!11)
(define-fun x!12 () Int (str.len x!4))
(define-fun x!13 () Bool (= 6 x!12))
(assert x!13)

(check-sat)
; sat
(get-value (x!0))
; ((x!0 "qwe\u{5c}x1crt"))
(get-value (x!2))
; ((x!2 "crtyQQ""QQ"))
(get-value (x!4))
; ((x!4 "x1crty"))
```

Z3 produces these results, which are what I expect, and which used to be produced by CVC 1.7
```
sat
((x!0 "qwe\x1CrtyQQ"))
((x!2 "\x1CrtyQQ""QQ"))
((x!4 "we\x1Crty"))
```

And a simpler example:
```
(set-option :produce-models true)
(set-option :global-declarations true)
(set-logic ALL_SUPPORTED)

(define-fun str () String "\x1c")
(define-fun len () Int (str.len str))

(check-sat)
; sat
(get-value (str))
; ((str "\u{5c}x1c"))
(get-value (len))
; ((len 4))
```

Expected output is:
```
sat
((str "\x1c"))
((len 1))
```

**Comment by 4tXJ7f** [comment]
Since release 1.8, CVC4's string solver follows the [SMT-LIB string standard](http://smtlib.cs.uiowa.edu/theories-UnicodeStrings.shtml), including its escape rules. Replacing `\x??` by `\u{??}`, should give the desired results (e.g. `\u{1c}` instead of `\x1c`).

**Comment by ajreynol** [comment]
This is expected behavior, CVC4 is compliant with the new strings standard as Andres mentions.  See also: https://github.com/Z3Prover/z3/issues/4708.
