### ISSUE TITLE
Standard citation for CVC4 on webpage has typographic error

### ISSUE THREAD

**Issue by dnjansen** [CVC4/CVC4#5417]
**Describe the bug**
In the reference BibTeX entry for CVC4 at the top of https://cvc4.github.io/publications.html, the name of the fifth author is written `Dejan Jovanovi{'{c}}` but should be written `Dejan Jovanovi{\'{c}}`, i.e. a backslash before the apostrophe should be added.

(Also, Springer’s website mentions that the booktitle is `"Computer Aided Verification. CAV 2011"`, and I recommend adding the DOI to the Bibtex entry: `DOI = "10.1007/978-3-642-22110-1_14"`.)

**Comment by aniemetz** [comment]
Thanks for the report!
We're now using the DBLP entry for consistency: https://cvc4.github.io/publications.html
