### ISSUE TITLE
CVC4 suffered a segfault

### ISSUE THREAD

**Issue by hernanponcedeleon** [CVC4/CVC4#5441]
**Describe the bug**
CVC4 suffered a segfault in the attached input.
[for_infinite_loop_1-O0.bpl.smt2.zip](https://github.com/CVC4/CVC4/files/5538750/for_infinite_loop_1-O0.bpl.smt2.zip)

*Note*: If the bug is triggered with an SMT2 input file please minimize it with [ddsmt](https://github.com/aniemetz/ddSMT).
The reducer did not managed to minimise the input (timeout after 5 min)

**CVC4 version/commit**:
This is CVC4 version 1.7
compiled with GCC version 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.32.62)

**Operating system**:
MacOS 10.15.4

**Comment by nafur** [comment]
Seems to be a MacOS issue, can not reproduce on Linux (neither 1.7 nor current master).

**Comment by hernanponcedeleon** [comment]
I build cvc4 from the master branch and it does not crash for the file I uploaded.
I got many other similar crashes (in the master branch) but I was not able to reproduce any of them in Linux.
