### ISSUE TITLE
(fmf-bound) Solution unsoundness on ANIA formula

### ISSUE THREAD

**Issue by muchang** [CVC4/CVC4#5482]
CVC4 with --strings-exp gives an incorrect sat on this unsat formula:
```
[601] % cvc4 small.smt2
unsat
[602] % cvc4 --strings-exp small.smt2
sat
[603] % 
[603] % cat small.smt2
(set-logic AUFNIA)
(declare-fun a () Int)
(declare-fun b () (Array Int Int))
(declare-fun c () (Array Int Int))
(declare-fun d () Int)
(assert
 (exists ((e Int))
 (and (<= e 0)
  (exists ((f Int))
  (and (<= 0 f e)
   (> (select (store b 0 (select c (div a d))) f)
   (select (store b 0 (select c (div a d))) e)))))))
(check-sat)
[604] %
```

OS: Ubuntu 18.04
Commit: f2ed7b1

**Comment by ajreynol** [comment]
Btw, instead of reporting issues with `--strings-exp`, can you always try to see if `--fmf-bound` also triggers the same issue?  (In this case it does).  The option `--strings-exp` automatically enables `--fmf-bound`, which more accurately reflects the option that is to blame.
