### ISSUE TITLE
revisit use of propagateAsDecision (Bugzilla #334)

### ISSUE THREAD

**Issue by mpreiner** [CVC4/CVC4#553]
**Imported from Bugzilla**
Reporter: *Clark Barrett*
Status: *NEW*
Severity: *enhancement*
Assigned to: *Clark Barrett*
Component: *Arrays*
Milestone: *1.6*
Version: *master*
Platform: *PC*
OS: *Linux*

On 2012-05-14 11:26:56 -0700, Clark Barrett wrote:
> When a new lemma of the form i \= j \/ read(a,j) \= read(b,j) is queued up,
> propagateAsDecision is used to force SAT solver to prefer splitting on i \= j.  This may be too heavy\-handed.  Needs to be revisited.

**Comment by ajreynol** [comment]
Note that propagateAsDecision is a deprecated feature. It was replaced by "getNextDecisionRequest". I'm not sure if this issue is still relevant.

**Comment by barrettcw** [comment]
With your PR, I think we can close this issue.

-Clark
