### ISSUE TITLE
Unbalanced S-Expression printed by `get-value`

### ISSUE THREAD

**Issue by abakst** [CVC4/CVC4#5648]
**Describe the bug**

```
(set-option :produce-models true)
(set-logic ALL_SUPPORTED)
(define-fun x!34 () (_ FloatingPoint 8 24) ((_ to_fp 8 24) RNE (_ bv1 32)))
(assert (= x!34 (fp #b0 #b01111111 #b00000000000000000000000)))
(check-sat)
(get-value (x!34))
```
prints
```
sat
((x!34 (fp #b0 #b01111111 #b00000000000000000000000))
```
(notice there is a missing `)`)

*Note*: If the bug is triggered with an SMT2 input file please minimize it with [ddsmt](https://github.com/aniemetz/ddSMT).

**Command line arguments**: --lang=smt2
**CVC4 version/commit**: 1.8 release (--version indicates git master 3bc4a541)
**Operating system**: macOS 11.0.1

**`configure.sh` options**
N/A

**`configure.sh` output**
N/A

**Comment by nafur** [comment]
Though I clearly remember this issue, I'm unable to find when it was fixed. In current master, the output is fixed:
```
$ cat cur.smt2 
(set-option :produce-models true)
(set-logic ALL_SUPPORTED)
(define-fun x!34 () (_ FloatingPoint 8 24) ((_ to_fp 8 24) RNE (_ bv1 32)))
(assert (= x!34 (fp #b0 #b01111111 #b00000000000000000000000)))
(check-sat)
(get-value (x!34))
$ bin/cvc4 -m cur.smt2 
sat
((x!34 (fp #b0 #b01111111 #b00000000000000000000000)))

```

**Comment by abakst** [comment]
Thank you!
