### ISSUE TITLE
How to build from cvc4 binary file into your Linux system

### ISSUE THREAD

**Issue by htethtetoo20** [CVC4/CVC4#5650]
Hello,
I installed CVC4 binaries for linux from website.I don't know how to install CVC4 program into my Linux System from this binary file.
Best wishes.

**Comment by martin-cs** [comment]
If you make the binaries executable (from the command line that is `chmod 755 file-name-goes-here`) then you should be able to run them directly.

**Comment by nafur** [comment]
I assume the issue has been resolved. Please comment again within this issue otherwise.
