### ISSUE TITLE
pip install fails with python3.6

### ISSUE THREAD

**Issue by CloudApiStudy** [CVC4/CVC4#5651]
Hi, I'm trying to install CVC4 with pip (python 3.6) on an Ubuntu system. Package info shows up with command `pip3 show cvc4`. However, when testing with code

```
from CVC4 import ExprManager
ExprManager()
```
it shows
```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from CVC4 import ExprManager
ModuleNotFoundError: No module named 'CVC4'
```

Is there anything I missed to set it up?

**Comment by nafur** [comment]
I'm not sure what you installed, but I can't find a `cvc4` package on [pypi.org](https://pypi.org/search/?q=cvc4). There is `cvc4-solver`, but this is not maintained by us (as in: the CVC4 developers). While we plan to have a proper package (see #5418), but there are still some open questions about how to do this.

**Comment by CloudApiStudy** [comment]
Sorry for the typo. It's `cvc4-solver`.
