### ISSUE TITLE
Set Cartesain product

### ISSUE THREAD

**Issue by XiaoLi0614** [CVC4/CVC4#5686]
Hi, 

I struggled with set cartesian product operation. I know that cvc4 can handle cartesian product on finite relation datatype. Is there any way to have a cartesian product on set datatype? Or is there any way to covert between set and relation datatypes? Thank you.

**Comment by mudathirmahgoub** [comment]
Relations are sets where elements are tuples. The product operator is only defined in such sets. 
Applying the product operator on sets whose elements are not tuples would generate an error. 
You can check this [example](https://cvc4.github.io/app/#examples%2Fsmt-lib%2Frelations).

**Comment by XiaoLi0614** [comment]
Thank you so much for the quick response. 

One more related question about the relation and set datatype. In set theory, we can declare a singleton set. But I did not find how to instantiate a singleton tuple. I find the following description in wiki for cvc4: 

>  "however, a single-element tuple cannot be directly created, as (\ \_\ ) is interpreted as a parenthesized (non-tuple) expression." 

My question is how to initiate a relation variable which has the type of: `MyRelation: TYPE = SET OF [MyType];`

**Comment by mudathirmahgoub** [comment]
In smtlib language you would write something like this:
```smt2
(set-logic ALL)
(set-option :produce-models true)

(declare-fun r () (Set (Tuple Int)))
(assert (= r (singleton (mkTuple 5))))

(check-sat)
(get-model)

```
In cvc language you would write:
```cvc
OPTION "logic" "ALL";
OPTION "produce-models";

r : SET OF [INT];
ASSERT (r = {TUPLE(5)});
CHECKSAT;
COUNTERMODEL;
```
