### ISSUE TITLE
CVC4 interrupted by SIGTERM for finite set theory

### ISSUE THREAD

**Issue by XiaoLi0614** [CVC4/CVC4#5727]
Hi, I'm working on the finite set theory in CVC4 and I got the following output with the input file: [https://cvc4.github.io/app/#temp_3ccc8aa5-8e9f-4a62-b24f-750539b3a4af](url)

> CVC4 interrupted by SIGTERM.

When I delete only one constraint `NOT(Q  = {}:: SET OF SET OF INT)` on line 101, I got a model produced by cvc4. The input file with one less constraint is in the link below:
[https://cvc4.github.io/app/#temp_81595cda-625d-4c8e-976f-4c2b40ccccf0](url) 

I would like to know what kind of issue triggers the SIGTERM. I tried to enlarge the time limit but I still got the same results. Is there any way that I can trace the internal problem cvc4 met?

**Comment by nafur** [comment]
I'm sorry, but apparently I can't access the inputs you are talking about via these links. I always see an smt-lib input that works just fine. Can you post the input right here in the issue?

**Comment by nafur** [comment]
Closing now. Please reopen the issue if you still have this issue, properly providing the failing input.
