### ISSUE TITLE
the str.in.re operation cannot be parse when using cvc4 --strings-exp

### ISSUE THREAD

**Issue by Zhangyao-zzyy** [CVC4/CVC4#5730]
when i run this case by **cvc4 --strings-exp**, the error " Symbol 'str.in.re' not declared as a variable"" ocurrs.

(set-logic QF_SLIA)
(declare-fun var0 () String)
(declare-fun var1 () String)
(declare-fun var2 () String)
(declare-fun var3 () Int)
(declare-fun var4 () Int)
(declare-fun var5 () Int)
(declare-fun var6 () Bool)
(declare-fun var7 () Bool)
(declare-fun var8 () Bool)
(assert (str.prefixof var0 var0))
(assert (<= (str.len var1) (str.len var2)))
(assert (< var3 var5))
(assert (str.in.re (str.substr (str.replace "=:>Z1YZpV!" var2 var0) (str.len var1) (str.len var1)) (re.* re.allchar)))
(check-sat)

**Comment by rainoftime** [comment]
The standard has changed. try str.in_re

**Comment by Zhangyao-zzyy** [comment]
> The standard has changed. try str.in_re

thanks, that's correct
