### ISSUE TITLE
The dag output doesn't take into account binder (Bugzilla #358)

### ISSUE THREAD

**Issue by mpreiner** [CVC4/CVC4#577]
**Imported from Bugzilla**
Reporter: *François Bobot*
Status: *NEW*
Severity: *major*
Assigned to: *Clark Barrett*
Component: *{Internals} Utilities*
Milestone: *1.6*
Version: *master*
Platform: *All*
OS: *All*

On 2012-06-15 15:56:29 -0700, FranÃ§ois Bobot wrote:
> The dag output use top\-level let to factorize sub\-term without taking into account quantifiers and binders. So variable can go outside there scope.
> 
> (assert (let ((\_let\_0 (join (store ?m ?p ?q) ?u ?v)) [...] ) (forall (((?p (SORT\_TYPE SORT\_TAG:var\_91)) (?q (SORT\_TYPE SORT\_TAG:var\_91)) (?m (ARRAY\_TYPE (SORT\_TYPE SORT\_TAG:var\_91) (SORT\_TYPE SORT\_TAG:var\_91))) (?u (SORT\_TYPE SORT\_TAG:var\_91)) (?v (SORT\_TYPE SORT\_TAG:var\_91))) (\= \_let\_0 ([...]))) ((\_let\_0)))))
> 
> 
> ( The [...] correspond to sub\-terms that I manually removed for the sake of readability )

On 2012-07-26 14:06:14 -0700, Morgan Deters wrote:
> Note to self: revisit smt2\_printer.cpp around line 290 for Francois' change that corrects for this problem.

**Comment by ajreynol** [comment]
Closing this since it is duplicate of #1863.

**Comment by 4tXJ7f** [comment]
Actually closing it :)
