### ISSUE TITLE
Dead link on Rewritng Theory page

### ISSUE THREAD

**Issue by jakevossen5** [CVC4/CVC4#5770]
There is a dead link on the "Rewriting Theory" page here: https://cvc4.github.io/rewriting-theory.html

Near the bottom, where it says "The tests use during the development are in here ". Not only is the link broken, but I cannot seem to find the location of where these tests moved too, so if anyone could point me in that direction it would be much appreciated!

**Comment by ajreynol** [comment]
Hello,

This documentation describes a feature from older versions of CVC4.  It is no longer supported in the current CVC4.  We do plan on adding support for a similar feature in the future, but it will likely have a different syntax.

Out of curiosity, how did you link to this page?  I didn't think we had any links to it from the webpage currently.

Cheers,
Andy

**Comment by jakevossen5** [comment]
Ah, thanks for the info, that makes sense! I found the page by googling around for custom rewrite rules in the SMT-LIB language, and found it.
