### ISSUE TITLE
get-qe returns internal symbol (delta_4)

### ISSUE THREAD

**Issue by daniel-larraz** [CVC4/CVC4#5899]
The `get-qe` command in this script [delta.txt](https://github.com/CVC4/CVC4/files/5968501/delta.txt) returns a new symbol (`delta_4`) not declared in the script.

**Command line arguments**: `--lang smt2 --incremental`
**CVC4 version/commit**: 1.9-prerelease / cbd66977
**Operating system**: Ubuntu 20.04.1

**Comment by ajreynol** [comment]
Sorry for the delay, delta_4 is the traditional "smallest real" value such that `0<t+delta` is equivalent to `0<=t`.

It should be fairly straightforward to remove this.
