### ISSUE TITLE
Build failure with CVC4 in a long path

### ISSUE THREAD

**Issue by 0152la** [CVC4/CVC4#5921]
**Describe the bug**
It seems that if CVC4 is attempted to be built in a long enough path, then building fails with a `Argument list too long` error. The issue seems to stem from the `Debug_tags.tmp-<xxxxx>.sh` and `Trace_tags.tmp-<xxxxx>.sh` files produced by cmake. Unsure about the exact length, but a fresh clone into `/home/verylongpathevenlongername/makeiteverlongerifpossible/andonemorelevelofmakingitevenlonger` triggers the issue. However, one level up does not trigger the issue.

On the two systems tested, `getconf ARG_MAX` yields 2097152.

**Command line arguments**: n/a
**CVC4 version/commit**: c6210af1db67701495efa263207b91064a3bcd0b
**Operating system**: Tested on both Archlinux and a clean Ubuntu 18.04 docker container.

**`configure.sh` options**
No special options passed.

**`configure.sh` output**
[cvc4_configure.txt](https://github.com/CVC4/CVC4/files/6002004/cvc4_configure.txt)

**Comment by nafur** [comment]
So this seems to be a known issue with larger projects, and some work was done inside cmake (e.g., https://cmake.org/Bug/view.php?id=15650, https://gitlab.kitware.com/cmake/cmake/-/issues/16206, https://gitlab.kitware.com/cmake/cmake/-/issues/17877, https://gitlab.kitware.com/cmake/cmake/-/issues/18360).
What cmake version(s) are you using?

**Comment by 0152la** [comment]
Using version 3.19.6 on the Archlinux machine, and 3.16.3 on the Ubuntu one. I didn't realise it would be a CMake issue, since what I did on my machine was just pull and suddenly CVC4 would not compile anymore (presumably as more files were added to this argument list).

**Comment by nafur** [comment]
Hm, it actually does seem to be on our side: we call custom scripts via `add_custom_command` and pass all the filenames on the commandline (https://github.com/CVC4/CVC4/blob/master/src/base/CMakeLists.txt#L54 and below). We should probably write the source files to a temporary file and make the scripts use that one...

**Comment by nafur** [comment]
Could you check whether the changes from #5996 fix the issue on your machine?

**Comment by 0152la** [comment]
I went on the Archlinux machine and did
```
> cd {CVC4_ROOT} # at long path which previously failed
> git pull
> git checkout refactor-tag-collection
> cd build
> ninja -j5
```
and it seems things are coming along nicely, where before they would crash in this repo (I do have another repo at a shorter path which I used for access to later versions).
