### ISSUE TITLE
Retrieving model with C++ API

### ISSUE THREAD

**Issue by 0152la** [CVC4/CVC4#5923]
Is it currently possible to retrieve the model via the exposed C++ API, and then further evaluate an expression with the corresponding model? The general workflow I would like to achieve is create a solver, set `produce-models` to `true`, assert some term *t*, then, if the solver returns `sat`, check whether a different term, *t'* is satisfiable given the free variable bindings from any model satisfying *t*. I was able to dig and find that there is the notion of a model in the `SmtEngine` field, which is temporarily made available in the `Solver` class, but the additional code required to use those model functions seem to be explicitly private, and seemingly not callable from the exposed C++ API.

**Comment by nafur** [comment]
The `Solver` class has a method `getValue()`, which is usually used to query the model. Though there is no way to evaluate a term over an arbitrary assignment, you can use `getValue()` to evaluate any term over the current model. Hence, for your case, calling `getValue(t')` should do what you want.

**Comment by 0152la** [comment]
So then, just to write it down, supposing there exists a Solver *s* and two Terms, *t1*, *t2*, both of sort Bool, known to be satisfiable, and both declared over the same set of free variables, the sequence

```
s.push();
s.assertFormula(t1);
s.checkSat();
s.getValue(t2);
s.pop();
s.push();
s.assertFormula(t2);
s.checkSat();
s.getValue(t1);
s.pop();
```

Would, in turn, return the value of *t2* over some satisfying model of *t1*, and then conversely return the value of *t1* over some satisfying model of *t2*. Is that correct?

**Comment by nafur** [comment]
Exactly, here is a small working example:
```
  Solver slv;
  slv.setOption("produce-models", "true");
  Term a = slv.mkConst(slv.getBooleanSort());
  Term b = slv.mkConst(slv.getBooleanSort());
  Term t1 = slv.mkTerm(Kind::OR, {a, b});
  Term t2 = slv.mkTerm(Kind::AND, {a, b});

  slv.push();
  slv.assertFormula(t1);
  slv.checkSat();
  std::cout << slv.getValue(t2) << std::endl;
  slv.pop();
  slv.push();
  slv.assertFormula(t2);
  slv.checkSat();
  std::cout << slv.getValue(t1) << std::endl;
  slv.pop();
```
