### ISSUE TITLE
CVC4 Native Input Language - future plans?

### ISSUE THREAD

**Issue by logicReasoner** [CVC4/CVC4#6200]
This one is more of a question than a bug report, so someone should apply the correct label to it.

I've been reading the syntax of the CVC4 Native Input Language at: [https://cvc4.github.io/cvc4-native-input-language.html](https://cvc4.github.io/cvc4-native-input-language.html) and definitely like it more than SMT-LIB v2.6. 
So what are the future plans for the native CVC4 language? Is it going to be supported long-term or more likely to be deprecated in favor of say SMT-LIB 3 or another language? In other words, is the native CVC4 language a safe choice for writing user code regarding maintainability in the long-term?

**Comment by martin-cs** [comment]
I am not sure I can answer your question but maybe I can provide some input.  SMT-LIB was always intended to be a program<->program interface.  Machine readability has always been prioritised above human readability.  In that sense the CVC4 native language is not solving the same problem as it is human<->program.

**Comment by logicReasoner** [comment]
Yes, I am aware of that. SMT-lib can be generated by software, but one can definitely write it by hand, too. That said, the CVC4 native language seems much more expressive (powerful) and user friendly. 
But does anyone use it extensively? I am worried that it may be obsoleted at some point if it remains unpopular.

**Comment by nafur** [comment]
[Disclaimer: I'm not 100% sure about the current state of affairs.]
In recent discussions about which input languages CVC4 should support in the future (in particular in future releases), the idea to remove support for the CVC language did come up and had significant support. Though being called "CVC Native Input Language", SMT-LIB has for quite some time been the main input language in CVC4. As a result, new features have not been ported (back) to CVC (like floating-points).

The only reason to keep CVC right now (from what I gathered from these discussions) is to have a language that is easy to read and write for humans. Does this warrant maintaining (and updating) the CVC language and the parser? Let's just say that this has not happened lately.

**Comment by logicReasoner** [comment]
@nafur what you said supports my intuition as well. Let's wait and see whether any other developers will chime in with their PoV.

**Comment by nafur** [comment]
The internal discussion has come to a conclusion. Citing from the announcement about the upcoming CVC5:

> - Support for the old “CVC” language will be discontinued; users will be encouraged to use the SMT-LIB standard input language instead

Thus: please consider using SMT-LIB.
