### ISSUE TITLE
semantics of to_real when the argument is a real

### ISSUE THREAD

**Issue by zhendongsu** [CVC4/CVC4#6208]
Hi, I wonder what should be the semantics of`(to_real 0.5)`.  Should it be rejected as `to_real` expects an integer, viewed as `(to_real (to_int 0.5))`, or treated like identity?   Thanks.

```
[600] % cvc4 --strict-parsing small.smt2 
sat
unsat
[601] % z3release small.smt2 
unsat
unsat
[602] % 
[602] % cat small.smt2 
(set-logic QF_NIRA)
(assert (= 0.5 (to_real 0.5)))
(check-sat)
(reset)
(set-logic QF_NIRA)
(assert (= 0.5 (to_real (to_int 0.5))))
(check-sat)
[603] % 
```

**Comment by ajreynol** [comment]
Thanks for pointing this out.

After reading https://smtlib.cs.uiowa.edu/theories-Reals_Ints.shtml, I believe that `(to_real 0.5)` should be a syntax error, since to_real expects an integer but a real is provided. 

The fix in CVC4 would be to make the parser more pedantic.

**Comment by zhendongsu** [comment]
@ajreynol 

Andrew, this seems to have regressed:
```
[561] % cvc5 issue6208.smt2 
sat
unsat
[562] % cat issue6208.smt2 
(set-logic QF_NIRA)
(assert (= 0.5 (to_real 0.5)))
(check-sat)
(reset)
(set-logic QF_NIRA)
(assert (= 0.5 (to_real (to_int 0.5))))
(check-sat)
```
