### ISSUE TITLE
Discussion: moving away from `deps` folder

### ISSUE THREAD

**Issue by andrewvaughanj** [CVC4/CVC4#6221]
This is an an end-user comment on #6202 -- please don't take what I'm writing negatively, I'm just trying to share the experience of someone who builds CVC4 "fairly regularly" ...

That being said, I actually *really* liked the "old way" of doing it -- having a "deps" folder was great, I could download/build/etc. all of CVC4's dependencies *in one place* and then share these across multiple git worktrees via symlink.

My folder structure is typically something like this:

```
.
├── CVC4.git
├── deps
├── glpk_lib_path
└── master
```

(where `master` and `glpk_lib_path` are worktrees)

My deps folder looks like this:

```
deps
├── antlr-3.4
├── cryptominisat5
├── glpk-cut-log
├── install
└── symfpu-CVC4
```

My guess here is that, if you move something like GLPK to this cmake-based approach, I'm going to have to build GLPK *every-time I build CVC4* ... if I blast the `build` folder, then I'm going to have to rebuild all of the dependencies I need for that branch.

I'm totally fine for you to say: "Andrew, why do you keep deleting the build folder?" -- that's just my typical way of doing a clean build.

Now I've written this, I feel I've possibly totally missed the point of the new approach, because my use-case seems so "normal" that I can't have understood #6202 correctly ...

**Comment by nafur** [comment]
I already apologize as my answer may not be very coherent.

The main reason for the push towards integrating our dependencies into cmake (ANTLR3 only happened to be the first one to be merged) was to make building CVC4 easier for new users. Essentially, we want `./configure.sh production; cd build; make` to be sufficient to obtain a good version of CVC4 (good = not a minimal one without any optional dependencies).

Of course, we could directly build the dependencies within the configure.sh script. This feels wrong, and also does not solve your problem. IMHO, managing dependencies is one of the core reasons we use a build system like cmake and there is no reason not to use it. The contrib scripts are in some sense reminiscent of the previous autotools build system, and we try to get to an idiomatic cmake build system.

There is another issue related to cross-compilation. We want to support arm builds, and also would like to better support windows builds (mingw, not native Windows). The current dependency setup does not really support this: when you call the contrib scripts, you essentially decide for which target system you want to compile for the whole checkout. We really like the possibility to have multiple build folders within one checkout for different target architectures.

You are right that this configuration now builds the configuration separately for every build folder. We found this to be a rather small price, as removing the build folder seemed not to be part of the regular development process for any of us. May I ask why `make clean` is not sufficient? :-) Still, building the dependencies is pretty fast (compared to building CVC4). Also, we usually use `ccache` to speed up builds, and the dependencies would now also benefit from this setup.

I understand the reason for your setup (one deps folder that is symlinked), and I'm pretty sure we can support this pretty easily. Note that we still check whether the dependencies are installed in the system. I would assume that you could put an additional path into `CMAKE_PREFIX_PATH` (either in the cmake cache or as an environment variable) and have it found there. It may not be as convenient now to setup this directory, though.

**Comment by andrewvaughanj** [comment]
> I already apologize as my answer may not be very coherent.
>

Perfectly coherent :)

> May I ask why make clean is not sufficient? :-) 
>

This would be the first "major" project I've worked with that has used `ExternalProject`s at all -- given this, the way (in the past) I've made sure to get a clean build (with no "cruft") is just to nuke the `build` folder all together.

As nothing else I've worked with has used `ExternalProject`s, it is therefore "unusual" (**to me**!!!) that stuff that's "outside" of the current repo gets pulled down into `build` -- however, I'll admit, **any** project that uses `ExternalProject`s would be an "issue" for my "just delete `build`" workflow.

> Still, building the dependencies is pretty fast (compared to building CVC4)
>

I mean, _sort of_, but I'd also not like not waste time building stuff that does take "some time"; e.g., GLPK takes 84.99 user/16.47 wall and CMS takes 105.79 user/20.20 wall.

I'd like to avoid doing this "needlessly" (especially if I'm creating/deleting worktrees).

> Also, we usually use ccache to speed up builds
>

How many of your "new users" are using ccache? I'll put it this way: I am *not* using it (again, I also `rm -rf builld`, so maybe I'm just a stupid user 🤪)

> I would assume that you could put an additional path into CMAKE_PREFIX_PATH (either in the cmake cache or as an environment variable)
>

Could this be something that could be added to `./configure.sh`? Like, "check for deps here first"? Then you could have an ARM deps, a Windows deps and a Linux deps. If a dep isn't found in the CVC4-controlled `CMAKE_PREFIX_PATH`, *then* do it via `ExternalProject`?

> It may not be as convenient now to setup this directory, though.
>

Would it be possible to have a way to run the `ExternalProject`s projects targeting this "deps" dir? I'm thinking of something like `./contrib/get-antlr-3.4` which could run the **new** cmake way, but targeting this deps dir.

Thanks for being open to discussing this!

**Comment by nafur** [comment]
I would support adding an option to `configure.sh` to specify a base folder for already existing dependencies.

The simplest way (as in: least changes to our build system) would be if you have a "dummy checkout" of CVC4 where you only build the dependencies (`cd build ; make ANTLR3-EP-runtime CaDiCaL-EP ...`) and then pass `--new-option-for-basedir cvcdummy/build/deps/` to the configure script. But this seems a bit awkward to use.

An alternative could be to provide an additional cmake project (like we do for examples) that only builds the dependencies in such a way that you would have them installed directly to the build folder. Then you could have a dedicated `build_deps` and the base dir for dependencies would just be this folder.

**Comment by andrewvaughanj** [comment]
> The simplest way (as in: least changes to our build system) would be if you have a "dummy checkout" of CVC4 where you only build the dependencies (cd build ; make ANTLR3-EP-runtime CaDiCaL-EP ...) and then pass --new-option-for-basedir cvcdummy/build/deps/ to the configure script. But this seems a bit awkward to use.

This is fine by me.

Anything that makes it easy for me to cache these results, and means the minimum work for the CVC4 team.

Maybe this already works today if I use `CMAKE_PREFIX_PATH`?

**Comment by nafur** [comment]
> Maybe this already works today if I use `CMAKE_PREFIX_PATH`?

Yes, I would expect this to work already.

**Comment by andrewvaughanj** [comment]
> Yes, I would expect this to work already.

My machine is now occupied for evening (running something I don't want to disturb); I'll try this tomorrow.

If this is the case, then probably nothing further is needed, as I can just set `CMAKE_PREFIX_PATH` permanently (or have some CVC4-specific env vars to use when building CVC4).

> Of course, we could directly build the dependencies within the configure.sh script. This feels wrong, and also does not solve your problem. 

I just remembered that Boolector does this for Google Test -- it is "slightly irritating" when I'm editing something and blasting `build` that it keeps getting re-pulled-down ... I'm sure after a few (and *that* not many), you start getting rate-limited on `https://github.com/google/googletest.git`.

**Comment by mpreiner** [comment]
@andrewvaughanj any update on this?

**Comment by andrewvaughanj** [comment]
@mpreiner 🤦 sorry, life got in the way ... I'll try this tonight.

> An alternative could be to provide an additional cmake project (like we do for examples) that only builds the dependencies in such a way that you would have them installed directly to the build folder. 
>

Would this be something you'd be interested in a PR for? It seems like a really nice solution -- sort of like "setup-all.sh", but driven by CMake.

**Comment by mpreiner** [comment]
For now we decided to have a `--auto` (or similar) flag for configure.sh to automatically download dependencies (off by default) and a `--path` option to specify custom paths to dependencies.

As for the dependencies project: I don't know how many changes this would require to the Find*.cmake scripts we currently use. @nafur opinions? I'm not sure if it is really required since you could once auto download the dependencies with `--auto`, copy the installed dependencies to `foo/deps` and then configure subsequent builds with `--path foo/deps`.

**Comment by nafur** [comment]
As I see it, we would mostly have the "dependencies project" for @andrewvaughanj's use case. I would imagine it to work by invoking all the Find scripts (`find_package`) and then possibly copy the stuff somewhere. I don't think we would need to change the Find scripts in any way.

**Comment by mpreiner** [comment]
Would the dependencies project consider the configuration options passed to configure (to enable/disable specific dependencies)? What's the advantage of having an additional project compared to copying the dependencies from the build directory once?

**Comment by andrewvaughanj** [comment]
> I'm not sure if it is really required since you could once auto download the dependencies with --auto, copy the installed dependencies to foo/deps and then configure subsequent builds with --path foo/deps.
>

This is fine by me ... I don't like the idea of dedicated CVC4^W5 time spent to support my "weird" edge-case.

`./configure.sh --symfpu --auto` ... do the copy ... forever more do `./configure.sh --symfpu --path` ... if now I need GLPK, I can do `./configure.sh --glpk --auto` ... copy into my "old" folder, then start doing `./configure.sh --path`.

Tbf, before this change, I used to have symlink-in my deps folder into the right place, so I was already doing manual steps!

**Comment by nafur** [comment]
I understand that your process still works with a slightly adapted workflow and everyone is fine with it. I thus close this issue.
Just re-open it (or open another issue) if you have any further problems.

**Comment by nafur** [comment]
PS @andrewvaughanj: I have not yet migrated the glpk stuff to an external project. But it will happen at some point as well...
