### ISSUE TITLE
infinite loop in rewriting?

### ISSUE THREAD

**Issue by kanigsson** [CVC4/CVC4#6227]
**Describe the bug**
[repr.smt2.txt](https://github.com/CVC4/CVC4/files/6218775/repr.smt2.txt)

On the attached input file, current master of cvc4 returns immediately with a resource limit set like this:
```
$ cvc4 --rlimit=20000 repr.smt2
unknown
(returns immediately)
```
but runs for a very long time when tweaking resource steps like this:

```
$ cvc4 --rlimit=20000 --rewrite-step=0 repr.smt2
... does not return ...
```

I'm reporting this as it might indicate an infinite loop in the rewrite step. If you think it's expected behavior, please let me know.

I tried to reduce the input file using ddSMT but the tool doesn't handle datatype declarations.

This is with commit 442bc26b6ce093efed14bfd6764dac30bfdf918f.

**Operating system**: Linux 64bit

**`configure.sh` options**

./configure.sh production --symfpu --static --no-debug-symbols --no-proofs --symfpu-dir=/home/kanig/wave/x86_64-linux/cvc4/src/symfpu-CVC4 --antlr-dir=/home/kanig/wave/x86_64-linux/antlr/install --gmp-dir=/home/kanig/wave/x86_64-linux/gmp_bootstrap/install --prefix=/home/kanig/wave/x86_64-linux/cvc4/pkg --no-static-binary

**`configure.sh` output**

-- The C compiler identification is GNU 10.2.1
-- The CXX compiler identification is GNU 10.2.1
-- Check for working C compiler: /home/kanig/wave/x86_64-linux/gcc/install/bin/gcc
-- Check for working C compiler: /home/kanig/wave/x86_64-linux/gcc/install/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /home/kanig/wave/x86_64-linux/gcc/install/bin/g++
-- Check for working CXX compiler: /home/kanig/wave/x86_64-linux/gcc/install/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building Production build
-- Performing Test HAVE_FLAG_O3
-- Performing Test HAVE_FLAG_O3 - Success
-- Configuring with C flag '-O3'
-- Configuring with CXX flag '-O3'
-- Performing Test HAVE_FLAG_Wall
-- Performing Test HAVE_FLAG_Wall - Success
-- Configuring with C flag '-Wall'
-- Configuring with CXX flag '-Wall'
-- Performing Test HAVE_FLAG_Wno_unused_private_field
-- Performing Test HAVE_FLAG_Wno_unused_private_field - Success
-- Configuring with C flag '-Wno-unused-private-field'
-- Configuring with CXX flag '-Wno-unused-private-field'
-- Performing Test HAVE_FLAG_fexceptions
-- Performing Test HAVE_FLAG_fexceptions - Success
-- Configuring with C flag '-fexceptions'
-- Performing Test HAVE_FLAG_Wsuggest_override
-- Performing Test HAVE_FLAG_Wsuggest_override - Success
-- Configuring with CXX flag '-Wsuggest-override'
-- Performing Test HAVE_FLAG_Wnon_virtual_dtor
-- Performing Test HAVE_FLAG_Wnon_virtual_dtor - Success
-- Configuring with CXX flag '-Wnon-virtual-dtor'
-- Performing Test HAVE_FLAG_Wimplicit_fallthrough
-- Performing Test HAVE_FLAG_Wimplicit_fallthrough - Success
-- Configuring with C flag '-Wimplicit-fallthrough'
-- Configuring with CXX flag '-Wimplicit-fallthrough'
-- Performing Test HAVE_FLAG_Wshadow
-- Performing Test HAVE_FLAG_Wshadow - Success
-- Configuring with C flag '-Wshadow'
-- Configuring with CXX flag '-Wshadow'
-- Performing Test HAVE_FLAG_Wno_class_memaccess
-- Performing Test HAVE_FLAG_Wno_class_memaccess - Success
-- Configuring with CXX flag '-Wno-class-memaccess'
-- Using GNU gold linker.
CMake Warning at CMakeLists.txt:280 (message):
  Disabling unit tests since assertions are disabled.

-- Found PythonInterp: /home/kanig/wave/x86_64-linux/cvc4/src/venv/bin/python3 (found suitable version "3.8.3", minimum required is "3") 
-- Found GMP: /home/kanig/wave/x86_64-linux/gmp_bootstrap/install/include  
-- Found GMP libs: /home/kanig/wave/x86_64-linux/gmp_bootstrap/install/lib64/libgmp.a
-- Found SymFPU: /home/kanig/wave/x86_64-linux/cvc4/src/symfpu-CVC4  
-- Performing Test CVC4_NEED_INT64_T_OVERLOADS
-- Performing Test CVC4_NEED_INT64_T_OVERLOADS - Failed
-- Performing Test CVC4_NEED_HASH_UINT64_T_OVERLOAD
-- Performing Test CVC4_NEED_HASH_UINT64_T_OVERLOAD - Failed
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for C++ include ext/stdio_filebuf.h
-- Looking for C++ include ext/stdio_filebuf.h - found
-- Looking for clock_gettime
-- Looking for clock_gettime - found
-- Looking for ffs
-- Looking for ffs - found
-- Looking for optreset
-- Looking for optreset - not found
-- Looking for sigaltstack
-- Looking for sigaltstack - found
-- Looking for strerror_r
-- Looking for strerror_r - found
-- Looking for strtok_r
-- Looking for strtok_r - found
-- Looking for setitimer
-- Looking for setitimer - found
-- Performing Test STRERROR_R_CHAR_P
-- Performing Test STRERROR_R_CHAR_P - Failed
-- Found Git: /usr/bin/git (found version "2.26.2") 
-- Looking for antlr3FileStreamNew
-- Looking for antlr3FileStreamNew - found
-- Found ANTLR: /home/kanig/wave/x86_64-linux/antlr/install/bin/antlr3  
-- Found ANTLR libs: /home/kanig/wave/x86_64-linux/antlr/install/lib/libantlr3c.a
-- Found Java: /home/kanig/wave/x86_64-linux/java-1.6-default-oracle/install/bin/java (found version "1.6.0.23") found components:  Runtime 
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
CVC4 1.9-prerelease

Build profile             : production

GPL                       : off
Best configuration        : off

Assertions                : off
Debug symbols             : off
Debug context mem mgr     : off

Dumping                   : on
Muzzle                    : off
Proofs                    : off
Statistics                : on
Tracing                   : off

ASan                      : off
UBSan                     : off
TSan                      : off
Coverage (gcov)           : off
Profiling (gprof)         : off
Unit tests                : off
Valgrind                  : off

Shared libs               : off
Static binary             : off
Python bindings           : off
Java bindings             : off
Python2                   : off

ABC                       : off
CaDiCaL                   : off
CryptoMiniSat             : off
drat2er                   : off
GLPK                      : off
Kissat                    : off
LFSC                      : off
LibPoly                   : off

Build libcvc4 only        : off
MP library                : gmp
Editline                  : off
SymFPU                    : on

ANTLR dir                 : /home/kanig/wave/x86_64-linux/antlr/install
GMP dir                   : /home/kanig/wave/x86_64-linux/gmp_bootstrap/install
SYMFPU dir                : /home/kanig/wave/x86_64-linux/cvc4/src/symfpu-CVC4

CPPLAGS (-D...)           : NDEBUG CVC4_DUMPING CVC4_STATISTICS_ON CVC4_USE_SYMFPU
CXXFLAGS                  : -O3 -Wall -Wno-unused-private-field -Wsuggest-override -Wnon-virtual-dtor -Wimplicit-fallthrough -Wshadow -Wno-class-memaccess
CFLAGS                    : -O3 -Wall -Wno-unused-private-field -fexceptions -Wimplicit-fallthrough -Wshadow
Linker flags              : -static-libgcc -static-libstdc++ -fuse-ld=gold

Install prefix            : /home/kanig/wave/x86_64-linux/cvc4/pkg

CVC4 license              : modified BSD

Note that this configuration is NOT built against any GPL'ed libraries, so
it is covered by the (modified) BSD license.  This is, however, not the best
performing configuration of CVC4.  To build against GPL'ed libraries which
improve CVC4's performance, re-configure with '-DENABLE_GPL -DENABLE_BEST'.

Now change to 'build' and type 'make', followed by 'make check' or 'make install'.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/kanig/wave/x86_64-linux/cvc4/src/build

**Comment by ajreynol** [comment]
I'm not sure about the use of `--rewrite-step=0` (I'm not familiar with the resource infrastructure).

However, I can say that CVC4 seems to having non-exceptional behavior on this problem.  The quantifiers module is not invoking many instantiations, the bottleneck is non-linear arithmetic, but nothing out of the ordinary is happening.

Perhaps there is some misleading behavior going on with resource limits? @nafur can you take a look?

**Comment by nafur** [comment]
`--rewrite-step=0` essentially disables resource spending for rewrites. By default, this value is set to `1` and we thus spend one resource for every rewriting (even more than once, depending on how rewriting goes: https://github.com/CVC4/CVC4/blob/master/src/theory/rewriter.cpp#L225).

Given the size of the input problem, I wondered what we would expect as the number of resources spent on rewrite steps. Note that rewriting that is an essential procedure for normalization and considered to be pretty cheap. It is thus used "all the time all over the place". On my machine, cvc4 (in debug mode) spends about 28k resources on rewrites within 5 seconds (check the output of `$ bin/cvc4 --tlimit=5000 --stats test.smt2` for `resource::RewriteStep`), the overall resources are about 37k.

**Comment by kanigsson** [comment]
Hello all, thanks for your comments. So I am assuming there is nothing wrong here. I will remove that switch from our use of cvc4 then.
