### ISSUE TITLE
Cvc4 SyGuS does not properly parase parametric datatypes

### ISSUE THREAD

**Issue by bavalpey** [CVC4/CVC4#6298]
**Describe the bug**
Using cvc4's sygus checker with declare-datatypes causes a parse error: unexpected token for parametric datatypes.  Parsing of the same line works with the --lang=smt2 flag.
For instance, the example from the SyGuS language standard causes a parsing error.
`(declare-datatypes (( List 1)) (
(par (T) ((nil) (cons (head T) (tail (List T)))))))`
**Command line arguments**: --lang=sygus2
**CVC4 version/commit**: git master 9d571cb1
**Operating system**: Debian Ubuntu

**Comment by ajreynol** [comment]
Thanks for pointing this out. Previously, we were not parsing `par` in sygus since parametric datatypes were not supported internally.

Initial support for parametric datatypes in sygus is added in #6304.
