### ISSUE TITLE
using CVC4 in OCaml 

### ISSUE THREAD

**Issue by SunBeomSo** [CVC4/CVC4#6310]
I would like to use CVC4 in my OCaml code, but CVC4 currently does not provide apis for OCaml.

Could you provide some suggestions on how to use CVC4 in OCaml?

One option would be generating formulas in smtlib2 format and passing them to CVC4.

One challenge that I expect in this option is, it seems I should write my own parser for parsing models (when the satisfying models are found by CVC4).

There is a repository for OCaml-CVC4 bindings, but it supports only QF_EUF theory:
https://github.com/chsticksel/cvc4-ocaml

**Comment by florianschanda** [comment]
I would strongly suggest you use SMTLIB2 to communicate. It makes everything easier, especially debugging, benchmark generation, etc. Sure some native API might be "faster" but trust me when I say: you'll want to debug your stuff and have a natural way to make benchmarks and reproduce stuff. :)

There is already such a thing written in Ocaml called [Why3](http://why3.lri.fr/); that is used by tools like [SPARK](https://github.com/AdaCore/spark2014) but one of the key problems there is that it's virtually impossible to generate QF problems, which you should if you can.

**Comment by SunBeomSo** [comment]
Thanks for the helpful suggestion and detailed explanation !
