### ISSUE TITLE
Quantified constraints in SyGuS

### ISSUE THREAD

**Issue by remysucre** [CVC4/CVC4#6344]
When experimenting with the sygus support, I found that having quantifiers in the constraints immediately makes synthesis to return unknown. The program below is a trivial synthesis problem where the grammar gives away the solution. Yet with the first constraint present, synthesis immediately returns unknown, whereas if I comment out the constraint the synthesis succeeds. Are there some knobs to turn to make problems like this work? 

```
; COMMAND-LINE: ./cvc4 --lang=sygus2 --uf-ho
(set-logic ALL)
(define-fun mul ((v Int) (u Int)) Int (* v u))

; the grammar gives away the solution
(synth-fun prod ((v Int) (u Int)) Int  ((Sol Int))  ((Sol Int ((* v u)))))
(declare-var v Int)
(declare-var u Int)

; "distance" function; note that `d` is completely
; unrelated to the synthesis problem
(declare-var d (-> Int Int Int))

; triangle inequality. this causes synthesis to
; return unknown
(constraint (forall ((s Int) (t Int) (u Int)) (<= (d s u) (+ (d s t) (d t u)))))

(constraint (= (prod v u) (mul v u)))
(check-synth)
```
cvc4 installed from macOS homebrew tap nightly: 
```
% cvc4 --version
This is CVC4 version 1.9-prerelease [git master ec0daa92]
compiled with GCC version Apple LLVM 12.0.0 (clang-1200.0.32.29)
on Apr 12 2021 22:48:35
```

**Comment by ajreynol** [comment]
Hi, 
The reason why CVC4 returns "unknown" here is because the conjecture is infeasible.
Part of the given conjecture here says that "for functions d, d satisfies the triangle inequality".  This is not the case, in fact, CVC4 is finding a particular `d` that witnesses that this is not the case, hence the entire conjecture is equivalent to false.

Is there a reason for why `d` must be used here?

-Andy

PS I'm going to make CVC4 output warnings when it believes the conjecture is infeasible so issues like this are easier to debug.

**Comment by remysucre** [comment]
> Part of the given conjecture here says that "for functions d, d satisfies the triangle inequality".

Do you mean "forall functions d"?

**Comment by ajreynol** [comment]
Right, for all functions d, ...

FYI I've opened PR https://github.com/CVC4/CVC4/pull/6345 so that we will warn about infeasibility in the future.

**Comment by remysucre** [comment]
I don't see how that's results from the conjecture? In my mind the conjecture is along the line of: 
```
exists prod . forall v u d . (forall ((s Int) (t Int) (u Int)) (<= (d s u) (+ (d s t) (d t u)))) => (= (prod v u) (mul v u))
```
And now typing this out I see the last forall becomes an exists, and the quantifier alternation might be the problem?

**Comment by ajreynol** [comment]
`constraint` adds a new conjunct to the conjecture.  The conjecture is hence:

`exists prod . forall v u d . (and (forall ((s Int) (t Int) (u Int)) (<= (d s u) (+ (d s t) (d t u)))) (= (prod v u) (mul v u)))

For now, you'll need to add the entire implication as a single `(constraint ...)` command. 

Coincidentally, we are planning to add a new command to the SyGuS language soon called `(assume F)`, which would generate a conjecture how you want above, where F is a formula to add to the left hand side of an implication.

**Comment by remysucre** [comment]
Aha, wonderful. Now I'm surprised that this works, given the quantifier alternation. Is that because the underlying CEGIS problem doesn't actually have quantifier alternations?

**Comment by ajreynol** [comment]
For the CEGIS verification subcalls, CVC4 will invoke the SMT solver for whatever logic is given, even if that logic is undecidable (e.g. if the body contains universal quantifiers).

For these use cases, some verification subcalls may be non-terminating, or terminate with "unknown".  In the latter case, the SyGuS solver will block the current solution and continue. In practice, this means that the SyGuS solver may fail to report a real solution even if it encounters it.  Regardless, the SyGuS solver should only terminate with "unknown" if it believes the conjecture is truly infeasible.

**Comment by remysucre** [comment]
I see, thank you very much!
