### ISSUE TITLE
`Unknown` reported for a recursive function LIA query 

### ISSUE THREAD

**Issue by wonhyukchoi** [CVC4/CVC4#6359]
**Describe the bug**
`Unknown` reported for a minor recursive LIA satisfiability query based off a [regression test](https://github.com/CVC4/CVC4/blob/fba1437c772b6733ce678b93b5ef7d95e366c82d/test/regress/regress1/quantifiers/arith-rec-fun.smt2):

```
(set-logic UFLIA)
(define-fun-rec sumr ((x Int)) Int 
    (+ x (ite (> x 0) (sumr (- x 1)) 0)))
(assert (= (sumr 2) 3))
(check-sat)
```
**Command line arguments**: None
**CVC4 version/commit**: [Nightly 23-Mar-2021](http://cvc4.cs.stanford.edu/downloads/builds/x86_64-linux-opt/unstable/)
**Operating system**: `5.9.16-1-MANJARO`, `x86-64`

**Comment by ajreynol** [comment]
Hi, thanks for the benchmark.

In general, showing "sat" in the presence of recursive function definitions is difficult.  By default, CVC4 will not try to answer "sat" when recursive functions are present.

However, You can try the option `--fmf-fun`, which implements techniques from this paper: https://homepage.divms.uiowa.edu/~ajreynol/ijcar16a.pdf.

With this option, CVC4 answers "sat" quickly on the given benchmark.

-Andy

**Comment by wonhyukchoi** [comment]
Hi Andy, thanks for the response.

I guess I should have studied the command-line options more. The benchmark behaves well with `--fmf-fun`.
