### ISSUE TITLE
Large model for string formula

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#6384]
Hi, cvc4 reports an error on the following formula "The model was computed to have strings of length 7523652864. We only allow strings up to length 4294967295".

Is this behavior CVC4-specific, or specified in the SMT-LIB standard? Thanks!
~~~~
(declare-fun str2 () String)
(declare-fun str3 () String)
(push)
(assert (= (str.len str3) (* 3 13 7 13 16 7 13 7 13 16)))
(assert (= 1 (str.to_int str2)))
(check-sat)
~~~~
~~~~
cvc4 -q -i --check-models --strings-exp delta.out.smt2 
(error "The model was computed to have strings of length 7523652864. We only allow strings up to length 4294967295")
Fatal failure within void cvc5::Minisat::Solver::pop() at //CVC4/src/prop/minisat/core/Solver.cc:2135
Check failure

 decisionLevel() == 0

Aborted (core dumped)
~~~~

**Comment by ajreynol** [comment]
This behavior is expected.  In case like this one, it is not possible (or practical) for cvc5 to generate a model with a string of that length.

**Comment by rainoftime** [comment]
Thanks!
