### ISSUE TITLE
Extracting python native values from a model with the new Python API

### ISSUE THREAD

**Issue by drlagos** [CVC4/CVC4#6433]
Dear cvc5 team (congratulations on the new version, well deserved version bump)

I've been playing around with the new Python API in cvc4, and it works relatively well but I'm not sure how to convert the result of a solver.getValue(x) to a native python type.

In the old api there were method like getUnsignedLong() and such, are they still in the new one? They aren't used in the examples.
I need the appropriate extraction method for bools, ints and reals.

Sorry if this is a really obvious question that I just missed the answer...

As a bit of an aside, autocompletion doesn't seem to work in Pycharm for pycvc4.kinds, and that file seems to be generated from the grammar but with different, more pythonic names. It's a bit awkward to have to read the C++ kinds and mentally adapt BOUND_VAR_LIST to BoundVarList and such.

Something to consider for cvc5. I would just go with the C++ names as they are.

**Comment by makaimann** [comment]
Hi @drlagos, I think `term.toPythonObj` should do what you want. Here it is in the source file with some more info in the comment: https://github.com/CVC4/CVC4/blob/642c8b738e6681fe511dfb3610d896d3b67bbd7d/src/api/python/cvc5.pxi#L1553

Better documentation is in the works (thanks to other team members) so hopefully that should be clearer soon.

Let us know if you run into any issues with it!

**Comment by makaimann** [comment]
Regarding the kinds, I can look into the auto completion issue and we’ll take the suggestion on the names into account!

**Comment by drlagos** [comment]
That's exactly what I needed, thank you so much!
