### ISSUE TITLE
Trivial bitvector + UF problem, CVC4 taking too long (Bugzilla #485)

### ISSUE THREAD

**Issue by mpreiner** [CVC4/CVC4#704]
**Imported from Bugzilla**
Reporter: *Levent Erkok*
Status: *NEW*
Severity: *enhancement*
Assigned to: *Clark Barrett*
Component: *Bitvectors*
Milestone: *1.6*
Version: *master*
Platform: *Macintosh*
OS: *Mac OS*

Original attachment names and IDs:
- _[a.smt2](http://cvc4.cs.stanford.edu/bugzilla_attachments/145_a.smt2)_ (SMTLib2 benchmark file, ID 145)

On 2012-12-22 00:26:31 -0800, Levent Erkok wrote:
> Created attachment 145
> SMTLib2 benchmark file
> 
> For the attached benchmark, CVC4 takes really really long (more than I was willing to wait) to respond. It's actually a trivial problem: For instance Z3 responds unsat instantaneously.

On 2015-08-24 07:10:46 -0700, Liana Hadarean wrote:
> There seem to be two things going on. One issue is that because the problem contains only bit\-vector equalities, the bit\-vector core solver is complete and attempts to build a model. Because all 256 possible 8\-bit constant values are in the equality engine, it ends up generating huge cardinality lemmas (i.e. at least two of the equivalence classes are equal). This can be fixed by adding a threshold on lemma size, and deferring to the bit\-blasting sub\-solver if the lemmas exceed this threshold.
> 
> I tried this fix, and it exposes the second problem. Now computing the care graph is what dominates the solve time. I will continue looking into this.

**Comment by ajreynol** [comment]
This is solved in 2 seconds in master.
