### ISSUE TITLE
Review ITE simplification at preprocessing (Bugzilla #530)

### ISSUE THREAD

**Issue by mpreiner** [CVC4/CVC4#749]
**Imported from Bugzilla**
Reporter: *Morgan Deters*
Status: *NEW*
Severity: *enhancement*
Assigned to: *Clark Barrett*
Component: *Miscellaneous*
Milestone: *1.6*
Version: *master*
Platform: *All*
OS: *All*

Original attachment names and IDs:
- _[ite-simp-bug.smt2](http://cvc4.cs.stanford.edu/bugzilla_attachments/190_ite-simp-bug.smt2)_ (Minimized, buggy input for CVC4 *before* commit 663c2df0 ---run with -i, get SAT, without, get UNSAT, ID 190)
- _[ite-simp-bug.handminimized.smt2](http://cvc4.cs.stanford.edu/bugzilla_attachments/191_ite-simp-bug.handminimized.smt2)_ (Better, further-hand-minimized attachment, ID 191)

On 2013-08-21 19:12:28 -0700, Morgan Deters wrote:
> Created attachment 190
> Minimized, buggy input for CVC4 \*before\* commit 663c2df0 \-\-\-run with \-i, get SAT, without, get UNSAT
> 
> Commit 663c2df0 (on August 8) contained a one\-line change that changed the applicability of ITE simplification at preprocessing time: specifically, it no longer applies after realAssertionsEnd.  Prior to the commit, and including releases 1.0, 1.1, and 1.2, the following was happening:
> 
> ITE simplification bug
> 
> 1. A term\-level ITE is identified and removed, replaced with a termITE. A new Boolean ITE is put in the assertions list, after d\_realAssertionsEnd, to constrain it.
> 
> 2. If "incremental" is on, the term substitution (termITE \=\=> (ite ....)) is added as a new assertion (before d\_realAssertionsEnd), so that the rest of the system will see it.
> 
> 3. Repeated simplification runs. This new assertion is picked up as a top\-level substitution (that is, termITE rewrites\-to (ite ...))
> 
> 4. The assertions that had termITE in them are now replaced with the (ite ...) expansion, since that's a top\-level substitution.
> 
> 5. The termITE assertion (after d\_realAssertionsEnd) now becomes TRUE after substitution.
> 
> 6. The (ite...) terms are again replaced with termITE when ITE removal runs. It's cached, so the assertions about termITE (now simplified away) aren't made again.
> 
> Again, the solution was to \*not\* do ITE simplification after d\_realAssertionsEnd.  You can see the diff with "git show 663c2df0".
> 
> Another way to fix the bug was to remove this bit of code from the SmtEngine:
> 
>       // For some reason this is needed for some benchmarks, such as
>       // http://church.cims.nyu.edu/benchmarks/smtlib2/QF_AUFBV/dwp_formulas/try5_small_difret_functions_dwp_tac.re_node_set_remove_at.il.dwp.smt2
>       // Figure it out later
>       removeITEs();
> 
> ...but that has other consequences.  Perhaps this is the core issue behind the bug though.

On 2013-08-21 19:18:27 -0700, Morgan Deters wrote:
> Created attachment 191
> Better, further\-hand\-minimized attachment
> 
> Another minimized attachment (the new ddsmt tool doesn't try substituting (\=> true \phi) to \phi, etc.
> 
> This version of the input is hand\-minimized to remove some of that garbage.
> 
> Again, run with \-i gets sat
> Without \-i gets unsat.
> (the incremental flag just turns on one of the features that leads to this bug, but the unsat\=>sat transition occurs in the ITE simplifications).
> 
> In debug builds, you may see a model\-building assert\-fail rather than a wrong answer.

**Comment by 4tXJ7f** [comment]
With a recent build this issue also does not appear but I'd like to understand better what's the problem here.

**Comment by mpreiner** [comment]
It seems that this issue is not reproducible in the current state. I'll close the issue for now. @4tXJ7f feel free to open it again once you revisit it.
