### ISSUE TITLE
Regression 2143275 broken (normalized-j12058_4-sat.smt2) empty => empty (Bugzilla #564)

### ISSUE THREAD

**Issue by mpreiner** [CVC4/CVC4#783]
**Imported from Bugzilla**
Reporter: *Tim King*
Status: *NEW*
Severity: *normal*
Assigned to: *Tim King*
Component: *Arithmetic*
Milestone: *1.6*
Version: *master*
Platform: *PC*
OS: *Linux*

On 2014-05-12 11:03:45 -0700, Tim King wrote nothing.

**Comment by ajreynol** [comment]
I'm not sure what regression this is referring to. Perhaps this can be closed?

**Comment by barrettcw** [comment]
This seems to be a benchmark in QF_LIA/pb2010.  My guess is that it is broken with some flags on (maybe the pseudo-Boolean flag?)
