### ISSUE TITLE
unsound result (Bugzilla #569)

### ISSUE THREAD

**Issue by mpreiner** [CVC4/CVC4#788]
**Imported from Bugzilla**
Reporter: *Liana Hadarean*
Status: *NEW*
Severity: *enhancement*
Assigned to: *Clark Barrett*
Component: *{Internals} Shared terms/theory combination*
Milestone: *1.6*
Version: *master*
Platform: *PC*
OS: *Linux*

Original attachment names and IDs:
- _[arith.smt2](http://cvc4.cs.stanford.edu/bugzilla_attachments/226_arith.smt2)_ (Input that causes bug, ID 226)
- _[subtype_eq.patch](http://cvc4.cs.stanford.edu/bugzilla_attachments/227_subtype_eq.patch)_ (subtype patch, ID 227)

On 2014-06-04 16:02:16 -0700, Liana Hadarean wrote:
> On the attached .smt2 problem cvc4 returns sat, when the problem is unsat. It passes \-\-check\-models but crashes when (get\-model) is called because a variable of type Int is assigned a Real value.

On 2014-06-04 16:02:43 -0700, Liana Hadarean wrote:
> Created attachment 226
> Input that causes bug

On 2014-06-05 20:28:45 -0700, Tim King wrote:
> This is a sharing infrastructure problem. The atom (\= v1 (\+ v3 v5)) is sent to the theory of arrays. Arithmetic is never notified of the equality.
> 
> Here is the output of \-d theory::assertions.
> 
> Assertions of THEORY\_ARITH: 
> (0): (not (>\= v5 1))
> (1): (not (>\= (\* (\- 1) v5) 0))
> Shared terms of THEORY\_ARITH: 
> [0]: v5
> [1]: v3
> [2]: (\+ v3 v5)
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> Assertions of THEORY\_ARRAY: 
> [0]: (\= v1 (\+ v3 v5))
> Shared terms of THEORY\_ARRAY: 
> [0]: v5
> [1]: v3
> [2]: (\+ v3 v5)
> 
> 
> I am CC'ing sharing infrastructure people. I'll continue to dig on this.

On 2014-06-05 20:59:00 -0700, Tim King wrote:
> I have confirmed that the set d\_sharedTerms in TheoryArrays contains  v3, v5 and (\+ v3 v5) and that arrays does not split shared terms that are in d\_sharedOther. The resulting care graph is empty and TheoryEngine::combineTheories() ends without splitting anything.
> 
> I still have not confirmed why arrays is being sent these terms.

On 2014-06-05 21:07:05 -0700, Dejan Jovanovic wrote:
> (In reply to comment \# 2)
> > Assertions of THEORY\_ARITH: 
> > (0): (not (>\= v5 1))
> > (1): (not (>\= (\* (\- 1) v5) 0))
> > Shared terms of THEORY\_ARITH: 
> > [0]: v5
> > [1]: v3
> > [2]: (\+ v3 v5)
> > \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> > Assertions of THEORY\_ARRAY: 
> > [0]: (\= v1 (\+ v3 v5))
> > Shared terms of THEORY\_ARRAY: 
> > [0]: v5
> > [1]: v3
> > [2]: (\+ v3 v5)
> 
> This is a horrible problem. 
> 
> Basically, the broken assumption here seems to be: if you have 
> 
>   v1 \= v3 \+ v5
> 
> then for any values of v3 and v5 you can assign v1 a value. 
> 
> Here this is not the case because it's mixed integer real (v1, v3 int, v5 real).

On 2014-06-05 21:11:10 -0700, Dejan Jovanovic wrote:
> > Basically, the broken assumption here seems to be: if you have 
> >   v1 \= v3 \+ v5
> > then for any values of v3 and v5 you can assign v1 a value. 
> > Here this is not the case because it's mixed integer real (v1, v3 int, v5
> > real).
> 
> I think this might go away if you always solve mixed equalities by the real variables, i.e. in this case
> 
>   v5 \= v1 \- v3

On 2014-06-05 22:59:07 -0700, Tim King wrote:
> (In reply to comment \# 5)
> > I think this might go away if you always solve mixed equalities by the real
> > variables, i.e. in this case
> > 
> >   v5 \= v1 \- v3
> 
> This is supposed to be happening. I am surprised it does not. I can fix this bug.  It should solve this (and then trigger Andrew's infinite loop, but which I still need to fix). I am not sure if this really solves the larger problem though.

On 2014-06-05 23:20:39 -0700, Dejan Jovanovic wrote:
> > I still need to fix). I am not sure if this really solves the larger problem
> > though.
> 
> There is (almost) no symptoms of a larger issue here. 
> 
> As far as arrays are concerned, v1 is just a variable, and it's not shared since it doesn't appear in any arithmetic constraints. As long as the other side of the equality, i.e. (v3 \+ v5), which is a shared term, get's interpreted correctly, arrays take v1 to be the same value. Well, this is where it breaks because (v3 \+ v5) can be assigned to a non\-integer value.
> 
> If you make arithmetic always solve for the reals, then this is never an issue for combination with arithmetic. Otherwise, we have to make another exception in the theoryOf for equalities to make them belong to arithmetic if they are equating an integer term to a real term.
> 
> In general, for any theory theory that covers equalities among possible subtypes the same issue will pop up.

On 2014-06-06 00:19:48 -0700, Clark Barrett wrote:
> I see the problem.  Our algorithm for assigning equalities to theories assumes that if a variable occurs alone on either side of the equality, then it can go to any theory.  This is true unless subsorts get involved.  So, our choices are
> 
> 1) modify theoryof to account for this case
> 2) ensure that a subsort variable never appears alone on one side of an equality, set equal to a supersort on the other side.
> 
> It's easy to ensure (2) for linear arithmetic.  It may be trickier for other theories, but it seems like it should be doable.
> 
> I'm OK with (2) as long as we add some assertions that will catch it in case we miss it sometime later.

On 2014-06-06 10:26:49 -0700, Tim King wrote:
> (In reply to comment \# 8)
> > 1) modify theoryof to account for this case
> > 2) ensure that a subsort variable never appears alone on one side of an
> > equality, set equal to a supersort on the other side.
> 
> I believe that we need to do both (1) and (2) to ensure that  the owner of the supersort rewrites mismatches. If arrays is the rewriter for the equality (\= v1 (\+ v3 v5)) then nothing would happen.

On 2014-06-06 11:45:23 -0700, Tim King wrote:
> Created attachment 227
> subtype patch
> 
> Here is my proposed solution for the subtyping bug.  On equalities with disequal types with the theory of mode defaulting to the term based model, default to the theory of the left type as it must be a subtyping relation (if it is properly typed).

On 2014-06-06 14:49:01 -0700, Tim King wrote:
> I am now sitting on a fix the normal form part as well.  Clark and Dejan, can one of you please approve the patch to theoryOf?  Once I get a thumbs up, I'll commit both.

On 2014-06-06 15:39:06 -0700, Clark Barrett wrote:
> (In reply to comment \# 11)
> 
> Hey Tim \- this looks almost right but I think the check for different types should come \*before\* the check to see if both are the same theory.  Otherwise, you could have an equation x \= y where x is Integer and y is Real.  According to term\-based theoryOf, both x and y belong to the uninterpreted owner, so this equation would go there instead of to arithmetic, even though x and y are of different types.  In this case, I'm not sure if it's a problem but it worries me enough that I think we should play it safe.
> 
> It makes good sense to send equations like this based on their type.  If subtyping is involved, the only theory that can make sense of what is going on is the theory that owns those types.

On 2015-08-19 13:00:59 -0700, Clark Barrett wrote:
> To review:
> https://github.com/CVC4/CVC4/commit/6ec8f46

**Comment by 4tXJ7f** [comment]
I tested this with a recent build and the bug seems fixed. Closing the issue.
