### ISSUE TITLE
Cyclic substitution produced by Arith ITE utils

### ISSUE THREAD

**Issue by mpreiner** [CVC4/CVC4#789]
**Imported from Bugzilla**
Reporter: *Morgan Deters*
Status: *NEW*
Severity: *normal*
Assigned to: *Clark Barrett*
Component: *Miscellaneous*
Milestone: *1.6*
Version: *master*
Platform: *PC*
OS: *Linux*

Original attachment names and IDs:
- _[memory.smt2](http://cvc4.cs.stanford.edu/bugzilla_attachments/230_memory.smt2)_ (memory hog, ID 230)

On 2014-06-20 20:52:38 -0700, Morgan Deters wrote:
> Created attachment 230
> memory hog
> 
> Attached testcase eats gigs and gigs of memory really quickly.  Investigate.

On 2014-06-20 21:07:34 -0700, Morgan Deters wrote:
> Derived from a scrambling of 20\-vars/cut\_lemma\_01\_006.smt2.

**Comment by ajreynol** [comment]
This is related to --ite-simp.  The arithmetic ITE utility is generating a cyclic substitution which is causing the SubstitutionMap to infinite loop.
