### ISSUE TITLE
--continued-execution doesn't work when reading from file (Bugzilla #573)

### ISSUE THREAD

**Issue by mpreiner** [CVC4/CVC4#792]
**Imported from Bugzilla**
Reporter: *Morgan Deters*
Status: *NEW*
Severity: *normal*
Assigned to: *Clark Barrett*
Component: *Miscellaneous*
Milestone: *1.6*
Version: *master*
Platform: *All*
OS: *All*

Original attachment names and IDs:
- _[x.smt2](http://cvc4.cs.stanford.edu/bugzilla_attachments/232_x.smt2)_ (example input, ID 232)

On 2014-06-25 23:07:13 -0700, Morgan Deters wrote:
> Created attachment 232
> example input
> 
> When redirected from stdin, \-\-continued\-execution works fine.  When directly from a file, though, it doesn't work.  E.g.:
> 
> [mdeters_@church cvc4 master (1)]$ builds/bin/cvc4  \-L smt2 \-\-continued\-execution x.smt2
> sat
> ((x 0) (y 0))
> unsat
> [mdeters_@church cvc4 master (1)]$ 
> 
> 
> but with stdin it goes one command further:
> 
> [mdeters_@church cvc4 master (1)]$ builds/bin/cvc4  \-L smt2 \-\-continued\-execution < x.smt2
> sat
> ((x 0) (y 0))
> unsat
> unsat
> 
> [mdeters_@church cvc4 master (1)]$

On 2014-06-26 00:44:21 -0700, Kshitij wrote:
> Not sure we support this. We added for when input was getting piped in for a specific user (if you remember the discussion), we didn't add support for file input. I am surprised it doesn't print any errors, just exits with non\-zero exit status.
> 
> I looked at the code, basically to support files we can switch to using InteractiveShell class. But InteractiveShell defaults to reading from standard input, no way pass file as an argument. Thoughts?

On 2014-06-26 00:54:11 -0700, Morgan Deters wrote:
> Potential fix as a pull request \-  https://github.com/CVC4/CVC4/pull/4

On 2014-06-26 01:45:47 -0700, Morgan Deters wrote:
> I'm still not entirely comfortable reading files with the interactive
> shell.  Can't we catch certain parse errors (such as undefined variable, or
> type error) and continue, and other parse errors (mismatched parens) and
> just give the necessary cascade of failures that follows?  I don't see why
> continued\-execution should require us to magically figure out how to parse
> beyond syntactically bad input.
> 
> In interactive mode (from stdin with a user sitting at a terminal) of
> course it makes sense\-\-\-they're learning the syntactic guidelines with
> trial and error.  But the common errors in scripts that you want
> continued\-execution from are things like undefined\-var,
> can't\-get\-proof\-because\-answer\-was\-sat, etc.

On 2014-06-26 15:52:33 -0700, Morgan Deters wrote:
> Partially addressed by 4746a04, now in master.
> 
> Parsing errors (and typing errors in debug builds I guess?) are still an issue.  Perhaps we can wrap the "nextCommand()" calls in a try { } catch and in continued\-execution mode at least \*try\* to recover, even if it's a recovery attempt without any smarts?  This should work for e.g. typing violations.  Others may leave the parser in a bad state.

On 2014-06-26 15:59:18 -0700, Kshitij wrote:
> I agree. If we are going to have \-\-continued\-execution more widely used and publicized, we don't want users to see sudden performance changes (which would happen currently in case of piping it in).
> 
> As for what parser errors to handle, I don't think magically figuring out mismatched parentheses should be the aim. The aim should be continue on other errors like : number of operators incorrect, undefined symbol etc.
> 
> Perhaps we can make parser make use of the continuedExecution option and try parsing next command instead of "throwing" an error? Don't know how well parser will resume parsing from arbitrary point though.
> 
> For SMTLIB2 perhaps what should happen is to jump to next outermost parentheses.

**Comment by aniemetz** [comment]
We decided in the team meeting today that we will not support this option anymore.  We will remove this option.
