### ISSUE TITLE
Should verify --bv-aig-simp string (Bugzilla #584)

### ISSUE THREAD

**Issue by mpreiner** [CVC4/CVC4#803]
**Imported from Bugzilla**
Reporter: *Morgan Deters*
Status: *NEW*
Severity: *enhancement*
Assigned to: *Clark Barrett*
Component: *Bitvectors*
Milestone: *1.6*
Version: *1.4 release*
Platform: *All*
OS: *All*

On 2014-09-27 12:43:28 -0700, Morgan Deters wrote:
> Any string is permitted with \-\-bv\-aig\-simp.  This behavior should be re\-evaluated, since e.g.:
> 
>   cvc4 \-\-bv\-aig\-simp \-\-some\-other\-important\-option foo.smt2
> 
> will completely "eat" \-\-some\-other\-important\-option, which is clearly what's not intended here.

**Comment by 4tXJ7f** [comment]
Just tested, this is still an issue. I would suggest that for string options, we only accept `--foo=X`-style arguments. What do you think?

**Comment by mpreiner** [comment]
How about we only allow `--long-option=<value>` for long options?

**Comment by 4tXJ7f** [comment]
I would be fine with that.
