### ISSUE TITLE
Approx solver violating an assertion (Bugzilla #624)

### ISSUE THREAD

**Issue by mpreiner** [CVC4/CVC4#843]
**Imported from Bugzilla**
Reporter: *Tim King*
Status: *NEW*
Severity: *normal*
Assigned to: *Tim King*
Component: *Arithmetic*
Milestone: *1.6*
Version: *master*
Platform: *PC*
OS: *Linux*

On 2015-04-19 11:57:24 -0700, Tim King wrote:
> There are 4 QF\_LIA examples with failing assertions. The star exec job is 7007.
> 
> normalized\-j1208\_10\-unsat.smt2	cvc4.rp.debug.1c0b804 attempt 2	cvc4\_rp\_debug\_1c0b804\_approx	complete (7)	648.71 s	starexec\-unknown
> normalized\-j6013\_2\-unsat.smt2	cvc4.rp.debug.1c0b804 attempt 2	cvc4\_rp\_debug\_1c0b804\_approx	complete (7)	358.85 s	starexec\-unknown
> normalized\-j9035\_1\-unsat.smt2	cvc4.rp.debug.1c0b804 attempt 2	cvc4\_rp\_debug\_1c0b804\_approx	complete (7)	423.38 s	starexec\-unknown
> prime\_cone\_unsat\_10.smt2	cvc4.rp.debug.1c0b804 attempt 2	cvc4\_rp\_debug\_1c0b804\_approx	complete (7)	0.51 s	starexec\-unknown
> 
> 
> This should occur on CVC4's master 174e038. This occurs on the configuration.
> \#!/bin/sh
> ./cvc4.debug.rp.1c0b804 \
>     \-\-enable\-miplib\-trick \-\-miplib\-trick\-subs\=4 \-\-use\-approx \
>     \-\-lemmas\-on\-replay\-failure \-\-replay\-early\-close\-depth\=4 \
>     \-\-replay\-lemma\-reject\-cut\=128 \-\-replay\-reject\-cut\=512 \-\-unconstrained\-simp \-\-use\-soi $1
> 
> 
> There are two different assertion failures:
> 
> For prime\_cone\_unsat\_10.smt2
> 
> 0.00/0.50	
> 0.00/0.50	CVC4 threw an "unexpected" exception (one that wasn't properly specified
> 0.00/0.50	in the throws() specifier for the throwing function).
> 0.00/0.50	
> 0.00/0.50	The exception is:
> 0.00/0.50	Assertion failure.
> 0.00/0.50	void CVC4::theory::arith::Constraint::impliedByIntHole(const ConstraintCPVec&, bool)
> 0.00/0.50	/home/king/ws/cvc4/tk/builds/x86\_64\-unknown\-linux\-gnu/debug\-glpk\-staticbinary\-proof/../../../src/theory/arith/constraint.cpp:1278:
> 0.00/0.50	
> 0.00/0.50	  !hasProof()
> 0.00/0.50	
> 0.00/0.50	
> 0.00/0.50	terminate called after throwing an instance of 'CVC4::AssertionException'
> 0.00/0.50	  what():  Assertion failure.
> 0.00/0.50	void CVC4::theory::arith::Constraint::impliedByIntHole(const ConstraintCPVec&, bool)
> 0.00/0.50	/home/king/ws/cvc4/tk/builds/x86\_64\-unknown\-linux\-gnu/debug\-glpk\-staticbinary\-proof/../../../src/theory/arith/constraint.cpp:1278:
> 0.00/0.50	
> 0.00/0.50	  !hasProof()
> 0.00/0.50	
> 0.00/0.51	/export/starexec/sandbox/solver/bin/starexec\_run\_cvc4\_rp\_debug\_1c0b804\_approx: line 5: 16062 Aborted                 (core dumped) ./cvc4.debug.rp.1c0b804 \-\-enable\-miplib\-trick \-\-miplib\-trick\-subs\=4 \-\-use\-approx \-\-lemmas\-on\-replay\-failure \-\-replay\-early\-close\-depth\=4 \-\-replay\-lemma\-reject\-cut\=128 \-\-replay\-reject\-cut\=512 \-\-unconstrained\-simp \-\-use\-soi $1
> 0.00/0.51	EOF
> 
> For the rest:
> 358.40/358.34	
> 358.40/358.34	CVC4 threw an "unexpected" exception (one that wasn't properly specified
> 358.40/358.34	in the throws() specifier for the throwing function).
> 358.40/358.34	
> 358.40/358.34	The exception is:
> 358.40/358.34	Assertion failure.
> 358.40/358.34	void CVC4::theory::arith::TheoryArithPrivate::check(CVC4::theory::Theory::Effort)
> 358.40/358.34	/home/king/ws/cvc4/tk/builds/x86\_64\-unknown\-linux\-gnu/debug\-glpk\-staticbinary\-proof/../../../src/theory/arith/theory\_arith\_private.cpp:3551:
> 358.40/358.34	
> 358.40/358.34	  !Theory::fullEffort(effortLevel)
> 358.40/358.34	
> 358.40/358.34	
> 358.40/358.34	terminate called after throwing an instance of 'CVC4::AssertionException'
> 358.40/358.34	  what():  Assertion failure.
> 358.40/358.34	void CVC4::theory::arith::TheoryArithPrivate::check(CVC4::theory::Theory::Effort)
> 358.40/358.34	/home/king/ws/cvc4/tk/builds/x86\_64\-unknown\-linux\-gnu/debug\-glpk\-staticbinary\-proof/../../../src/theory/arith/theory\_arith\_private.cpp:3551:
> 358.40/358.34	
> 358.40/358.34	  !Theory::fullEffort(effortLevel)
> 358.40/358.34	
> 358.90/358.84	/export/starexec/sandbox2/solver/bin/starexec\_run\_cvc4\_rp\_debug\_1c0b804\_approx: line 5: 31832 Aborted                 (core dumped) ./cvc4.debug.rp.1c0b804 \-\-enable\-miplib\-trick \-\-miplib\-trick\-subs\=4 \-\-use\-approx \-\-lemmas\-on\-replay\-failure \-\-replay\-early\-close\-depth\=4 \-\-replay\-lemma\-reject\-cut\=128 \-\-replay\-reject\-cut\=512 \-\-unconstrained\-simp \-\-use\-soi $1
> 358.90/358.84	EOF

On 2015-08-26 15:17:55 -0700, Clark Barrett wrote:
> Need to verify whether this is still an issue

**Comment by nafur** [comment]
```
$ time bin/cvc4 --miplib-trick --miplib-trick-subs=4 --use-approx --lemmas-on-replay-failure --replay-early-close-depth=4 --replay-lemma-reject-cut=128 --replay-reject-cut=512 --unconstrained-simp --use-soi prime_cone_unsat_10.smt2 
unsat

real	0m0,078s
user	0m0,070s
sys	0m0,008s
```
All the other examples run way longer than they needed to trigger the error:
```
$ time bin/cvc4 --miplib-trick --miplib-trick-subs=4 --use-approx --lemmas-on-replay-failure --replay-early-close-depth=4 --replay-lemma-reject-cut=128 --replay-reject-cut=512 --unconstrained-simp --use-soi normalized-j6013_2-unsat.smt2 
^CCVC4 interrupted by user.
Aborted (core dumped)

real	31m5,905s
user	31m2,723s
sys	0m0,736s
```
```
$ time bin/cvc4 --miplib-trick --miplib-trick-subs=4 --use-approx --lemmas-on-replay-failure --replay-early-close-depth=4 --replay-lemma-reject-cut=128 --replay-reject-cut=512 --unconstrained-simp --use-soi normalized-j9035_1-unsat.smt2 
^CCVC4 interrupted by user.
Aborted (core dumped)

real	24m40,078s
user	24m36,666s
sys	0m1,115s
```
```
$ time bin/cvc4 --miplib-trick --miplib-trick-subs=4 --use-approx --lemmas-on-replay-failure --replay-early-close-depth=4 --replay-lemma-reject-cut=128 --replay-reject-cut=512 --unconstrained-simp --use-soi normalized-j1208_10-unsat.smt2 
^CCVC4 interrupted by user.
Aborted (core dumped)

real	25m10,838s
user	25m7,865s
sys	0m0,838s
```
All this is on a rather new Ryzen 5 2600 at 3.4GHz. I thus consider these issues fixed and close this issue.
