### ISSUE TITLE
Models do not work with --tear-down-incremental (Bugzilla #628)

### ISSUE THREAD

**Issue by mpreiner** [CVC4/CVC4#847]
**Imported from Bugzilla**
Reporter: *Andrew Reynolds*
Status: *NEW*
Severity: *enhancement*
Assigned to: *Clark Barrett*
Component: *Models and counterexamples*
Milestone: *1.6*
Version: *master*
Platform: *PC*
OS: *Linux*

Original attachment names and IDs:
- _[test2.smt2](http://cvc4.cs.stanford.edu/bugzilla_attachments/276_test2.smt2)_ (failing benchmark, ID 276)

On 2015-05-12 10:42:50 -0700, Andrew Reynolds wrote:
> Created attachment 276
> failing benchmark
> 
> Running the latest cvc4 (12\-May\-20150 with options:
> 
> \-q \-\-produce\-models \-\-no\-incremental \-\-tear\-down\-incremental \-\-lang smt \-\-print\-success \-\-dt\-rewrite\-error\-sel
> 
> On the attachment gives:
> 
> success
> success
> success
> success
> success
> success
> success
> success
> success
> unsat
> success
> success
> success
> sat
> (model
> )
> 
> Where notice the model is empty.  It seems the models for any benchmark are empty when the option \-\-tear\-down\-incremental is used.
> 
> \-Andy

On 2015-08-19 13:52:51 -0700, Clark Barrett wrote:
> For now, we don't support model building in tear\-down\-incremental but would be nice to have some day.

**Comment by 4tXJ7f** [comment]
In the long run, we would like to get rid of --tear-down-incremental, so it is not worth fixing this. I am creating a new issue to output an error when model production and --tear-down-incremental are both used.
