### ISSUE TITLE
miplib segfaults (Bugzilla #640)

### ISSUE THREAD

**Issue by mpreiner** [CVC4/CVC4#859]
**Imported from Bugzilla**
Reporter: *Tim King*
Status: *NEW*
Severity: *major*
Assigned to: *Tim King*
Component: *Arithmetic*
Milestone: *1.6*
Version: *master*
Platform: *PC*
OS: *Linux*

On 2015-06-13 09:14:04 -0700, Tim King wrote:
> Job:
> 
> https://www.starexec.org/starexec/secure/details/job.jsp?id=7435
> 
> Failing output:
> 
> 
> ./Job7435\_output/QF\_arith/QF\_LRA/miplib/CVC4\-2015\-06\-05\-8f5698e\-main\_\_\_default/danoint\-66.smt2/95759080.txt:42.41/42.45	CVC4 suffered a segfault.
> ./Job7435\_output/QF\_arith/QF\_LRA/miplib/CVC4\-2015\-06\-05\-8f5698e\-main\_\_\_default/danoint\-66.smt2/95759080.txt:42.41/42.45	Offending address is 0x40846d31c
> ./Job7435\_output/QF\_arith/QF\_LRA/miplib/CVC4\-2015\-06\-05\-8f5698e\-main\_\_\_default/danoint\-65.smt2/95759078.txt:46.11/46.14	CVC4 suffered a segfault.
> ./Job7435\_output/QF\_arith/QF\_LRA/miplib/CVC4\-2015\-06\-05\-8f5698e\-main\_\_\_default/danoint\-65.smt2/95759078.txt:46.11/46.14	Offending address is 0x403ccba6c
> ./Job7435\_output/QF\_arith/QF\_LRA/miplib/CVC4\-2015\-06\-05\-8f5698e\-main\_\_\_default/fixnet\-3983.smt2/95759086.txt:42.20/42.20	CVC4 suffered a segfault.
> ./Job7435\_output/QF\_arith/QF\_LRA/miplib/CVC4\-2015\-06\-05\-8f5698e\-main\_\_\_default/fixnet\-3983.smt2/95759086.txt:42.20/42.20	Offending address is 0x3fffffffc
> ./Job7435\_output/QF\_arith/QF\_LRA/miplib/CVC4\-2015\-06\-05\-8f5698e\-main\_\_\_default/pp08a\-7349.smt2/95759136.txt:4.40/4.49	CVC4 suffered a segfault.
> ./Job7435\_output/QF\_arith/QF\_LRA/miplib/CVC4\-2015\-06\-05\-8f5698e\-main\_\_\_default/pp08a\-7349.smt2/95759136.txt:4.40/4.49	Offending address is 0x3fffffffc

On 2015-08-26 15:27:32 -0700, Clark Barrett wrote:
> Need to verify whether still fails

**Comment by nafur** [comment]
On current master, none of these instances segfault: all time out after two minutes on the cluster.
Apparently, this has been fixed in the meantime.
