### ISSUE TITLE
Quantifiers API example (Bugzilla #678)

### ISSUE THREAD

**Issue by mpreiner** [CVC4/CVC4#897]
**Imported from Bugzilla**
Reporter: *Kshitij*
Status: *NEW*
Severity: *enhancement*
Assigned to: *Andrew Reynolds*
Component: *Quantifiers*
Milestone: *1.6*
Version: *master*
Platform: *All*
OS: *All*

On 2015-10-01 22:16:10 -0700, Kshitij wrote nothing.

**Comment by ajreynol** [comment]
This is fixed in https://github.com/CVC4/CVC4/commit/4a4c0806ef75254f0344978bdfba0f077a1e663a
