### ISSUE TITLE
proof changing search (Bugzilla #680)

### ISSUE THREAD

**Issue by mpreiner** [CVC4/CVC4#899]
**Imported from Bugzilla**
Reporter: *Kshitij*
Status: *NEW*
Severity: *minor*
Assigned to: *Clark Barrett*
Component: *Proofs*
Milestone: *1.6*
Version: *master*
Platform: *PC*
OS: *Linux*

On 2015-10-07 18:00:31 -0700, Kshitij wrote:
> Wanted a bug to point to from the wiki, so creating this...
> 
> Liana says:
> 
> 
> cvc4\-e00d64b2\-proof default (cvc)  vs  cvc4\-e00d64b2\-proof proof
> (cvcProof)
> 
> 
> CONFIRMED PROBLEMS:
> 
> default is slower: 150 seconds vs 96 in proof build and search goes differently
> 
> 0.47246705831  
> UFLIA/grasshopper/instantiated/difference\_postcondition\_of\_difference\_38\_8.smt2
>                 (result: unsat,  status: complete,  cpu\_time: 236.154,  wall\_time: 236.099)
>                 (result: unsat,  status: complete,  cpu\_time: 124.542,  wall\_time: 124.55)

**Comment by ajreynol** [comment]
Since we enabled proof builds by default, I don't think this is relevant anymore.
