### ISSUE TITLE
Incremental problem not solved (Bugzilla #689)

### ISSUE THREAD

**Issue by mpreiner** [CVC4/CVC4#908]
**Imported from Bugzilla**
Reporter: *Pierre van de Laar*
Status: *NEW*
Severity: *enhancement*
Assigned to: *Clark Barrett*
Component: *{Internals} Incrementality*
Milestone: *1.6*
Version: *master*
Platform: *PC*
OS: *Windows*

Original attachment names and IDs:
- _[20151105issue.smt2](http://cvc4.cs.stanford.edu/bugzilla_attachments/334_20151105issue.smt2)_ (SMT2 file that is no solved incrementally, ID 334)

On 2015-11-05 06:17:59 -0800, Pierre van de Laar wrote:
> running the attached smt\-document on windows (Microsoft Windows [Version 6.1.7601])
> as follows:
> cvc4\-2015\-11\-03\-win32\-opt.exe \-\-lang\=smt \-\-incremental \-\-strings\-exp \-\-fmf\-fun\-rlv \-\-uf\-ss\-fair 20151105issue.smt2
> produces no output for the second step in 15 minutes on my PC.
> 
> Yet, running it as follows:
> cvc4\-2015\-11\-03\-win32\-opt.exe \-\-lang\=smt \-\-tear\-down\-incremental \-\-strings\-exp \-\-fmf\-fun\-rlv \-\-uf\-ss\-fair 20151105issue.smt2
> produces output within a minute.

On 2015-11-05 06:18:47 -0800, Pierre van de Laar wrote:
> Created attachment 334
> SMT2 file that is no solved incrementally

**Comment by ajreynol** [comment]
This is solved in 20 seconds on latest master. I checked https://github.com/CVC4/CVC4/commit/1823d6d537a59d85a17f09f53c8128d934c420a3 and it solved, although I'm not sure the cause of what commit solved this issue.
