### ISSUE TITLE
Poor incremental solving (Bugzilla #690)

### ISSUE THREAD

**Issue by mpreiner** [CVC4/CVC4#909]
**Imported from Bugzilla**
Reporter: *John Backes*
Status: *NEW*
Severity: *normal*
Assigned to: *Clark Barrett*
Component: *{Internals} Incrementality*
Milestone: *1.6*
Version: *master*
Platform: *PC*
OS: *Linux*

Original attachment names and IDs:
- _[example_incr.smt2](http://cvc4.cs.stanford.edu/bugzilla_attachments/335_example_incr.smt2)_ (I cannot remember if I attached this with the original bug..., ID 335)

On 2015-11-11 11:49:51 -0800, John Backes wrote:
> I found another example that seems to have poor performance during incremental solving. A counterexample exists for this example. I'm using just the \-\-fmf\-fun flag.  In the attached example the first two quieries are solved immediately, while the last query hangs. If you remove the pushes and pops (and the assertions and check\-sats in between) the last query is solved immediately.
> 
> \- John

On 2015-11-11 13:13:58 -0800, John Backes wrote:
> Created attachment 335
> I cannot remember if I attached this with the original bug...

**Comment by ajreynol** [comment]
Appears to be solved in current master (checked https://github.com/CVC4/CVC4/commit/406bcd32cbf8a1ee48af02fc6cddc618158762f0).
Closing this issue.
