### ISSUE TITLE
Antlr Nondeterminism (Bugzilla #700)

### ISSUE THREAD

**Issue by mpreiner** [CVC4/CVC4#919]
**Imported from Bugzilla**
Reporter: *Tim King*
Status: *NEW*
Severity: *normal*
Assigned to: *Clark Barrett*
Component: *SMT-LIB support*
Milestone: *1.6*
Version: *master*
Platform: *PC*
OS: *Linux*

Original attachment names and IDs:
- _[log_fail.txt](http://cvc4.cs.stanford.edu/bugzilla_attachments/344_log_fail.txt)_ (log_fail.txt, ID 344)
- _[success_log.txt](http://cvc4.cs.stanford.edu/bugzilla_attachments/345_success_log.txt)_ (success log, ID 345)
- _[log98572564.txt](http://cvc4.cs.stanford.edu/bugzilla_attachments/346_log98572564.txt)_ (Another failure, ID 346)

On 2015-12-23 18:42:56 -0800, Tim King wrote:
> My previous email to cvc4\-devel_@
> 
> \-\-\-\-\-\-\-\-\-\-\-\-
> 
> Hi all,
> 
> Here is an example of antlr non\-deterministically giving an error on the most recent commit to master:
> https://travis-ci.org/CVC4/CVC4/jobs/96020584#L2150
> 
> Attached are the output of Smt2Lexer.h succeeding and failing. The difference between the two is how they interpret Smt2.g:1520:3. Successful runs give two warnings for this line and succeed. Failing runs give a different set of 13 warnings, then an error message and exit.
> 
> Does anybody have any ideas for how to handle this?

On 2015-12-23 18:43:27 -0800, Tim King wrote:
> Created attachment 344
> log\_fail.txt

On 2015-12-23 18:43:46 -0800, Tim King wrote:
> Created attachment 345
> success log

On 2015-12-23 18:46:15 -0800, Tim King wrote:
> Created attachment 346
> Another failure

**Comment by 4tXJ7f** [comment]
@aniemetz, @HanielB and I all haven't seen this issue in a long time/ever, so I am closing this issue.
