### ISSUE TITLE
String Resource Out In Incremental (Bugzilla #709)

### ISSUE THREAD

**Issue by mpreiner** [CVC4/CVC4#928]
**Imported from Bugzilla**
Reporter: *Tim King*
Status: *NEW*
Severity: *enhancement*
Assigned to: *Clark Barrett*
Component: *{Internals} Incrementality*
Milestone: *1.6*
Version: *master*
Platform: *PC*
OS: *Linux*

Original attachment names and IDs:
- _[example1.smt](http://cvc4.cs.stanford.edu/bugzilla_attachments/351_example1.smt)_ (One more failing example, ID 351)

On 2016-01-15 03:39:45 -0800, Tim King wrote:
> Strings appears to be running out of resources in incremental mode.
> 
> \-\-Mike's Email to cvc\-devel\-\-
> 
> Hello, CVC developers!
> 
> Fristly, I'd like to thank you for such a wonderful tool. It works very fast and gives reasonable outputs. 
> 
> I use CVC4 extensively, especially its string theory. 
> 
> Today I've faced an issue with incremental mode. When feeding CVC with two very similar queries, if it fails on first, then it automatically fails on second. Let me give an example (slightly changed, but this is essentially a part of a real task):
> 
> (set\-logic QF\_BVS)
> (set\-option :strings\-exp true)
> 
> (push 1)
> (declare\-fun DUEwPBYu () String)
> (declare\-fun AYRaicxP () String)
> (assert (str.suffixof AYRaicxP DUEwPBYu))
> (assert (\= (str.at AYRaicxP 0) "<"))
> (assert (\= (str.indexof AYRaicxP "<" 1) (\- 1)))
> (assert (str.contains AYRaicxP "<xxxxxxx<qwerty"))
> (check\-sat)
> (pop 1)
> 
> (push 1)
> (declare\-fun dgtLpVAm () String)
> (declare\-fun KNOeeuim () String)
> (assert (str.contains dgtLpVAm "<abcbdberer>"))
> (assert (str.suffixof dgtLpVAm KNOeeuim))
> (assert (\= (str.at dgtLpVAm 0) "<"))
> (assert (\= (str.indexof dgtLpVAm "<" 1) (\- 1)))
> (check\-sat)
> (pop 1)
> 
> (side note: by doing such queries, I'm trying to model PHP's strrchr function)
> 
> As you can see, those two packs of asserts are different only inside str.contains predicate. However, this difference is significant: the first query is unsatisfiable, while the second is satisfiable.
> 
> I'm running this file using latest Windows binary like this:
> cvc4\-2016\-01\-09\-win32\-opt.exe \-m \-\-incremental \-\-lang smt \-\-tlimit\-per\=5000 < caching\_example.txt
> (side note: the issue appears in several CVC 1.5 builds, not just the latest)
> 
> The program thinks for several seconds, outputs "unknown", then immediately outputs "unknown" second time and terminates. The issue here is that the second "unknown" is given right away, without any thinking. I guess this arises from some sort of caching of queries inside CVC.
> 
> However, if I switch those two packs of asserts, I get the result just right: 
> "sat
> unknown".
> 
> Do you consider this a flaw? Will this issue be addressed sometime? I can provide more examples, feel free to ask for further details.
> 
> Thank you for your work!
> 
> Mike Koltsov

On 2016-01-15 03:55:58 -0800, Tim King wrote:
> 
> > Do you consider this a flaw? Will this issue be addressed sometime? I can provide more examples, feel free to ask for further details.
> 
> My initial hunch is that this is a bad interaction between \-\-interactive and \-\-tlmit\-per (though there are other candidates). It is an issue. But if my hunch is right, I think it is reasonable for us to treat this as an enhancement request. (Resource limiting is a bit of a brittle feature.)
> 
> We don't have much in the way of resources for enhancements like this until after the 1.5 release, which is now likely to be after the CAV and IJCAR deadlines.
> 
> In the meantime, we do want a couple more small examples. If you could add them to the bug report, that would help us out.
> 
> If you want a more robust \*hack\* around this issue, try \-\-tear\-down\-incremental or separating queries into different processes periodically. Ugly to be sure, but it might alleviate some of the current pain.
> 
> Clark, Can you find someone to confirm if my diagnosis is on the ball? If it is something more serious we can look into it.

On 2016-01-15 09:31:38 -0800, Mike Koltsov wrote:
> Created attachment 351
> One more failing example

On 2016-01-15 09:40:31 -0800, Mike Koltsov wrote:
> Thank you for looking into this!
> 
> > In the meantime, we do want a couple more small examples. If you could add them
> > to the bug report, that would help us out.
> 
> I've added another example as an attachment. It contains two similar hard queries (satisfiable, though) and one very easy. If any of hard examples fail, then the third also fails, which rules out my guess for caching. 
> 
> 
> 
> > If you want a more robust \*hack\* around this issue, try \-\-tear\-down\-incremental
> > or separating queries into different processes periodically. Ugly to be sure,
> > but it might alleviate some of the current pain.
> 
> Thank you! I've came up with similar hack: restart CVC if it gives "unknown". Works fine for me.

On 2016-01-17 18:41:49 -0800, Andrew Reynolds wrote:
> I believe there is a bug with options "\-\-incremental \-\-tlimit\-per\=N".
> 
> On the original benchmark, CVC4 does not even call strings::check at full effort on the second "check\-sat".  Whereas, "\-\-tear\-down\-incremenal\=1 \-\-tlimit\-per\=5000" leads to expected behavior (unknown, sat).
> 
> A similar query has the same behavior for a simple quantifiers problem that times out, use "cvc4 \-\-full\-saturate\-quant \-\-tlimit\-per\=5000 \-\-incremental" on:
> 
> (set\-logic ALL\_SUPPORTED)
> (declare\-sort $$unsorted 0)
> (declare\-fun f (Int) Int)
> (declare\-fun a () Int)
> (declare\-fun b () Int)
> (push 1)
> (assert (forall ((X Int)) (< X (f X))))
> (assert (forall ((X Int)) (> (\+ a b) (f X))))
> (check\-sat)
> (pop 1)
> 
> (push 1)
> (assert (forall ((X Int)) (< X (f X))))
> (assert (forall ((X Int)) (> (\+ a b) (f X))))
> (check\-sat)
> (pop 1)
> 
> whereas: "cvc4 \-\-full\-saturate\-quant \-\-tlimit\-per\=5000 \-\-tear\-down\-incremental\=1" leads to timeout after 5 sec, timeout after 5 sec.
> 
> \-Andy

**Comment by ajreynol** [comment]
All three queries of this benchmark are solved in 0.1 second in current master. I checked https://github.com/CVC4/CVC4/commit/1823d6d537a59d85a17f09f53c8128d934c420a3 but I don't know the cause of when this benchmark became fast.

I also tested the combination of incremental and tlimit-per and it seems these options are compatible now.
