### ISSUE TITLE
Why prefer (re.++ (re.union *)) over (re.union *)? (Bugzilla #715)

### ISSUE THREAD

**Issue by mpreiner** [CVC4/CVC4#934]
**Imported from Bugzilla**
Reporter: *Pierre van de Laar*
Status: *NEW*
Severity: *enhancement*
Assigned to: *Andrew Reynolds*
Component: *Strings*
Milestone: *1.6*
Version: *master*
Platform: *PC*
OS: *Windows*

Original attachment names and IDs:
- _[debugSMT.2016-03-09 15-49-08.1344522.smt2](http://cvc4.cs.stanford.edu/bugzilla_attachments/359_debugSMT.2016-03-09%2015-49-08.1344522.smt2)_ (generate random strings, ID 359)

On 2016-03-09 10:07:07 -0800, Pierre van de Laar wrote:
> Created attachment 359
> generate random strings
> 
> The attached file ask CVC4 to generate 100 random strings.
> Never is a string of length 1 generated.
> For example, see line 34 of the file
> (assert (or (str.in.re $S$1033$0$1$ (re.union (re.range "?" "\~") (re.range " " ">") ) ) (or (str.in.re $S$1033$0$1$ (re.\+\+ (re.union (re.range "a" "\~") (re.range " " "\`") ) (re.union (re.range "t" "\~") (re.range " " "s") ) (re.union (re.range "&" "\~") (re.range " " "%") ) ) ) (or (str.in.re $S$1033$0$1$ (re.\+\+ (re.union (re.range "L" "\~") (re.range " " "K") ) (re.union (re.range "\_" "\~") (re.range " " "^") ) ) ) (str.in.re $S$1033$0$1$ (re.\* (re.union (re.range "\x00" "\x09") (re.range "\x0B" "\x0C") (re.range "\x0E" "\x7F") ) ) )))))
> In this subproblem "at&" is obtained as answer (see comment on line 43).
> 
> Yet, since "at&" is obtained the sub expression:
> (str.in.re $S$1033$0$1$ (re.union (re.range "?" "\~") (re.range " " ">") ) )
> is skipped in preference of the far more complex sub expression:
> (str.in.re $S$1033$0$1$ (re.\+\+ (re.union (re.range "a" "\~") (re.range " " "\`") ) (re.union (re.range "t" "\~") (re.range " " "s") ) (re.union (re.range "&" "\~") (re.range " " "%") ) ) )
> 
> Is a heuristic based on the depth of regular expression nesting not always better than prefering re.\+\+ over re.union?
> 
> Tested with the latest version of cvc4 on windows and the following parameters:
> cvc4\-2016\-03\-08\-win32\-opt.exe \-\-lang\=smt \-\-tear\-down\-incremental 1 \-\-strings\-exp \-\-fmf\-fun\-rlv \-\-uf\-ss\-fair

On 2016-03-09 10:27:34 -0800, Pierre van de Laar wrote:
> For additional illustration: adding re.\+ to the first sub expression, yields a string of length 1: "?"
> 
> 
> (assert 
> (or 
> (str.in.re $S$1033$0$1$ (re.\+ (re.union (re.range "?" "\~") (re.range " " ">") ) ) )
>             (or (str.in.re $S$1033$0$1$ (re.\+\+ (re.union (re.range "a" "\~") (re.range " " "\`") ) (re.union (re.range "t" "\~") (re.range " " "s") ) (re.union (re.range "&" "\~") (re.range " " "%") ) ) ) 
>             (or (str.in.re $S$1033$0$1$ (re.\+\+ (re.union (re.range "L" "\~") (re.range " " "K") ) (re.union (re.range "\_" "\~") (re.range " " "^") ) ) ) 
>             (str.in.re $S$1033$0$1$ (re.\* (re.union (re.range "\x00" "\x09") (re.range "\x0B" "\x0C") (re.range "\x0E" "\x7F") ) ) ))
>             ))
> )
> 
> This doesn't happen when 
> (re.\+\+ (str.to.re "") x )
> or 
> (re.\+\+ x (str.to.re "") )
> is added.
> 
> For me, the applied heuristic is unclear and seems suboptimal.

**Comment by ajreynol** [comment]
CVC4 quickly solves all queries in the benchmark with either

--strings-exp -i --fmf-fun-rlv
or
--strings-exp --tear-down-incremental=1 --fmf-fun-rlv

The heuristics are determined by the SAT solver, we do not have any heuristics for changing the decision order based on string literals, although this is explored in a recent paper: https://arxiv.org/pdf/1704.07935.pdf

I'm closing this issue, since in the past I have not had much success with these heuristics, and the current benchmark attached to this issue solves quickly.
