### ISSUE TITLE
Swig Expr Ref Count Issue (Bugzilla #730)

### ISSUE THREAD

**Issue by mpreiner** [CVC4/CVC4#949]
**Imported from Bugzilla**
Reporter: *Tim King*
Status: *NEW*
Severity: *normal*
Assigned to: *Clark Barrett*
Component: *Compatibility layer (CVC3 API: C++, C, and Java)*
Milestone: *1.6*
Version: *master*
Platform: *PC*
OS: *Linux*

On 2016-04-03 17:00:47 -0700, Tim King wrote:
> http://www.swig.org/Doc1.3/Java.html#java_multithread_libraries
> 
> There is a danger that by having the garbage collector called in a different thread that this will corrupt datastructures in Expr.

**Comment by nafur** [comment]
We no longer use SWIG, and thus close this ticket.
