### ISSUE TITLE
summary of regressions without --no-cbqi (Bugzilla #745)

### ISSUE THREAD

**Issue by mpreiner** [CVC4/CVC4#964]
**Imported from Bugzilla**
Reporter: *Florian Schanda*
Status: *NEW*
Severity: *enhancement*
Assigned to: *Andrew Reynolds*
Component: *Miscellaneous*
Milestone: *1.6*
Version: *master*
Platform: *All*
OS: *All*

Original attachment names and IDs:
- _[regressions.tar.xz](http://cvc4.cs.stanford.edu/bugzilla_attachments/377_regressions.tar.xz)_ (133 regressions without --no-cbqi, ID 377)

On 2016-07-11 08:15:50 -0700, Florian Schanda wrote:
> Created attachment 377
> 133 regressions without \-\-no\-cbqi
> 
> Hi Andrew,
> 
> As discussed previously we use the \-\-no\-cbqi flag as it generally helps in our testsuite. I will attach a tarball containing all 133 files that cvc4 e9381ce8 with \-\-no\-cbqi manages to prove in less than 2 seconds, but cvc4 with no options does not. You may also want to know there are 8 improvements as well, but this seems minor given 133 regressions.
> 
> Of course, our testsuite may be skewed and in real life it might turn out that those 8 improvements are much more useful than those 133 regressions. I am not sure I have a good way of checking that but I will keep looking.
> 
> I have now a set of scripts done where I can easily extract this kind of benchmark collections. I will try and set up a continuous checking for this that you guys could monitor.
> 
> Hope this helps!

On 2016-07-14 15:17:57 -0700, Andrew Reynolds wrote:
> Hi Florian,
> 
> I do understand why the cbqi option is affecting these benchmarks negatively.
> 
> It has to do with the operator "bv2nat", which is currently being translated to a large set of cases over bv\+arithmetic eagerly.  This is in turn triggering the counterexample\-based quantified instantiation "cbqi" to do a lot of work to derive relevant instances.
> 
> The solution is to reason about bv2nat as an uninterpreted function first, before expanding its semantics (thus fast E\-matching kicks in first).
> 
> I will ask around about what the best way to do this is, but it may take some time. 
> 
> But, the end expectation is that having better support for bv2nat should help out a lot overall. I'll try to prioritize making progress on this.
> 
> \-Andy

**Comment by florianschanda** [comment]
I take it bugzilla is basically being phased out?

Anyway, I will re-visit this soon as we have now more infrastructure for measuring this kind of thing. We're still seeing some regressions without --no-cbqi but we're also seeing some improvements. I am going to assemble a new updated list of benchmarks where --no-cbqi is needed.

**Comment by ajreynol** [comment]
Hi Florian,

On Wed, Oct 11, 2017 at 5:13 AM, Florian Schanda <notifications@github.com>
wrote:

> I take it bugzilla is basically being phased out?
>

We've migrated to github issues.

Your previous bugzilla reports are there, e.g. :
https://github.com/CVC4/CVC4/issues/969


> Anyway, I will re-visit this soon as we have now more infrastructure for
> measuring this kind of thing. We're still seeing some regressions without
> --no-cbqi but we're also seeing some improvements. I am going to assemble a
> new updated list of benchmarks where --no-cbqi is needed.
>
>
Great. It'd be nice to consolidate this to one github issue and have the
most up-to-date benchmarks.

Btw, it looks like the open github issues regarding this are:

https://github.com/CVC4/CVC4/issues/963
https://github.com/CVC4/CVC4/issues/964
https://github.com/CVC4/CVC4/issues/969

Cheers,
Andy
