### ISSUE TITLE
Various regressions at 811834a and a7a9ba3 (Bugzilla #750)

### ISSUE THREAD

**Issue by mpreiner** [CVC4/CVC4#969]
**Imported from Bugzilla**
Reporter: *Florian Schanda*
Status: *NEW*
Severity: *enhancement*
Assigned to: *Andrew Reynolds*
Component: *Quantifiers*
Milestone: *1.6*
Version: *master*
Platform: *All*
OS: *All*

Original attachment names and IDs:
- _[total.pdf](http://cvc4.cs.stanford.edu/bugzilla_attachments/386_total.pdf)_ (overall behaviour of cvc4, ID 386)
- _[regression_811834a.pdf](http://cvc4.cs.stanford.edu/bugzilla_attachments/387_regression_811834a.pdf)_ (behaviour around 811834a, ID 387)
- _[regression_a7a9ba3.pdf](http://cvc4.cs.stanford.edu/bugzilla_attachments/388_regression_a7a9ba3.pdf)_ (behaviour around a7a9ba3, ID 388)
- _[interesting_e9381ce.pdf](http://cvc4.cs.stanford.edu/bugzilla_attachments/389_interesting_e9381ce.pdf)_ (behaviour around e9381ce, ID 389)
- _[regressions_811834a_20s_no-cbqi.tar](http://cvc4.cs.stanford.edu/bugzilla_attachments/390_regressions_811834a_20s_no-cbqi.tar)_ (worst offenders at 811834a (--no-cbqi), ID 390)
- _[regressions_a7a9ba3_20s_no-cbqi.tar](http://cvc4.cs.stanford.edu/bugzilla_attachments/391_regressions_a7a9ba3_20s_no-cbqi.tar)_ (worst offenders at a7a9ba3 (--no-cbqi), ID 391)
- _[crashes_7d5a85cb05.tar](http://cvc4.cs.stanford.edu/bugzilla_attachments/394_crashes_7d5a85cb05.tar)_ (two vcs crashing extTheoryBV, ID 394)
- _[analysis_d63865a.tar.xz](http://cvc4.cs.stanford.edu/bugzilla_attachments/395_analysis_d63865a.tar.xz)_ (results and benchmarks on extTheoryBV branch, ID 395)
- _[suite_x86.tar.xz](http://cvc4.cs.stanford.edu/bugzilla_attachments/396_suite_x86.tar.xz)_ (All benchmarks from the "x86" testsuite, ID 396)

On 2016-08-15 10:06:19 -0700, Florian Schanda wrote:
> Hi Andrew,
> 
> We have a user that has a bunch of VCs (all unsat) that are not like other VCs
> in our daily regression test, hence I am only reporting on them now. They
> noticed that over time (26b8cc7f onwards) things got worse for them.
> 
> Attached are a bunch of amusing pictures.
> 
> total.pdf shows the overall behaviour of CVC4 since 26b8cc7f (yep, all \~380
> revisions).
> 
> regression\_811834a.pdf and regression\_a7a9ba3.pdf zoom in for two of the interesting big changes. interesting\_e9381ce.pdf shows the end of the graph
> where for the first time cbqi is better than no\-cbqi on these benchmarks.
> 
> In all pictures, the blue line shows the number of VCs solved by \*both\*
> the cbqi and no\-cbqi flags. The magenta line shows the number of VCs
> solved by the \*combination\* of the cbqi and no\-cbqi flags. The other two
> lines show how many VCs are solved by either option in isolation. In other
> words:
>    blue \+ (cbqi \- blue) \+ (no\-cbqi \- blue) \=\= magenta
> 
> I have also attached a bunch of VCs where this is especially noticeable.
> 
> I should stress that the overall number of VCs that \*can\* be solved has not
> really suffered that much, but things have definitely slowed down a lot; so
> much that they can no longer complete their overnight analysis in a sane
> amount of time.

On 2016-08-15 10:07:28 -0700, Florian Schanda wrote:
> Created attachment 386
> overall behaviour of cvc4

On 2016-08-15 10:08:04 -0700, Florian Schanda wrote:
> Created attachment 387
> behaviour around 811834a

On 2016-08-15 10:08:50 -0700, Florian Schanda wrote:
> Created attachment 388
> behaviour around a7a9ba3

On 2016-08-15 10:09:34 -0700, Florian Schanda wrote:
> Created attachment 389
> behaviour around e9381ce

On 2016-08-15 10:10:52 -0700, Florian Schanda wrote:
> Created attachment 390
> worst offenders at 811834a (\-\-no\-cbqi)

On 2016-08-15 10:11:29 -0700, Florian Schanda wrote:
> Created attachment 391
> worst offenders at a7a9ba3 (\-\-no\-cbqi)

On 2016-08-15 17:50:30 -0700, Andrew Reynolds wrote:
> Hi Florian,
> 
> Thanks a lot for this report, this is nice to see.  
> 
> I'm a bit confused by the pdf's, I'm seeing 2 brown lines, a blue area and a magenta area.  I assume the top of the blue area is the "both solved" line and the bottom of the magenta area is the "solved by portfolio" line?
> 
> 
> I know what caused the drop at 811834a.  It has to do with rewriting equalities between constructors, e.g.
> 
> (ref a) \= (ref b) is equivalent to a \= b
> 
> There are cases where CVC4's theory combination needs to explicitly deduce the fact (ref a) \= (ref b), so I cannot apply the above as a dynamic rewrite.  However, I can apply the above rewrite as a preprocess step.  I notice that this applies to many assertions in the benchmarks you attached.   I'll let you know when this is ready.
> 
> Also, I'm currently working on better support for "bv2nat" which is the original reason for the difference between \-\-cbqi and \-\-no\-cbqi.  
> 
> \-Andy

On 2016-08-16 03:21:15 -0700, Florian Schanda wrote:
> On Monday 15 Aug 2016 17:50:30 bugzilla_@church.cims.nyu.edu wrote:
> > I'm a bit confused by the pdf's, I'm seeing 2 brown lines, a blue area and a
> > magenta area.  I assume the top of the blue area is the "both solved" line
> > and the bottom of the magenta area is the "solved by portfolio" line?
> 
> Yes and yes. And the two brown lines are the cbqi and no\-cbqi lines (you can 
> sort\-of tell them apart; one is x and the other uses \+).
> 
> > I know what caused the drop at 811834a.  It has to do with rewriting
> > equalities between constructors, e.g.
> > 
> > (ref a) \= (ref b) is equivalent to a \= b
> > 
> > There are cases where CVC4's theory combination needs to explicitly deduce
> > the fact (ref a) \= (ref b), so I cannot apply the above as a dynamic
> > rewrite. However, I can apply the above rewrite as a preprocess step.  I
> > notice that this applies to many assertions in the benchmarks you attached.
> >   I'll let you know when this is ready.
> 
> Great, thanks!
> 
> > Also, I'm currently working on better support for "bv2nat" which is the
> > original reason for the difference between \-\-cbqi and \-\-no\-cbqi.
> 
> Ah, yes. Sadly we use this function a lot (for $REASONS) and better support is 
> definitely appreciated.
> 
> 	Florian

On 2016-08-17 15:42:24 -0700, Andrew Reynolds wrote:
> Hi Florian,
> 
> I worked on improved support for bv2nat and int2bv in CVC4 yesterday.  The changes are fairly major so I've put the changes in a branch for now:
> 
> https://github.com/ajreynol/CVC4/tree/extTheoryBV
> 
> Would it be possible for you to test this branch?  I can provide a binary if that is easier for you.
> 
> I've noticed the new version on the above branch does substantially better on benchmarks you reported on bug 745.  If you can confirm this change helps on a larger set, this would help expedite merging these changes to master.
> 
> Let me know,
> Andy

On 2016-08-18 03:10:48 -0700, Florian Schanda wrote:
> On Wednesday 17 Aug 2016 15:42:25 bugzilla_@church.cims.nyu.edu wrote:
> > Would it be possible for you to test this branch?  I can provide a binary if
> > that is easier for you.
> 
> Of course, binary not necessary (we have no problem with building things :))
> 
> I'll let you know once I have results.
> 
> 	Florian

On 2016-08-23 10:14:11 -0700, Florian Schanda wrote:
> Created attachment 394
> two vcs crashing extTheoryBV
> 
> Hi Andrew,
> 
> I have tried the branch, and on our main testsuite there are a lot of
> regressions, but I am trying to chase down what is going on exactly.
> First impressions may not be representative since our setup is complex.
> 
> In the meanwhile, attached here are 2 VCs that produce a crash on the branch
> you gave me to experiment on.

On 2016-08-23 11:59:48 -0700, Andrew Reynolds wrote:
> Thanks, I fixed the crashes.  Also made some minor improvements.
> 
> Do update to the latest version on the branch.
> 
> \-Andy

On 2016-08-24 03:19:32 -0700, Florian Schanda wrote:
> On Tuesday 23 Aug 2016 11:59:48 bugzilla_@church.cims.nyu.edu wrote:
> > http://church.cims.nyu.edu/bugzilla3/show_bug.cgi?id=750
> > 
> > \-\-\- Comment \# 12 from Andrew Reynolds <andrew.j.reynolds_@gmail.com>
> > 2016\-08\-23 11:59:48 EDT \-\-\- Thanks, I fixed the crashes.  Also made some
> > minor improvements.
> > 
> > Do update to the latest version on the branch.
> 
> Ok, updating and re\-running the benchmarks. I'll have graphs and tarballs of 
> regressions ready in a few hours.
> 
> 	Florian

On 2016-08-24 08:54:21 -0700, Florian Schanda wrote:
> Created attachment 395
> results and benchmarks on extTheoryBV branch
> 
> Andrew,
> 
> Attached here is the result of my benchmarking. Overall, not too much change as
> far as I can tell. The tarball contains:
> 
> Three graphs in pdf form, in the style already used on this bug:
>    extTheoryBV\_x86.pdf
>    extTheoryBV\_x86\_15s.pdf    (the same, but with longer timeout)
>    extTheoryBV\_spark2014.pdf  (looking at our standard regression test)
> 
> In the x86 tests you can see a very minor improvement, in the standard tests there is minor regression. The revisions I have plotted are:
>    26b8cc7f \- shipped with SPARK 16.0.1
>    e9381ce8 \- shipped with SPARK master branch
>    36cfaab5 \- where you took the extTheoryBV branch
>    7d5a85cb \- when I reported the two crashes
>    d63865af \- current head of extTheoryBV branch
> 
> I suppose you will be most interested in the effect of your changes on branch, so also included are tarballs that contain a copy of all VCs that are newly solved / no longer solved for revisions 36cfaab5 and d63865af.
> 
> Finally, I will also attach all VCs from the x86 testsuite (they are shareable,
> i.e. the original customer has agreed that we can put them into our public
> repository).
> 
> I can also send you all the VCs from our normal (also publicly visible) testsuite, but that file is a bit bigger (5M, so maybe bugzilla is not the appropriate way to share)?

On 2016-08-24 08:55:45 -0700, Florian Schanda wrote:
> Created attachment 396
> All benchmarks from the "x86" testsuite
> 
> We believe they are \*all\* unsat, but have not verified this.

**Comment by florianschanda** [comment]
This is quite far in the past now. I think it might be easiest to close this ticket and instead look at #1396 which is a more recent result.

**Comment by ajreynol** [comment]
Ok, I'll close, should I also close #964 and #963 ?

**Comment by florianschanda** [comment]
Sure, might as well clean up a bit. I'll raise new issues with the current state of affairs :)
