### ISSUE TITLE
Set attribute on RegExp for special case of model construction (Bugzilla #751)

### ISSUE THREAD

**Issue by mpreiner** [CVC4/CVC4#970]
**Imported from Bugzilla**
Reporter: *Andrew Reynolds*
Status: *NEW*
Severity: *enhancement*
Assigned to: *Andrew Reynolds*
Component: *Strings*
Milestone: *1.6*
Version: *master*
Platform: *PC*
OS: *Linux*

On 2016-08-17 17:36:52 -0700, Andrew Reynolds wrote:
> Currently, RegExp is handled as a special case in a few places in TheoryModel.
> 
> The issue is:
> 
> (1) Theory of strings should do congruence over STRING\_IN\_REGEXP, e.g. to infer conflicts like
> (str.in.re x R1) ^ (\= x y) ^ (not (str.in.re y R2)
> This means R1 and R2 are added as equivalence classes to the equality engine of strings
> (2) RegExp do not normalize to a canonical form. So, RegExp operators do not maintain the invariant that when they are applied to constants, they return a constant.
> 
> 
> We should standardize this by setting an attribute on RegExp nodes.

**Comment by ajreynol** [comment]
We should probably use the notion of first-class type in #1203 to fix this.

**Comment by ajreynol** [comment]
Fixed by #1236.
