### ISSUE TITLE
--statistics ends with an abort (and possibly core dump) (Bugzilla #767)

### ISSUE THREAD

**Issue by mpreiner** [CVC4/CVC4#984]
**Imported from Bugzilla**
Reporter: *Jasmin Blanchette*
Status: *ASSIGNED*
Severity: *normal*
Assigned to: *Andres Noetzli*
Component: *Miscellaneous*
Milestone: *1.5*
Version: *master*
Platform: *PC*
OS: *Linux*

On 2016-11-23 15:09:41 -0800, Jasmin Blanchette wrote:
> From Isabelle's Sledgehammer, we invoke CVC4 with its timeout option and kill the process if it keeps running a few seconds beyond the time limit, or if the user aborts Sledgehammer. This killing is what we do for all provers, but somehow CVC4 doesn't react to it in the same way as the others. Namely, it crashes. We found out that passing \-\-no\-statistics solves the problem, so this is not severe for us.
> 
> Some systems are configured to (1) produce core dumps and/or (2) display an annoying alert in the user interface. One user has been reporting (1) and (2) on Ubuntu 16.04 LTS (amd64). Makarius Wenzel, Isabelle's lead developer, looked into the issue. He writes:
> 
> "Looking through the cvc4 sources, I've found several signal handlers here: https://github.com/CVC4/CVC4/blob/master/src/main/util.cpp \-\- they usually end with abort(), which causes SIGABRT on the process.
> 
> I am not proficient in C\+\+ system programming and can't say if there is something wrong on the cvc4 side. At a high\-level, a process that reacts strangely when sent SIGINT looks bad, but in some sense it is also a very common situation \-\- reminds me of E prover some years ago.
> 
> Isabelle as interactive system works under the global assumption that all internal and external processes can always be interrupted cleanly."
> 
> This issue seems to have been around for a long time. Eugene has reported it for both 363e4c37 (6 February 2015) and e79e6432 (21 October 2016).

On 2016-12-02 05:46:19 -0800, Jasmin Blanchette wrote:
> Update: It turns out that passing \-\-no\-statistics does not (always?) solve the problem, as reported by one of our users:
> 
>     https://lists.cam.ac.uk/pipermail/cl-isabelle-users/2016-November/msg00135.html
> 
> So we would be grateful for a fix.

On 2017-01-11 12:40:37 -0800, Tim King wrote:
> \*\*\* Bug 762 has been marked as a duplicate of this bug. \*\*\*

On 2017-01-13 18:17:53 -0800, Tim King wrote:
> Jasmin, quick update. Clark and I discussed this. We think our solution is going to be to not install the signal handlers in the first place (unless they are requested during ./configure so developers can keep using these). This corresponds roughly adding a CVC4\_DEBUG\_SIGNALHANDLERS flag to replace the guards for \_\_WIN32\_\_ in this file. Please let us know if you \*don't\* think this is going to be a viable solution for you.

**Comment by nafur** [comment]
@blanchette
Is this still an issue? We recently refactored the time limits, and also printing of statistics has changed since.

**Comment by blanchette** [comment]
I haven't heard about this issue from users lately. I don't know if it's because CVC4 no longer has the issue or if it's just a coincidence. The solution suggested by Tim King above sounded good to me, though.

**Comment by nafur** [comment]
After looking closer at this, I noticed that this has most probably already been resolved in a cleaner way. Note that code in signal handlers is severely restricted and it seems the affected version used unsafe code to print the statistics. See https://github.com/CVC4/CVC4/blob/master/src/main/signal_handlers.cpp#L16 for some hints about this.
@4tXJ7f  has refactored this code in the meantime, hence the segfaults should be gone. Interrupting CVC4 should since work cleanly. If you find that merely printing the statistics takes a long time, please open a new issue about this.
